In [20]:

import pandas as pd
import os


# Read the CSV file
data = pd.read_csv('sql_queries.csv')

# Display the data

total_queries = len(data)
print(total_queries)
data.head()

1676

                                           SQL Query
0                 No value found for "SQL Query" key
1                 No value found for "SQL Query" key
2  SELECT player_id FROM public.agg_season_player...
3                 No value found for "SQL Query" key
4                 No value found for "SQL Query" key

In [21]:
# Clean queries that have less than 10 characters

clean_data = data[data['SQL Query'].str.len() >= 10]

clean_data_len = len(clean_data)
print(f"Removed {total_queries - clean_data_len}")

Removed 5

In [22]:
clean_data2 = clean_data[clean_data['SQL Query'] != 'No value found for "SQL Query" key']
clean_data2_len = len(clean_data2)

print(f"Removed {clean_data_len - clean_data2_len}")

Removed 48

In [23]:
# Calculate the length of the DataFrame before removing duplicates
clean_data2_len = len(clean_data2)

# Remove duplicates without using inplace
rmv_dupli_data = clean_data2.drop_duplicates()

# Calculate the length of the DataFrame after removing duplicates
rmv_dupli_data_len = len(rmv_dupli_data)

# Print the number of duplicates removed
print(f"Removed {clean_data2_len - rmv_dupli_data_len} duplicates")

Removed 461 duplicates

In [25]:
len_data = len(rmv_dupli_data)

print(f"Rows: {len_data}")

rmv_dupli_data.to_csv('sql_queries_clean.csv', index=False)

Rows: 1162

# Running queries in DB

In [27]:

# Read the CSV file
queries_df = pd.read_csv('sql_queries_clean.csv')

queries_df.head()

                                           SQL Query
0  SELECT player_id FROM public.agg_season_player...
1  SELECT player_name, SUM(dl_index) AS total_goa...
2  SELECT player_name, goals FROM vm_agg_season_p...
3  SELECT player_name, goals FROM vm_agg_season_p...
4  SELECT player_id, team_id, score_pd FROM publi...

SQL Query    SELECT player_id FROM public.agg_season_player...
Name: 0, dtype: object

In [41]:
from logger_manager import LoggerManager
from run_query import get_db_data, init_connection_pool,close_connection_pool, get_db_data2
from print_colors import print_colored

def test_query(query, logger):
    data = get_db_data(query,logger)
    
    if data[0] == 'Database error':
        print("Failed query")
        return False, data[2]

    else:
        print("Sucessful query")
        columns , rows = data
        # Calculate the shape
        num_columns = len(columns)
        num_rows = len(rows)
        shape = (num_rows, num_columns)
        print(f"Data Shape: {shape} ")
        return True , shape
    
logger = LoggerManager.get_logger("SQL_Query_test2").get_logger()
logger.info("TEST 33")

query = queries_df.loc[0, 'SQL Query']
print(query)


init_connection_pool()

valid, description = test_query(query, logger)
print(valid, description)
close_connection_pool()

06-21 16:08:31 - logger_SQL_Query_test2 - INFO - TEST 33
INFO:logger_SQL_Query_test2:TEST 33

SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND age < 25 AND height > 180 AND team_id IN (4265, 4279) AND games_played_65mins >= 20 AND mins_played >= 2000 AND score_pd_float < 50 AND player_id IN (SELECT player_id FROM t_player WHERE country_id = 1 AND position = 'DL') ORDER BY score_pd DESC LIMIT 1
Database connection pool initialized at: 06-21 16:08:31

06-21 16:08:31 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:08:31 -> SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND age < 25 AND height > 180 AND team_id IN (4265, 4279) AND games_played_65mins >= 20 AND mins_played >= 2000 AND score_pd_float < 50 AND player_id IN (SELECT player_id FROM t_player WHERE country_id = 1 AND position = 'DL') ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:08:31 -> SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND age < 25 AND height > 180 AND team_id IN (4265, 4279) AND games_played_65mins >= 20 AND mins_played >= 2000 AND score_pd_float < 50 AND player_id IN (SELECT player_id FROM t_player WHERE country_id = 1 AND position = 'DL') ORDER BY score_pd DESC LIMIT 1
ERROR:root:Database error: column "age" does not exist
LINE 1: ...agg_season_player_pd WHERE season_id = 816527 AND age < 25 A...
                                                             ^

Failed query RED
False column "age" does not exist
LINE 1: ...agg_season_player_pd WHERE season_id = 816527 AND age < 25 A...
                                                             ^

Database connection pool closed at: 06-21 16:08:31

In [46]:
import time
import pandas as pd
from logger_manager import LoggerManager
from run_query import get_db_data, init_connection_pool, close_connection_pool
from print_colors import print_colored

def test_query(query, logger):
    data = get_db_data(query, logger)
    
    if data[0] == 'Database error':
        print("Failed query")
        return False, data[2]

    else:
        print("Successful query")
        columns, rows = data
        # Calculate the shape
        num_columns = len(columns)
        num_rows = len(rows)
        shape = (num_rows, num_columns)
        print(f"Data Shape: {shape} ")
        return True, shape

def run_queries_in_batches(queries_df, batch_size=20, wait_time=2):
    # Initialize the connection pool
    init_connection_pool()

    # Prepare results list
    results = []

    logger = LoggerManager.get_logger("SQL_Query_test2").get_logger()
    logger.info("Starting batch query test")

    # Process queries in batches
    for i in range(0, len(queries_df), batch_size):
        batch = queries_df.iloc[i:i + batch_size]

        for index, row in batch.iterrows():
            query = row['SQL Query']
            print(f"Running query: {query}")

            valid, description = test_query(query, logger)
            results.append({
                'SQL Query': query,
                'Valid': valid,
                'Description': description
            })
        

        # Wait between batches
        time.sleep(wait_time)

    # Close the connection pool
    close_connection_pool()

    # Create a new DataFrame from the results
    results_df = pd.DataFrame(results)
    return results_df

# Example usage:
# Assuming queries_df is your DataFrame containing SQL queries
# queries_df = pd.DataFrame({'SQL Query': [...your queries...]})

# Run the queries in batches
results_df = run_queries_in_batches(queries_df)

# Print or save the results DataFrame
print(results_df)
# Optionally, save to a CSV file
results_df.to_csv('sql_query_results.csv', index=True)

Database connection pool initialized at: 06-21 16:16:04

06-21 16:16:04 - logger_SQL_Query_test2 - INFO - Starting batch query test
INFO:logger_SQL_Query_test2:Starting batch query test

Running query: SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND age < 25 AND height > 180 AND team_id IN (4265, 4279) AND games_played_65mins >= 20 AND mins_played >= 2000 AND score_pd_float < 50 AND player_id IN (SELECT player_id FROM t_player WHERE country_id = 1 AND position = 'DL') ORDER BY score_pd DESC LIMIT 1

06-21 16:16:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:04 -> SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND age < 25 AND height > 180 AND team_id IN (4265, 4279) AND games_played_65mins >= 20 AND mins_played >= 2000 AND score_pd_float < 50 AND player_id IN (SELECT player_id FROM t_player WHERE country_id = 1 AND position = 'DL') ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:04 -> SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND age < 25 AND height > 180 AND team_id IN (4265, 4279) AND games_played_65mins >= 20 AND mins_played >= 2000 AND score_pd_float < 50 AND player_id IN (SELECT player_id FROM t_player WHERE country_id = 1 AND position = 'DL') ORDER BY score_pd DESC LIMIT 1
ERROR:root:Database error: column "age" does not exist
LINE 1: ...agg_season_player_pd WHERE season_id = 816527 AND age < 25 A...
                                                             ^

Failed query
Running query: SELECT player_name, SUM(dl_index) AS total_goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 GROUP BY player_name ORDER BY total_goals DESC LIMIT 1

06-21 16:16:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:04 -> SELECT player_name, SUM(dl_index) AS total_goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 GROUP BY player_name ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:04 -> SELECT player_name, SUM(dl_index) AS total_goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 GROUP BY player_name ORDER BY total_goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY goals DESC LIMIT 1

06-21 16:16:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:04 -> SELECT player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:04 -> SELECT player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (0, 2)
Running query: SELECT player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:16:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:05 -> SELECT player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:05 -> SELECT player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, team_id, score_pd FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY score_pd DESC LIMIT 1

06-21 16:16:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:05 -> SELECT player_id, team_id, score_pd FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:05 -> SELECT player_id, team_id, score_pd FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY score_pd DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, COUNT(*) AS goals_scored FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1

06-21 16:16:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:05 -> SELECT player_id, COUNT(*) AS goals_scored FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:05 -> SELECT player_id, COUNT(*) AS goals_scored FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...COUNT(*) AS goals_scored FROM public.t_goal WHERE season_id ...
                                                             ^

Failed query
Running query: SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY score_pd DESC LIMIT 1

06-21 16:16:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:05 -> SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:05 -> SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY score_pd DESC LIMIT 1

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY goals DESC LIMIT 1

06-21 16:16:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:05 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:05 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (0, 3)
Running query: SELECT player_id, player_name, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY games_lost ASC LIMIT 1

06-21 16:16:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:05 -> SELECT player_id, player_name, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY games_lost ASC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:05 -> SELECT player_id, player_name, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY games_lost ASC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...T player_id, player_name, team_id, season_id FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, team_id, season_id, non_penalty_shots_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY non_penalty_shots_90 DESC LIMIT 1

06-21 16:16:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:05 -> SELECT player_id, player_name, team_id, season_id, non_penalty_shots_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY non_penalty_shots_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:05 -> SELECT player_id, player_name, team_id, season_id, non_penalty_shots_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY non_penalty_shots_90 DESC LIMIT 1

Successful query
Data Shape: (1, 5)
Running query: SELECT player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_country_name = 'Spain' ORDER BY goals DESC LIMIT 1

06-21 16:16:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:05 -> SELECT player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_country_name = 'Spain' ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:05 -> SELECT player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_country_name = 'Spain' ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, season_id, SUM(goals_scored) AS total_goals FROM vm_agg_season_player_all WHERE season_id IN (816527, 816019, 815453, 814198, 813658) AND league_type_id = 1 GROUP BY player_id, season_id ORDER BY total_goals DESC;

06-21 16:16:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:05 -> SELECT player_id, season_id, SUM(goals_scored) AS total_goals FROM vm_agg_season_player_all WHERE season_id IN (816527, 816019, 815453, 814198, 813658) AND league_type_id = 1 GROUP BY player_id, season_id ORDER BY total_goals DESC;
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:05 -> SELECT player_id, season_id, SUM(goals_scored) AS total_goals FROM vm_agg_season_player_all WHERE season_id IN (816527, 816019, 815453, 814198, 813658) AND league_type_id = 1 GROUP BY player_id, season_id ORDER BY total_goals DESC;
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ... season_id, SUM(goals_scored) AS total_goals FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, season_id, SUM(dl_index) AS total_score FROM vm_agg_season_player_similarity WHERE season_id IN (816527, 816019, 815453, 814198, 813658) GROUP BY player_id, season_id ORDER BY total_score DESC;

06-21 16:16:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:06 -> SELECT player_id, season_id, SUM(dl_index) AS total_score FROM vm_agg_season_player_similarity WHERE season_id IN (816527, 816019, 815453, 814198, 813658) GROUP BY player_id, season_id ORDER BY total_score DESC;
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:06 -> SELECT player_id, season_id, SUM(dl_index) AS total_score FROM vm_agg_season_player_similarity WHERE season_id IN (816527, 816019, 815453, 814198, 813658) GROUP BY player_id, season_id ORDER BY total_score DESC;

Successful query
Data Shape: (20, 3)
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND player_position IN ('FW', 'AML', 'AMR', 'FWL', 'FWR') ORDER BY goals DESC LIMIT 1;

06-21 16:16:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:06 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND player_position IN ('FW', 'AML', 'AMR', 'FWL', 'FWR') ORDER BY goals DESC LIMIT 1;
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:06 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND player_position IN ('FW', 'AML', 'AMR', 'FWL', 'FWR') ORDER BY goals DESC LIMIT 1;

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1;

06-21 16:16:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:06 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1;
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:06 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1;
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...goal_id) AS goals_scored FROM public.t_goal WHERE season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, goals, season_id FROM vm_agg_season_player_opta WHERE season_id IN (816527, 816019, 815453, 814198, 813658) AND league_country_name = 'Spain' AND player_position = 'FW' ORDER BY goals DESC;

06-21 16:16:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:06 -> SELECT player_id, player_name, goals, season_id FROM vm_agg_season_player_opta WHERE season_id IN (816527, 816019, 815453, 814198, 813658) AND league_country_name = 'Spain' AND player_position = 'FW' ORDER BY goals DESC;
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:06 -> SELECT player_id, player_name, goals, season_id FROM vm_agg_season_player_opta WHERE season_id IN (816527, 816019, 815453, 814198, 813658) AND league_country_name = 'Spain' AND player_position = 'FW' ORDER BY goals DESC;

Successful query
Data Shape: (20, 4)
Running query: SELECT player_id, team_id, season_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (     SELECT player_id     FROM t_player     WHERE age < 25     AND height > 180     AND player_id IN (         SELECT player_id         FROM public.agg_season_player_pd         WHERE games_played_65mins >= 20         AND mins_played >= 2000         AND score

06-21 16:16:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:06 -> SELECT player_id, team_id, season_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (     SELECT player_id     FROM t_player     WHERE age < 25     AND height > 180     AND player_id IN (         SELECT player_id         FROM public.agg_season_player_pd         WHERE games_played_65mins >= 20         AND mins_played >= 2000         AND score
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:06 -> SELECT player_id, team_id, season_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (     SELECT player_id     FROM t_player     WHERE age < 25     AND height > 180     AND player_id IN (         SELECT player_id         FROM public.agg_season_player_pd         WHERE games_played_65mins >= 20         AND mins_played >= 2000         AND score
ERROR:root:Database error: syntax error at end of input
LINE 1: ...mins >= 20         AND mins_played >= 2000         AND score
                                                                       ^

Failed query
Running query: SELECT player_id, player_name, team_id, season_id, age, height, games, minutes_played, dl_index, tackles_90 FROM vm_agg_season_player_similarity WHERE age < 25 AND height > 180 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1 AND league_id = 1) AND games >= 20 AND minutes_played >= 2000 AND dl_index < 50 AND position = 'DL

06-21 16:16:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:06 -> SELECT player_id, player_name, team_id, season_id, age, height, games, minutes_played, dl_index, tackles_90 FROM vm_agg_season_player_similarity WHERE age < 25 AND height > 180 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1 AND league_id = 1) AND games >= 20 AND minutes_played >= 2000 AND dl_index < 50 AND position = 'DL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:06 -> SELECT player_id, player_name, team_id, season_id, age, height, games, minutes_played, dl_index, tackles_90 FROM vm_agg_season_player_similarity WHERE age < 25 AND height > 180 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1 AND league_id = 1) AND games >= 20 AND minutes_played >= 2000 AND dl_index < 50 AND position = 'DL
ERROR:root:Database error: unterminated quoted string at or near "'DL"
LINE 1: ... minutes_played >= 2000 AND dl_index < 50 AND position = 'DL
                                                                    ^

Failed query
Running query: SELECT player_id, player_name, height, age, games_played, minutes_played, market_value, dl_index, player_position, player_secondary_position, team_name, league_name FROM vm_agg_season_player_info WHERE age < 25 AND height > 180 AND player_country_name = 'Spain' AND games_played >= 20 AND minutes_played >= 2000 AND market_value < 50000000 AND dl_foot = 'left' AND league_name = 'La Liga

06-21 16:16:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:06 -> SELECT player_id, player_name, height, age, games_played, minutes_played, market_value, dl_index, player_position, player_secondary_position, team_name, league_name FROM vm_agg_season_player_info WHERE age < 25 AND height > 180 AND player_country_name = 'Spain' AND games_played >= 20 AND minutes_played >= 2000 AND market_value < 50000000 AND dl_foot = 'left' AND league_name = 'La Liga
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:06 -> SELECT player_id, player_name, height, age, games_played, minutes_played, market_value, dl_index, player_position, player_secondary_position, team_name, league_name FROM vm_agg_season_player_info WHERE age < 25 AND height > 180 AND player_country_name = 'Spain' AND games_played >= 20 AND minutes_played >= 2000 AND market_value < 50000000 AND dl_foot = 'left' AND league_name = 'La Liga
ERROR:root:Database error: unterminated quoted string at or near "'La Liga"
LINE 1: ...e < 50000000 AND dl_foot = 'left' AND league_name = 'La Liga
                                                               ^

Failed query
Running query: SELECT player_id, player_name, age, height, games_played, mins_played, market_value, player_position, percent_tackles, dl_index FROM vm_agg_season_player_opta WHERE age < 25 AND height > 180 AND country_id = 1 AND games_played >= 20 AND mins_played >= 2000 AND market_value < 50000000 AND dl_foot = 'Left' AND league_id = 1

06-21 16:16:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:06 -> SELECT player_id, player_name, age, height, games_played, mins_played, market_value, player_position, percent_tackles, dl_index FROM vm_agg_season_player_opta WHERE age < 25 AND height > 180 AND country_id = 1 AND games_played >= 20 AND mins_played >= 2000 AND market_value < 50000000 AND dl_foot = 'Left' AND league_id = 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:06 -> SELECT player_id, player_name, age, height, games_played, mins_played, market_value, player_position, percent_tackles, dl_index FROM vm_agg_season_player_opta WHERE age < 25 AND height > 180 AND country_id = 1 AND games_played >= 20 AND mins_played >= 2000 AND market_value < 50000000 AND dl_foot = 'Left' AND league_id = 1
ERROR:root:Database error: column "percent_tackles" does not exist
LINE 1: ...ayed, mins_played, market_value, player_position, percent_ta...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, age, team_id, season_id, mins_played, games_lost FROM vm_agg_season_player_all WHERE age < 25 AND player_country_code = 'ESP' AND team_games_played >= 20 AND team_mins_played >= 2000 AND market_value < 50 AND height > 180 AND league_type_id = 1 AND position = 'DL' AND season_id = 816527 ORDER BY games_lost ASC LIMIT 1;

06-21 16:16:09 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:09 -> SELECT player_id, player_name, age, team_id, season_id, mins_played, games_lost FROM vm_agg_season_player_all WHERE age < 25 AND player_country_code = 'ESP' AND team_games_played >= 20 AND team_mins_played >= 2000 AND market_value < 50 AND height > 180 AND league_type_id = 1 AND position = 'DL' AND season_id = 816527 ORDER BY games_lost ASC LIMIT 1;
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:09 -> SELECT player_id, player_name, age, team_id, season_id, mins_played, games_lost FROM vm_agg_season_player_all WHERE age < 25 AND player_country_code = 'ESP' AND team_games_played >= 20 AND team_mins_played >= 2000 AND market_value < 50 AND height > 180 AND league_type_id = 1 AND position = 'DL' AND season_id = 816527 ORDER BY games_lost ASC LIMIT 1;
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ... team_id, season_id, mins_played, games_lost FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, COUNT(saved_shot_id) AS total_saves FROM public.t_saved_shot WHERE outcome = true AND season_id = 816527 GROUP BY player_id ORDER BY total_saves DESC LIMIT 1

06-21 16:16:09 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:09 -> SELECT player_id, COUNT(saved_shot_id) AS total_saves FROM public.t_saved_shot WHERE outcome = true AND season_id = 816527 GROUP BY player_id ORDER BY total_saves DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:09 -> SELECT player_id, COUNT(saved_shot_id) AS total_saves FROM public.t_saved_shot WHERE outcome = true AND season_id = 816527 GROUP BY player_id ORDER BY total_saves DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...FROM public.t_saved_shot WHERE outcome = true AND season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, COUNT(save_id) AS total_saves FROM public.t_save WHERE match_id IN (SELECT match_id FROM public.t_match WHERE season_id = 816527) GROUP BY player_id ORDER BY total_saves DESC LIMIT 1

06-21 16:16:09 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:09 -> SELECT player_id, COUNT(save_id) AS total_saves FROM public.t_save WHERE match_id IN (SELECT match_id FROM public.t_match WHERE season_id = 816527) GROUP BY player_id ORDER BY total_saves DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:09 -> SELECT player_id, COUNT(save_id) AS total_saves FROM public.t_save WHERE match_id IN (SELECT match_id FROM public.t_match WHERE season_id = 816527) GROUP BY player_id ORDER BY total_saves DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

06-21 16:16:09 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:09 -> SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:09 -> SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1

06-21 16:16:10 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:10 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:10 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, max_acceleration FROM public.agg_period_player_pd WHERE max_acceleration IS NOT NULL ORDER BY max_acceleration DESC LIMIT 1

06-21 16:16:10 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:10 -> SELECT player_id, max_acceleration FROM public.agg_period_player_pd WHERE max_acceleration IS NOT NULL ORDER BY max_acceleration DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:10 -> SELECT player_id, max_acceleration FROM public.agg_period_player_pd WHERE max_acceleration IS NOT NULL ORDER BY max_acceleration DESC LIMIT 1

Successful query
Data Shape: (0, 2)
Running query: SELECT player_id, goals FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:16:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:11 -> SELECT player_id, goals FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:11 -> SELECT player_id, goals FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, non_penalty_goals FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY non_penalty_goals DESC LIMIT 1

06-21 16:16:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:11 -> SELECT player_id, non_penalty_goals FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY non_penalty_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:11 -> SELECT player_id, non_penalty_goals FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY non_penalty_goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, goals FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:16:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:12 -> SELECT player_id, goals FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:12 -> SELECT player_id, goals FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
ERROR:root:Database error: column "goals" does not exist
LINE 1: SELECT player_id, goals FROM public.vt_season_metric_player ...
                          ^

Failed query
Running query: SELECT saves_total FROM public.vt_season_stat_player WHERE season_id = 816529 AND player_id = (SELECT player_id FROM public.vt_season_info_player WHERE season_id = 816529 AND player_id = (SELECT player_id FROM t_player WHERE name = 'Onana')) AND saves_total IS NOT NULL

06-21 16:16:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:12 -> SELECT saves_total FROM public.vt_season_stat_player WHERE season_id = 816529 AND player_id = (SELECT player_id FROM public.vt_season_info_player WHERE season_id = 816529 AND player_id = (SELECT player_id FROM t_player WHERE name = 'Onana')) AND saves_total IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:12 -> SELECT saves_total FROM public.vt_season_stat_player WHERE season_id = 816529 AND player_id = (SELECT player_id FROM public.vt_season_info_player WHERE season_id = 816529 AND player_id = (SELECT player_id FROM t_player WHERE name = 'Onana')) AND saves_total IS NOT NULL

Successful query
Data Shape: (0, 1)
Running query: SELECT player_id, xg FROM public.vt_season_metric_player ORDER BY xg DESC LIMIT 10

06-21 16:16:14 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:14 -> SELECT player_id, xg FROM public.vt_season_metric_player ORDER BY xg DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:14 -> SELECT player_id, xg FROM public.vt_season_metric_player ORDER BY xg DESC LIMIT 10

Successful query
Data Shape: (10, 2)
Running query: SELECT player_id, goals FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:16:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:16 -> SELECT player_id, goals FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:16 -> SELECT player_id, goals FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, goals FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:16:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:16 -> SELECT player_id, goals FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:16 -> SELECT player_id, goals FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE season_id = 816527 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

06-21 16:16:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:16 -> SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE season_id = 816527 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:16 -> SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE season_id = 816527 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1

06-21 16:16:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:17 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:17 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

06-21 16:16:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:17 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:17 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, max_speed FROM public.agg_period_player_pd WHERE max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

06-21 16:16:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:17 -> SELECT player_id, max_speed FROM public.agg_period_player_pd WHERE max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:17 -> SELECT player_id, max_speed FROM public.agg_period_player_pd WHERE max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, max_speed FROM public.agg_period_player_pd...
                          ^

Failed query
Running query: SELECT player_id, player_name, team_name, prev_team_name FROM public.v_player_dup WHERE player_name = 'Artem Dovbyk'

06-21 16:16:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:17 -> SELECT player_id, player_name, team_name, prev_team_name FROM public.v_player_dup WHERE player_name = 'Artem Dovbyk'
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:17 -> SELECT player_id, player_name, team_name, prev_team_name FROM public.v_player_dup WHERE player_name = 'Artem Dovbyk'

Successful query
Data Shape: (1, 4)
Running query: SELECT player_id, team_id, player_name, team_name, season_name FROM public.v_player_sc WHERE player_name = 'Artem Dovbyk' AND season_name = 'ESP I 2023' AND team_name = 'Girona FC'

06-21 16:16:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:37 -> SELECT player_id, team_id, player_name, team_name, season_name FROM public.v_player_sc WHERE player_name = 'Artem Dovbyk' AND season_name = 'ESP I 2023' AND team_name = 'Girona FC'
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:37 -> SELECT player_id, team_id, player_name, team_name, season_name FROM public.v_player_sc WHERE player_name = 'Artem Dovbyk' AND season_name = 'ESP I 2023' AND team_name = 'Girona FC'

Successful query
Data Shape: (0, 5)
Running query: SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE team_id = 4265 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

06-21 16:16:38 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:38 -> SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE team_id = 4265 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:38 -> SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE team_id = 4265 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE team_id = 4265 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1

06-21 16:16:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:40 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE team_id = 4265 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:40 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE team_id = 4265 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, xa FROM public.vt_season_opta_player WHERE team_id = 4265 AND season_id = 816527 AND xa IS NOT NULL ORDER BY xa DESC LIMIT 1

06-21 16:16:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:40 -> SELECT player_id, xa FROM public.vt_season_opta_player WHERE team_id = 4265 AND season_id = 816527 AND xa IS NOT NULL ORDER BY xa DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:40 -> SELECT player_id, xa FROM public.vt_season_opta_player WHERE team_id = 4265 AND season_id = 816527 AND xa IS NOT NULL ORDER BY xa DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, xa FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 AND xa IS NOT NULL ORDER BY xa DESC LIMIT 1

06-21 16:16:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:40 -> SELECT player_id, xa FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 AND xa IS NOT NULL ORDER BY xa DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:40 -> SELECT player_id, xa FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 AND xa IS NOT NULL ORDER BY xa DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, dribbles_total FROM public.vt_season_opta_player ORDER BY dribbles_total DESC LIMIT 1

06-21 16:16:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:41 -> SELECT player_id, dribbles_total FROM public.vt_season_opta_player ORDER BY dribbles_total DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:41 -> SELECT player_id, dribbles_total FROM public.vt_season_opta_player ORDER BY dribbles_total DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, position FROM t_player WHERE player_id = 'he' AND position IS NOT NULL

06-21 16:16:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:46 -> SELECT player_id, position FROM t_player WHERE player_id = 'he' AND position IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:46 -> SELECT player_id, position FROM t_player WHERE player_id = 'he' AND position IS NOT NULL
ERROR:root:Database error: invalid input syntax for integer: "he"
LINE 1: ...ayer_id, position FROM t_player WHERE player_id = 'he' AND p...
                                                             ^

Failed query
Running query: SELECT position FROM t_player WHERE name = 'he' AND position IS NOT NULL

06-21 16:16:47 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:47 -> SELECT position FROM t_player WHERE name = 'he' AND position IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:47 -> SELECT position FROM t_player WHERE name = 'he' AND position IS NOT NULL

Successful query
Data Shape: (0, 1)
Running query: SELECT player_id, position FROM t_player WHERE name = 'he' AND position IS NOT NULL

06-21 16:16:47 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:47 -> SELECT player_id, position FROM t_player WHERE name = 'he' AND position IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:47 -> SELECT player_id, position FROM t_player WHERE name = 'he' AND position IS NOT NULL

Successful query
Data Shape: (0, 2)
Running query: SELECT league_name, current_season_name FROM public.v_season_dup WHERE current_season_id = 816527

06-21 16:16:48 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:48 -> SELECT league_name, current_season_name FROM public.v_season_dup WHERE current_season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:48 -> SELECT league_name, current_season_name FROM public.v_season_dup WHERE current_season_id = 816527

Successful query
Data Shape: (0, 2)
Running query: SELECT league_code FROM public.v_season_dup_competition WHERE season_id = 816527

06-21 16:16:48 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:48 -> SELECT league_code FROM public.v_season_dup_competition WHERE season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:48 -> SELECT league_code FROM public.v_season_dup_competition WHERE season_id = 816527

Successful query
Data Shape: (0, 1)
Running query: SELECT name FROM public.v_season_w_name WHERE season_id = 816527

06-21 16:16:48 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:48 -> SELECT name FROM public.v_season_w_name WHERE season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:48 -> SELECT name FROM public.v_season_w_name WHERE season_id = 816527

Successful query
Data Shape: (0, 1)
Running query: SELECT player_id, SUM(dribbles_won) AS total_dribbles FROM public.vt_season_stat_player WHERE season_id = 816527 GROUP BY player_id ORDER BY total_dribbles DESC LIMIT 1

06-21 16:16:48 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:48 -> SELECT player_id, SUM(dribbles_won) AS total_dribbles FROM public.vt_season_stat_player WHERE season_id = 816527 GROUP BY player_id ORDER BY total_dribbles DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:48 -> SELECT player_id, SUM(dribbles_won) AS total_dribbles FROM public.vt_season_stat_player WHERE season_id = 816527 GROUP BY player_id ORDER BY total_dribbles DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, SUM(dribbles_won) AS total_dribbles FROM public.agg_season_player_pd WHERE season_id = 816527 GROUP BY player_id ORDER BY total_dribbles DESC LIMIT 1

06-21 16:16:48 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:48 -> SELECT player_id, SUM(dribbles_won) AS total_dribbles FROM public.agg_season_player_pd WHERE season_id = 816527 GROUP BY player_id ORDER BY total_dribbles DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:48 -> SELECT player_id, SUM(dribbles_won) AS total_dribbles FROM public.agg_season_player_pd WHERE season_id = 816527 GROUP BY player_id ORDER BY total_dribbles DESC LIMIT 1
ERROR:root:Database error: column "dribbles_won" does not exist
LINE 1: SELECT player_id, SUM(dribbles_won) AS total_dribbles FROM p...
                              ^

Failed query
Running query: SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE season_id = 816529 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

06-21 16:16:48 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:48 -> SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE season_id = 816529 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:48 -> SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE season_id = 816529 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1

06-21 16:16:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:49 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:49 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, dribbles_total FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY dribbles_total DESC LIMIT 10

06-21 16:16:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:49 -> SELECT player_id, dribbles_total FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY dribbles_total DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:49 -> SELECT player_id, dribbles_total FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY dribbles_total DESC LIMIT 10

Successful query
Data Shape: (10, 2)
Running query: SELECT player_id, dribbles_won FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY dribbles_won DESC LIMIT 10

06-21 16:16:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:50 -> SELECT player_id, dribbles_won FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY dribbles_won DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:50 -> SELECT player_id, dribbles_won FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY dribbles_won DESC LIMIT 10

Successful query
Data Shape: (10, 2)
Running query: SELECT product_name, price FROM products WHERE category = 'electronics' AND stock > 0

06-21 16:16:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:50 -> SELECT product_name, price FROM products WHERE category = 'electronics' AND stock > 0
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:50 -> SELECT product_name, price FROM products WHERE category = 'electronics' AND stock > 0
ERROR:root:Database error: relation "products" does not exist
LINE 1: SELECT product_name, price FROM products WHERE category = 'e...
                                        ^

Failed query
Running query: SELECT customer_name, order_date FROM orders WHERE order_status = 'delivered' AND order_total > 1000

06-21 16:16:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:50 -> SELECT customer_name, order_date FROM orders WHERE order_status = 'delivered' AND order_total > 1000
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:50 -> SELECT customer_name, order_date FROM orders WHERE order_status = 'delivered' AND order_total > 1000
ERROR:root:Database error: relation "orders" does not exist
LINE 1: SELECT customer_name, order_date FROM orders WHERE order_sta...
                                              ^

Failed query
Running query: SELECT supplier_name, product_name FROM suppliers INNER JOIN products ON suppliers.supplier_id = products.supplier_id WHERE products.price > 50

06-21 16:16:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:50 -> SELECT supplier_name, product_name FROM suppliers INNER JOIN products ON suppliers.supplier_id = products.supplier_id WHERE products.price > 50
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:50 -> SELECT supplier_name, product_name FROM suppliers INNER JOIN products ON suppliers.supplier_id = products.supplier_id WHERE products.price > 50
ERROR:root:Database error: relation "suppliers" does not exist
LINE 1: SELECT supplier_name, product_name FROM suppliers INNER JOIN...
                                                ^

Failed query
Running query: SELECT player_id, passes_total FROM public.vt_season_stat_player ORDER BY passes_total DESC LIMIT 1

06-21 16:16:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:16:50 -> SELECT player_id, passes_total FROM public.vt_season_stat_player ORDER BY passes_total DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:16:50 -> SELECT player_id, passes_total FROM public.vt_season_stat_player ORDER BY passes_total DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT product_name FROM products WHERE condition and product_name IS NOT NULL

06-21 16:17:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:29 -> SELECT product_name FROM products WHERE condition and product_name IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:29 -> SELECT product_name FROM products WHERE condition and product_name IS NOT NULL
ERROR:root:Database error: relation "products" does not exist
LINE 1: SELECT product_name FROM products WHERE condition and produc...
                                 ^

Failed query
Running query: SELECT category_name FROM categories WHERE condition and category_name IS NOT NULL

06-21 16:17:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:29 -> SELECT category_name FROM categories WHERE condition and category_name IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:29 -> SELECT category_name FROM categories WHERE condition and category_name IS NOT NULL
ERROR:root:Database error: relation "categories" does not exist
LINE 1: SELECT category_name FROM categories WHERE condition and cat...
                                  ^

Failed query
Running query: SELECT supplier_name FROM suppliers WHERE condition and supplier_name IS NOT NULL

06-21 16:17:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:29 -> SELECT supplier_name FROM suppliers WHERE condition and supplier_name IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:29 -> SELECT supplier_name FROM suppliers WHERE condition and supplier_name IS NOT NULL
ERROR:root:Database error: relation "suppliers" does not exist
LINE 1: SELECT supplier_name FROM suppliers WHERE condition and supp...
                                  ^

Failed query
Running query: SELECT assists, goals, non_penalty_goals FROM public.vt_season_info_player WHERE player_id = 80759 AND season_id = 816019

06-21 16:17:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:29 -> SELECT assists, goals, non_penalty_goals FROM public.vt_season_info_player WHERE player_id = 80759 AND season_id = 816019
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:29 -> SELECT assists, goals, non_penalty_goals FROM public.vt_season_info_player WHERE player_id = 80759 AND season_id = 816019

Successful query
Data Shape: (0, 3)
Running query: SELECT xg, xa, xg_faced, xt FROM public.vt_season_info_player WHERE player_id = 80759 AND season_id = 816019

06-21 16:17:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:29 -> SELECT xg, xa, xg_faced, xt FROM public.vt_season_info_player WHERE player_id = 80759 AND season_id = 816019
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:29 -> SELECT xg, xa, xg_faced, xt FROM public.vt_season_info_player WHERE player_id = 80759 AND season_id = 816019

Successful query
Data Shape: (0, 4)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

06-21 16:17:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:29 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:29 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT name FROM t_team WHERE country_id = (SELECT country_id FROM t_team WHERE name = 'Hello') AND name IS NOT NULL

06-21 16:17:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:29 -> SELECT name FROM t_team WHERE country_id = (SELECT country_id FROM t_team WHERE name = 'Hello') AND name IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:29 -> SELECT name FROM t_team WHERE country_id = (SELECT country_id FROM t_team WHERE name = 'Hello') AND name IS NOT NULL

Successful query
Data Shape: (0, 1)
Running query: SELECT name FROM t_player WHERE country_id = (SELECT country_id FROM t_team WHERE name = 'Hello') AND name IS NOT NULL

06-21 16:17:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:30 -> SELECT name FROM t_player WHERE country_id = (SELECT country_id FROM t_team WHERE name = 'Hello') AND name IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:30 -> SELECT name FROM t_player WHERE country_id = (SELECT country_id FROM t_team WHERE name = 'Hello') AND name IS NOT NULL

Successful query
Data Shape: (0, 1)
Running query: SELECT name, market_value FROM public.t_team WHERE team_id = 4266 AND market_value IS NOT NULL

06-21 16:17:31 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:31 -> SELECT name, market_value FROM public.t_team WHERE team_id = 4266 AND market_value IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:31 -> SELECT name, market_value FROM public.t_team WHERE team_id = 4266 AND market_value IS NOT NULL

Successful query
Data Shape: (1, 2)
Running query: SELECT team_name, gbe_tier FROM public.v_team_notm WHERE team_id = 4266 AND gbe_tier IS NOT NULL

06-21 16:17:31 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:31 -> SELECT team_name, gbe_tier FROM public.v_team_notm WHERE team_id = 4266 AND gbe_tier IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:31 -> SELECT team_name, gbe_tier FROM public.v_team_notm WHERE team_id = 4266 AND gbe_tier IS NOT NULL

Successful query
Data Shape: (0, 2)
Running query: SELECT transfer_balance FROM public.agg_season_team_info WHERE team_id = 4266 AND transfer_balance IS NOT NULL

06-21 16:17:31 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:31 -> SELECT transfer_balance FROM public.agg_season_team_info WHERE team_id = 4266 AND transfer_balance IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:31 -> SELECT transfer_balance FROM public.agg_season_team_info WHERE team_id = 4266 AND transfer_balance IS NOT NULL

Successful query
Data Shape: (5, 1)
Running query: SELECT player_id, dribbles_total FROM public.vt_season_opta_player WHERE team_id = 4265 AND dribbles_total IS NOT NULL ORDER BY dribbles_total DESC LIMIT 5

06-21 16:17:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:32 -> SELECT player_id, dribbles_total FROM public.vt_season_opta_player WHERE team_id = 4265 AND dribbles_total IS NOT NULL ORDER BY dribbles_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:32 -> SELECT player_id, dribbles_total FROM public.vt_season_opta_player WHERE team_id = 4265 AND dribbles_total IS NOT NULL ORDER BY dribbles_total DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, dribbles_total FROM public.vt_season_stat_player WHERE team_id = 4265 AND dribbles_total IS NOT NULL ORDER BY dribbles_total DESC LIMIT 5

06-21 16:17:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:32 -> SELECT player_id, dribbles_total FROM public.vt_season_stat_player WHERE team_id = 4265 AND dribbles_total IS NOT NULL ORDER BY dribbles_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:32 -> SELECT player_id, dribbles_total FROM public.vt_season_stat_player WHERE team_id = 4265 AND dribbles_total IS NOT NULL ORDER BY dribbles_total DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:17:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:32 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:32 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, avg_max_speed FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY avg_max_speed DESC LIMIT 1

06-21 16:17:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:32 -> SELECT player_id, avg_max_speed FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY avg_max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:32 -> SELECT player_id, avg_max_speed FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY avg_max_speed DESC LIMIT 1
ERROR:root:Database error: column "avg_max_speed" does not exist
LINE 1: SELECT player_id, avg_max_speed FROM public.vt_season_metric...
                          ^

Failed query
Running query: SELECT player_id, goals FROM public.vt_season_info_player WHERE player_id = 45067 AND season_id = 816530 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

06-21 16:17:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:32 -> SELECT player_id, goals FROM public.vt_season_info_player WHERE player_id = 45067 AND season_id = 816530 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:32 -> SELECT player_id, goals FROM public.vt_season_info_player WHERE player_id = 45067 AND season_id = 816530 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, goals FROM public.vt_season_opta_player WHERE player_id = 45067 AND season_id = 816530 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

06-21 16:17:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:32 -> SELECT player_id, goals FROM public.vt_season_opta_player WHERE player_id = 45067 AND season_id = 816530 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:32 -> SELECT player_id, goals FROM public.vt_season_opta_player WHERE player_id = 45067 AND season_id = 816530 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816528 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

06-21 16:17:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:32 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816528 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:32 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816528 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816528 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1

06-21 16:17:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:32 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816528 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:32 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816528 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, team_id, passes_total FROM public.vt_season_stat_player WHERE season_id = 816529 ORDER BY passes_total DESC LIMIT 1

06-21 16:17:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:32 -> SELECT player_id, team_id, passes_total FROM public.vt_season_stat_player WHERE season_id = 816529 ORDER BY passes_total DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:32 -> SELECT player_id, team_id, passes_total FROM public.vt_season_stat_player WHERE season_id = 816529 ORDER BY passes_total DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, team_id, passes_accurate FROM public.vt_season_opta_player WHERE season_id = 816529 ORDER BY passes_accurate DESC LIMIT 1

06-21 16:17:35 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:35 -> SELECT player_id, team_id, passes_accurate FROM public.vt_season_opta_player WHERE season_id = 816529 ORDER BY passes_accurate DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:35 -> SELECT player_id, team_id, passes_accurate FROM public.vt_season_opta_player WHERE season_id = 816529 ORDER BY passes_accurate DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, xa FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xa DESC LIMIT 1

06-21 16:17:35 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:35 -> SELECT player_id, xa FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xa DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:35 -> SELECT player_id, xa FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xa DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, assists FROM public.vt_season_opta_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY assists DESC LIMIT 1

06-21 16:17:35 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:35 -> SELECT player_id, assists FROM public.vt_season_opta_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY assists DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:35 -> SELECT player_id, assists FROM public.vt_season_opta_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY assists DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT team_name, country_code, gbe_tier, league_id FROM public.v_team_notm WHERE team_id = 4266

06-21 16:17:35 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:35 -> SELECT team_name, country_code, gbe_tier, league_id FROM public.v_team_notm WHERE team_id = 4266
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:35 -> SELECT team_name, country_code, gbe_tier, league_id FROM public.v_team_notm WHERE team_id = 4266

Successful query
Data Shape: (0, 4)
Running query: SELECT * FROM public.agg_season_team_info WHERE team_id = 4266 AND season_id = 816527

06-21 16:17:35 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:35 -> SELECT * FROM public.agg_season_team_info WHERE team_id = 4266 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:35 -> SELECT * FROM public.agg_season_team_info WHERE team_id = 4266 AND season_id = 816527

Successful query
Data Shape: (1, 14)
Running query: SELECT ranking, wins, draws, loses, goals, goals_against, diff_goals, points FROM public.t_season_team_rank WHERE team_id = 4266 AND season_id = 816527

06-21 16:17:35 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:35 -> SELECT ranking, wins, draws, loses, goals, goals_against, diff_goals, points FROM public.t_season_team_rank WHERE team_id = 4266 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:35 -> SELECT ranking, wins, draws, loses, goals, goals_against, diff_goals, points FROM public.t_season_team_rank WHERE team_id = 4266 AND season_id = 816527

Successful query
Data Shape: (1, 8)
Running query: SELECT player_id, name, height FROM public.vt_season_stat_player ORDER BY scoring_contribution DESC LIMIT 10

06-21 16:17:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:36 -> SELECT player_id, name, height FROM public.vt_season_stat_player ORDER BY scoring_contribution DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:36 -> SELECT player_id, name, height FROM public.vt_season_stat_player ORDER BY scoring_contribution DESC LIMIT 10
ERROR:root:Database error: column "name" does not exist
LINE 1: SELECT player_id, name, height FROM public.vt_season_stat_pl...
                          ^

Failed query
Running query: SELECT player_id, name, height FROM public.vt_season_metric_player ORDER BY xp DESC LIMIT 10

06-21 16:17:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:36 -> SELECT player_id, name, height FROM public.vt_season_metric_player ORDER BY xp DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:36 -> SELECT player_id, name, height FROM public.vt_season_metric_player ORDER BY xp DESC LIMIT 10
ERROR:root:Database error: column "name" does not exist
LINE 1: SELECT player_id, name, height FROM public.vt_season_metric_...
                          ^
HINT:  Perhaps you meant to reference the column "vt_season_metric_player.games".

Failed query
Running query: SELECT player_id, name, height FROM public.vt_season_opta_player ORDER BY progressive_passes_total DESC LIMIT 10

06-21 16:17:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:36 -> SELECT player_id, name, height FROM public.vt_season_opta_player ORDER BY progressive_passes_total DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:36 -> SELECT player_id, name, height FROM public.vt_season_opta_player ORDER BY progressive_passes_total DESC LIMIT 10
ERROR:root:Database error: column "name" does not exist
LINE 1: SELECT player_id, name, height FROM public.vt_season_opta_pl...
                          ^

Failed query
Running query: SELECT position FROM public.vt_season_position_player WHERE player_id = 151980 AND season_id = 816527 AND team_id = 14350 AND position IS NOT NULL

06-21 16:17:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:36 -> SELECT position FROM public.vt_season_position_player WHERE player_id = 151980 AND season_id = 816527 AND team_id = 14350 AND position IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:36 -> SELECT position FROM public.vt_season_position_player WHERE player_id = 151980 AND season_id = 816527 AND team_id = 14350 AND position IS NOT NULL

Successful query
Data Shape: (3, 1)
Running query: SELECT field_position_id FROM public.vt_season_position_player WHERE player_id = 151980 AND season_id = 816527 AND team_id = 14350 AND field_position_id IS NOT NULL

06-21 16:17:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:36 -> SELECT field_position_id FROM public.vt_season_position_player WHERE player_id = 151980 AND season_id = 816527 AND team_id = 14350 AND field_position_id IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:36 -> SELECT field_position_id FROM public.vt_season_position_player WHERE player_id = 151980 AND season_id = 816527 AND team_id = 14350 AND field_position_id IS NOT NULL

Successful query
Data Shape: (3, 1)
Running query: SELECT xg FROM public.vt_game_metric_player WHERE player_id = 45067 AND season_id = 816530 AND team_id = 3651

06-21 16:17:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:36 -> SELECT xg FROM public.vt_game_metric_player WHERE player_id = 45067 AND season_id = 816530 AND team_id = 3651
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:36 -> SELECT xg FROM public.vt_game_metric_player WHERE player_id = 45067 AND season_id = 816530 AND team_id = 3651

Successful query
Data Shape: (20, 1)
Running query: SELECT xg FROM public.vt_season_metric_player WHERE player_id = 45067 AND season_id = 816530 AND team_id = 3651

06-21 16:17:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:36 -> SELECT xg FROM public.vt_season_metric_player WHERE player_id = 45067 AND season_id = 816530 AND team_id = 3651
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:36 -> SELECT xg FROM public.vt_season_metric_player WHERE player_id = 45067 AND season_id = 816530 AND team_id = 3651

Successful query
Data Shape: (1, 1)
Running query: SELECT goals FROM public.vt_season_info_player WHERE player_id = (SELECT player_id FROM t_player WHERE name = 'Harry Kane') AND goals IS NOT NULL

06-21 16:17:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:36 -> SELECT goals FROM public.vt_season_info_player WHERE player_id = (SELECT player_id FROM t_player WHERE name = 'Harry Kane') AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:36 -> SELECT goals FROM public.vt_season_info_player WHERE player_id = (SELECT player_id FROM t_player WHERE name = 'Harry Kane') AND goals IS NOT NULL

Successful query
Data Shape: (20, 1)
Running query: SELECT goals FROM public.vt_season_opta_player WHERE player_id = (SELECT player_id FROM t_player WHERE name = 'Harry Kane') AND goals IS NOT NULL

06-21 16:17:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:37 -> SELECT goals FROM public.vt_season_opta_player WHERE player_id = (SELECT player_id FROM t_player WHERE name = 'Harry Kane') AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:37 -> SELECT goals FROM public.vt_season_opta_player WHERE player_id = (SELECT player_id FROM t_player WHERE name = 'Harry Kane') AND goals IS NOT NULL

Successful query
Data Shape: (20, 1)
Running query: SELECT team_id, name, alias FROM t_team WHERE country_id = 'Key information'

06-21 16:17:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:37 -> SELECT team_id, name, alias FROM t_team WHERE country_id = 'Key information'
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:37 -> SELECT team_id, name, alias FROM t_team WHERE country_id = 'Key information'
ERROR:root:Database error: invalid input syntax for integer: "Key information"
LINE 1: ...am_id, name, alias FROM t_team WHERE country_id = 'Key infor...
                                                             ^

Failed query
Running query: SELECT player_id, name, position FROM t_player WHERE country_id = 'Key information' AND position IS NOT NULL

06-21 16:17:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:37 -> SELECT player_id, name, position FROM t_player WHERE country_id = 'Key information' AND position IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:37 -> SELECT player_id, name, position FROM t_player WHERE country_id = 'Key information' AND position IS NOT NULL
ERROR:root:Database error: invalid input syntax for integer: "Key information"
LINE 1: ..., name, position FROM t_player WHERE country_id = 'Key infor...
                                                             ^

Failed query
Running query: SELECT match_id, season_id, home_team_id, away_team_id, home_score, away_score, match_date FROM t_match WHERE country_id = 'Key information'

06-21 16:17:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:37 -> SELECT match_id, season_id, home_team_id, away_team_id, home_score, away_score, match_date FROM t_match WHERE country_id = 'Key information'
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:37 -> SELECT match_id, season_id, home_team_id, away_team_id, home_score, away_score, match_date FROM t_match WHERE country_id = 'Key information'
ERROR:root:Database error: column "home_score" does not exist
LINE 1: ... match_id, season_id, home_team_id, away_team_id, home_score...
                                                             ^

Failed query
Running query: SELECT player_id, dribbles_total FROM public.vt_season_opta_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY dribbles_total DESC LIMIT 1

06-21 16:17:38 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:38 -> SELECT player_id, dribbles_total FROM public.vt_season_opta_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY dribbles_total DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:38 -> SELECT player_id, dribbles_total FROM public.vt_season_opta_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY dribbles_total DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, dribbles_total FROM public.vt_season_opta_player WHERE team_id = 4265 AND season_id = 816527 AND dribbles_total IS NOT NULL ORDER BY dribbles_total DESC LIMIT 1

06-21 16:17:38 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:38 -> SELECT player_id, dribbles_total FROM public.vt_season_opta_player WHERE team_id = 4265 AND season_id = 816527 AND dribbles_total IS NOT NULL ORDER BY dribbles_total DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:38 -> SELECT player_id, dribbles_total FROM public.vt_season_opta_player WHERE team_id = 4265 AND season_id = 816527 AND dribbles_total IS NOT NULL ORDER BY dribbles_total DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT ranking, wins, draws, loses, goals, goals_against, points FROM public.t_season_team_rank WHERE season_id = 816527 AND team_id = 63403

06-21 16:17:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:40 -> SELECT ranking, wins, draws, loses, goals, goals_against, points FROM public.t_season_team_rank WHERE season_id = 816527 AND team_id = 63403
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:40 -> SELECT ranking, wins, draws, loses, goals, goals_against, points FROM public.t_season_team_rank WHERE season_id = 816527 AND team_id = 63403

Successful query
Data Shape: (0, 7)
Running query: SELECT strength_of_schedule, games_remaining, match_date FROM pro.agg_history_season_team_sos WHERE season_id = 816527 AND team_id = 63403

06-21 16:17:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:40 -> SELECT strength_of_schedule, games_remaining, match_date FROM pro.agg_history_season_team_sos WHERE season_id = 816527 AND team_id = 63403
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:40 -> SELECT strength_of_schedule, games_remaining, match_date FROM pro.agg_history_season_team_sos WHERE season_id = 816527 AND team_id = 63403

Successful query
Data Shape: (0, 3)
Running query: SELECT player_id, xg, xa FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg DESC, xa DESC LIMIT 5

06-21 16:17:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:40 -> SELECT player_id, xg, xa FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg DESC, xa DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:40 -> SELECT player_id, xg, xa FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg DESC, xa DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, xg, xg_chain FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg DESC, xg_chain DESC LIMIT 5

06-21 16:17:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:40 -> SELECT player_id, xg, xg_chain FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg DESC, xg_chain DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:40 -> SELECT player_id, xg, xg_chain FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg DESC, xg_chain DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, goals FROM public.vt_season_info_player WHERE season_id = 816529 ORDER BY goals DESC LIMIT 1

06-21 16:17:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:40 -> SELECT player_id, goals FROM public.vt_season_info_player WHERE season_id = 816529 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:40 -> SELECT player_id, goals FROM public.vt_season_info_player WHERE season_id = 816529 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, non_penalty_goals FROM public.vt_season_stat_player WHERE season_id = 816529 ORDER BY non_penalty_goals DESC LIMIT 1

06-21 16:17:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:41 -> SELECT player_id, non_penalty_goals FROM public.vt_season_stat_player WHERE season_id = 816529 ORDER BY non_penalty_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:41 -> SELECT player_id, non_penalty_goals FROM public.vt_season_stat_player WHERE season_id = 816529 ORDER BY non_penalty_goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, goals FROM public.vt_season_metric_player WHERE season_id = 816529 ORDER BY goals DESC LIMIT 1

06-21 16:17:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:41 -> SELECT player_id, goals FROM public.vt_season_metric_player WHERE season_id = 816529 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:41 -> SELECT player_id, goals FROM public.vt_season_metric_player WHERE season_id = 816529 ORDER BY goals DESC LIMIT 1
ERROR:root:Database error: column "goals" does not exist
LINE 1: SELECT player_id, goals FROM public.vt_season_metric_player ...
                          ^

Failed query
Running query: SELECT goals FROM public.agg_competition_player WHERE player_id = 1296920 AND team_id = 4265 AND competition_id = 816527 AND goals IS NOT NULL

06-21 16:17:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:41 -> SELECT goals FROM public.agg_competition_player WHERE player_id = 1296920 AND team_id = 4265 AND competition_id = 816527 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:41 -> SELECT goals FROM public.agg_competition_player WHERE player_id = 1296920 AND team_id = 4265 AND competition_id = 816527 AND goals IS NOT NULL

Successful query
Data Shape: (0, 1)
Running query: SELECT goals FROM public.vt_game_stat_player WHERE player_id = 1296920 AND team_id = 4265 AND season_id = 816527 AND goals IS NOT NULL

06-21 16:17:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:41 -> SELECT goals FROM public.vt_game_stat_player WHERE player_id = 1296920 AND team_id = 4265 AND season_id = 816527 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:41 -> SELECT goals FROM public.vt_game_stat_player WHERE player_id = 1296920 AND team_id = 4265 AND season_id = 816527 AND goals IS NOT NULL

Successful query
Data Shape: (20, 1)
Running query: SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

06-21 16:17:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:41 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:41 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, goals FROM public.agg_season_player_pd WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

06-21 16:17:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:41 -> SELECT player_id, goals FROM public.agg_season_player_pd WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:41 -> SELECT player_id, goals FROM public.agg_season_player_pd WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
ERROR:root:Database error: column "goals" does not exist
LINE 1: SELECT player_id, goals FROM public.agg_season_player_pd WHE...
                          ^

Failed query
Running query: SELECT player_id, goals FROM vm_agg_season_team WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

06-21 16:17:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:42 -> SELECT player_id, goals FROM vm_agg_season_team WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:42 -> SELECT player_id, goals FROM vm_agg_season_team WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
ERROR:root:Database error: column "player_id" does not exist
LINE 1: SELECT player_id, goals FROM vm_agg_season_team WHERE season...
               ^

Failed query
Running query: SELECT COUNT(DISTINCT match_id) FROM public.t_goal WHERE player_id = 1163220 AND season_id = 816527 AND outcome = TRUE

06-21 16:17:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:42 -> SELECT COUNT(DISTINCT match_id) FROM public.t_goal WHERE player_id = 1163220 AND season_id = 816527 AND outcome = TRUE
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:42 -> SELECT COUNT(DISTINCT match_id) FROM public.t_goal WHERE player_id = 1163220 AND season_id = 816527 AND outcome = TRUE
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ... FROM public.t_goal WHERE player_id = 1163220 AND season_id ...
                                                             ^

Failed query
Running query: SELECT COUNT(DISTINCT match_id) FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527 AND goals > 0

06-21 16:17:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:42 -> SELECT COUNT(DISTINCT match_id) FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527 AND goals > 0
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:42 -> SELECT COUNT(DISTINCT match_id) FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527 AND goals > 0
ERROR:root:Database error: column "match_id" does not exist
LINE 1: SELECT COUNT(DISTINCT match_id) FROM vm_agg_season_player_op...
                              ^

Failed query
Running query: SELECT COUNT(*) FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527 AND goals > 0

06-21 16:17:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:42 -> SELECT COUNT(*) FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527 AND goals > 0
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:42 -> SELECT COUNT(*) FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527 AND goals > 0

Successful query
Data Shape: (1, 1)
Running query: SELECT COUNT(*) FROM vm_agg_season_player_all WHERE player_id = 1163220 AND season_id = 816527 AND games_lost = 0

06-21 16:17:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:42 -> SELECT COUNT(*) FROM vm_agg_season_player_all WHERE player_id = 1163220 AND season_id = 816527 AND games_lost = 0
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:42 -> SELECT COUNT(*) FROM vm_agg_season_player_all WHERE player_id = 1163220 AND season_id = 816527 AND games_lost = 0
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT COUNT(*) FROM vm_agg_season_player_all WHERE player_i...
                             ^

Failed query
Running query: SELECT COUNT(*) FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527 AND score_pd > 0

06-21 16:17:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:42 -> SELECT COUNT(*) FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527 AND score_pd > 0
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:42 -> SELECT COUNT(*) FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527 AND score_pd > 0

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1

06-21 16:17:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:42 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:42 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...goal_id) AS goals_scored FROM public.t_goal WHERE season_id ...
                                                             ^

Failed query
Running query: SELECT player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_label = 'La Liga' ORDER BY goals DESC LIMIT 1

06-21 16:17:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:42 -> SELECT player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_label = 'La Liga' ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:42 -> SELECT player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_label = 'La Liga' ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_name, position, score_diff FROM vm_agg_year_player_loan WHERE current_year_team_name != 'Real Madrid' AND position IN ('FW', 'AMC', 'AMR') AND current_season_id = 816527 ORDER BY score_diff DESC LIMIT 1

06-21 16:17:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:42 -> SELECT player_name, position, score_diff FROM vm_agg_year_player_loan WHERE current_year_team_name != 'Real Madrid' AND position IN ('FW', 'AMC', 'AMR') AND current_season_id = 816527 ORDER BY score_diff DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:42 -> SELECT player_name, position, score_diff FROM vm_agg_year_player_loan WHERE current_year_team_name != 'Real Madrid' AND position IN ('FW', 'AMC', 'AMR') AND current_season_id = 816527 ORDER BY score_diff DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND goals_90 IS NOT NULL AND age < 25 ORDER BY goals_90 DESC LIMIT 5

06-21 16:17:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:45 -> SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND goals_90 IS NOT NULL AND age < 25 ORDER BY goals_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:45 -> SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND goals_90 IS NOT NULL AND age < 25 ORDER BY goals_90 DESC LIMIT 5
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: SELECT player_id, player_name, goals_90 FROM vm_agg_season_p...
                                       ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_all WHERE season_id = 816527 AND goals_90 IS NOT NULL AND age < 25 ORDER BY goals_90 DESC LIMIT 5

06-21 16:17:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:45 -> SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_all WHERE season_id = 816527 AND goals_90 IS NOT NULL AND age < 25 ORDER BY goals_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:45 -> SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_all WHERE season_id = 816527 AND goals_90 IS NOT NULL AND age < 25 ORDER BY goals_90 DESC LIMIT 5
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, player_name, goals_90 FROM vm_agg_season_p...
                                                     ^

Failed query
Running query: SELECT player_id, team_id, season_id, age FROM t_player WHERE team_id = 4265 AND age < 25 ORDER BY age ASC LIMIT 1

06-21 16:17:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:45 -> SELECT player_id, team_id, season_id, age FROM t_player WHERE team_id = 4265 AND age < 25 ORDER BY age ASC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:45 -> SELECT player_id, team_id, season_id, age FROM t_player WHERE team_id = 4265 AND age < 25 ORDER BY age ASC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: SELECT player_id, team_id, season_id, age FROM t_player WHER...
                                   ^

Failed query
Running query: SELECT player_id, team_id, season_id, age FROM t_player WHERE team_id = 4265 AND age < 25 ORDER BY age DESC LIMIT 1

06-21 16:17:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:45 -> SELECT player_id, team_id, season_id, age FROM t_player WHERE team_id = 4265 AND age < 25 ORDER BY age DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:45 -> SELECT player_id, team_id, season_id, age FROM t_player WHERE team_id = 4265 AND age < 25 ORDER BY age DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: SELECT player_id, team_id, season_id, age FROM t_player WHER...
                                   ^

Failed query
Running query: SELECT player_id, team_id, season_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM t_player WHERE age < 20) ORDER BY max_speed DESC LIMIT 5

06-21 16:17:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:45 -> SELECT player_id, team_id, season_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM t_player WHERE age < 20) ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:45 -> SELECT player_id, team_id, season_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM t_player WHERE age < 20) ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, player_name, age FROM vm_agg_season_player_all WHERE age < 25 AND season_id = 816527 AND team_id = 4265 ORDER BY player_name ASC LIMIT 1

06-21 16:17:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:46 -> SELECT player_id, player_name, age FROM vm_agg_season_player_all WHERE age < 25 AND season_id = 816527 AND team_id = 4265 ORDER BY player_name ASC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:46 -> SELECT player_id, player_name, age FROM vm_agg_season_player_all WHERE age < 25 AND season_id = 816527 AND team_id = 4265 ORDER BY player_name ASC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, player_name, age FROM vm_agg_season_player...
                                                ^

Failed query
Running query: SELECT player_id, player_name, age FROM vm_agg_season_player_similarity WHERE age < 25 AND season_id = 816527 AND team_id = 4265 ORDER BY age ASC LIMIT 1

06-21 16:17:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:46 -> SELECT player_id, player_name, age FROM vm_agg_season_player_similarity WHERE age < 25 AND season_id = 816527 AND team_id = 4265 ORDER BY age ASC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:46 -> SELECT player_id, player_name, age FROM vm_agg_season_player_similarity WHERE age < 25 AND season_id = 816527 AND team_id = 4265 ORDER BY age ASC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT pct_int_game, band_league, band_cont_league, gbe_score FROM vm_det_player_gbe WHERE player_id = 1598188 AND regular_season_id = 816527

06-21 16:17:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:46 -> SELECT pct_int_game, band_league, band_cont_league, gbe_score FROM vm_det_player_gbe WHERE player_id = 1598188 AND regular_season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:46 -> SELECT pct_int_game, band_league, band_cont_league, gbe_score FROM vm_det_player_gbe WHERE player_id = 1598188 AND regular_season_id = 816527
ERROR:root:Database error: relation "vm_det_player_gbe" does not exist
LINE 1: ...me, band_league, band_cont_league, gbe_score FROM vm_det_pla...
                                                             ^

Failed query
Running query: SELECT band_league, band_cont_league, gbe_score FROM vm_det_player_gbe WHERE team_id = 20076 AND regular_season_id = 816527

06-21 16:17:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:46 -> SELECT band_league, band_cont_league, gbe_score FROM vm_det_player_gbe WHERE team_id = 20076 AND regular_season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:46 -> SELECT band_league, band_cont_league, gbe_score FROM vm_det_player_gbe WHERE team_id = 20076 AND regular_season_id = 816527
ERROR:root:Database error: relation "vm_det_player_gbe" does not exist
LINE 1: ...ECT band_league, band_cont_league, gbe_score FROM vm_det_pla...
                                                             ^

Failed query
Running query: SELECT player_name, goals, assists, yellow_cards, red_cards FROM vm_agg_year_player_info WHERE player_name = 'Lamine Yamal' AND year = 2023

06-21 16:17:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:46 -> SELECT player_name, goals, assists, yellow_cards, red_cards FROM vm_agg_year_player_info WHERE player_name = 'Lamine Yamal' AND year = 2023
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:46 -> SELECT player_name, goals, assists, yellow_cards, red_cards FROM vm_agg_year_player_info WHERE player_name = 'Lamine Yamal' AND year = 2023

Successful query
Data Shape: (2, 5)
Running query: SELECT score_this_year, mins_played_this_year, mins_perc_this_year FROM vm_agg_year_player_loan WHERE player_name = 'Lamine Yamal' AND current_year_team_name = 'FC Barcelona'

06-21 16:17:58 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:58 -> SELECT score_this_year, mins_played_this_year, mins_perc_this_year FROM vm_agg_year_player_loan WHERE player_name = 'Lamine Yamal' AND current_year_team_name = 'FC Barcelona'
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:58 -> SELECT score_this_year, mins_played_this_year, mins_perc_this_year FROM vm_agg_year_player_loan WHERE player_name = 'Lamine Yamal' AND current_year_team_name = 'FC Barcelona'

Successful query
Data Shape: (1, 3)
Running query: SELECT player_name, goals, assists, yellow_cards, red_cards FROM vm_agg_year_player_info WHERE player_id = 1776309 AND year = 2023 AND team_id = 4279

06-21 16:17:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:59 -> SELECT player_name, goals, assists, yellow_cards, red_cards FROM vm_agg_year_player_info WHERE player_id = 1776309 AND year = 2023 AND team_id = 4279
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:59 -> SELECT player_name, goals, assists, yellow_cards, red_cards FROM vm_agg_year_player_info WHERE player_id = 1776309 AND year = 2023 AND team_id = 4279
ERROR:root:Database error: column "team_id" does not exist
LINE 1: ...nfo WHERE player_id = 1776309 AND year = 2023 AND team_id = ...
                                                             ^

Failed query
Running query: SELECT score_this_year, mins_played_this_year, mins_perc_this_year FROM vm_agg_year_player_loan WHERE player_id = 1776309 AND current_year_team_id = 4279 AND current_season_id = 816527

06-21 16:17:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:59 -> SELECT score_this_year, mins_played_this_year, mins_perc_this_year FROM vm_agg_year_player_loan WHERE player_id = 1776309 AND current_year_team_id = 4279 AND current_season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:59 -> SELECT score_this_year, mins_played_this_year, mins_perc_this_year FROM vm_agg_year_player_loan WHERE player_id = 1776309 AND current_year_team_id = 4279 AND current_season_id = 816527

Successful query
Data Shape: (1, 3)
Running query: SELECT global_score FROM vm_det_player_placer WHERE player_id = 1598188 AND regular_season_id = 816527

06-21 16:17:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:59 -> SELECT global_score FROM vm_det_player_placer WHERE player_id = 1598188 AND regular_season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:59 -> SELECT global_score FROM vm_det_player_placer WHERE player_id = 1598188 AND regular_season_id = 816527
ERROR:root:Database error: relation "vm_det_player_placer" does not exist
LINE 1: SELECT global_score FROM vm_det_player_placer WHERE player_i...
                                 ^

Failed query
Running query: SELECT gbe_score FROM vm_det_player_gbe WHERE player_id = 1598188 AND regular_season_id = 816527

06-21 16:17:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:59 -> SELECT gbe_score FROM vm_det_player_gbe WHERE player_id = 1598188 AND regular_season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:59 -> SELECT gbe_score FROM vm_det_player_gbe WHERE player_id = 1598188 AND regular_season_id = 816527
ERROR:root:Database error: relation "vm_det_player_gbe" does not exist
LINE 1: SELECT gbe_score FROM vm_det_player_gbe WHERE player_id = 15...
                              ^

Failed query
Running query: SELECT gbe_score FROM vm_det_player_gbe WHERE team_id = 20076 AND regular_season_id = 816527

06-21 16:17:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:59 -> SELECT gbe_score FROM vm_det_player_gbe WHERE team_id = 20076 AND regular_season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:59 -> SELECT gbe_score FROM vm_det_player_gbe WHERE team_id = 20076 AND regular_season_id = 816527
ERROR:root:Database error: relation "vm_det_player_gbe" does not exist
LINE 1: SELECT gbe_score FROM vm_det_player_gbe WHERE team_id = 2007...
                              ^

Failed query
Running query: SELECT COUNT(*) FROM vm_agg_season_team WHERE player_id = 1163220 AND season_id = 816527 AND goals > 0

06-21 16:17:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:59 -> SELECT COUNT(*) FROM vm_agg_season_team WHERE player_id = 1163220 AND season_id = 816527 AND goals > 0
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:59 -> SELECT COUNT(*) FROM vm_agg_season_team WHERE player_id = 1163220 AND season_id = 816527 AND goals > 0
ERROR:root:Database error: column "player_id" does not exist
LINE 1: SELECT COUNT(*) FROM vm_agg_season_team WHERE player_id = 11...
                                                      ^

Failed query
Running query: SELECT * FROM vm_det_player_gbe WHERE player_id = 1646392 AND band_league IS NOT NULL

06-21 16:17:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:17:59 -> SELECT * FROM vm_det_player_gbe WHERE player_id = 1646392 AND band_league IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:17:59 -> SELECT * FROM vm_det_player_gbe WHERE player_id = 1646392 AND band_league IS NOT NULL
ERROR:root:Database error: relation "vm_det_player_gbe" does not exist
LINE 1: SELECT * FROM vm_det_player_gbe WHERE player_id = 1646392 AN...
                      ^

Failed query
Running query: SELECT * FROM vm_det_player_placer WHERE player_id = 1646392 AND global_score IS NOT NULL

06-21 16:18:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:00 -> SELECT * FROM vm_det_player_placer WHERE player_id = 1646392 AND global_score IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:00 -> SELECT * FROM vm_det_player_placer WHERE player_id = 1646392 AND global_score IS NOT NULL
ERROR:root:Database error: relation "vm_det_player_placer" does not exist
LINE 1: SELECT * FROM vm_det_player_placer WHERE player_id = 1646392...
                      ^

Failed query
Running query: SELECT * FROM vm_det_player_placer WHERE player_id = 1646392 AND index_score IS NOT NULL

06-21 16:18:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:00 -> SELECT * FROM vm_det_player_placer WHERE player_id = 1646392 AND index_score IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:00 -> SELECT * FROM vm_det_player_placer WHERE player_id = 1646392 AND index_score IS NOT NULL
ERROR:root:Database error: relation "vm_det_player_placer" does not exist
LINE 1: SELECT * FROM vm_det_player_placer WHERE player_id = 1646392...
                      ^

Failed query
Running query: SELECT field_position_id FROM vm_det_player_placer WHERE player_id = 1598188 AND team_id = 20076 AND season_id = 816527

06-21 16:18:02 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:02 -> SELECT field_position_id FROM vm_det_player_placer WHERE player_id = 1598188 AND team_id = 20076 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:02 -> SELECT field_position_id FROM vm_det_player_placer WHERE player_id = 1598188 AND team_id = 20076 AND season_id = 816527
ERROR:root:Database error: relation "vm_det_player_placer" does not exist
LINE 1: SELECT field_position_id FROM vm_det_player_placer WHERE pla...
                                      ^

Failed query
Running query: SELECT player_id, pct_int_game, current_band_league, last_band_league, band_league, gbe_score FROM vm_det_player_gbe WHERE player_id = 1598188 AND band_league IS NOT NULL AND regular_season_id = 816527

06-21 16:18:02 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:02 -> SELECT player_id, pct_int_game, current_band_league, last_band_league, band_league, gbe_score FROM vm_det_player_gbe WHERE player_id = 1598188 AND band_league IS NOT NULL AND regular_season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:02 -> SELECT player_id, pct_int_game, current_band_league, last_band_league, band_league, gbe_score FROM vm_det_player_gbe WHERE player_id = 1598188 AND band_league IS NOT NULL AND regular_season_id = 816527
ERROR:root:Database error: relation "vm_det_player_gbe" does not exist
LINE 1: ...ue, last_band_league, band_league, gbe_score FROM vm_det_pla...
                                                             ^

Failed query
Running query: SELECT player_id FROM public.vt_season_info_player WHERE goals > 15 AND season_id = 816527

06-21 16:18:02 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:02 -> SELECT player_id FROM public.vt_season_info_player WHERE goals > 15 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:02 -> SELECT player_id FROM public.vt_season_info_player WHERE goals > 15 AND season_id = 816527

Successful query
Data Shape: (9, 1)
Running query: SELECT player_id FROM public.vt_season_metric_player WHERE non_penalty_goals > 15 AND season_id = 816527

06-21 16:18:02 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:02 -> SELECT player_id FROM public.vt_season_metric_player WHERE non_penalty_goals > 15 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:02 -> SELECT player_id FROM public.vt_season_metric_player WHERE non_penalty_goals > 15 AND season_id = 816527
ERROR:root:Database error: column "non_penalty_goals" does not exist
LINE 1: ...ayer_id FROM public.vt_season_metric_player WHERE non_penalt...
                                                             ^

Failed query
Running query: SELECT player_id FROM public.vt_season_stat_player WHERE goals > 15 AND season_id = 816527

06-21 16:18:02 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:02 -> SELECT player_id FROM public.vt_season_stat_player WHERE goals > 15 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:02 -> SELECT player_id FROM public.vt_season_stat_player WHERE goals > 15 AND season_id = 816527

Successful query
Data Shape: (9, 1)
Running query: SELECT player_id, touches FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY touches DESC LIMIT 1

06-21 16:18:02 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:02 -> SELECT player_id, touches FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY touches DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:02 -> SELECT player_id, touches FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY touches DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, touches_in_team FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY touches_in_team DESC LIMIT 1

06-21 16:18:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:03 -> SELECT player_id, touches_in_team FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY touches_in_team DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:03 -> SELECT player_id, touches_in_team FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY touches_in_team DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, touches FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY touches DESC LIMIT 1

06-21 16:18:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:03 -> SELECT player_id, touches FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY touches DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:03 -> SELECT player_id, touches FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY touches DESC LIMIT 1
ERROR:root:Database error: column "touches" does not exist
LINE 1: SELECT player_id, touches FROM public.vt_season_metric_playe...
                          ^

Failed query
Running query: SELECT points FROM public.t_season_team_rank WHERE team_id = 1926 AND season_id = 816529

06-21 16:18:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:03 -> SELECT points FROM public.t_season_team_rank WHERE team_id = 1926 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:03 -> SELECT points FROM public.t_season_team_rank WHERE team_id = 1926 AND season_id = 816529

Successful query
Data Shape: (1, 1)
Running query: SELECT points FROM public.t_season_team_rank WHERE team_id = 1946 AND season_id = 816529

06-21 16:18:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:03 -> SELECT points FROM public.t_season_team_rank WHERE team_id = 1946 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:03 -> SELECT points FROM public.t_season_team_rank WHERE team_id = 1946 AND season_id = 816529

Successful query
Data Shape: (1, 1)
Running query: SELECT COUNT(*) FROM t_player WHERE player_id = 80965 AND position = 'GK'

06-21 16:18:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:03 -> SELECT COUNT(*) FROM t_player WHERE player_id = 80965 AND position = 'GK'
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:03 -> SELECT COUNT(*) FROM t_player WHERE player_id = 80965 AND position = 'GK'

Successful query
Data Shape: (1, 1)
Running query: SELECT COUNT(*) FROM t_match WHERE home_team_id = 4265 AND home_score IS NOT NULL AND away_score IS NOT NULL

06-21 16:18:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:03 -> SELECT COUNT(*) FROM t_match WHERE home_team_id = 4265 AND home_score IS NOT NULL AND away_score IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:03 -> SELECT COUNT(*) FROM t_match WHERE home_team_id = 4265 AND home_score IS NOT NULL AND away_score IS NOT NULL
ERROR:root:Database error: column "home_score" does not exist
LINE 1: ...UNT(*) FROM t_match WHERE home_team_id = 4265 AND home_score...
                                                             ^

Failed query
Running query: SELECT COUNT(*) FROM t_match WHERE away_team_id = 4265 AND home_score IS NOT NULL AND away_score IS NOT NULL

06-21 16:18:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:03 -> SELECT COUNT(*) FROM t_match WHERE away_team_id = 4265 AND home_score IS NOT NULL AND away_score IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:03 -> SELECT COUNT(*) FROM t_match WHERE away_team_id = 4265 AND home_score IS NOT NULL AND away_score IS NOT NULL
ERROR:root:Database error: column "home_score" does not exist
LINE 1: ...UNT(*) FROM t_match WHERE away_team_id = 4265 AND home_score...
                                                             ^

Failed query
Running query: SELECT team_id, team FROM public.t_player_value WHERE player_id = 1598188 AND team_id = 20076 AND date = CURRENT_DATE

06-21 16:18:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:03 -> SELECT team_id, team FROM public.t_player_value WHERE player_id = 1598188 AND team_id = 20076 AND date = CURRENT_DATE
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:03 -> SELECT team_id, team FROM public.t_player_value WHERE player_id = 1598188 AND team_id = 20076 AND date = CURRENT_DATE

Successful query
Data Shape: (0, 2)
Running query: SELECT team_id, team FROM public.t_player_value WHERE player_id = 1598188 AND team_id = 20076 AND update_ts = (SELECT MAX(update_ts) FROM public.t_player_value WHERE player_id = 1598188)

06-21 16:18:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:03 -> SELECT team_id, team FROM public.t_player_value WHERE player_id = 1598188 AND team_id = 20076 AND update_ts = (SELECT MAX(update_ts) FROM public.t_player_value WHERE player_id = 1598188)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:03 -> SELECT team_id, team FROM public.t_player_value WHERE player_id = 1598188 AND team_id = 20076 AND update_ts = (SELECT MAX(update_ts) FROM public.t_player_value WHERE player_id = 1598188)

Successful query
Data Shape: (1, 2)
Running query: SELECT xg_saved_per_xg_faced_on_target FROM public.vt_season_opta_player WHERE player_id = 1168102 AND season_id = 816527 AND xg_saved_per_xg_faced_on_target IS NOT NULL

06-21 16:18:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:04 -> SELECT xg_saved_per_xg_faced_on_target FROM public.vt_season_opta_player WHERE player_id = 1168102 AND season_id = 816527 AND xg_saved_per_xg_faced_on_target IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:04 -> SELECT xg_saved_per_xg_faced_on_target FROM public.vt_season_opta_player WHERE player_id = 1168102 AND season_id = 816527 AND xg_saved_per_xg_faced_on_target IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, name, speed FROM t_player WHERE league = 'La Liga' AND speed IS NOT NULL ORDER BY speed DESC LIMIT 1

06-21 16:18:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:04 -> SELECT player_id, name, speed FROM t_player WHERE league = 'La Liga' AND speed IS NOT NULL ORDER BY speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:04 -> SELECT player_id, name, speed FROM t_player WHERE league = 'La Liga' AND speed IS NOT NULL ORDER BY speed DESC LIMIT 1
ERROR:root:Database error: column "speed" does not exist
LINE 1: SELECT player_id, name, speed FROM t_player WHERE league = '...
                                ^

Failed query
Running query: SELECT player_id, name, speed FROM t_player WHERE league = 'La Liga' AND speed IS NOT NULL ORDER BY speed ASC LIMIT 1

06-21 16:18:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:04 -> SELECT player_id, name, speed FROM t_player WHERE league = 'La Liga' AND speed IS NOT NULL ORDER BY speed ASC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:04 -> SELECT player_id, name, speed FROM t_player WHERE league = 'La Liga' AND speed IS NOT NULL ORDER BY speed ASC LIMIT 1
ERROR:root:Database error: column "speed" does not exist
LINE 1: SELECT player_id, name, speed FROM t_player WHERE league = '...
                                ^

Failed query
Running query: SELECT player_id, name, speed FROM t_player WHERE league = 'La Liga' AND speed IS NOT NULL ORDER BY RAND() LIMIT 1

06-21 16:18:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:04 -> SELECT player_id, name, speed FROM t_player WHERE league = 'La Liga' AND speed IS NOT NULL ORDER BY RAND() LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:04 -> SELECT player_id, name, speed FROM t_player WHERE league = 'La Liga' AND speed IS NOT NULL ORDER BY RAND() LIMIT 1
ERROR:root:Database error: column "speed" does not exist
LINE 1: SELECT player_id, name, speed FROM t_player WHERE league = '...
                                ^

Failed query
Running query: SELECT goals FROM public.vt_season_info_player WHERE player_id = 1598188 AND season_id = 816527

06-21 16:18:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:04 -> SELECT goals FROM public.vt_season_info_player WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:04 -> SELECT goals FROM public.vt_season_info_player WHERE player_id = 1598188 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT goals FROM public.vt_season_opta_player WHERE player_id = 1598188 AND season_id = 816527 AND goals IS NOT NULL

06-21 16:18:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:06 -> SELECT goals FROM public.vt_season_opta_player WHERE player_id = 1598188 AND season_id = 816527 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:06 -> SELECT goals FROM public.vt_season_opta_player WHERE player_id = 1598188 AND season_id = 816527 AND goals IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT goals FROM public.vt_season_stat_player WHERE player_id = 1598188 AND season_id = 816527 AND goals IS NOT NULL

06-21 16:18:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:06 -> SELECT goals FROM public.vt_season_stat_player WHERE player_id = 1598188 AND season_id = 816527 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:06 -> SELECT goals FROM public.vt_season_stat_player WHERE player_id = 1598188 AND season_id = 816527 AND goals IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT team_id, team_name FROM public.t_team WHERE team_id = 20076

06-21 16:18:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:06 -> SELECT team_id, team_name FROM public.t_team WHERE team_id = 20076
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:06 -> SELECT team_id, team_name FROM public.t_team WHERE team_id = 20076
ERROR:root:Database error: column "team_name" does not exist
LINE 1: SELECT team_id, team_name FROM public.t_team WHERE team_id =...
                        ^
HINT:  Perhaps you meant to reference the column "t_team.tm_name".

Failed query
Running query: SELECT team_id, regular_season_name FROM public.t_team WHERE regular_season_id = 816527 AND team_id = 20076

06-21 16:18:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:06 -> SELECT team_id, regular_season_name FROM public.t_team WHERE regular_season_id = 816527 AND team_id = 20076
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:06 -> SELECT team_id, regular_season_name FROM public.t_team WHERE regular_season_id = 816527 AND team_id = 20076
ERROR:root:Database error: column "regular_season_name" does not exist
LINE 1: SELECT team_id, regular_season_name FROM public.t_team WHERE...
                        ^

Failed query
Running query: SELECT team_id, team_name FROM public.t_team WHERE regular_season_id = 816527

06-21 16:18:07 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:07 -> SELECT team_id, team_name FROM public.t_team WHERE regular_season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:07 -> SELECT team_id, team_name FROM public.t_team WHERE regular_season_id = 816527
ERROR:root:Database error: column "team_name" does not exist
LINE 1: SELECT team_id, team_name FROM public.t_team WHERE regular_s...
                        ^
HINT:  Perhaps you meant to reference the column "t_team.tm_name".

Failed query
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816530 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

06-21 16:18:07 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:07 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816530 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:07 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816530 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816530 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1

06-21 16:18:07 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:07 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816530 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:07 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816530 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE player_id = 1165587 AND season_id = 816529

06-21 16:18:07 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:07 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE player_id = 1165587 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:07 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE player_id = 1165587 AND season_id = 816529

Successful query
Data Shape: (3, 2)
Running query: SELECT player_id, max_speed FROM public.vt_season_opta_player WHERE player_id = 1165587 AND season_id = 816529 AND max_speed IS NOT NULL

06-21 16:18:07 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:07 -> SELECT player_id, max_speed FROM public.vt_season_opta_player WHERE player_id = 1165587 AND season_id = 816529 AND max_speed IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:07 -> SELECT player_id, max_speed FROM public.vt_season_opta_player WHERE player_id = 1165587 AND season_id = 816529 AND max_speed IS NOT NULL
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, max_speed FROM public.vt_season_opta_playe...
                          ^

Failed query
Running query: SELECT player_id, team_id, season_id, games_played, mins_played, assists, goals, non_penalty_goals, yellow_cards, red_cards, position, age FROM public.vt_season_info_player WHERE player_id = 1598188 AND team_id = 20076 AND season_id = 816527

06-21 16:18:07 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:07 -> SELECT player_id, team_id, season_id, games_played, mins_played, assists, goals, non_penalty_goals, yellow_cards, red_cards, position, age FROM public.vt_season_info_player WHERE player_id = 1598188 AND team_id = 20076 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:07 -> SELECT player_id, team_id, season_id, games_played, mins_played, assists, goals, non_penalty_goals, yellow_cards, red_cards, position, age FROM public.vt_season_info_player WHERE player_id = 1598188 AND team_id = 20076 AND season_id = 816527

Successful query
Data Shape: (1, 12)
Running query: SELECT player_id, team_id, season_id, games_played, mins_played, assists, goals, non_penalty_goals, yellow_cards, red_cards, position, age FROM public.vt_season_info_player WHERE player_id = 80965 AND team_id = 4265 AND season_id = 816527

06-21 16:18:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:08 -> SELECT player_id, team_id, season_id, games_played, mins_played, assists, goals, non_penalty_goals, yellow_cards, red_cards, position, age FROM public.vt_season_info_player WHERE player_id = 80965 AND team_id = 4265 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:08 -> SELECT player_id, team_id, season_id, games_played, mins_played, assists, goals, non_penalty_goals, yellow_cards, red_cards, position, age FROM public.vt_season_info_player WHERE player_id = 80965 AND team_id = 4265 AND season_id = 816527

Successful query
Data Shape: (1, 12)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 4279 AND season_id = 816527 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

06-21 16:18:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:08 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 4279 AND season_id = 816527 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:08 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 4279 AND season_id = 816527 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, avg_max_speed FROM public.vt_season_metric_player WHERE team_id = 4279 AND season_id = 816527 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1

06-21 16:18:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:08 -> SELECT player_id, avg_max_speed FROM public.vt_season_metric_player WHERE team_id = 4279 AND season_id = 816527 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:08 -> SELECT player_id, avg_max_speed FROM public.vt_season_metric_player WHERE team_id = 4279 AND season_id = 816527 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1
ERROR:root:Database error: column "avg_max_speed" does not exist
LINE 1: SELECT player_id, avg_max_speed FROM public.vt_season_metric...
                          ^

Failed query
Running query: SELECT MAX(speed) FROM player_speed_stats WHERE player_id = 1165587 AND season_id = 816529 AND speed IS NOT NULL

06-21 16:18:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:08 -> SELECT MAX(speed) FROM player_speed_stats WHERE player_id = 1165587 AND season_id = 816529 AND speed IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:08 -> SELECT MAX(speed) FROM player_speed_stats WHERE player_id = 1165587 AND season_id = 816529 AND speed IS NOT NULL
ERROR:root:Database error: relation "player_speed_stats" does not exist
LINE 1: SELECT MAX(speed) FROM player_speed_stats WHERE player_id = ...
                               ^

Failed query
Running query: SELECT MAX(speed) FROM player_speed_stats WHERE player_id = 1165587 AND season_id = 816529 AND speed > 0

06-21 16:18:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:08 -> SELECT MAX(speed) FROM player_speed_stats WHERE player_id = 1165587 AND season_id = 816529 AND speed > 0
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:08 -> SELECT MAX(speed) FROM player_speed_stats WHERE player_id = 1165587 AND season_id = 816529 AND speed > 0
ERROR:root:Database error: relation "player_speed_stats" does not exist
LINE 1: SELECT MAX(speed) FROM player_speed_stats WHERE player_id = ...
                               ^

Failed query
Running query: SELECT product_name, price FROM products WHERE category = 'electronics' AND price IS NOT NULL

06-21 16:18:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:08 -> SELECT product_name, price FROM products WHERE category = 'electronics' AND price IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:08 -> SELECT product_name, price FROM products WHERE category = 'electronics' AND price IS NOT NULL
ERROR:root:Database error: relation "products" does not exist
LINE 1: SELECT product_name, price FROM products WHERE category = 'e...
                                        ^

Failed query
Running query: SELECT customer_name, order_date FROM orders WHERE order_status = 'delivered' AND order_date IS NOT NULL

06-21 16:18:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:08 -> SELECT customer_name, order_date FROM orders WHERE order_status = 'delivered' AND order_date IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:08 -> SELECT customer_name, order_date FROM orders WHERE order_status = 'delivered' AND order_date IS NOT NULL
ERROR:root:Database error: relation "orders" does not exist
LINE 1: SELECT customer_name, order_date FROM orders WHERE order_sta...
                                              ^

Failed query
Running query: SELECT manufacturer_name, warranty_period FROM manufacturers WHERE country = 'Germany' AND warranty_period IS NOT NULL

06-21 16:18:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:08 -> SELECT manufacturer_name, warranty_period FROM manufacturers WHERE country = 'Germany' AND warranty_period IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:08 -> SELECT manufacturer_name, warranty_period FROM manufacturers WHERE country = 'Germany' AND warranty_period IS NOT NULL
ERROR:root:Database error: relation "manufacturers" does not exist
LINE 1: SELECT manufacturer_name, warranty_period FROM manufacturers...
                                                       ^

Failed query
Running query: SELECT dribbles_won, dribbles_total FROM public.vt_season_stat_player WHERE player_id = 122649 AND season_id = 816527 AND team_id = 62390

06-21 16:18:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:08 -> SELECT dribbles_won, dribbles_total FROM public.vt_season_stat_player WHERE player_id = 122649 AND season_id = 816527 AND team_id = 62390
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:08 -> SELECT dribbles_won, dribbles_total FROM public.vt_season_stat_player WHERE player_id = 122649 AND season_id = 816527 AND team_id = 62390

Successful query
Data Shape: (0, 2)
Running query: SELECT dribbles_won, dribbles_total FROM public.vt_season_stat_player WHERE player_id = 1169460 AND season_id = 816527 AND team_id = 4265

06-21 16:18:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:08 -> SELECT dribbles_won, dribbles_total FROM public.vt_season_stat_player WHERE player_id = 1169460 AND season_id = 816527 AND team_id = 4265
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:08 -> SELECT dribbles_won, dribbles_total FROM public.vt_season_stat_player WHERE player_id = 1169460 AND season_id = 816527 AND team_id = 4265

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, dribbles_won, dribbles_total FROM public.vt_season_stat_player WHERE player_id IN (SELECT player_id FROM public.vt_season_stat_player WHERE player_id = 1169460 OR player_id = 1296920) AND season_id = 816527 AND team_id = 4265

06-21 16:18:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:11 -> SELECT player_id, dribbles_won, dribbles_total FROM public.vt_season_stat_player WHERE player_id IN (SELECT player_id FROM public.vt_season_stat_player WHERE player_id = 1169460 OR player_id = 1296920) AND season_id = 816527 AND team_id = 4265
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:11 -> SELECT player_id, dribbles_won, dribbles_total FROM public.vt_season_stat_player WHERE player_id IN (SELECT player_id FROM public.vt_season_stat_player WHERE player_id = 1169460 OR player_id = 1296920) AND season_id = 816527 AND team_id = 4265

Successful query
Data Shape: (2, 3)
Running query: SELECT * FROM public.agg_season_team_info WHERE team_id = 20076 AND season_id = 816527

06-21 16:18:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:11 -> SELECT * FROM public.agg_season_team_info WHERE team_id = 20076 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:11 -> SELECT * FROM public.agg_season_team_info WHERE team_id = 20076 AND season_id = 816527

Successful query
Data Shape: (1, 14)
Running query: SELECT games, xg, xg_per_game, xa, xa_per_game FROM public.vt_season_metric_team WHERE team_id = 20076 AND season_id = 816527

06-21 16:18:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:11 -> SELECT games, xg, xg_per_game, xa, xa_per_game FROM public.vt_season_metric_team WHERE team_id = 20076 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:11 -> SELECT games, xg, xg_per_game, xa, xa_per_game FROM public.vt_season_metric_team WHERE team_id = 20076 AND season_id = 816527

Successful query
Data Shape: (3, 5)
Running query: SELECT player_id, (goals - xg) AS goals_difference FROM public.vt_season_opta_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals_difference DESC LIMIT 1

06-21 16:18:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:11 -> SELECT player_id, (goals - xg) AS goals_difference FROM public.vt_season_opta_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals_difference DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:11 -> SELECT player_id, (goals - xg) AS goals_difference FROM public.vt_season_opta_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals_difference DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, max_speed FROM player_tracking_data WHERE player_id = 1165587 AND max_speed IS NOT NULL

06-21 16:18:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:11 -> SELECT player_id, max_speed FROM player_tracking_data WHERE player_id = 1165587 AND max_speed IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:11 -> SELECT player_id, max_speed FROM player_tracking_data WHERE player_id = 1165587 AND max_speed IS NOT NULL
ERROR:root:Database error: relation "player_tracking_data" does not exist
LINE 1: SELECT player_id, max_speed FROM player_tracking_data WHERE ...
                                         ^

Failed query
Running query: SELECT player_id, max_speed FROM player_statistics WHERE player_id = 1165587 AND max_speed IS NOT NULL

06-21 16:18:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:11 -> SELECT player_id, max_speed FROM player_statistics WHERE player_id = 1165587 AND max_speed IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:11 -> SELECT player_id, max_speed FROM player_statistics WHERE player_id = 1165587 AND max_speed IS NOT NULL
ERROR:root:Database error: relation "player_statistics" does not exist
LINE 1: SELECT player_id, max_speed FROM player_statistics WHERE pla...
                                         ^

Failed query
Running query: SELECT player_id, max_speed FROM player_performance WHERE player_id = 1165587 AND max_speed IS NOT NULL

06-21 16:18:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:11 -> SELECT player_id, max_speed FROM player_performance WHERE player_id = 1165587 AND max_speed IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:11 -> SELECT player_id, max_speed FROM player_performance WHERE player_id = 1165587 AND max_speed IS NOT NULL
ERROR:root:Database error: relation "player_performance" does not exist
LINE 1: SELECT player_id, max_speed FROM player_performance WHERE pl...
                                         ^

Failed query
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE player_id = 1165587 AND season_id = 816529 AND max_speed IS NOT NULL

06-21 16:18:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:11 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE player_id = 1165587 AND season_id = 816529 AND max_speed IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:11 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE player_id = 1165587 AND season_id = 816529 AND max_speed IS NOT NULL

Successful query
Data Shape: (3, 2)
Running query: SELECT * FROM pro.agg_history_season_team_sos WHERE team_id = 4266 AND season_id = 816527

06-21 16:18:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:12 -> SELECT * FROM pro.agg_history_season_team_sos WHERE team_id = 4266 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:12 -> SELECT * FROM pro.agg_history_season_team_sos WHERE team_id = 4266 AND season_id = 816527

Successful query
Data Shape: (0, 12)
Running query: SELECT xg, xg_per_game, xa, xa_per_game FROM public.vt_season_metric_team WHERE team_id = 4266 AND season_id = 816527 AND xg IS NOT NULL AND xa IS NOT NULL

06-21 16:18:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:12 -> SELECT xg, xg_per_game, xa, xa_per_game FROM public.vt_season_metric_team WHERE team_id = 4266 AND season_id = 816527 AND xg IS NOT NULL AND xa IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:12 -> SELECT xg, xg_per_game, xa, xa_per_game FROM public.vt_season_metric_team WHERE team_id = 4266 AND season_id = 816527 AND xg IS NOT NULL AND xa IS NOT NULL

Successful query
Data Shape: (3, 4)
Running query: SELECT team_name FROM public.v_player_short_name WHERE player_name = 'Jude Bellingham' AND team_name IS NOT NULL

06-21 16:18:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:12 -> SELECT team_name FROM public.v_player_short_name WHERE player_name = 'Jude Bellingham' AND team_name IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:12 -> SELECT team_name FROM public.v_player_short_name WHERE player_name = 'Jude Bellingham' AND team_name IS NOT NULL

Successful query
Data Shape: (0, 1)
Running query: SELECT name FROM public.t_player WHERE first_name = 'Jude' AND last_name = 'Bellingham' AND team_id IS NOT NULL

06-21 16:18:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:12 -> SELECT name FROM public.t_player WHERE first_name = 'Jude' AND last_name = 'Bellingham' AND team_id IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:12 -> SELECT name FROM public.t_player WHERE first_name = 'Jude' AND last_name = 'Bellingham' AND team_id IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT team FROM public.t_player_value WHERE player_id = 1296920 AND team IS NOT NULL

06-21 16:18:14 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:14 -> SELECT team FROM public.t_player_value WHERE player_id = 1296920 AND team IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:14 -> SELECT team FROM public.t_player_value WHERE player_id = 1296920 AND team IS NOT NULL

Successful query
Data Shape: (0, 1)
Running query: SELECT player_id, team_name, prev_team_name, elo, match_date FROM public.v_player_dup WHERE player_name = 'Artem Dovbyk'

06-21 16:18:14 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:14 -> SELECT player_id, team_name, prev_team_name, elo, match_date FROM public.v_player_dup WHERE player_name = 'Artem Dovbyk'
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:14 -> SELECT player_id, team_name, prev_team_name, elo, match_date FROM public.v_player_dup WHERE player_name = 'Artem Dovbyk'

Successful query
Data Shape: (1, 5)
Running query: SELECT season_id, team_id, player_id, match_date, games_played, mins_played, dl_index FROM public.vt_history_score_player WHERE player_id = 1598188

06-21 16:18:38 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:38 -> SELECT season_id, team_id, player_id, match_date, games_played, mins_played, dl_index FROM public.vt_history_score_player WHERE player_id = 1598188
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:38 -> SELECT season_id, team_id, player_id, match_date, games_played, mins_played, dl_index FROM public.vt_history_score_player WHERE player_id = 1598188

Successful query
Data Shape: (20, 7)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 815820 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

06-21 16:18:38 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:38 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 815820 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:38 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 815820 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (0, 2)
Running query: SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 815820 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1

06-21 16:18:38 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:38 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 815820 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:38 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 815820 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1

Successful query
Data Shape: (0, 2)
Running query: SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE team_id = 4279 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

06-21 16:18:38 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:38 -> SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE team_id = 4279 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:38 -> SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE team_id = 4279 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE team_id = 4279 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1

06-21 16:18:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:39 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE team_id = 4279 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:39 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE team_id = 4279 AND avg_max_speed IS NOT NULL ORDER BY avg_max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT ranking, wins, draws, loses, goals, goals_against, diff_goals, points FROM public.t_season_team_rank WHERE season_id = 816527 AND team_id = 4266

06-21 16:18:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:39 -> SELECT ranking, wins, draws, loses, goals, goals_against, diff_goals, points FROM public.t_season_team_rank WHERE season_id = 816527 AND team_id = 4266
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:39 -> SELECT ranking, wins, draws, loses, goals, goals_against, diff_goals, points FROM public.t_season_team_rank WHERE season_id = 816527 AND team_id = 4266

Successful query
Data Shape: (1, 8)
Running query: SELECT * FROM pro.agg_history_season_team_sos WHERE season_id = 816527 AND team_id = 4266

06-21 16:18:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:41 -> SELECT * FROM pro.agg_history_season_team_sos WHERE season_id = 816527 AND team_id = 4266
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:41 -> SELECT * FROM pro.agg_history_season_team_sos WHERE season_id = 816527 AND team_id = 4266

Successful query
Data Shape: (0, 12)
Running query: SELECT goals FROM public.vt_season_info_player WHERE player_id = 1296920 AND season_id = 816527

06-21 16:18:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:41 -> SELECT goals FROM public.vt_season_info_player WHERE player_id = 1296920 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:41 -> SELECT goals FROM public.vt_season_info_player WHERE player_id = 1296920 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT goals FROM public.vt_season_info_player WHERE player_id = 1296920 AND season_id = 816690

06-21 16:18:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:41 -> SELECT goals FROM public.vt_season_info_player WHERE player_id = 1296920 AND season_id = 816690
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:41 -> SELECT goals FROM public.vt_season_info_player WHERE player_id = 1296920 AND season_id = 816690

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, passes_total, team_id, season_id FROM public.vt_season_stat_player WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY passes_total DESC LIMIT 5

06-21 16:18:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:42 -> SELECT player_id, passes_total, team_id, season_id FROM public.vt_season_stat_player WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY passes_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:42 -> SELECT player_id, passes_total, team_id, season_id FROM public.vt_season_stat_player WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY passes_total DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, goals, team_id, season_id FROM public.vt_season_stat_player WHERE season_id = 816527 AND goals IS NOT NULL AND player_id IN (SELECT player_id FROM t_player WHERE age > 30) ORDER BY goals DESC LIMIT 5

06-21 16:18:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:42 -> SELECT player_id, goals, team_id, season_id FROM public.vt_season_stat_player WHERE season_id = 816527 AND goals IS NOT NULL AND player_id IN (SELECT player_id FROM t_player WHERE age > 30) ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:42 -> SELECT player_id, goals, team_id, season_id FROM public.vt_season_stat_player WHERE season_id = 816527 AND goals IS NOT NULL AND player_id IN (SELECT player_id FROM t_player WHERE age > 30) ORDER BY goals DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT team_id, season_id, expected_points FROM public.vt_season_metric_team WHERE team_id = 4265 AND season_id = 816527

06-21 16:18:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:42 -> SELECT team_id, season_id, expected_points FROM public.vt_season_metric_team WHERE team_id = 4265 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:42 -> SELECT team_id, season_id, expected_points FROM public.vt_season_metric_team WHERE team_id = 4265 AND season_id = 816527

Successful query
Data Shape: (3, 3)
Running query: SELECT team_id, season_id, expected_points FROM public.vt_season_metric_team WHERE team_id = 4279 AND season_id = 816527

06-21 16:18:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:42 -> SELECT team_id, season_id, expected_points FROM public.vt_season_metric_team WHERE team_id = 4279 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:42 -> SELECT team_id, season_id, expected_points FROM public.vt_season_metric_team WHERE team_id = 4279 AND season_id = 816527

Successful query
Data Shape: (3, 3)
Running query: SELECT name FROM public.t_player WHERE first_name = 'Artem' AND last_name = 'Dovbyk' AND team_id = 20076

06-21 16:18:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:42 -> SELECT name FROM public.t_player WHERE first_name = 'Artem' AND last_name = 'Dovbyk' AND team_id = 20076
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:42 -> SELECT name FROM public.t_player WHERE first_name = 'Artem' AND last_name = 'Dovbyk' AND team_id = 20076

Successful query
Data Shape: (1, 1)
Running query: SELECT team_name FROM public.v_player_dup WHERE player_name = 'Artem Dovbyk'

06-21 16:18:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:42 -> SELECT team_name FROM public.v_player_dup WHERE player_name = 'Artem Dovbyk'
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:42 -> SELECT team_name FROM public.v_player_dup WHERE player_name = 'Artem Dovbyk'

Successful query
Data Shape: (1, 1)
Running query: SELECT team FROM public.t_player_value WHERE player_id = 1598188

06-21 16:18:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:18:59 -> SELECT team FROM public.t_player_value WHERE player_id = 1598188
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:18:59 -> SELECT team FROM public.t_player_value WHERE player_id = 1598188

Successful query
Data Shape: (20, 1)
Running query: SELECT player_id, (xg - goals) AS xg_diff FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg_diff DESC LIMIT 1

06-21 16:19:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:00 -> SELECT player_id, (xg - goals) AS xg_diff FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg_diff DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:00 -> SELECT player_id, (xg - goals) AS xg_diff FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg_diff DESC LIMIT 1
ERROR:root:Database error: column "goals" does not exist
LINE 1: SELECT player_id, (xg - goals) AS xg_diff FROM public.vt_sea...
                                ^

Failed query
Running query: SELECT player_id, team_id, season_id FROM public.vt_season_metric_player WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'FW') ORDER BY ball_progression_90 DESC LIMIT 5

06-21 16:19:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:00 -> SELECT player_id, team_id, season_id FROM public.vt_season_metric_player WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'FW') ORDER BY ball_progression_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:00 -> SELECT player_id, team_id, season_id FROM public.vt_season_metric_player WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'FW') ORDER BY ball_progression_90 DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, player_name, team_name, prev_team_name, elo, match_date FROM public.v_player_dup WHERE player_name = 'Artem Dovbyk'

06-21 16:19:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:00 -> SELECT player_id, player_name, team_name, prev_team_name, elo, match_date FROM public.v_player_dup WHERE player_name = 'Artem Dovbyk'
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:00 -> SELECT player_id, player_name, team_name, prev_team_name, elo, match_date FROM public.v_player_dup WHERE player_name = 'Artem Dovbyk'

Successful query
Data Shape: (1, 6)
Running query: SELECT player_profile_id, name_eng, name_esp, des_eng, des_esp FROM public.v_player_profile WHERE name_eng = 'Artem Dovbyk' AND name_esp = 'Artem Dovbyk'

06-21 16:19:19 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:19 -> SELECT player_profile_id, name_eng, name_esp, des_eng, des_esp FROM public.v_player_profile WHERE name_eng = 'Artem Dovbyk' AND name_esp = 'Artem Dovbyk'
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:19 -> SELECT player_profile_id, name_eng, name_esp, des_eng, des_esp FROM public.v_player_profile WHERE name_eng = 'Artem Dovbyk' AND name_esp = 'Artem Dovbyk'

Successful query
Data Shape: (0, 5)
Running query: SELECT goals FROM public.vt_season_info_player WHERE player_id = 1598188 AND season_id = 816527 AND goals IS NOT NULL

06-21 16:19:19 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:19 -> SELECT goals FROM public.vt_season_info_player WHERE player_id = 1598188 AND season_id = 816527 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:19 -> SELECT goals FROM public.vt_season_info_player WHERE player_id = 1598188 AND season_id = 816527 AND goals IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT goals FROM public.vt_season_info_player WHERE player_id = 1296920 AND season_id = 816527 AND goals IS NOT NULL

06-21 16:19:19 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:19 -> SELECT goals FROM public.vt_season_info_player WHERE player_id = 1296920 AND season_id = 816527 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:19 -> SELECT goals FROM public.vt_season_info_player WHERE player_id = 1296920 AND season_id = 816527 AND goals IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT * FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527

06-21 16:19:19 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:19 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:19 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527

Successful query
Data Shape: (4, 57)
Running query: SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527

06-21 16:19:19 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:19 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:19 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT * FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY xg DESC LIMIT 1

06-21 16:19:19 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:19 -> SELECT * FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY xg DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:19 -> SELECT * FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY xg DESC LIMIT 1

Successful query
Data Shape: (1, 189)
Running query: SELECT * FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY scoring_contribution DESC LIMIT 1

06-21 16:19:20 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:20 -> SELECT * FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY scoring_contribution DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:20 -> SELECT * FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY scoring_contribution DESC LIMIT 1

Successful query
Data Shape: (1, 383)
Running query: SELECT player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_label = \'La Liga\' ORDER BY goals DESC LIMIT 1

06-21 16:19:22 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:22 -> SELECT player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_label = \'La Liga\' ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:22 -> SELECT player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_label = \'La Liga\' ORDER BY goals DESC LIMIT 1
ERROR:root:Database error: syntax error at or near "\"
LINE 1: ..._opta WHERE season_id = 816527 AND league_label = \'La Liga\...
                                                             ^

Failed query
Running query: SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816527) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1

06-21 16:19:22 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:22 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816527) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:22 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816527) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ..._id IN (SELECT player_id FROM public.t_goal WHERE season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, COUNT(goal_id) as goals_scored FROM public.t_goal WHERE player_id IN (SELECT player_id FROM t_player WHERE age < 25) AND match_id IN (SELECT match_id FROM t_match WHERE season_id = 816527) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 5

06-21 16:19:22 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:22 -> SELECT player_id, COUNT(goal_id) as goals_scored FROM public.t_goal WHERE player_id IN (SELECT player_id FROM t_player WHERE age < 25) AND match_id IN (SELECT match_id FROM t_match WHERE season_id = 816527) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:22 -> SELECT player_id, COUNT(goal_id) as goals_scored FROM public.t_goal WHERE player_id IN (SELECT player_id FROM t_player WHERE age < 25) AND match_id IN (SELECT match_id FROM t_match WHERE season_id = 816527) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND age < 25 ORDER BY npg_90 DESC LIMIT 5

06-21 16:19:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:23 -> SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND age < 25 ORDER BY npg_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:23 -> SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND age < 25 ORDER BY npg_90 DESC LIMIT 5

Successful query
Data Shape: (5, 5)
Running query: SELECT player_id, COUNT(*) AS goals_scored FROM public.t_goal WHERE player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816527) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1

06-21 16:19:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:23 -> SELECT player_id, COUNT(*) AS goals_scored FROM public.t_goal WHERE player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816527) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:23 -> SELECT player_id, COUNT(*) AS goals_scored FROM public.t_goal WHERE player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816527) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ..._id IN (SELECT player_id FROM public.t_goal WHERE season_id ...
                                                             ^

Failed query
Running query: SELECT match_id, max_speed FROM public.agg_game_player_pd WHERE player_id = 1163220 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:19:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:23 -> SELECT match_id, max_speed FROM public.agg_game_player_pd WHERE player_id = 1163220 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:23 -> SELECT match_id, max_speed FROM public.agg_game_player_pd WHERE player_id = 1163220 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT match_id, runs_distance FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY runs_distance DESC LIMIT 1

06-21 16:19:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:23 -> SELECT match_id, runs_distance FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY runs_distance DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:23 -> SELECT match_id, runs_distance FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY runs_distance DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, player_name, max_speed FROM vm_agg_season_player_similarity WHERE team_id = 4279 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:19:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:23 -> SELECT player_id, player_name, max_speed FROM vm_agg_season_player_similarity WHERE team_id = 4279 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:23 -> SELECT player_id, player_name, max_speed FROM vm_agg_season_player_similarity WHERE team_id = 4279 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, player_name, max_speed FROM vm_agg_season_...
                                       ^

Failed query
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 4279 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:19:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:23 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 4279 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:23 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 4279 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT match_id, xg FROM public.vt_game_metric_player WHERE player_id = 1296920 AND season_id = 816527 ORDER BY xg DESC LIMIT 1

06-21 16:19:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:23 -> SELECT match_id, xg FROM public.vt_game_metric_player WHERE player_id = 1296920 AND season_id = 816527 ORDER BY xg DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:23 -> SELECT match_id, xg FROM public.vt_game_metric_player WHERE player_id = 1296920 AND season_id = 816527 ORDER BY xg DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT match_id, xp FROM public.vt_game_stat_player WHERE player_id = 1296920 AND season_id = 816527 ORDER BY xp DESC LIMIT 1

06-21 16:19:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:24 -> SELECT match_id, xp FROM public.vt_game_stat_player WHERE player_id = 1296920 AND season_id = 816527 ORDER BY xp DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:24 -> SELECT match_id, xp FROM public.vt_game_stat_player WHERE player_id = 1296920 AND season_id = 816527 ORDER BY xp DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, SUM(score_pd) AS total_goals FROM public.agg_season_player_pd WHERE season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1

06-21 16:19:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:24 -> SELECT player_id, SUM(score_pd) AS total_goals FROM public.agg_season_player_pd WHERE season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:24 -> SELECT player_id, SUM(score_pd) AS total_goals FROM public.agg_season_player_pd WHERE season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_label = 'La Liga' ORDER BY goals DESC LIMIT 1

06-21 16:19:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:24 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_label = 'La Liga' ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:24 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_label = 'La Liga' ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, team_id, season_id, runs_distance FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY runs_distance DESC LIMIT 1

06-21 16:19:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:24 -> SELECT player_id, team_id, season_id, runs_distance FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY runs_distance DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:24 -> SELECT player_id, team_id, season_id, runs_distance FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY runs_distance DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT assists FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527

06-21 16:19:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:24 -> SELECT assists FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:24 -> SELECT assists FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT COUNT(*) FROM public.t_goal WHERE player_id = 1163220 AND season_id = 816527

06-21 16:19:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:24 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:24 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 1163220 AND season_id = 816527
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ... FROM public.t_goal WHERE player_id = 1163220 AND season_id ...
                                                             ^

Failed query
Running query: SELECT match_id, max_speed FROM public.agg_game_player_pd WHERE player_id = 1163220 AND max_speed IS NOT NULL AND max_speed > 0 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:19:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:24 -> SELECT match_id, max_speed FROM public.agg_game_player_pd WHERE player_id = 1163220 AND max_speed IS NOT NULL AND max_speed > 0 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:24 -> SELECT match_id, max_speed FROM public.agg_game_player_pd WHERE player_id = 1163220 AND max_speed IS NOT NULL AND max_speed > 0 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT match_id, runs_distance FROM public.vt_game_metric_player WHERE player_id = 1163220 AND runs_distance IS NOT NULL AND runs_distance > 0 AND season_id = 816527 ORDER BY runs_distance DESC LIMIT 1

06-21 16:19:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:24 -> SELECT match_id, runs_distance FROM public.vt_game_metric_player WHERE player_id = 1163220 AND runs_distance IS NOT NULL AND runs_distance > 0 AND season_id = 816527 ORDER BY runs_distance DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:24 -> SELECT match_id, runs_distance FROM public.vt_game_metric_player WHERE player_id = 1163220 AND runs_distance IS NOT NULL AND runs_distance > 0 AND season_id = 816527 ORDER BY runs_distance DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT match_id, max_speed FROM public.agg_game_player_pd WHERE player_id = (SELECT player_id FROM t_player WHERE name = 'Vinicus Junior') AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:19:25 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:25 -> SELECT match_id, max_speed FROM public.agg_game_player_pd WHERE player_id = (SELECT player_id FROM t_player WHERE name = 'Vinicus Junior') AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:25 -> SELECT match_id, max_speed FROM public.agg_game_player_pd WHERE player_id = (SELECT player_id FROM t_player WHERE name = 'Vinicus Junior') AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (0, 2)
Running query: SELECT player_id, team_id, match_id, season_id, runs_distance FROM public.vt_game_metric_player WHERE player_id = (SELECT player_id FROM public.t_player WHERE name = 'Vinicus Junior') AND season_id = 816527 ORDER BY runs_distance DESC LIMIT 1

06-21 16:19:25 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:25 -> SELECT player_id, team_id, match_id, season_id, runs_distance FROM public.vt_game_metric_player WHERE player_id = (SELECT player_id FROM public.t_player WHERE name = 'Vinicus Junior') AND season_id = 816527 ORDER BY runs_distance DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:25 -> SELECT player_id, team_id, match_id, season_id, runs_distance FROM public.vt_game_metric_player WHERE player_id = (SELECT player_id FROM public.t_player WHERE name = 'Vinicus Junior') AND season_id = 816527 ORDER BY runs_distance DESC LIMIT 1

Successful query
Data Shape: (0, 5)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:19:28 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:28 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:28 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, max_speed FROM vm_agg_season_player_opta WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:19:28 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:28 -> SELECT player_id, max_speed FROM vm_agg_season_player_opta WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:28 -> SELECT player_id, max_speed FROM vm_agg_season_player_opta WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT COUNT(*) FROM public.agg_season_player_pd WHERE player_id = 1163220 AND score_pd >= 1 AND season_id = 816527

06-21 16:19:28 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:28 -> SELECT COUNT(*) FROM public.agg_season_player_pd WHERE player_id = 1163220 AND score_pd >= 1 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:28 -> SELECT COUNT(*) FROM public.agg_season_player_pd WHERE player_id = 1163220 AND score_pd >= 1 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT COUNT(*) FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND goals >= 1 AND season_id = 816527

06-21 16:19:28 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:28 -> SELECT COUNT(*) FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND goals >= 1 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:28 -> SELECT COUNT(*) FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND goals >= 1 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND team_id = 4265 ORDER BY max_speed DESC LIMIT 1

06-21 16:19:28 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:28 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND team_id = 4265 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:28 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND team_id = 4265 ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, max_speed FROM vm_agg_season_player_opta WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:19:28 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:28 -> SELECT player_id, max_speed FROM vm_agg_season_player_opta WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:28 -> SELECT player_id, max_speed FROM vm_agg_season_player_opta WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT assists_90 FROM vm_agg_season_player_similarity WHERE player_name = 'Artem Dovbyk' AND season_id = 816527

06-21 16:19:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:29 -> SELECT assists_90 FROM vm_agg_season_player_similarity WHERE player_name = 'Artem Dovbyk' AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:29 -> SELECT assists_90 FROM vm_agg_season_player_similarity WHERE player_name = 'Artem Dovbyk' AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT assists FROM vm_agg_season_player_opta WHERE player_name = 'Artem Dovbyk' AND season_id = 816527

06-21 16:19:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:29 -> SELECT assists FROM vm_agg_season_player_opta WHERE player_name = 'Artem Dovbyk' AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:29 -> SELECT assists FROM vm_agg_season_player_opta WHERE player_name = 'Artem Dovbyk' AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT * FROM public.agg_season_player_pd WHERE player_id = 1598188 AND season_id = 816527

06-21 16:19:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:29 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:29 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 1598188 AND season_id = 816527

Successful query
Data Shape: (4, 57)
Running query: SELECT player_id, team_id, season_id, goals, shots, xg, xa FROM vm_agg_season_player_opta WHERE player_id = 1598188 AND season_id = 816527

06-21 16:19:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:29 -> SELECT player_id, team_id, season_id, goals, shots, xg, xa FROM vm_agg_season_player_opta WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:29 -> SELECT player_id, team_id, season_id, goals, shots, xg, xa FROM vm_agg_season_player_opta WHERE player_id = 1598188 AND season_id = 816527

Successful query
Data Shape: (1, 7)
Running query: SELECT player_id, player_name, max_speed FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 5

06-21 16:19:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:29 -> SELECT player_id, player_name, max_speed FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:29 -> SELECT player_id, player_name, max_speed FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 5
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, player_name, max_speed FROM vm_agg_season_...
                                       ^

Failed query
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 5

06-21 16:19:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:29 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:29 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, team_id, season_id, age FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527

06-21 16:19:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:29 -> SELECT player_id, team_id, season_id, age FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:29 -> SELECT player_id, team_id, season_id, age FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527
ERROR:root:Database error: column "age" does not exist
LINE 1: SELECT player_id, team_id, season_id, age FROM public.agg_se...
                                              ^

Failed query
Running query: SELECT age FROM vm_agg_season_player_similarity WHERE player_name = 'Vinicius Junior' AND team_name = 'Real Madrid' AND season_id = 816527

06-21 16:19:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:29 -> SELECT age FROM vm_agg_season_player_similarity WHERE player_name = 'Vinicius Junior' AND team_name = 'Real Madrid' AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:29 -> SELECT age FROM vm_agg_season_player_similarity WHERE player_name = 'Vinicius Junior' AND team_name = 'Real Madrid' AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT match_id, max_speed FROM public.agg_game_player_pd WHERE player_id = 1163220 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

06-21 16:19:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:30 -> SELECT match_id, max_speed FROM public.agg_game_player_pd WHERE player_id = 1163220 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:30 -> SELECT match_id, max_speed FROM public.agg_game_player_pd WHERE player_id = 1163220 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT match_id, runs_distance FROM public.vt_game_metric_player WHERE player_id = 1163220 AND runs_distance = (SELECT MAX(runs_distance) FROM public.vt_game_metric_player WHERE player_id = 1163220) AND season_id = 816527

06-21 16:19:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:30 -> SELECT match_id, runs_distance FROM public.vt_game_metric_player WHERE player_id = 1163220 AND runs_distance = (SELECT MAX(runs_distance) FROM public.vt_game_metric_player WHERE player_id = 1163220) AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:30 -> SELECT match_id, runs_distance FROM public.vt_game_metric_player WHERE player_id = 1163220 AND runs_distance = (SELECT MAX(runs_distance) FROM public.vt_game_metric_player WHERE player_id = 1163220) AND season_id = 816527

Successful query
Data Shape: (0, 2)
Running query: SELECT player_id, match_id, goals, assists, shots_on_target, passes_accurate, tackles_total FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY goals DESC, assists DESC, shots_on_target DESC, passes_accurate DESC, tackles_total DESC LIMIT 5

06-21 16:19:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:30 -> SELECT player_id, match_id, goals, assists, shots_on_target, passes_accurate, tackles_total FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY goals DESC, assists DESC, shots_on_target DESC, passes_accurate DESC, tackles_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:30 -> SELECT player_id, match_id, goals, assists, shots_on_target, passes_accurate, tackles_total FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY goals DESC, assists DESC, shots_on_target DESC, passes_accurate DESC, tackles_total DESC LIMIT 5

Successful query
Data Shape: (5, 7)
Running query: SELECT player_id, team_id, match_id, xg, xa_open_play, xa_set_piece, xg_chain, xg_build_up, xg_faced, xg_faced_on_target, mins_played FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY xg DESC LIMIT 5

06-21 16:19:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:30 -> SELECT player_id, team_id, match_id, xg, xa_open_play, xa_set_piece, xg_chain, xg_build_up, xg_faced, xg_faced_on_target, mins_played FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY xg DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:30 -> SELECT player_id, team_id, match_id, xg, xa_open_play, xa_set_piece, xg_chain, xg_build_up, xg_faced, xg_faced_on_target, mins_played FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY xg DESC LIMIT 5

Successful query
Data Shape: (5, 11)
Running query: SELECT match_id, max(runs_distance) as max_distance FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527 GROUP BY match_id ORDER BY max_distance DESC LIMIT 1

06-21 16:19:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:30 -> SELECT match_id, max(runs_distance) as max_distance FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527 GROUP BY match_id ORDER BY max_distance DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:30 -> SELECT match_id, max(runs_distance) as max_distance FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527 GROUP BY match_id ORDER BY max_distance DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:19:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:30 -> SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:30 -> SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY avg_max_speed DESC LIMIT 1

06-21 16:19:33 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:33 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY avg_max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:33 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY avg_max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, xg FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY xg DESC LIMIT 1

06-21 16:19:33 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:33 -> SELECT player_id, xg FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY xg DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:33 -> SELECT player_id, xg FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY xg DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, assists FROM public.vt_season_info_player WHERE season_id = 816529 ORDER BY assists DESC LIMIT 1

06-21 16:19:33 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:33 -> SELECT player_id, assists FROM public.vt_season_info_player WHERE season_id = 816529 ORDER BY assists DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:33 -> SELECT player_id, assists FROM public.vt_season_info_player WHERE season_id = 816529 ORDER BY assists DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, assists, position FROM public.vt_season_info_player WHERE season_id = 816529 ORDER BY assists DESC LIMIT 1

06-21 16:19:33 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:33 -> SELECT player_id, assists, position FROM public.vt_season_info_player WHERE season_id = 816529 ORDER BY assists DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:33 -> SELECT player_id, assists, position FROM public.vt_season_info_player WHERE season_id = 816529 ORDER BY assists DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, assists, position FROM public.vt_season_metric_player WHERE season_id = 816529 ORDER BY assists DESC LIMIT 1

06-21 16:19:33 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:33 -> SELECT player_id, assists, position FROM public.vt_season_metric_player WHERE season_id = 816529 ORDER BY assists DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:33 -> SELECT player_id, assists, position FROM public.vt_season_metric_player WHERE season_id = 816529 ORDER BY assists DESC LIMIT 1
ERROR:root:Database error: column "assists" does not exist
LINE 1: SELECT player_id, assists, position FROM public.vt_season_me...
                          ^

Failed query
Running query: SELECT player_id, team_id, first_name, last_name, position, age FROM public.t_player WHERE player_id = 1598188 AND team_id = 20076

06-21 16:19:33 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:33 -> SELECT player_id, team_id, first_name, last_name, position, age FROM public.t_player WHERE player_id = 1598188 AND team_id = 20076
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:33 -> SELECT player_id, team_id, first_name, last_name, position, age FROM public.t_player WHERE player_id = 1598188 AND team_id = 20076

Successful query
Data Shape: (1, 6)
Running query: SELECT player_name, team_name, season_name, mins_played FROM public.v_player_sc WHERE player_id = 1598188 AND team_id = 20076 AND season_name = 'ESP I 2023'

06-21 16:19:34 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:34 -> SELECT player_name, team_name, season_name, mins_played FROM public.v_player_sc WHERE player_id = 1598188 AND team_id = 20076 AND season_name = 'ESP I 2023'
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:34 -> SELECT player_name, team_name, season_name, mins_played FROM public.v_player_sc WHERE player_id = 1598188 AND team_id = 20076 AND season_name = 'ESP I 2023'

Successful query
Data Shape: (0, 4)
Running query: SELECT player_id, goals FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5

06-21 16:19:34 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:34 -> SELECT player_id, goals FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:34 -> SELECT player_id, goals FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, non_penalty_goals FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY non_penalty_goals DESC LIMIT 5

06-21 16:19:34 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:34 -> SELECT player_id, non_penalty_goals FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY non_penalty_goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:34 -> SELECT player_id, non_penalty_goals FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY non_penalty_goals DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, goals FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5

06-21 16:19:34 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:34 -> SELECT player_id, goals FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:34 -> SELECT player_id, goals FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5
ERROR:root:Database error: column "goals" does not exist
LINE 1: SELECT player_id, goals FROM public.vt_season_metric_player ...
                          ^

Failed query
Running query: SELECT player_id, team_id, season_id, xg FROM public.vt_season_metric_player WHERE season_id = 816529 AND position = 'Midfielder' ORDER BY xg DESC LIMIT 10

06-21 16:19:34 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:34 -> SELECT player_id, team_id, season_id, xg FROM public.vt_season_metric_player WHERE season_id = 816529 AND position = 'Midfielder' ORDER BY xg DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:34 -> SELECT player_id, team_id, season_id, xg FROM public.vt_season_metric_player WHERE season_id = 816529 AND position = 'Midfielder' ORDER BY xg DESC LIMIT 10
ERROR:root:Database error: column "position" does not exist
LINE 1: ...season_metric_player WHERE season_id = 816529 AND position =...
                                                             ^

Failed query
Running query: SELECT player_id, team_id, season_id, xg FROM public.vt_season_info_player WHERE season_id = 816529 AND position = 'Midfielder' ORDER BY xg DESC LIMIT 10

06-21 16:19:34 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:34 -> SELECT player_id, team_id, season_id, xg FROM public.vt_season_info_player WHERE season_id = 816529 AND position = 'Midfielder' ORDER BY xg DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:34 -> SELECT player_id, team_id, season_id, xg FROM public.vt_season_info_player WHERE season_id = 816529 AND position = 'Midfielder' ORDER BY xg DESC LIMIT 10

Successful query
Data Shape: (0, 4)
Running query: SELECT player_id, non_penalty_goals FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY non_penalty_goals DESC LIMIT 5

06-21 16:19:34 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:34 -> SELECT player_id, non_penalty_goals FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY non_penalty_goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:34 -> SELECT player_id, non_penalty_goals FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY non_penalty_goals DESC LIMIT 5
ERROR:root:Database error: column "non_penalty_goals" does not exist
LINE 1: SELECT player_id, non_penalty_goals FROM public.vt_season_me...
                          ^

Failed query
Running query: SELECT player_id, goals FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5

06-21 16:19:35 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:35 -> SELECT player_id, goals FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:35 -> SELECT player_id, goals FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, xg FROM public.vt_season_metric_player WHERE season_id = 816529 AND position = 'Midfielder' ORDER BY xg DESC LIMIT 10

06-21 16:19:35 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:35 -> SELECT player_id, xg FROM public.vt_season_metric_player WHERE season_id = 816529 AND position = 'Midfielder' ORDER BY xg DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:35 -> SELECT player_id, xg FROM public.vt_season_metric_player WHERE season_id = 816529 AND position = 'Midfielder' ORDER BY xg DESC LIMIT 10
ERROR:root:Database error: column "position" does not exist
LINE 1: ...season_metric_player WHERE season_id = 816529 AND position =...
                                                             ^

Failed query
Running query: SELECT player_id, xg FROM public.vt_season_info_player WHERE season_id = 816529 AND position = 'Midfielder' ORDER BY xg DESC LIMIT 10

06-21 16:19:35 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:35 -> SELECT player_id, xg FROM public.vt_season_info_player WHERE season_id = 816529 AND position = 'Midfielder' ORDER BY xg DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:35 -> SELECT player_id, xg FROM public.vt_season_info_player WHERE season_id = 816529 AND position = 'Midfielder' ORDER BY xg DESC LIMIT 10

Successful query
Data Shape: (0, 2)
Running query: SELECT team_id, SUM(shots_on_target) AS total_shots_on_target FROM public.vt_season_metric_team WHERE season_id = 816527 GROUP BY team_id ORDER BY total_shots_on_target DESC LIMIT 1

06-21 16:19:35 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:35 -> SELECT team_id, SUM(shots_on_target) AS total_shots_on_target FROM public.vt_season_metric_team WHERE season_id = 816527 GROUP BY team_id ORDER BY total_shots_on_target DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:35 -> SELECT team_id, SUM(shots_on_target) AS total_shots_on_target FROM public.vt_season_metric_team WHERE season_id = 816527 GROUP BY team_id ORDER BY total_shots_on_target DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT goals FROM public.agg_competition_player WHERE player_id = 1340410 AND team_id = 20076 AND competition_id = 816527 AND goals IS NOT NULL

06-21 16:19:35 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:35 -> SELECT goals FROM public.agg_competition_player WHERE player_id = 1340410 AND team_id = 20076 AND competition_id = 816527 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:35 -> SELECT goals FROM public.agg_competition_player WHERE player_id = 1340410 AND team_id = 20076 AND competition_id = 816527 AND goals IS NOT NULL

Successful query
Data Shape: (0, 1)
Running query: SELECT goals FROM public.vt_game_stat_player WHERE player_id = 1340410 AND team_id = 20076 AND season_id = 816527 AND goals IS NOT NULL

06-21 16:19:35 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:35 -> SELECT goals FROM public.vt_game_stat_player WHERE player_id = 1340410 AND team_id = 20076 AND season_id = 816527 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:35 -> SELECT goals FROM public.vt_game_stat_player WHERE player_id = 1340410 AND team_id = 20076 AND season_id = 816527 AND goals IS NOT NULL

Successful query
Data Shape: (20, 1)
Running query: SELECT goals FROM public.vt_season_info_player WHERE player_id = 1330225 AND season_id = 816529

06-21 16:19:35 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:35 -> SELECT goals FROM public.vt_season_info_player WHERE player_id = 1330225 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:35 -> SELECT goals FROM public.vt_season_info_player WHERE player_id = 1330225 AND season_id = 816529

Successful query
Data Shape: (2, 1)
Running query: SELECT goals FROM public.vt_season_info_player WHERE player_id = 1359502 AND season_id = 816529

06-21 16:19:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:37 -> SELECT goals FROM public.vt_season_info_player WHERE player_id = 1359502 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:37 -> SELECT goals FROM public.vt_season_info_player WHERE player_id = 1359502 AND season_id = 816529

Successful query
Data Shape: (1, 1)
Running query: SELECT xg, goals FROM public.vt_season_metric_player WHERE player_id = 1598188 AND season_id = 816527

06-21 16:19:38 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:38 -> SELECT xg, goals FROM public.vt_season_metric_player WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:38 -> SELECT xg, goals FROM public.vt_season_metric_player WHERE player_id = 1598188 AND season_id = 816527
ERROR:root:Database error: column "goals" does not exist
LINE 1: SELECT xg, goals FROM public.vt_season_metric_player WHERE p...
                   ^

Failed query
Running query: SELECT xg, non_penalty_goals FROM public.vt_season_info_player WHERE player_id = 1598188 AND season_id = 816527

06-21 16:19:38 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:38 -> SELECT xg, non_penalty_goals FROM public.vt_season_info_player WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:38 -> SELECT xg, non_penalty_goals FROM public.vt_season_info_player WHERE player_id = 1598188 AND season_id = 816527

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, assists FROM public.vt_season_metric_player WHERE season_id = 816529 ORDER BY assists DESC LIMIT 1

06-21 16:19:38 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:38 -> SELECT player_id, assists FROM public.vt_season_metric_player WHERE season_id = 816529 ORDER BY assists DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:38 -> SELECT player_id, assists FROM public.vt_season_metric_player WHERE season_id = 816529 ORDER BY assists DESC LIMIT 1
ERROR:root:Database error: column "assists" does not exist
LINE 1: SELECT player_id, assists FROM public.vt_season_metric_playe...
                          ^

Failed query
Running query: SELECT player_id, assists FROM public.vt_season_stat_player WHERE season_id = 816529 ORDER BY assists DESC LIMIT 1

06-21 16:19:38 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:38 -> SELECT player_id, assists FROM public.vt_season_stat_player WHERE season_id = 816529 ORDER BY assists DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:38 -> SELECT player_id, assists FROM public.vt_season_stat_player WHERE season_id = 816529 ORDER BY assists DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, SUM(goals) AS total_goals FROM public.vt_season_stat_player WHERE season_id = 816530 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1

06-21 16:19:38 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:38 -> SELECT player_id, SUM(goals) AS total_goals FROM public.vt_season_stat_player WHERE season_id = 816530 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:38 -> SELECT player_id, SUM(goals) AS total_goals FROM public.vt_season_stat_player WHERE season_id = 816530 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, team_id, season_id, tackles_total FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY tackles_total DESC LIMIT 1

06-21 16:19:38 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:38 -> SELECT player_id, team_id, season_id, tackles_total FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY tackles_total DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:38 -> SELECT player_id, team_id, season_id, tackles_total FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY tackles_total DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT player_id, team_id, season_id, tackles_successful_with_possession FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY tackles_successful_with_possession DESC LIMIT 1

06-21 16:19:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:39 -> SELECT player_id, team_id, season_id, tackles_successful_with_possession FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY tackles_successful_with_possession DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:39 -> SELECT player_id, team_id, season_id, tackles_successful_with_possession FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY tackles_successful_with_possession DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT match_id FROM public.vt_game_score_player WHERE player_id = 1598188 AND raw_score >= 2 AND season_id = 816527

06-21 16:19:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:39 -> SELECT match_id FROM public.vt_game_score_player WHERE player_id = 1598188 AND raw_score >= 2 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:39 -> SELECT match_id FROM public.vt_game_score_player WHERE player_id = 1598188 AND raw_score >= 2 AND season_id = 816527

Successful query
Data Shape: (18, 1)
Running query: SELECT match_id FROM public.vt_game_metric_player WHERE player_id = 1598188 AND xg >= 2 AND season_id = 816527

06-21 16:19:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:39 -> SELECT match_id FROM public.vt_game_metric_player WHERE player_id = 1598188 AND xg >= 2 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:39 -> SELECT match_id FROM public.vt_game_metric_player WHERE player_id = 1598188 AND xg >= 2 AND season_id = 816527

Successful query
Data Shape: (0, 1)
Running query: SELECT match_id, xg FROM public.vt_game_metric_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY xg DESC LIMIT 5

06-21 16:19:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:39 -> SELECT match_id, xg FROM public.vt_game_metric_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY xg DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:39 -> SELECT match_id, xg FROM public.vt_game_metric_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY xg DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT match_id, xg FROM public.vt_game_score_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY xg DESC LIMIT 5

06-21 16:19:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:39 -> SELECT match_id, xg FROM public.vt_game_score_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY xg DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:39 -> SELECT match_id, xg FROM public.vt_game_score_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY xg DESC LIMIT 5
ERROR:root:Database error: column "xg" does not exist
LINE 1: SELECT match_id, xg FROM public.vt_game_score_player WHERE p...
                         ^

Failed query
Running query: SELECT player_id, team_id, season_id, mins_played, position FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY mins_played DESC LIMIT 10

06-21 16:19:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:39 -> SELECT player_id, team_id, season_id, mins_played, position FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY mins_played DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:39 -> SELECT player_id, team_id, season_id, mins_played, position FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY mins_played DESC LIMIT 10

Successful query
Data Shape: (10, 5)
Running query: SELECT player_id, team_id, season_id, mins_played, field_position_id FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY mins_played DESC LIMIT 10

06-21 16:19:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:39 -> SELECT player_id, team_id, season_id, mins_played, field_position_id FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY mins_played DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:39 -> SELECT player_id, team_id, season_id, mins_played, field_position_id FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY mins_played DESC LIMIT 10

Successful query
Data Shape: (10, 5)
Running query: SELECT player_id, xg FROM public.vt_season_metric_player WHERE season_id = 816529 AND position = 'MC' ORDER BY xg DESC LIMIT 10

06-21 16:19:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:40 -> SELECT player_id, xg FROM public.vt_season_metric_player WHERE season_id = 816529 AND position = 'MC' ORDER BY xg DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:40 -> SELECT player_id, xg FROM public.vt_season_metric_player WHERE season_id = 816529 AND position = 'MC' ORDER BY xg DESC LIMIT 10
ERROR:root:Database error: column "position" does not exist
LINE 1: ...season_metric_player WHERE season_id = 816529 AND position =...
                                                             ^

Failed query
Running query: SELECT player_id, xg FROM public.vt_season_info_player WHERE season_id = 816529 AND position = 'MC' ORDER BY xg DESC LIMIT 10

06-21 16:19:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:40 -> SELECT player_id, xg FROM public.vt_season_info_player WHERE season_id = 816529 AND position = 'MC' ORDER BY xg DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:40 -> SELECT player_id, xg FROM public.vt_season_info_player WHERE season_id = 816529 AND position = 'MC' ORDER BY xg DESC LIMIT 10

Successful query
Data Shape: (10, 2)
Running query: SELECT xg FROM public.vt_season_metric_player WHERE player_id = 1163110 AND season_id = 816529 AND team_id = 1946

06-21 16:19:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:40 -> SELECT xg FROM public.vt_season_metric_player WHERE player_id = 1163110 AND season_id = 816529 AND team_id = 1946
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:40 -> SELECT xg FROM public.vt_season_metric_player WHERE player_id = 1163110 AND season_id = 816529 AND team_id = 1946

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, tackles_total FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY tackles_total DESC LIMIT 5

06-21 16:19:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:40 -> SELECT player_id, tackles_total FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY tackles_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:40 -> SELECT player_id, tackles_total FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY tackles_total DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, tackles_successful_with_possession FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY tackles_successful_with_possession DESC LIMIT 5

06-21 16:19:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:40 -> SELECT player_id, tackles_successful_with_possession FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY tackles_successful_with_possession DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:40 -> SELECT player_id, tackles_successful_with_possession FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY tackles_successful_with_possession DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT match_id, MAX(xg) AS max_expected_goals FROM public.vt_game_metric_team WHERE season_id = 816527 GROUP BY match_id ORDER BY max_expected_goals DESC LIMIT 1

06-21 16:19:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:40 -> SELECT match_id, MAX(xg) AS max_expected_goals FROM public.vt_game_metric_team WHERE season_id = 816527 GROUP BY match_id ORDER BY max_expected_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:40 -> SELECT match_id, MAX(xg) AS max_expected_goals FROM public.vt_game_metric_team WHERE season_id = 816527 GROUP BY match_id ORDER BY max_expected_goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT xg, goals FROM public.vt_season_info_player WHERE player_id = 1598188 AND season_id = 816527

06-21 16:19:44 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:44 -> SELECT xg, goals FROM public.vt_season_info_player WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:44 -> SELECT xg, goals FROM public.vt_season_info_player WHERE player_id = 1598188 AND season_id = 816527

Successful query
Data Shape: (1, 2)
Running query: SELECT xg, non_penalty_goals FROM public.vt_season_stat_player WHERE player_id = 1598188 AND season_id = 816527

06-21 16:19:44 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:44 -> SELECT xg, non_penalty_goals FROM public.vt_season_stat_player WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:44 -> SELECT xg, non_penalty_goals FROM public.vt_season_stat_player WHERE player_id = 1598188 AND season_id = 816527
ERROR:root:Database error: column "xg" does not exist
LINE 1: SELECT xg, non_penalty_goals FROM public.vt_season_stat_play...
               ^
HINT:  Perhaps you meant to reference the column "vt_season_stat_player.xp".

Failed query
Running query: SELECT name, position, age FROM t_player WHERE player_id = 1598188 AND team_id = 20076

06-21 16:19:44 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:44 -> SELECT name, position, age FROM t_player WHERE player_id = 1598188 AND team_id = 20076
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:44 -> SELECT name, position, age FROM t_player WHERE player_id = 1598188 AND team_id = 20076

Successful query
Data Shape: (1, 3)
Running query: SELECT team_id, name, alias FROM t_team WHERE team_id = 20076

06-21 16:19:44 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:44 -> SELECT team_id, name, alias FROM t_team WHERE team_id = 20076
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:44 -> SELECT team_id, name, alias FROM t_team WHERE team_id = 20076

Successful query
Data Shape: (1, 3)
Running query: SELECT season_id, season_name FROM t_season WHERE season_id = 816527

06-21 16:19:44 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:44 -> SELECT season_id, season_name FROM t_season WHERE season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:44 -> SELECT season_id, season_name FROM t_season WHERE season_id = 816527
ERROR:root:Database error: column "season_name" does not exist
LINE 1: SELECT season_id, season_name FROM t_season WHERE season_id ...
                          ^

Failed query
Running query: SELECT player_id, team_id, season_id, dribbles_total FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY dribbles_total DESC LIMIT 1

06-21 16:19:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:45 -> SELECT player_id, team_id, season_id, dribbles_total FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY dribbles_total DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:45 -> SELECT player_id, team_id, season_id, dribbles_total FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY dribbles_total DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT player_id, team_id, season_id, dribbles_total FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY dribbles_total DESC LIMIT 1

06-21 16:19:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:45 -> SELECT player_id, team_id, season_id, dribbles_total FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY dribbles_total DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:45 -> SELECT player_id, team_id, season_id, dribbles_total FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY dribbles_total DESC LIMIT 1
ERROR:root:Database error: column "dribbles_total" does not exist
LINE 1: SELECT player_id, team_id, season_id, dribbles_total FROM pu...
                                              ^

Failed query
Running query: SELECT assists, goals FROM public.vt_game_stat_player WHERE player_id = 1165562 AND season_id = 816529 AND assists IS NOT NULL AND goals IS NOT NULL

06-21 16:19:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:45 -> SELECT assists, goals FROM public.vt_game_stat_player WHERE player_id = 1165562 AND season_id = 816529 AND assists IS NOT NULL AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:45 -> SELECT assists, goals FROM public.vt_game_stat_player WHERE player_id = 1165562 AND season_id = 816529 AND assists IS NOT NULL AND goals IS NOT NULL

Successful query
Data Shape: (20, 2)
Running query: SELECT assists, goals FROM public.vt_season_info_player WHERE player_id = 1165562 AND season_id = 816529 AND assists IS NOT NULL AND goals IS NOT NULL

06-21 16:19:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:45 -> SELECT assists, goals FROM public.vt_season_info_player WHERE player_id = 1165562 AND season_id = 816529 AND assists IS NOT NULL AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:45 -> SELECT assists, goals FROM public.vt_season_info_player WHERE player_id = 1165562 AND season_id = 816529 AND assists IS NOT NULL AND goals IS NOT NULL

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, SUM(goals) AS total_goals FROM public.vt_season_info_player WHERE season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1

06-21 16:19:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:45 -> SELECT player_id, SUM(goals) AS total_goals FROM public.vt_season_info_player WHERE season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:45 -> SELECT player_id, SUM(goals) AS total_goals FROM public.vt_season_info_player WHERE season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, SUM(goals) AS total_goals FROM public.vt_season_stat_player WHERE season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1

06-21 16:19:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:45 -> SELECT player_id, SUM(goals) AS total_goals FROM public.vt_season_stat_player WHERE season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:45 -> SELECT player_id, SUM(goals) AS total_goals FROM public.vt_season_stat_player WHERE season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, team_id, season_id, xg, xa FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY xa DESC LIMIT 5

06-21 16:19:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:46 -> SELECT player_id, team_id, season_id, xg, xa FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY xa DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:46 -> SELECT player_id, team_id, season_id, xg, xa FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY xa DESC LIMIT 5

Successful query
Data Shape: (5, 5)
Running query: SELECT player_id, team_id, first_name, last_name, position, age FROM public.t_player WHERE player_id = 1598188

06-21 16:19:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:46 -> SELECT player_id, team_id, first_name, last_name, position, age FROM public.t_player WHERE player_id = 1598188
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:46 -> SELECT player_id, team_id, first_name, last_name, position, age FROM public.t_player WHERE player_id = 1598188

Successful query
Data Shape: (1, 6)
Running query: SELECT player_id, team_id, player_name, team_name, season_name, mins_played FROM public.v_player_sc WHERE player_id = 1598188 AND mins_played IS NOT NULL

06-21 16:19:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:46 -> SELECT player_id, team_id, player_name, team_name, season_name, mins_played FROM public.v_player_sc WHERE player_id = 1598188 AND mins_played IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:46 -> SELECT player_id, team_id, player_name, team_name, season_name, mins_played FROM public.v_player_sc WHERE player_id = 1598188 AND mins_played IS NOT NULL

Successful query
Data Shape: (0, 6)
Running query: SELECT player_id, SUM(xg_on_target) AS total_shots_on_target FROM public.vt_season_info_player WHERE team_id = 4265 AND season_id = 816527 GROUP BY player_id ORDER BY total_shots_on_target DESC LIMIT 3

06-21 16:19:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:46 -> SELECT player_id, SUM(xg_on_target) AS total_shots_on_target FROM public.vt_season_info_player WHERE team_id = 4265 AND season_id = 816527 GROUP BY player_id ORDER BY total_shots_on_target DESC LIMIT 3
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:46 -> SELECT player_id, SUM(xg_on_target) AS total_shots_on_target FROM public.vt_season_info_player WHERE team_id = 4265 AND season_id = 816527 GROUP BY player_id ORDER BY total_shots_on_target DESC LIMIT 3
ERROR:root:Database error: column "xg_on_target" does not exist
LINE 1: SELECT player_id, SUM(xg_on_target) AS total_shots_on_target...
                              ^

Failed query
Running query: SELECT player_id, team_id, season_id, goals FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5

06-21 16:19:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:46 -> SELECT player_id, team_id, season_id, goals FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:46 -> SELECT player_id, team_id, season_id, goals FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, team_id, season_id, goals FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:19:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:46 -> SELECT player_id, team_id, season_id, goals FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:46 -> SELECT player_id, team_id, season_id, goals FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT player_id, team_id, assists FROM public.vt_season_info_player WHERE season_id = 816529 ORDER BY assists DESC LIMIT 1

06-21 16:19:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:46 -> SELECT player_id, team_id, assists FROM public.vt_season_info_player WHERE season_id = 816529 ORDER BY assists DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:46 -> SELECT player_id, team_id, assists FROM public.vt_season_info_player WHERE season_id = 816529 ORDER BY assists DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT first_name, last_name, position, dob, height, weight, nationality_confirmed FROM public.t_player WHERE player_id = 1598188 AND team_id = 20076

06-21 16:19:47 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:47 -> SELECT first_name, last_name, position, dob, height, weight, nationality_confirmed FROM public.t_player WHERE player_id = 1598188 AND team_id = 20076
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:47 -> SELECT first_name, last_name, position, dob, height, weight, nationality_confirmed FROM public.t_player WHERE player_id = 1598188 AND team_id = 20076

Successful query
Data Shape: (1, 7)
Running query: SELECT player_name, team_name, season_name, mins_played, country_code, elo FROM public.v_player_sc WHERE player_id = 1598188 AND team_id = 20076 AND season_name = 'ESP I 2023'

06-21 16:19:47 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:47 -> SELECT player_name, team_name, season_name, mins_played, country_code, elo FROM public.v_player_sc WHERE player_id = 1598188 AND team_id = 20076 AND season_name = 'ESP I 2023'
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:47 -> SELECT player_name, team_name, season_name, mins_played, country_code, elo FROM public.v_player_sc WHERE player_id = 1598188 AND team_id = 20076 AND season_name = 'ESP I 2023'

Successful query
Data Shape: (0, 6)
Running query: SELECT player_id, team_id, season_id, xa FROM public.vt_season_metric_player WHERE season_id = 816527 AND xa IS NOT NULL ORDER BY xa DESC LIMIT 5

06-21 16:19:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:49 -> SELECT player_id, team_id, season_id, xa FROM public.vt_season_metric_player WHERE season_id = 816527 AND xa IS NOT NULL ORDER BY xa DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:49 -> SELECT player_id, team_id, season_id, xa FROM public.vt_season_metric_player WHERE season_id = 816527 AND xa IS NOT NULL ORDER BY xa DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, team_id, season_id, xa FROM public.vt_season_info_player WHERE season_id = 816527 AND xa IS NOT NULL ORDER BY xa DESC LIMIT 5

06-21 16:19:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:49 -> SELECT player_id, team_id, season_id, xa FROM public.vt_season_info_player WHERE season_id = 816527 AND xa IS NOT NULL ORDER BY xa DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:49 -> SELECT player_id, team_id, season_id, xa FROM public.vt_season_info_player WHERE season_id = 816527 AND xa IS NOT NULL ORDER BY xa DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT first_name, last_name, position, dob, weight, height, nationality_confirmed, market_value FROM public.t_player WHERE player_id = 1598188 AND team_id = 20076

06-21 16:19:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:49 -> SELECT first_name, last_name, position, dob, weight, height, nationality_confirmed, market_value FROM public.t_player WHERE player_id = 1598188 AND team_id = 20076
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:49 -> SELECT first_name, last_name, position, dob, weight, height, nationality_confirmed, market_value FROM public.t_player WHERE player_id = 1598188 AND team_id = 20076

Successful query
Data Shape: (1, 8)
Running query: SELECT player_name, team_name, season_name, mins_played, country_code, elo FROM public.v_player_sc WHERE player_id = 1598188 AND team_id = 20076

06-21 16:19:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:49 -> SELECT player_name, team_name, season_name, mins_played, country_code, elo FROM public.v_player_sc WHERE player_id = 1598188 AND team_id = 20076
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:49 -> SELECT player_name, team_name, season_name, mins_played, country_code, elo FROM public.v_player_sc WHERE player_id = 1598188 AND team_id = 20076

Successful query
Data Shape: (0, 6)
Running query: SELECT match_id, passes_total FROM public.vt_season_stat_player WHERE player_id = 69699 AND season_id = 816527 ORDER BY passes_total DESC LIMIT 5

06-21 16:19:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:49 -> SELECT match_id, passes_total FROM public.vt_season_stat_player WHERE player_id = 69699 AND season_id = 816527 ORDER BY passes_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:49 -> SELECT match_id, passes_total FROM public.vt_season_stat_player WHERE player_id = 69699 AND season_id = 816527 ORDER BY passes_total DESC LIMIT 5
ERROR:root:Database error: column "match_id" does not exist
LINE 1: SELECT match_id, passes_total FROM public.vt_season_stat_pla...
               ^

Failed query
Running query: SELECT match_id, passes_total FROM public.vt_season_opta_player WHERE player_id = 69699 AND season_id = 816527 AND passes_total IS NOT NULL ORDER BY passes_total DESC LIMIT 5

06-21 16:19:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:50 -> SELECT match_id, passes_total FROM public.vt_season_opta_player WHERE player_id = 69699 AND season_id = 816527 AND passes_total IS NOT NULL ORDER BY passes_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:50 -> SELECT match_id, passes_total FROM public.vt_season_opta_player WHERE player_id = 69699 AND season_id = 816527 AND passes_total IS NOT NULL ORDER BY passes_total DESC LIMIT 5
ERROR:root:Database error: column "match_id" does not exist
LINE 1: SELECT match_id, passes_total FROM public.vt_season_opta_pla...
               ^

Failed query
Running query: SELECT player_id, passes_total, match_id, season_id FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY passes_total DESC LIMIT 5

06-21 16:19:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:50 -> SELECT player_id, passes_total, match_id, season_id FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY passes_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:50 -> SELECT player_id, passes_total, match_id, season_id FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY passes_total DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, passes_total, match_id, season_id FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 AND passes_total IS NOT NULL ORDER BY passes_total DESC LIMIT 5

06-21 16:19:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:50 -> SELECT player_id, passes_total, match_id, season_id FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 AND passes_total IS NOT NULL ORDER BY passes_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:50 -> SELECT player_id, passes_total, match_id, season_id FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 AND passes_total IS NOT NULL ORDER BY passes_total DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, xg FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY xg DESC LIMIT 1

06-21 16:19:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:50 -> SELECT player_id, xg FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY xg DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:50 -> SELECT player_id, xg FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY xg DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, xg FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY xg DESC LIMIT 1

06-21 16:19:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:50 -> SELECT player_id, xg FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY xg DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:50 -> SELECT player_id, xg FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY xg DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, xg FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY xg DESC LIMIT 1

06-21 16:19:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:50 -> SELECT player_id, xg FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY xg DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:50 -> SELECT player_id, xg FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY xg DESC LIMIT 1
ERROR:root:Database error: column "xg" does not exist
LINE 1: SELECT player_id, xg FROM public.vt_season_stat_player WHERE...
                          ^
HINT:  Perhaps you meant to reference the column "vt_season_stat_player.xp".

Failed query
Running query: SELECT player_id, goals FROM public.vt_season_opta_player WHERE season_id = 816529 ORDER BY goals DESC LIMIT 1

06-21 16:19:51 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:51 -> SELECT player_id, goals FROM public.vt_season_opta_player WHERE season_id = 816529 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:51 -> SELECT player_id, goals FROM public.vt_season_opta_player WHERE season_id = 816529 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, goals FROM public.vt_season_stat_player WHERE season_id = 816529 ORDER BY goals DESC LIMIT 1

06-21 16:19:51 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:51 -> SELECT player_id, goals FROM public.vt_season_stat_player WHERE season_id = 816529 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:51 -> SELECT player_id, goals FROM public.vt_season_stat_player WHERE season_id = 816529 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, goals FROM public.vt_season_info_player WHERE team_id = 3651 AND season_id = 816530 ORDER BY goals DESC LIMIT 5

06-21 16:19:51 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:51 -> SELECT player_id, goals FROM public.vt_season_info_player WHERE team_id = 3651 AND season_id = 816530 ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:51 -> SELECT player_id, goals FROM public.vt_season_info_player WHERE team_id = 3651 AND season_id = 816530 ORDER BY goals DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, non_penalty_goals FROM public.vt_season_stat_player WHERE team_id = 3651 AND season_id = 816530 ORDER BY non_penalty_goals DESC LIMIT 5

06-21 16:19:51 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:51 -> SELECT player_id, non_penalty_goals FROM public.vt_season_stat_player WHERE team_id = 3651 AND season_id = 816530 ORDER BY non_penalty_goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:51 -> SELECT player_id, non_penalty_goals FROM public.vt_season_stat_player WHERE team_id = 3651 AND season_id = 816530 ORDER BY non_penalty_goals DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT passes_total FROM public.vt_season_stat_player WHERE player_id = 1296920 AND season_id = 816527 AND passes_total IS NOT NULL

06-21 16:19:51 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:51 -> SELECT passes_total FROM public.vt_season_stat_player WHERE player_id = 1296920 AND season_id = 816527 AND passes_total IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:51 -> SELECT passes_total FROM public.vt_season_stat_player WHERE player_id = 1296920 AND season_id = 816527 AND passes_total IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT passes_accurate FROM public.vt_season_stat_player WHERE player_id = 1296920 AND season_id = 816527 AND passes_accurate IS NOT NULL

06-21 16:19:51 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:51 -> SELECT passes_accurate FROM public.vt_season_stat_player WHERE player_id = 1296920 AND season_id = 816527 AND passes_accurate IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:51 -> SELECT passes_accurate FROM public.vt_season_stat_player WHERE player_id = 1296920 AND season_id = 816527 AND passes_accurate IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, passes_total FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY passes_total DESC LIMIT 1

06-21 16:19:52 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:52 -> SELECT player_id, passes_total FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY passes_total DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:52 -> SELECT player_id, passes_total FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY passes_total DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, passes_accurate FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY passes_accurate DESC LIMIT 1

06-21 16:19:52 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:52 -> SELECT player_id, passes_accurate FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY passes_accurate DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:52 -> SELECT player_id, passes_accurate FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY passes_accurate DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT shots_on_target FROM public.vt_season_stat_player WHERE player_id = 69699 AND season_id = 816527 AND shots_on_target IS NOT NULL

06-21 16:19:52 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:52 -> SELECT shots_on_target FROM public.vt_season_stat_player WHERE player_id = 69699 AND season_id = 816527 AND shots_on_target IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:52 -> SELECT shots_on_target FROM public.vt_season_stat_player WHERE player_id = 69699 AND season_id = 816527 AND shots_on_target IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT shots_on_target FROM public.vt_season_opta_player WHERE player_id = 69699 AND season_id = 816527 AND shots_on_target IS NOT NULL

06-21 16:19:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:54 -> SELECT shots_on_target FROM public.vt_season_opta_player WHERE player_id = 69699 AND season_id = 816527 AND shots_on_target IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:54 -> SELECT shots_on_target FROM public.vt_season_opta_player WHERE player_id = 69699 AND season_id = 816527 AND shots_on_target IS NOT NULL
ERROR:root:Database error: column "shots_on_target" does not exist
LINE 1: SELECT shots_on_target FROM public.vt_season_opta_player WHE...
               ^

Failed query
Running query: SELECT passes_total FROM public.vt_season_stat_player WHERE player_id = 38908 AND season_id = 816528 AND passes_total IS NOT NULL

06-21 16:19:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:54 -> SELECT passes_total FROM public.vt_season_stat_player WHERE player_id = 38908 AND season_id = 816528 AND passes_total IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:54 -> SELECT passes_total FROM public.vt_season_stat_player WHERE player_id = 38908 AND season_id = 816528 AND passes_total IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT passes_accurate FROM public.vt_season_opta_player WHERE player_id = 38908 AND season_id = 816528 AND passes_accurate IS NOT NULL

06-21 16:19:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:54 -> SELECT passes_accurate FROM public.vt_season_opta_player WHERE player_id = 38908 AND season_id = 816528 AND passes_accurate IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:54 -> SELECT passes_accurate FROM public.vt_season_opta_player WHERE player_id = 38908 AND season_id = 816528 AND passes_accurate IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT assists FROM public.vt_season_info_player WHERE player_id = 69699 AND season_id = 816527 AND assists IS NOT NULL

06-21 16:19:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:54 -> SELECT assists FROM public.vt_season_info_player WHERE player_id = 69699 AND season_id = 816527 AND assists IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:54 -> SELECT assists FROM public.vt_season_info_player WHERE player_id = 69699 AND season_id = 816527 AND assists IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT assists FROM public.vt_season_opta_player WHERE player_id = 69699 AND season_id = 816527 AND assists IS NOT NULL

06-21 16:19:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:54 -> SELECT assists FROM public.vt_season_opta_player WHERE player_id = 69699 AND season_id = 816527 AND assists IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:54 -> SELECT assists FROM public.vt_season_opta_player WHERE player_id = 69699 AND season_id = 816527 AND assists IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT assists FROM public.vt_season_stat_player WHERE player_id = 69699 AND season_id = 816527 AND assists IS NOT NULL

06-21 16:19:55 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:55 -> SELECT assists FROM public.vt_season_stat_player WHERE player_id = 69699 AND season_id = 816527 AND assists IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:55 -> SELECT assists FROM public.vt_season_stat_player WHERE player_id = 69699 AND season_id = 816527 AND assists IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, goals FROM public.vt_season_info_player WHERE season_id = 816528 ORDER BY goals DESC LIMIT 1

06-21 16:19:55 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:55 -> SELECT player_id, goals FROM public.vt_season_info_player WHERE season_id = 816528 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:55 -> SELECT player_id, goals FROM public.vt_season_info_player WHERE season_id = 816528 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, goals FROM public.vt_season_opta_player WHERE season_id = 816528 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

06-21 16:19:55 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:55 -> SELECT player_id, goals FROM public.vt_season_opta_player WHERE season_id = 816528 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:55 -> SELECT player_id, goals FROM public.vt_season_opta_player WHERE season_id = 816528 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, goals FROM public.vt_season_stat_player WHERE season_id = 816528 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

06-21 16:19:55 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:55 -> SELECT player_id, goals FROM public.vt_season_stat_player WHERE season_id = 816528 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:55 -> SELECT player_id, goals FROM public.vt_season_stat_player WHERE season_id = 816528 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT passes_total FROM public.vt_season_stat_player WHERE player_id = 69699 AND season_id = 816527 AND passes_total IS NOT NULL

06-21 16:19:55 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:55 -> SELECT passes_total FROM public.vt_season_stat_player WHERE player_id = 69699 AND season_id = 816527 AND passes_total IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:55 -> SELECT passes_total FROM public.vt_season_stat_player WHERE player_id = 69699 AND season_id = 816527 AND passes_total IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT goals FROM public.vt_season_info_player WHERE player_id = 1359502 AND season_id = 816529 AND goals IS NOT NULL

06-21 16:19:55 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:55 -> SELECT goals FROM public.vt_season_info_player WHERE player_id = 1359502 AND season_id = 816529 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:55 -> SELECT goals FROM public.vt_season_info_player WHERE player_id = 1359502 AND season_id = 816529 AND goals IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT goals FROM public.vt_season_opta_player WHERE player_id = 1359502 AND season_id = 816529 AND goals IS NOT NULL

06-21 16:19:55 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:55 -> SELECT goals FROM public.vt_season_opta_player WHERE player_id = 1359502 AND season_id = 816529 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:55 -> SELECT goals FROM public.vt_season_opta_player WHERE player_id = 1359502 AND season_id = 816529 AND goals IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT goals FROM public.vt_season_stat_player WHERE player_id = 1359502 AND season_id = 816529 AND goals IS NOT NULL

06-21 16:19:55 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:55 -> SELECT goals FROM public.vt_season_stat_player WHERE player_id = 1359502 AND season_id = 816529 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:55 -> SELECT goals FROM public.vt_season_stat_player WHERE player_id = 1359502 AND season_id = 816529 AND goals IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT match_id, passes_total FROM public.vt_game_stat_player WHERE player_id = 69699 AND season_id = 816527 ORDER BY passes_total DESC LIMIT 5

06-21 16:19:56 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:56 -> SELECT match_id, passes_total FROM public.vt_game_stat_player WHERE player_id = 69699 AND season_id = 816527 ORDER BY passes_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:56 -> SELECT match_id, passes_total FROM public.vt_game_stat_player WHERE player_id = 69699 AND season_id = 816527 ORDER BY passes_total DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT match_id, passes_total FROM public.vt_game_stat_player WHERE player_id = 69699 AND season_id = 816527 AND passes_total IS NOT NULL ORDER BY passes_total DESC LIMIT 5

06-21 16:19:56 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:56 -> SELECT match_id, passes_total FROM public.vt_game_stat_player WHERE player_id = 69699 AND season_id = 816527 AND passes_total IS NOT NULL ORDER BY passes_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:56 -> SELECT match_id, passes_total FROM public.vt_game_stat_player WHERE player_id = 69699 AND season_id = 816527 AND passes_total IS NOT NULL ORDER BY passes_total DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT assists FROM public.vt_season_info_player WHERE player_id = 69699 AND season_id = 816372 AND assists IS NOT NULL

06-21 16:19:56 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:56 -> SELECT assists FROM public.vt_season_info_player WHERE player_id = 69699 AND season_id = 816372 AND assists IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:56 -> SELECT assists FROM public.vt_season_info_player WHERE player_id = 69699 AND season_id = 816372 AND assists IS NOT NULL

Successful query
Data Shape: (0, 1)
Running query: SELECT player_id, score_pd FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY score_pd DESC LIMIT 1

06-21 16:19:56 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:56 -> SELECT player_id, score_pd FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:56 -> SELECT player_id, score_pd FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY score_pd DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals_90 DESC LIMIT 1

06-21 16:19:56 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:56 -> SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:56 -> SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals_90 DESC LIMIT 1
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: SELECT player_id, player_name, goals_90 FROM vm_agg_season_p...
                                       ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE team_id = 4265 AND season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1

06-21 16:19:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:57 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE team_id = 4265 AND season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:57 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE team_id = 4265 AND season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...cored FROM public.t_goal WHERE team_id = 4265 AND season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, team_id, season_id, non_penalty_shots_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND team_id = 4279 ORDER BY non_penalty_shots_90 DESC LIMIT 1

06-21 16:19:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:57 -> SELECT player_id, player_name, team_id, season_id, non_penalty_shots_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND team_id = 4279 ORDER BY non_penalty_shots_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:57 -> SELECT player_id, player_name, team_id, season_id, non_penalty_shots_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND team_id = 4279 ORDER BY non_penalty_shots_90 DESC LIMIT 1

Successful query
Data Shape: (1, 5)
Running query: SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:19:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:59 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:59 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, team_id, season_id, goals_90, player_name FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND age < 25 ORDER BY goals_90 DESC LIMIT 5

06-21 16:19:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:59 -> SELECT player_id, team_id, season_id, goals_90, player_name FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND age < 25 ORDER BY goals_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:59 -> SELECT player_id, team_id, season_id, goals_90, player_name FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND age < 25 ORDER BY goals_90 DESC LIMIT 5
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: SELECT player_id, team_id, season_id, goals_90, player_name ...
                                              ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT player_id, team_id, season_id, score_pd FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (1169986, 1217644, 1237908, 1217696, 1221486) AND age < 25 ORDER BY score_pd DESC LIMIT 5

06-21 16:19:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:59 -> SELECT player_id, team_id, season_id, score_pd FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (1169986, 1217644, 1237908, 1217696, 1221486) AND age < 25 ORDER BY score_pd DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:59 -> SELECT player_id, team_id, season_id, score_pd FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (1169986, 1217644, 1237908, 1217696, 1221486) AND age < 25 ORDER BY score_pd DESC LIMIT 5
ERROR:root:Database error: column "age" does not exist
LINE 1: ...(1169986, 1217644, 1237908, 1217696, 1221486) AND age < 25 O...
                                                             ^

Failed query
Running query: SELECT player_id, team_id, season_id, season_year, player_name, age FROM vm_agg_season_player_all WHERE season_id = 816527 AND season_year = 2023 AND age < 25 AND league_type_id = 1 ORDER BY goals_scored DESC LIMIT 5

06-21 16:19:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:59 -> SELECT player_id, team_id, season_id, season_year, player_name, age FROM vm_agg_season_player_all WHERE season_id = 816527 AND season_year = 2023 AND age < 25 AND league_type_id = 1 ORDER BY goals_scored DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:59 -> SELECT player_id, team_id, season_id, season_year, player_name, age FROM vm_agg_season_player_all WHERE season_id = 816527 AND season_year = 2023 AND age < 25 AND league_type_id = 1 ORDER BY goals_scored DESC LIMIT 5
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...id, season_id, season_year, player_name, age FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, COUNT(goal_id) as goals FROM public.t_goal WHERE player_id IN (1169986, 1217644, 1237908, 1217696, 1221486) AND season_id = 816527 GROUP BY player_id ORDER BY goals DESC LIMIT 5

06-21 16:19:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:59 -> SELECT player_id, COUNT(goal_id) as goals FROM public.t_goal WHERE player_id IN (1169986, 1217644, 1237908, 1217696, 1221486) AND season_id = 816527 GROUP BY player_id ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:59 -> SELECT player_id, COUNT(goal_id) as goals FROM public.t_goal WHERE player_id IN (1169986, 1217644, 1237908, 1217696, 1221486) AND season_id = 816527 GROUP BY player_id ORDER BY goals DESC LIMIT 5
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...(1169986, 1217644, 1237908, 1217696, 1221486) AND season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, team_id, season_id, non_penalty_shots_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY non_penalty_shots_90 DESC LIMIT 1

06-21 16:19:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:59 -> SELECT player_id, player_name, team_id, season_id, non_penalty_shots_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY non_penalty_shots_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:59 -> SELECT player_id, player_name, team_id, season_id, non_penalty_shots_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY non_penalty_shots_90 DESC LIMIT 1

Successful query
Data Shape: (1, 5)
Running query: SELECT player_id, COUNT(goal_id) as goals FROM public.t_goal WHERE player_id IN (SELECT player_id FROM t_player WHERE age < 25) AND season_id = 816527 GROUP BY player_id ORDER BY goals DESC LIMIT 5

06-21 16:19:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:19:59 -> SELECT player_id, COUNT(goal_id) as goals FROM public.t_goal WHERE player_id IN (SELECT player_id FROM t_player WHERE age < 25) AND season_id = 816527 GROUP BY player_id ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:19:59 -> SELECT player_id, COUNT(goal_id) as goals FROM public.t_goal WHERE player_id IN (SELECT player_id FROM t_player WHERE age < 25) AND season_id = 816527 GROUP BY player_id ORDER BY goals DESC LIMIT 5
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...ELECT player_id FROM t_player WHERE age < 25) AND season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND age < 25 AND team_id IN (4265, 4279) ORDER BY goals_90 DESC LIMIT 5

06-21 16:20:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:00 -> SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND age < 25 AND team_id IN (4265, 4279) ORDER BY goals_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:00 -> SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND age < 25 AND team_id IN (4265, 4279) ORDER BY goals_90 DESC LIMIT 5
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: SELECT player_id, player_name, goals_90 FROM vm_agg_season_p...
                                       ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT player_id, team_id, season_id, player_name, age, team_games_played, team_mins_played, mins_played, games_lost FROM vm_agg_season_player_all WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND age < 25 ORDER BY mins_played DESC LIMIT 5)

06-21 16:20:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:00 -> SELECT player_id, team_id, season_id, player_name, age, team_games_played, team_mins_played, mins_played, games_lost FROM vm_agg_season_player_all WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND age < 25 ORDER BY mins_played DESC LIMIT 5)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:00 -> SELECT player_id, team_id, season_id, player_name, age, team_games_played, team_mins_played, mins_played, games_lost FROM vm_agg_season_player_all WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND age < 25 ORDER BY mins_played DESC LIMIT 5)
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...d, team_mins_played, mins_played, games_lost FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT assists FROM public.agg_season_player_pd WHERE player_id = 1598188 AND season_id = 816527

06-21 16:20:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:00 -> SELECT assists FROM public.agg_season_player_pd WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:00 -> SELECT assists FROM public.agg_season_player_pd WHERE player_id = 1598188 AND season_id = 816527
ERROR:root:Database error: column "assists" does not exist
LINE 1: SELECT assists FROM public.agg_season_player_pd WHERE player...
               ^

Failed query
Running query: SELECT match_id, MAX(score_pd) AS max_expected_goals FROM public.agg_game_player_pd WHERE player_id = 1598188 AND season_id = 816527

06-21 16:20:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:00 -> SELECT match_id, MAX(score_pd) AS max_expected_goals FROM public.agg_game_player_pd WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:00 -> SELECT match_id, MAX(score_pd) AS max_expected_goals FROM public.agg_game_player_pd WHERE player_id = 1598188 AND season_id = 816527
ERROR:root:Database error: column "agg_game_player_pd.match_id" must appear in the GROUP BY clause or be used in an aggregate function
LINE 1: SELECT match_id, MAX(score_pd) AS max_expected_goals FROM pu...
               ^

Failed query
Running query: SELECT match_id, xg FROM public.vt_game_metric_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY xg DESC LIMIT 1

06-21 16:20:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:00 -> SELECT match_id, xg FROM public.vt_game_metric_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY xg DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:00 -> SELECT match_id, xg FROM public.vt_game_metric_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY xg DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT match_id, xp FROM public.vt_game_stat_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY xp DESC LIMIT 1

06-21 16:20:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:00 -> SELECT match_id, xp FROM public.vt_game_stat_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY xp DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:00 -> SELECT match_id, xp FROM public.vt_game_stat_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY xp DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT team_name FROM vm_agg_season_team_similarity WHERE team_id = 119270 AND season_id = 816527

06-21 16:20:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:00 -> SELECT team_name FROM vm_agg_season_team_similarity WHERE team_id = 119270 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:00 -> SELECT team_name FROM vm_agg_season_team_similarity WHERE team_id = 119270 AND season_id = 816527

Successful query
Data Shape: (0, 1)
Running query: SELECT team_name FROM vm_agg_season_team WHERE team_id = 119270 AND season_id = 816527

06-21 16:20:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:00 -> SELECT team_name FROM vm_agg_season_team WHERE team_id = 119270 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:00 -> SELECT team_name FROM vm_agg_season_team WHERE team_id = 119270 AND season_id = 816527

Successful query
Data Shape: (0, 1)
Running query: SELECT team_name FROM vm_agg_season_team_opta WHERE team_id = 119270 AND season_id = 816527

06-21 16:20:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:01 -> SELECT team_name FROM vm_agg_season_team_opta WHERE team_id = 119270 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:01 -> SELECT team_name FROM vm_agg_season_team_opta WHERE team_id = 119270 AND season_id = 816527

Successful query
Data Shape: (0, 1)
Running query: SELECT player_id, COUNT(goal_id) as goals_scored FROM public.t_goal WHERE team_id = 4279 AND season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1

06-21 16:20:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:01 -> SELECT player_id, COUNT(goal_id) as goals_scored FROM public.t_goal WHERE team_id = 4279 AND season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:01 -> SELECT player_id, COUNT(goal_id) as goals_scored FROM public.t_goal WHERE team_id = 4279 AND season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...cored FROM public.t_goal WHERE team_id = 4279 AND season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, score_pd FROM public.agg_season_player_pd WHERE season_id = 816527 AND team_id = 4279 ORDER BY score_pd DESC LIMIT 1

06-21 16:20:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:01 -> SELECT player_id, score_pd FROM public.agg_season_player_pd WHERE season_id = 816527 AND team_id = 4279 ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:01 -> SELECT player_id, score_pd FROM public.agg_season_player_pd WHERE season_id = 816527 AND team_id = 4279 ORDER BY score_pd DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT shots_on_target_per_game FROM vm_agg_season_team WHERE team_id = 20076 AND season_id = 816527

06-21 16:20:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:01 -> SELECT shots_on_target_per_game FROM vm_agg_season_team WHERE team_id = 20076 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:01 -> SELECT shots_on_target_per_game FROM vm_agg_season_team WHERE team_id = 20076 AND season_id = 816527

Successful query
Data Shape: (3, 1)
Running query: SELECT shots_on_target_per_game FROM vm_agg_season_team_opta WHERE team_id = 20076 AND season_id = 816527

06-21 16:20:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:01 -> SELECT shots_on_target_per_game FROM vm_agg_season_team_opta WHERE team_id = 20076 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:01 -> SELECT shots_on_target_per_game FROM vm_agg_season_team_opta WHERE team_id = 20076 AND season_id = 816527

Successful query
Data Shape: (3, 1)
Running query: SELECT shots_on_target FROM vm_agg_season_player_opta WHERE player_id = 1598188 AND season_id = 816527

06-21 16:20:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:03 -> SELECT shots_on_target FROM vm_agg_season_player_opta WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:03 -> SELECT shots_on_target FROM vm_agg_season_player_opta WHERE player_id = 1598188 AND season_id = 816527
ERROR:root:Database error: column "shots_on_target" does not exist
LINE 1: SELECT shots_on_target FROM vm_agg_season_player_opta WHERE ...
               ^

Failed query
Running query: SELECT player_id, COUNT(goal_id) as goals_scored FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1

06-21 16:20:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:04 -> SELECT player_id, COUNT(goal_id) as goals_scored FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:04 -> SELECT player_id, COUNT(goal_id) as goals_scored FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...goal_id) as goals_scored FROM public.t_goal WHERE season_id ...
                                                             ^

Failed query
Running query: SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND provider_id = 1 ORDER BY score_pd DESC LIMIT 1

06-21 16:20:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:04 -> SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND provider_id = 1 ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:04 -> SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND provider_id = 1 ORDER BY score_pd DESC LIMIT 1

Successful query
Data Shape: (0, 1)
Running query: SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE team_id IN (4277, 20076) AND season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1

06-21 16:20:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:04 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE team_id IN (4277, 20076) AND season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:04 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE team_id IN (4277, 20076) AND season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ... public.t_goal WHERE team_id IN (4277, 20076) AND season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:20:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:04 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:04 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, SUM(dl_index) AS total_goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 GROUP BY player_id, player_name ORDER BY total_goals DESC LIMIT 1

06-21 16:20:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:04 -> SELECT player_id, player_name, SUM(dl_index) AS total_goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 GROUP BY player_id, player_name ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:04 -> SELECT player_id, player_name, SUM(dl_index) AS total_goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 GROUP BY player_id, player_name ORDER BY total_goals DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT match_id FROM public.t_goal WHERE player_id = 259935 AND season_id = 816529

06-21 16:20:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:04 -> SELECT match_id FROM public.t_goal WHERE player_id = 259935 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:04 -> SELECT match_id FROM public.t_goal WHERE player_id = 259935 AND season_id = 816529
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...d FROM public.t_goal WHERE player_id = 259935 AND season_id ...
                                                             ^

Failed query
Running query: SELECT match_id FROM public.vt_game_metric_player WHERE player_id = 259935 AND season_id = 816529 AND goals_xg_0 > 0

06-21 16:20:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:04 -> SELECT match_id FROM public.vt_game_metric_player WHERE player_id = 259935 AND season_id = 816529 AND goals_xg_0 > 0
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:04 -> SELECT match_id FROM public.vt_game_metric_player WHERE player_id = 259935 AND season_id = 816529 AND goals_xg_0 > 0

Successful query
Data Shape: (4, 1)
Running query: SELECT match_id, goals, match_date FROM public.vt_game_stat_player WHERE player_id = 259935 AND season_id = 816529 AND goals > 0

06-21 16:20:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:05 -> SELECT match_id, goals, match_date FROM public.vt_game_stat_player WHERE player_id = 259935 AND season_id = 816529 AND goals > 0
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:05 -> SELECT match_id, goals, match_date FROM public.vt_game_stat_player WHERE player_id = 259935 AND season_id = 816529 AND goals > 0

Successful query
Data Shape: (7, 3)
Running query: SELECT player_id, team_id, season_id, season_year, player_name, MAX(goals_scored) AS most_goals_scored FROM vm_agg_season_player_all WHERE season_id = 816527 AND team_id IN (4265, 4279) GROUP BY player_id, team_id, season_id, season_year, player_name ORDER BY most_goals_scored DESC LIMIT 1

06-21 16:20:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:06 -> SELECT player_id, team_id, season_id, season_year, player_name, MAX(goals_scored) AS most_goals_scored FROM vm_agg_season_player_all WHERE season_id = 816527 AND team_id IN (4265, 4279) GROUP BY player_id, team_id, season_id, season_year, player_name ORDER BY most_goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:06 -> SELECT player_id, team_id, season_id, season_year, player_name, MAX(goals_scored) AS most_goals_scored FROM vm_agg_season_player_all WHERE season_id = 816527 AND team_id IN (4265, 4279) GROUP BY player_id, team_id, season_id, season_year, player_name ORDER BY most_goals_scored DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...name, MAX(goals_scored) AS most_goals_scored FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_name, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals_90 DESC LIMIT 1

06-21 16:20:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:06 -> SELECT player_name, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:06 -> SELECT player_name, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals_90 DESC LIMIT 1
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: SELECT player_name, goals_90 FROM vm_agg_season_player_simil...
                            ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND provider_id = 4279 ORDER BY score_pd DESC LIMIT 1

06-21 16:20:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:06 -> SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND provider_id = 4279 ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:06 -> SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND provider_id = 4279 ORDER BY score_pd DESC LIMIT 1

Successful query
Data Shape: (0, 1)
Running query: SELECT player_id, player_name, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY npg_90 DESC LIMIT 1

06-21 16:20:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:06 -> SELECT player_id, player_name, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY npg_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:06 -> SELECT player_id, player_name, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY npg_90 DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals = (SELECT MAX(goals) FROM vm_agg_season_player_opta WHERE season_id = 816527)

06-21 16:20:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:06 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals = (SELECT MAX(goals) FROM vm_agg_season_player_opta WHERE season_id = 816527)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:06 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals = (SELECT MAX(goals) FROM vm_agg_season_player_opta WHERE season_id = 816527)

Successful query
Data Shape: (2, 2)
Running query: SELECT team_games_played FROM vm_agg_season_player_all WHERE player_id = 1598188 AND team_id = 20076 AND season_id = 816527

06-21 16:20:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:06 -> SELECT team_games_played FROM vm_agg_season_player_all WHERE player_id = 1598188 AND team_id = 20076 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:06 -> SELECT team_games_played FROM vm_agg_season_player_all WHERE player_id = 1598188 AND team_id = 20076 AND season_id = 816527
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT team_games_played FROM vm_agg_season_player_all WHERE...
                                      ^

Failed query
Running query: SELECT games_played_65mins FROM public.agg_season_player_pd WHERE player_id = 1598188 AND team_id = 20076 AND season_id = 816527

06-21 16:20:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:06 -> SELECT games_played_65mins FROM public.agg_season_player_pd WHERE player_id = 1598188 AND team_id = 20076 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:06 -> SELECT games_played_65mins FROM public.agg_season_player_pd WHERE player_id = 1598188 AND team_id = 20076 AND season_id = 816527

Successful query
Data Shape: (4, 1)
Running query: SELECT COUNT(DISTINCT match_id) FROM public.vt_game_stat_player WHERE player_id = 1598188 AND season_id = 816527

06-21 16:20:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:06 -> SELECT COUNT(DISTINCT match_id) FROM public.vt_game_stat_player WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:06 -> SELECT COUNT(DISTINCT match_id) FROM public.vt_game_stat_player WHERE player_id = 1598188 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, player_name, max_speed, team_id, season_id FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_country_name IN ('Spain', 'England', 'Germany', 'Italy', 'France') ORDER BY max_speed DESC LIMIT 5

06-21 16:20:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:06 -> SELECT player_id, player_name, max_speed, team_id, season_id FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_country_name IN ('Spain', 'England', 'Germany', 'Italy', 'France') ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:06 -> SELECT player_id, player_name, max_speed, team_id, season_id FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_country_name IN ('Spain', 'England', 'Germany', 'Italy', 'France') ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 5)
Running query: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816529 OR season_id = 816528 OR season_id = 816527 OR season_id = 816531 OR season_id = 817311 ORDER BY max_speed DESC LIMIT 5

06-21 16:20:07 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:07 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816529 OR season_id = 816528 OR season_id = 816527 OR season_id = 816531 OR season_id = 817311 ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:07 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816529 OR season_id = 816528 OR season_id = 816527 OR season_id = 816531 OR season_id = 817311 ORDER BY max_speed DESC LIMIT 5
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_...
                                              ^

Failed query
Running query: SELECT player_id, team_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY max_speed DESC LIMIT 5)

06-21 16:20:07 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:07 -> SELECT player_id, team_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY max_speed DESC LIMIT 5)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:07 -> SELECT player_id, team_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY max_speed DESC LIMIT 5)

Successful query
Data Shape: (18, 3)
Running query: SELECT COUNT(*) FROM public.t_goal WHERE player_id = 259935 AND season_id = 816529

06-21 16:20:09 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:09 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 259935 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:09 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 259935 AND season_id = 816529
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...) FROM public.t_goal WHERE player_id = 259935 AND season_id ...
                                                             ^

Failed query
Running query: SELECT score_pd FROM public.agg_season_player_pd WHERE player_id = 259935 AND season_id = 816529

06-21 16:20:09 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:09 -> SELECT score_pd FROM public.agg_season_player_pd WHERE player_id = 259935 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:09 -> SELECT score_pd FROM public.agg_season_player_pd WHERE player_id = 259935 AND season_id = 816529

Successful query
Data Shape: (3, 1)
Running query: SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 259935 AND season_id = 816529

06-21 16:20:09 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:09 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 259935 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:09 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 259935 AND season_id = 816529

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, global_score FROM vm_det_player_placer WHERE team_id = 4265 AND season_id = 816527 ORDER BY global_score DESC LIMIT 1

06-21 16:20:09 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:09 -> SELECT player_id, global_score FROM vm_det_player_placer WHERE team_id = 4265 AND season_id = 816527 ORDER BY global_score DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:09 -> SELECT player_id, global_score FROM vm_det_player_placer WHERE team_id = 4265 AND season_id = 816527 ORDER BY global_score DESC LIMIT 1
ERROR:root:Database error: relation "vm_det_player_placer" does not exist
LINE 1: SELECT player_id, global_score FROM vm_det_player_placer WHE...
                                            ^

Failed query
Running query: SELECT player_id, player_market_value, player_position_id FROM vm_fac_transfer WHERE team_to_id = 4265 AND transfer_year = 2023 ORDER BY player_market_value DESC LIMIT 1

06-21 16:20:09 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:09 -> SELECT player_id, player_market_value, player_position_id FROM vm_fac_transfer WHERE team_to_id = 4265 AND transfer_year = 2023 ORDER BY player_market_value DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:09 -> SELECT player_id, player_market_value, player_position_id FROM vm_fac_transfer WHERE team_to_id = 4265 AND transfer_year = 2023 ORDER BY player_market_value DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, position, height, age, score_this_year, mins_played_this_year FROM vm_agg_year_player_loan WHERE player_team_id <> 4265 AND current_season_id = 816527 ORDER BY score_this_year DESC LIMIT 1

06-21 16:20:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:11 -> SELECT player_id, player_name, position, height, age, score_this_year, mins_played_this_year FROM vm_agg_year_player_loan WHERE player_team_id <> 4265 AND current_season_id = 816527 ORDER BY score_this_year DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:11 -> SELECT player_id, player_name, position, height, age, score_this_year, mins_played_this_year FROM vm_agg_year_player_loan WHERE player_team_id <> 4265 AND current_season_id = 816527 ORDER BY score_this_year DESC LIMIT 1

Successful query
Data Shape: (1, 7)
Running query: SELECT player_id, team_id, season_id FROM public.agg_season_player_pd WHERE team_id = 4265 AND season_id = 816527 ORDER BY score_pd DESC LIMIT 5

06-21 16:20:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:11 -> SELECT player_id, team_id, season_id FROM public.agg_season_player_pd WHERE team_id = 4265 AND season_id = 816527 ORDER BY score_pd DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:11 -> SELECT player_id, team_id, season_id FROM public.agg_season_player_pd WHERE team_id = 4265 AND season_id = 816527 ORDER BY score_pd DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, goals FROM vm_agg_season_player_opta WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals DESC LIMIT 5

06-21 16:20:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:11 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:11 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE team_id = 4265 AND season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 5

06-21 16:20:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:11 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE team_id = 4265 AND season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:11 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE team_id = 4265 AND season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 5
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...cored FROM public.t_goal WHERE team_id = 4265 AND season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816529 OR season_id = 816528 OR season_id = 816527 OR season_id = 816531 OR season_id = 817309 ORDER BY max_speed DESC LIMIT 5

06-21 16:20:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:12 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816529 OR season_id = 816528 OR season_id = 816527 OR season_id = 816531 OR season_id = 817309 ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:12 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816529 OR season_id = 816528 OR season_id = 816527 OR season_id = 816531 OR season_id = 817309 ORDER BY max_speed DESC LIMIT 5
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_...
                                              ^

Failed query
Running query: SELECT player_id, player_name, max_speed, team_id, season_id FROM vm_agg_season_player_info WHERE season_id = 816527 AND country_id IN (1, 2, 3, 4, 5) ORDER BY max_speed DESC LIMIT 5

06-21 16:20:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:12 -> SELECT player_id, player_name, max_speed, team_id, season_id FROM vm_agg_season_player_info WHERE season_id = 816527 AND country_id IN (1, 2, 3, 4, 5) ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:12 -> SELECT player_id, player_name, max_speed, team_id, season_id FROM vm_agg_season_player_info WHERE season_id = 816527 AND country_id IN (1, 2, 3, 4, 5) ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 5)
Running query: SELECT player_id, team_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816529 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 2)) ORDER BY max_speed DESC LIMIT 5

06-21 16:20:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:12 -> SELECT player_id, team_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816529 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 2)) ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:12 -> SELECT player_id, team_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816529 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 2)) ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT * FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527 AND provider_id = 1

06-21 16:20:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:12 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527 AND provider_id = 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:12 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527 AND provider_id = 1

Successful query
Data Shape: (0, 57)
Running query: SELECT COUNT(*) FROM public.t_goal WHERE player_id = 1163220 AND match_id IN (SELECT match_id FROM public.t_match WHERE season_id = 816527)

06-21 16:20:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:12 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 1163220 AND match_id IN (SELECT match_id FROM public.t_match WHERE season_id = 816527)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:12 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 1163220 AND match_id IN (SELECT match_id FROM public.t_match WHERE season_id = 816527)

Successful query
Data Shape: (1, 1)
Running query: SELECT * FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816709

06-21 16:20:13 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:13 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816709
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:13 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816709

Successful query
Data Shape: (0, 57)
Running query: SELECT COUNT(*) FROM public.t_goal WHERE player_id = 1163220 AND match_id IN (SELECT match_id FROM public.t_match WHERE season_id = 816709)

06-21 16:20:13 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:13 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 1163220 AND match_id IN (SELECT match_id FROM public.t_match WHERE season_id = 816709)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:13 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 1163220 AND match_id IN (SELECT match_id FROM public.t_match WHERE season_id = 816709)

Successful query
Data Shape: (1, 1)
Running query: SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816709

06-21 16:20:13 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:13 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816709
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:13 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816709

Successful query
Data Shape: (1, 1)
Running query: SELECT COUNT(*) FROM public.t_goal WHERE player_id = 1163220 AND team_id = 4265 AND season_id = 816527

06-21 16:20:13 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:13 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 1163220 AND team_id = 4265 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:13 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 1163220 AND team_id = 4265 AND season_id = 816527
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ... WHERE player_id = 1163220 AND team_id = 4265 AND season_id ...
                                                             ^

Failed query
Running query: SELECT * FROM public.agg_season_player_pd WHERE player_id = 1163220 AND team_id = 4265 AND season_id = 816527

06-21 16:20:13 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:13 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 1163220 AND team_id = 4265 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:13 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 1163220 AND team_id = 4265 AND season_id = 816527

Successful query
Data Shape: (4, 57)
Running query: SELECT goals FROM vm_agg_season_player_opta WHERE player_name = 'Joselu' AND team_name = 'Real Madrid' AND season_id = 816527

06-21 16:20:13 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:13 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_name = 'Joselu' AND team_name = 'Real Madrid' AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:13 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_name = 'Joselu' AND team_name = 'Real Madrid' AND season_id = 816527

Successful query
Data Shape: (0, 1)
Running query: SELECT player_id, player_name, max_speed FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name IN ('ESP I', 'ENG I', 'GER I', 'ITA I', 'FRA I') ORDER BY max_speed DESC LIMIT 5

06-21 16:20:15 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:15 -> SELECT player_id, player_name, max_speed FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name IN ('ESP I', 'ENG I', 'GER I', 'ITA I', 'FRA I') ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:15 -> SELECT player_id, player_name, max_speed FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name IN ('ESP I', 'ENG I', 'GER I', 'ITA I', 'FRA I') ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (0, 3)
Running query: SELECT player_id, team_id, season_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816529 AND team_id IN (SELECT team_id FROM public.agg_season_player_pd WHERE season_id = 816529 AND provider_id = 2) ORDER BY max_speed DESC LIMIT 5

06-21 16:20:15 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:15 -> SELECT player_id, team_id, season_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816529 AND team_id IN (SELECT team_id FROM public.agg_season_player_pd WHERE season_id = 816529 AND provider_id = 2) ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:15 -> SELECT player_id, team_id, season_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816529 AND team_id IN (SELECT team_id FROM public.agg_season_player_pd WHERE season_id = 816529 AND provider_id = 2) ORDER BY max_speed DESC LIMIT 5
ERROR:root:Database error: syntax error at end of input
LINE 1: ... 816529 AND provider_id = 2) ORDER BY max_speed DESC LIMIT 5
                                                                       ^

Failed query
Running query: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816529 AND country_id = 2 ORDER BY max_speed DESC LIMIT 5

06-21 16:20:15 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:15 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816529 AND country_id = 2 ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:15 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816529 AND country_id = 2 ORDER BY max_speed DESC LIMIT 5
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_...
                                              ^

Failed query
Running query: SELECT player_id, SUM(shots_total) AS total_shots FROM public.vt_season_stat_player WHERE season_id = 816527 AND player_id NOT IN (60, 61,62,63,64,65,66) GROUP BY player_id ORDER BY total_shots DESC

06-21 16:20:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:16 -> SELECT player_id, SUM(shots_total) AS total_shots FROM public.vt_season_stat_player WHERE season_id = 816527 AND player_id NOT IN (60, 61,62,63,64,65,66) GROUP BY player_id ORDER BY total_shots DESC
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:16 -> SELECT player_id, SUM(shots_total) AS total_shots FROM public.vt_season_stat_player WHERE season_id = 816527 AND player_id NOT IN (60, 61,62,63,64,65,66) GROUP BY player_id ORDER BY total_shots DESC

Successful query
Data Shape: (20, 2)
Running query: SELECT player_id, team_id, xa FROM public.vt_season_metric_player WHERE team_id = 4279 ORDER BY xa DESC LIMIT 5

06-21 16:20:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:16 -> SELECT player_id, team_id, xa FROM public.vt_season_metric_player WHERE team_id = 4279 ORDER BY xa DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:16 -> SELECT player_id, team_id, xa FROM public.vt_season_metric_player WHERE team_id = 4279 ORDER BY xa DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, team_id, xa FROM public.vt_season_info_player WHERE team_id = 4279 ORDER BY xa DESC LIMIT 5

06-21 16:20:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:16 -> SELECT player_id, team_id, xa FROM public.vt_season_info_player WHERE team_id = 4279 ORDER BY xa DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:16 -> SELECT player_id, team_id, xa FROM public.vt_season_info_player WHERE team_id = 4279 ORDER BY xa DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, team_id, xa FROM public.vt_season_stat_player WHERE team_id = 4279 ORDER BY xa DESC LIMIT 5

06-21 16:20:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:16 -> SELECT player_id, team_id, xa FROM public.vt_season_stat_player WHERE team_id = 4279 ORDER BY xa DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:16 -> SELECT player_id, team_id, xa FROM public.vt_season_stat_player WHERE team_id = 4279 ORDER BY xa DESC LIMIT 5
ERROR:root:Database error: column "xa" does not exist
LINE 1: SELECT player_id, team_id, xa FROM public.vt_season_stat_pla...
                                   ^
HINT:  Perhaps you meant to reference the column "vt_season_stat_player.xp".

Failed query
Running query: SELECT player_id, goals FROM public.vt_season_info_player WHERE season_id = 816530 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

06-21 16:20:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:16 -> SELECT player_id, goals FROM public.vt_season_info_player WHERE season_id = 816530 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:16 -> SELECT player_id, goals FROM public.vt_season_info_player WHERE season_id = 816530 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, non_penalty_goals FROM public.vt_season_info_player WHERE season_id = 816530 AND non_penalty_goals IS NOT NULL ORDER BY non_penalty_goals DESC LIMIT 1

06-21 16:20:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:17 -> SELECT player_id, non_penalty_goals FROM public.vt_season_info_player WHERE season_id = 816530 AND non_penalty_goals IS NOT NULL ORDER BY non_penalty_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:17 -> SELECT player_id, non_penalty_goals FROM public.vt_season_info_player WHERE season_id = 816530 AND non_penalty_goals IS NOT NULL ORDER BY non_penalty_goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, team_id, xa FROM public.vt_season_metric_player WHERE team_id = 66883 ORDER BY xa DESC LIMIT 1

06-21 16:20:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:17 -> SELECT player_id, team_id, xa FROM public.vt_season_metric_player WHERE team_id = 66883 ORDER BY xa DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:17 -> SELECT player_id, team_id, xa FROM public.vt_season_metric_player WHERE team_id = 66883 ORDER BY xa DESC LIMIT 1

Successful query
Data Shape: (0, 3)
Running query: SELECT player_id, team_id, xa FROM public.vt_season_info_player WHERE team_id = 66883 ORDER BY xa DESC LIMIT 1

06-21 16:20:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:17 -> SELECT player_id, team_id, xa FROM public.vt_season_info_player WHERE team_id = 66883 ORDER BY xa DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:17 -> SELECT player_id, team_id, xa FROM public.vt_season_info_player WHERE team_id = 66883 ORDER BY xa DESC LIMIT 1

Successful query
Data Shape: (0, 3)
Running query: SELECT player_id, team_id, xa FROM public.vt_season_stat_player WHERE team_id = 66883 ORDER BY xa DESC LIMIT 1

06-21 16:20:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:17 -> SELECT player_id, team_id, xa FROM public.vt_season_stat_player WHERE team_id = 66883 ORDER BY xa DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:17 -> SELECT player_id, team_id, xa FROM public.vt_season_stat_player WHERE team_id = 66883 ORDER BY xa DESC LIMIT 1
ERROR:root:Database error: column "xa" does not exist
LINE 1: SELECT player_id, team_id, xa FROM public.vt_season_stat_pla...
                                   ^
HINT:  Perhaps you meant to reference the column "vt_season_stat_player.xp".

Failed query
Running query: SELECT match_id, xg FROM public.vt_game_metric_team WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg DESC LIMIT 1

06-21 16:20:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:17 -> SELECT match_id, xg FROM public.vt_game_metric_team WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:17 -> SELECT match_id, xg FROM public.vt_game_metric_team WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT match_id, goals_scored, goals_against FROM public.vm_game_stat_team WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals_scored DESC LIMIT 1

06-21 16:20:18 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:18 -> SELECT match_id, goals_scored, goals_against FROM public.vm_game_stat_team WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:18 -> SELECT match_id, goals_scored, goals_against FROM public.vm_game_stat_team WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals_scored DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT team_id, avg_win_chance FROM public.agg_season_team_info WHERE season_id = 816527 ORDER BY avg_win_chance DESC LIMIT 1

06-21 16:20:18 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:18 -> SELECT team_id, avg_win_chance FROM public.agg_season_team_info WHERE season_id = 816527 ORDER BY avg_win_chance DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:18 -> SELECT team_id, avg_win_chance FROM public.agg_season_team_info WHERE season_id = 816527 ORDER BY avg_win_chance DESC LIMIT 1
ERROR:root:Database error: column "avg_win_chance" does not exist
LINE 1: SELECT team_id, avg_win_chance FROM public.agg_season_team_i...
                        ^

Failed query
Running query: SELECT team_id, season_id, points FROM public.t_season_team_rank WHERE season_id = 816527 ORDER BY points DESC LIMIT 1

06-21 16:20:18 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:18 -> SELECT team_id, season_id, points FROM public.t_season_team_rank WHERE season_id = 816527 ORDER BY points DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:18 -> SELECT team_id, season_id, points FROM public.t_season_team_rank WHERE season_id = 816527 ORDER BY points DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT team_id, season_id, points FROM public.t_season_team_rank WHERE season_id = 816527 AND points IS NOT NULL ORDER BY points DESC LIMIT 1

06-21 16:20:18 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:18 -> SELECT team_id, season_id, points FROM public.t_season_team_rank WHERE season_id = 816527 AND points IS NOT NULL ORDER BY points DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:18 -> SELECT team_id, season_id, points FROM public.t_season_team_rank WHERE season_id = 816527 AND points IS NOT NULL ORDER BY points DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, team_id, season_id, tackles_total FROM public.vt_season_stat_player WHERE season_id = 816527 AND tackles_total IS NOT NULL ORDER BY tackles_total DESC LIMIT 10

06-21 16:20:18 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:18 -> SELECT player_id, team_id, season_id, tackles_total FROM public.vt_season_stat_player WHERE season_id = 816527 AND tackles_total IS NOT NULL ORDER BY tackles_total DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:18 -> SELECT player_id, team_id, season_id, tackles_total FROM public.vt_season_stat_player WHERE season_id = 816527 AND tackles_total IS NOT NULL ORDER BY tackles_total DESC LIMIT 10

Successful query
Data Shape: (10, 4)
Running query: SELECT player_id, team_id, season_id, tackles_total FROM public.vt_season_metric_player WHERE season_id = 816527 AND tackles_total IS NOT NULL ORDER BY tackles_total DESC LIMIT 10

06-21 16:20:18 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:18 -> SELECT player_id, team_id, season_id, tackles_total FROM public.vt_season_metric_player WHERE season_id = 816527 AND tackles_total IS NOT NULL ORDER BY tackles_total DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:18 -> SELECT player_id, team_id, season_id, tackles_total FROM public.vt_season_metric_player WHERE season_id = 816527 AND tackles_total IS NOT NULL ORDER BY tackles_total DESC LIMIT 10
ERROR:root:Database error: column "tackles_total" does not exist
LINE 1: SELECT player_id, team_id, season_id, tackles_total FROM pub...
                                              ^

Failed query
Running query: SELECT match_id, goals_scored, possession FROM public.vm_game_stat_team WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals_scored DESC LIMIT 1

06-21 16:20:18 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:18 -> SELECT match_id, goals_scored, possession FROM public.vm_game_stat_team WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:18 -> SELECT match_id, goals_scored, possession FROM public.vm_game_stat_team WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals_scored DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT match_id, goals_scored, possession FROM public.vm_game_stat_team WHERE team_id = 4265 AND season_id = 816527 AND possession IS NOT NULL ORDER BY possession DESC LIMIT 1

06-21 16:20:20 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:20 -> SELECT match_id, goals_scored, possession FROM public.vm_game_stat_team WHERE team_id = 4265 AND season_id = 816527 AND possession IS NOT NULL ORDER BY possession DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:20 -> SELECT match_id, goals_scored, possession FROM public.vm_game_stat_team WHERE team_id = 4265 AND season_id = 816527 AND possession IS NOT NULL ORDER BY possession DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT team_id, season_id, xa FROM public.vt_season_metric_team WHERE season_id = 816527 ORDER BY xa DESC LIMIT 1

06-21 16:20:20 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:20 -> SELECT team_id, season_id, xa FROM public.vt_season_metric_team WHERE season_id = 816527 ORDER BY xa DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:20 -> SELECT team_id, season_id, xa FROM public.vt_season_metric_team WHERE season_id = 816527 ORDER BY xa DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT team_id, season_id, xa FROM public.vt_season_info_team WHERE season_id = 816527 ORDER BY xa DESC LIMIT 1

06-21 16:20:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:21 -> SELECT team_id, season_id, xa FROM public.vt_season_info_team WHERE season_id = 816527 ORDER BY xa DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:21 -> SELECT team_id, season_id, xa FROM public.vt_season_info_team WHERE season_id = 816527 ORDER BY xa DESC LIMIT 1
ERROR:root:Database error: relation "public.vt_season_info_team" does not exist
LINE 1: SELECT team_id, season_id, xa FROM public.vt_season_info_tea...
                                           ^

Failed query
Running query: SELECT team_id, season_id, xa FROM public.agg_season_team_info WHERE season_id = 816527 ORDER BY xa DESC LIMIT 1

06-21 16:20:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:21 -> SELECT team_id, season_id, xa FROM public.agg_season_team_info WHERE season_id = 816527 ORDER BY xa DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:21 -> SELECT team_id, season_id, xa FROM public.agg_season_team_info WHERE season_id = 816527 ORDER BY xa DESC LIMIT 1
ERROR:root:Database error: column "xa" does not exist
LINE 1: SELECT team_id, season_id, xa FROM public.agg_season_team_in...
                                   ^

Failed query
Running query: SELECT player_id, team_id, season_id, tackles_total FROM public.vt_season_stat_player WHERE season_id = 816529 AND tackles_total IS NOT NULL ORDER BY tackles_total DESC LIMIT 10

06-21 16:20:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:21 -> SELECT player_id, team_id, season_id, tackles_total FROM public.vt_season_stat_player WHERE season_id = 816529 AND tackles_total IS NOT NULL ORDER BY tackles_total DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:21 -> SELECT player_id, team_id, season_id, tackles_total FROM public.vt_season_stat_player WHERE season_id = 816529 AND tackles_total IS NOT NULL ORDER BY tackles_total DESC LIMIT 10

Successful query
Data Shape: (10, 4)
Running query: SELECT player_id, SUM(shots_on_target) AS total_shots_on_target FROM public.vt_season_stat_player WHERE season_id = 816527 AND player_id NOT IN (60, 61,62,63,64,65,66) GROUP BY player_id ORDER BY total_shots_on_target DESC LIMIT 10

06-21 16:20:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:21 -> SELECT player_id, SUM(shots_on_target) AS total_shots_on_target FROM public.vt_season_stat_player WHERE season_id = 816527 AND player_id NOT IN (60, 61,62,63,64,65,66) GROUP BY player_id ORDER BY total_shots_on_target DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:21 -> SELECT player_id, SUM(shots_on_target) AS total_shots_on_target FROM public.vt_season_stat_player WHERE season_id = 816527 AND player_id NOT IN (60, 61,62,63,64,65,66) GROUP BY player_id ORDER BY total_shots_on_target DESC LIMIT 10

Successful query
Data Shape: (10, 2)
Running query: SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816530 ORDER BY points DESC LIMIT 5

06-21 16:20:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:21 -> SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816530 ORDER BY points DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:21 -> SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816530 ORDER BY points DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT team_id, wins, draws, loses, goals, goals_against, diff_goals, points FROM public.t_season_team_rank WHERE season_id = 816530 ORDER BY points DESC LIMIT 5

06-21 16:20:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:21 -> SELECT team_id, wins, draws, loses, goals, goals_against, diff_goals, points FROM public.t_season_team_rank WHERE season_id = 816530 ORDER BY points DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:21 -> SELECT team_id, wins, draws, loses, goals, goals_against, diff_goals, points FROM public.t_season_team_rank WHERE season_id = 816530 ORDER BY points DESC LIMIT 5

Successful query
Data Shape: (5, 8)
Running query: SELECT team_id, goals_against FROM public.t_season_team_rank WHERE season_id = 816528 AND team_id NOT IN (21,22,23,24,25,66,97,98,99) ORDER BY goals_against DESC LIMIT 5

06-21 16:20:22 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:22 -> SELECT team_id, goals_against FROM public.t_season_team_rank WHERE season_id = 816528 AND team_id NOT IN (21,22,23,24,25,66,97,98,99) ORDER BY goals_against DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:22 -> SELECT team_id, goals_against FROM public.t_season_team_rank WHERE season_id = 816528 AND team_id NOT IN (21,22,23,24,25,66,97,98,99) ORDER BY goals_against DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT team_id, SUM(expected_goals) AS total_expected_goals FROM t_match WHERE team_id NOT IN (21,22,23,24,25, 66, 97, 98, 99) AND season_id = 816527 GROUP BY team_id ORDER BY total_expected_goals DESC LIMIT 10

06-21 16:20:22 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:22 -> SELECT team_id, SUM(expected_goals) AS total_expected_goals FROM t_match WHERE team_id NOT IN (21,22,23,24,25, 66, 97, 98, 99) AND season_id = 816527 GROUP BY team_id ORDER BY total_expected_goals DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:22 -> SELECT team_id, SUM(expected_goals) AS total_expected_goals FROM t_match WHERE team_id NOT IN (21,22,23,24,25, 66, 97, 98, 99) AND season_id = 816527 GROUP BY team_id ORDER BY total_expected_goals DESC LIMIT 10
ERROR:root:Database error: column "team_id" does not exist
LINE 1: SELECT team_id, SUM(expected_goals) AS total_expected_goals ...
               ^
HINT:  Perhaps you meant to reference the column "t_match.tm_id".

Failed query
Running query: SELECT player_id, team_id, season_id, goals FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5

06-21 16:20:22 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:22 -> SELECT player_id, team_id, season_id, goals FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:22 -> SELECT player_id, team_id, season_id, goals FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, team_id, season_id, goals FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5

06-21 16:20:22 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:22 -> SELECT player_id, team_id, season_id, goals FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:22 -> SELECT player_id, team_id, season_id, goals FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5
ERROR:root:Database error: column "goals" does not exist
LINE 1: SELECT player_id, team_id, season_id, goals FROM public.vt_s...
                                              ^

Failed query
Running query: SELECT player_id, team_id, season_id, dribbles_total FROM public.vt_season_stat_player WHERE season_id = 816527 AND player_id NOT IN (60, 61,62,63,64,65,66) ORDER BY dribbles_total DESC LIMIT 10

06-21 16:20:22 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:22 -> SELECT player_id, team_id, season_id, dribbles_total FROM public.vt_season_stat_player WHERE season_id = 816527 AND player_id NOT IN (60, 61,62,63,64,65,66) ORDER BY dribbles_total DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:22 -> SELECT player_id, team_id, season_id, dribbles_total FROM public.vt_season_stat_player WHERE season_id = 816527 AND player_id NOT IN (60, 61,62,63,64,65,66) ORDER BY dribbles_total DESC LIMIT 10

Successful query
Data Shape: (10, 4)
Running query: SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816527 AND league_position_id = 2

06-21 16:20:22 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:22 -> SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816527 AND league_position_id = 2
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:22 -> SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816527 AND league_position_id = 2

Successful query
Data Shape: (0, 2)
Running query: SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816527 AND ranking = 2

06-21 16:20:22 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:22 -> SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816527 AND ranking = 2
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:22 -> SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816527 AND ranking = 2

Successful query
Data Shape: (1, 2)
Running query: SELECT first_name, last_name, position, age, nationality_confirmed, market_value FROM public.t_player WHERE player_id = 1296920 AND team_id = 4265

06-21 16:20:22 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:22 -> SELECT first_name, last_name, position, age, nationality_confirmed, market_value FROM public.t_player WHERE player_id = 1296920 AND team_id = 4265
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:22 -> SELECT first_name, last_name, position, age, nationality_confirmed, market_value FROM public.t_player WHERE player_id = 1296920 AND team_id = 4265

Successful query
Data Shape: (1, 6)
Running query: SELECT player_name, team_name, season_name, mins_played, goals, assists FROM public.v_player_sc WHERE player_id = 1296920 AND team_id = 4265 AND season_name = 'ESP I 2023'

06-21 16:20:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:23 -> SELECT player_name, team_name, season_name, mins_played, goals, assists FROM public.v_player_sc WHERE player_id = 1296920 AND team_id = 4265 AND season_name = 'ESP I 2023'
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:23 -> SELECT player_name, team_name, season_name, mins_played, goals, assists FROM public.v_player_sc WHERE player_id = 1296920 AND team_id = 4265 AND season_name = 'ESP I 2023'
ERROR:root:Database error: column "goals" does not exist
LINE 1: ...player_name, team_name, season_name, mins_played, goals, ass...
                                                             ^

Failed query
Running query: SELECT player_id, team_id, season_id, tackles_total FROM public.vt_season_stat_player WHERE season_id = 816527 AND tackles_total IS NOT NULL ORDER BY tackles_total DESC LIMIT 1

06-21 16:20:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:23 -> SELECT player_id, team_id, season_id, tackles_total FROM public.vt_season_stat_player WHERE season_id = 816527 AND tackles_total IS NOT NULL ORDER BY tackles_total DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:23 -> SELECT player_id, team_id, season_id, tackles_total FROM public.vt_season_stat_player WHERE season_id = 816527 AND tackles_total IS NOT NULL ORDER BY tackles_total DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT team_id, win_chance FROM public.vt_season_metric_team WHERE season_id = 816527 ORDER BY win_chance DESC LIMIT 1

06-21 16:20:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:23 -> SELECT team_id, win_chance FROM public.vt_season_metric_team WHERE season_id = 816527 ORDER BY win_chance DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:23 -> SELECT team_id, win_chance FROM public.vt_season_metric_team WHERE season_id = 816527 ORDER BY win_chance DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT team_id, SUM(expected_goals) AS total_expected_goals FROM t_match WHERE team_id NOT IN (21,22,23,24,25, 66, 97, 98, 99) GROUP BY team_id ORDER BY total_expected_goals DESC LIMIT 10

06-21 16:20:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:23 -> SELECT team_id, SUM(expected_goals) AS total_expected_goals FROM t_match WHERE team_id NOT IN (21,22,23,24,25, 66, 97, 98, 99) GROUP BY team_id ORDER BY total_expected_goals DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:23 -> SELECT team_id, SUM(expected_goals) AS total_expected_goals FROM t_match WHERE team_id NOT IN (21,22,23,24,25, 66, 97, 98, 99) GROUP BY team_id ORDER BY total_expected_goals DESC LIMIT 10
ERROR:root:Database error: column "team_id" does not exist
LINE 1: SELECT team_id, SUM(expected_goals) AS total_expected_goals ...
               ^
HINT:  Perhaps you meant to reference the column "t_match.tm_id".

Failed query
Running query: SELECT player_id, xg FROM public.vt_game_metric_player WHERE match_id = 550143 ORDER BY xg DESC LIMIT 1

06-21 16:20:25 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:25 -> SELECT player_id, xg FROM public.vt_game_metric_player WHERE match_id = 550143 ORDER BY xg DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:25 -> SELECT player_id, xg FROM public.vt_game_metric_player WHERE match_id = 550143 ORDER BY xg DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, team_id, player_name, team_name, season_name, mins_played, country_code, elo FROM public.v_player_sc WHERE player_id = 1340410 AND team_id = 20076 AND season_name = 'ESP I 2023' AND player_id NOT IN (60, 61,62,63,64,65,66)

06-21 16:20:25 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:25 -> SELECT player_id, team_id, player_name, team_name, season_name, mins_played, country_code, elo FROM public.v_player_sc WHERE player_id = 1340410 AND team_id = 20076 AND season_name = 'ESP I 2023' AND player_id NOT IN (60, 61,62,63,64,65,66)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:25 -> SELECT player_id, team_id, player_name, team_name, season_name, mins_played, country_code, elo FROM public.v_player_sc WHERE player_id = 1340410 AND team_id = 20076 AND season_name = 'ESP I 2023' AND player_id NOT IN (60, 61,62,63,64,65,66)

Successful query
Data Shape: (0, 8)
Running query: SELECT max_speed FROM public.agg_game_player_pd WHERE player_id = 349 AND team_id = 4265 AND season_id = 816527 AND max_speed IS NOT NULL

06-21 16:20:25 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:25 -> SELECT max_speed FROM public.agg_game_player_pd WHERE player_id = 349 AND team_id = 4265 AND season_id = 816527 AND max_speed IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:25 -> SELECT max_speed FROM public.agg_game_player_pd WHERE player_id = 349 AND team_id = 4265 AND season_id = 816527 AND max_speed IS NOT NULL

Successful query
Data Shape: (20, 1)
Running query: SELECT max_speed FROM public.agg_game_player_pd WHERE player_id = 349 AND team_id = 4265 AND season_id = 816690 AND max_speed IS NOT NULL

06-21 16:20:25 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:25 -> SELECT max_speed FROM public.agg_game_player_pd WHERE player_id = 349 AND team_id = 4265 AND season_id = 816690 AND max_speed IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:25 -> SELECT max_speed FROM public.agg_game_player_pd WHERE player_id = 349 AND team_id = 4265 AND season_id = 816690 AND max_speed IS NOT NULL

Successful query
Data Shape: (0, 1)
Running query: SELECT COUNT(DISTINCT match_id) FROM public.vt_game_metric_player WHERE player_id = 349 AND team_id = 4265 AND season_id = 816527 AND xg = 1.46511167

06-21 16:20:26 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:26 -> SELECT COUNT(DISTINCT match_id) FROM public.vt_game_metric_player WHERE player_id = 349 AND team_id = 4265 AND season_id = 816527 AND xg = 1.46511167
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:26 -> SELECT COUNT(DISTINCT match_id) FROM public.vt_game_metric_player WHERE player_id = 349 AND team_id = 4265 AND season_id = 816527 AND xg = 1.46511167

Successful query
Data Shape: (1, 1)
Running query: SELECT COUNT(DISTINCT match_id) FROM public.vt_game_metric_player WHERE player_id = 349 AND team_id = 4265 AND season_id = 816690 AND xg = 0.85969759

06-21 16:20:26 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:26 -> SELECT COUNT(DISTINCT match_id) FROM public.vt_game_metric_player WHERE player_id = 349 AND team_id = 4265 AND season_id = 816690 AND xg = 0.85969759
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:26 -> SELECT COUNT(DISTINCT match_id) FROM public.vt_game_metric_player WHERE player_id = 349 AND team_id = 4265 AND season_id = 816690 AND xg = 0.85969759

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, team_id, season_id, passes_no_filtered_total FROM public.vt_game_stat_player WHERE team_id = 4265 AND season_id = 816527 AND player_id NOT IN (60, 61,62,63,64,65,66) ORDER BY passes_no_filtered_total DESC LIMIT 5

06-21 16:20:26 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:26 -> SELECT player_id, team_id, season_id, passes_no_filtered_total FROM public.vt_game_stat_player WHERE team_id = 4265 AND season_id = 816527 AND player_id NOT IN (60, 61,62,63,64,65,66) ORDER BY passes_no_filtered_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:26 -> SELECT player_id, team_id, season_id, passes_no_filtered_total FROM public.vt_game_stat_player WHERE team_id = 4265 AND season_id = 816527 AND player_id NOT IN (60, 61,62,63,64,65,66) ORDER BY passes_no_filtered_total DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, SUM(goals) AS total_goals FROM public.agg_competition_player WHERE competition_id = 816527 AND team_id IN (SELECT team_id FROM public.t_team WHERE country_id = (SELECT country_id FROM public.t_country WHERE name = 'Spain')) GROUP BY player_id ORDER BY total_goals DESC LIMIT 1

06-21 16:20:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:29 -> SELECT player_id, SUM(goals) AS total_goals FROM public.agg_competition_player WHERE competition_id = 816527 AND team_id IN (SELECT team_id FROM public.t_team WHERE country_id = (SELECT country_id FROM public.t_country WHERE name = 'Spain')) GROUP BY player_id ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:29 -> SELECT player_id, SUM(goals) AS total_goals FROM public.agg_competition_player WHERE competition_id = 816527 AND team_id IN (SELECT team_id FROM public.t_team WHERE country_id = (SELECT country_id FROM public.t_country WHERE name = 'Spain')) GROUP BY player_id ORDER BY total_goals DESC LIMIT 1

Successful query
Data Shape: (0, 2)
Running query: SELECT team_id, points FROM public.agg_competition_team_rank WHERE competition_id = 816529 ORDER BY points DESC LIMIT 5

06-21 16:20:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:29 -> SELECT team_id, points FROM public.agg_competition_team_rank WHERE competition_id = 816529 ORDER BY points DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:29 -> SELECT team_id, points FROM public.agg_competition_team_rank WHERE competition_id = 816529 ORDER BY points DESC LIMIT 5

Successful query
Data Shape: (0, 2)
Running query: SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816529 ORDER BY points DESC LIMIT 5

06-21 16:20:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:30 -> SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816529 ORDER BY points DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:30 -> SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816529 ORDER BY points DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT team_id, points FROM public.agg_season_team_info WHERE season_id = 816529 ORDER BY points DESC LIMIT 5

06-21 16:20:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:30 -> SELECT team_id, points FROM public.agg_season_team_info WHERE season_id = 816529 ORDER BY points DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:30 -> SELECT team_id, points FROM public.agg_season_team_info WHERE season_id = 816529 ORDER BY points DESC LIMIT 5
ERROR:root:Database error: column "points" does not exist
LINE 1: SELECT team_id, points FROM public.agg_season_team_info WHER...
                        ^

Failed query
Running query: SELECT team_id, points FROM public.agg_competition_team_rank WHERE competition_id = 816529 ORDER BY points DESC LIMIT 1

06-21 16:20:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:30 -> SELECT team_id, points FROM public.agg_competition_team_rank WHERE competition_id = 816529 ORDER BY points DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:30 -> SELECT team_id, points FROM public.agg_competition_team_rank WHERE competition_id = 816529 ORDER BY points DESC LIMIT 1

Successful query
Data Shape: (0, 2)
Running query: SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816529 ORDER BY points DESC LIMIT 1

06-21 16:20:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:30 -> SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816529 ORDER BY points DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:30 -> SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816529 ORDER BY points DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT team_id, points FROM public.agg_season_team_info WHERE season_id = 816529 ORDER BY points DESC LIMIT 1

06-21 16:20:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:30 -> SELECT team_id, points FROM public.agg_season_team_info WHERE season_id = 816529 ORDER BY points DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:30 -> SELECT team_id, points FROM public.agg_season_team_info WHERE season_id = 816529 ORDER BY points DESC LIMIT 1
ERROR:root:Database error: column "points" does not exist
LINE 1: SELECT team_id, points FROM public.agg_season_team_info WHER...
                        ^

Failed query
Running query: SELECT player_id, team_id, season_id, goals FROM public.vt_game_stat_player WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM public.t_team WHERE country_id = 189) AND player_id NOT IN (60, 61,62,63,64,65,66) ORDER BY goals DESC LIMIT 5

06-21 16:20:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:20:30 -> SELECT player_id, team_id, season_id, goals FROM public.vt_game_stat_player WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM public.t_team WHERE country_id = 189) AND player_id NOT IN (60, 61,62,63,64,65,66) ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:20:30 -> SELECT player_id, team_id, season_id, goals FROM public.vt_game_stat_player WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM public.t_team WHERE country_id = 189) AND player_id NOT IN (60, 61,62,63,64,65,66) ORDER BY goals DESC LIMIT 5

Successful query
Data Shape: (0, 4)
Running query: SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816527 ORDER BY points DESC LIMIT 1

06-21 16:23:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:04 -> SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816527 ORDER BY points DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:04 -> SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816527 ORDER BY points DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816527 AND points IS NOT NULL ORDER BY points DESC LIMIT 1

06-21 16:23:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:05 -> SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816527 AND points IS NOT NULL ORDER BY points DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:05 -> SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816527 AND points IS NOT NULL ORDER BY points DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816527 AND points > 0 ORDER BY points DESC LIMIT 1

06-21 16:23:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:05 -> SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816527 AND points > 0 ORDER BY points DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:05 -> SELECT team_id, points FROM public.t_season_team_rank WHERE season_id = 816527 AND points > 0 ORDER BY points DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, team_id, mins_played FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY mins_played DESC LIMIT 5

06-21 16:23:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:05 -> SELECT player_id, team_id, mins_played FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY mins_played DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:05 -> SELECT player_id, team_id, mins_played FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY mins_played DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, team_id, mins_played FROM public.v_player_sc WHERE season_name = 'ESP I 2023' ORDER BY mins_played DESC LIMIT 5

06-21 16:23:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:05 -> SELECT player_id, team_id, mins_played FROM public.v_player_sc WHERE season_name = 'ESP I 2023' ORDER BY mins_played DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:05 -> SELECT player_id, team_id, mins_played FROM public.v_player_sc WHERE season_name = 'ESP I 2023' ORDER BY mins_played DESC LIMIT 5

Successful query
Data Shape: (0, 3)
Running query: SELECT team_id, team_name, points, ranking FROM public.t_season_team_rank WHERE season_id = 816529 AND total_teams > 0 ORDER BY ranking ASC LIMIT 5

06-21 16:23:09 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:09 -> SELECT team_id, team_name, points, ranking FROM public.t_season_team_rank WHERE season_id = 816529 AND total_teams > 0 ORDER BY ranking ASC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:09 -> SELECT team_id, team_name, points, ranking FROM public.t_season_team_rank WHERE season_id = 816529 AND total_teams > 0 ORDER BY ranking ASC LIMIT 5
ERROR:root:Database error: column "team_name" does not exist
LINE 1: SELECT team_id, team_name, points, ranking FROM public.t_sea...
                        ^

Failed query
Running query: SELECT team_id, team_name, goals, goals_against, diff_goals, points FROM public.t_season_team_rank WHERE season_id = 816529 AND total_teams > 0 ORDER BY points DESC LIMIT 5

06-21 16:23:09 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:09 -> SELECT team_id, team_name, goals, goals_against, diff_goals, points FROM public.t_season_team_rank WHERE season_id = 816529 AND total_teams > 0 ORDER BY points DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:09 -> SELECT team_id, team_name, goals, goals_against, diff_goals, points FROM public.t_season_team_rank WHERE season_id = 816529 AND total_teams > 0 ORDER BY points DESC LIMIT 5
ERROR:root:Database error: column "team_name" does not exist
LINE 1: SELECT team_id, team_name, goals, goals_against, diff_goals,...
                        ^

Failed query
Running query: SELECT player_id, team_id, player_name, mins_played FROM public.v_player_sc WHERE season_name = 'ESP I 2023' ORDER BY mins_played DESC LIMIT 5

06-21 16:23:09 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:09 -> SELECT player_id, team_id, player_name, mins_played FROM public.v_player_sc WHERE season_name = 'ESP I 2023' ORDER BY mins_played DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:09 -> SELECT player_id, team_id, player_name, mins_played FROM public.v_player_sc WHERE season_name = 'ESP I 2023' ORDER BY mins_played DESC LIMIT 5

Successful query
Data Shape: (0, 4)
Running query: SELECT player_id, team_id, player_name, mins_played FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY mins_played DESC LIMIT 5

06-21 16:23:10 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:10 -> SELECT player_id, team_id, player_name, mins_played FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY mins_played DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:10 -> SELECT player_id, team_id, player_name, mins_played FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY mins_played DESC LIMIT 5
ERROR:root:Database error: column "player_name" does not exist
LINE 1: SELECT player_id, team_id, player_name, mins_played FROM pub...
                                   ^

Failed query
Running query: SELECT mins_played FROM public.vt_season_info_player WHERE player_id = 1296920 AND season_id = 816527

06-21 16:23:10 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:10 -> SELECT mins_played FROM public.vt_season_info_player WHERE player_id = 1296920 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:10 -> SELECT mins_played FROM public.vt_season_info_player WHERE player_id = 1296920 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, team_id, mins_played FROM public.v_player_sc WHERE season_name = 'ESP I 2023' ORDER BY mins_played DESC LIMIT 10

06-21 16:23:10 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:10 -> SELECT player_id, team_id, mins_played FROM public.v_player_sc WHERE season_name = 'ESP I 2023' ORDER BY mins_played DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:10 -> SELECT player_id, team_id, mins_played FROM public.v_player_sc WHERE season_name = 'ESP I 2023' ORDER BY mins_played DESC LIMIT 10

Successful query
Data Shape: (0, 3)
Running query: SELECT player_id, team_id, mins_played FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY mins_played DESC LIMIT 10

06-21 16:23:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:11 -> SELECT player_id, team_id, mins_played FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY mins_played DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:11 -> SELECT player_id, team_id, mins_played FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY mins_played DESC LIMIT 10

Successful query
Data Shape: (10, 3)
Running query: SELECT player_id, COUNT(*) AS total_saves FROM public.t_saved_shot WHERE outcome = true AND season_id = 816527 GROUP BY player_id ORDER BY total_saves DESC LIMIT 1

06-21 16:23:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:11 -> SELECT player_id, COUNT(*) AS total_saves FROM public.t_saved_shot WHERE outcome = true AND season_id = 816527 GROUP BY player_id ORDER BY total_saves DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:11 -> SELECT player_id, COUNT(*) AS total_saves FROM public.t_saved_shot WHERE outcome = true AND season_id = 816527 GROUP BY player_id ORDER BY total_saves DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...FROM public.t_saved_shot WHERE outcome = true AND season_id ...
                                                             ^

Failed query
Running query: SELECT tackles_total FROM public.vt_season_stat_player WHERE player_id = 349 AND team_id = 4265 AND season_id = 816527 AND tackles_total IS NOT NULL

06-21 16:23:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:11 -> SELECT tackles_total FROM public.vt_season_stat_player WHERE player_id = 349 AND team_id = 4265 AND season_id = 816527 AND tackles_total IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:11 -> SELECT tackles_total FROM public.vt_season_stat_player WHERE player_id = 349 AND team_id = 4265 AND season_id = 816527 AND tackles_total IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT tackles_total FROM public.vt_season_stat_player WHERE player_id = 349 AND team_id = 4265 AND season_id = 816690 AND tackles_total IS NOT NULL

06-21 16:23:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:11 -> SELECT tackles_total FROM public.vt_season_stat_player WHERE player_id = 349 AND team_id = 4265 AND season_id = 816690 AND tackles_total IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:11 -> SELECT tackles_total FROM public.vt_season_stat_player WHERE player_id = 349 AND team_id = 4265 AND season_id = 816690 AND tackles_total IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, team_id, mins_played FROM public.vt_season_info_player WHERE season_id = 816527 AND player_id NOT IN (60, 61, 62, 63, 64, 65, 66) ORDER BY mins_played DESC LIMIT 5

06-21 16:23:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:11 -> SELECT player_id, team_id, mins_played FROM public.vt_season_info_player WHERE season_id = 816527 AND player_id NOT IN (60, 61, 62, 63, 64, 65, 66) ORDER BY mins_played DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:11 -> SELECT player_id, team_id, mins_played FROM public.vt_season_info_player WHERE season_id = 816527 AND player_id NOT IN (60, 61, 62, 63, 64, 65, 66) ORDER BY mins_played DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, goals FROM public.vt_season_info_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:23:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:12 -> SELECT player_id, goals FROM public.vt_season_info_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:12 -> SELECT player_id, goals FROM public.vt_season_info_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT xg FROM public.vt_season_metric_player WHERE player_id = 349 AND team_id = 4265 AND season_id = 816527 AND xg IS NOT NULL

06-21 16:23:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:12 -> SELECT xg FROM public.vt_season_metric_player WHERE player_id = 349 AND team_id = 4265 AND season_id = 816527 AND xg IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:12 -> SELECT xg FROM public.vt_season_metric_player WHERE player_id = 349 AND team_id = 4265 AND season_id = 816527 AND xg IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT xg FROM public.vt_season_metric_player WHERE player_id = 349 AND team_id = 4265 AND season_id = 816690 AND xg IS NOT NULL

06-21 16:23:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:12 -> SELECT xg FROM public.vt_season_metric_player WHERE player_id = 349 AND team_id = 4265 AND season_id = 816690 AND xg IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:12 -> SELECT xg FROM public.vt_season_metric_player WHERE player_id = 349 AND team_id = 4265 AND season_id = 816690 AND xg IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, SUM(goals) AS total_goals FROM public.vt_season_info_player WHERE team_id IN (SELECT team_id FROM public.vt_team WHERE country = 'Spain' AND division = '1') AND season_id = 816527 AND player_id NOT IN (60, 61,62,63,64,65,66) GROUP BY player_id ORDER BY total_goals DESC LIMIT 1

06-21 16:23:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:12 -> SELECT player_id, SUM(goals) AS total_goals FROM public.vt_season_info_player WHERE team_id IN (SELECT team_id FROM public.vt_team WHERE country = 'Spain' AND division = '1') AND season_id = 816527 AND player_id NOT IN (60, 61,62,63,64,65,66) GROUP BY player_id ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:12 -> SELECT player_id, SUM(goals) AS total_goals FROM public.vt_season_info_player WHERE team_id IN (SELECT team_id FROM public.vt_team WHERE country = 'Spain' AND division = '1') AND season_id = 816527 AND player_id NOT IN (60, 61,62,63,64,65,66) GROUP BY player_id ORDER BY total_goals DESC LIMIT 1
ERROR:root:Database error: relation "public.vt_team" does not exist
LINE 1: ...info_player WHERE team_id IN (SELECT team_id FROM public.vt_...
                                                             ^

Failed query
Running query: SELECT player_id, team_id, player_name, team_name, mins_played FROM public.v_player_sc WHERE season_name = 'ESP I 2023' AND mins_played IS NOT NULL ORDER BY mins_played DESC LIMIT 5

06-21 16:23:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:12 -> SELECT player_id, team_id, player_name, team_name, mins_played FROM public.v_player_sc WHERE season_name = 'ESP I 2023' AND mins_played IS NOT NULL ORDER BY mins_played DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:12 -> SELECT player_id, team_id, player_name, team_name, mins_played FROM public.v_player_sc WHERE season_name = 'ESP I 2023' AND mins_played IS NOT NULL ORDER BY mins_played DESC LIMIT 5

Successful query
Data Shape: (0, 5)
Running query: SELECT points FROM public.t_season_team_rank WHERE team_id = 4265 AND season_id = 816527

06-21 16:23:13 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:13 -> SELECT points FROM public.t_season_team_rank WHERE team_id = 4265 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:13 -> SELECT points FROM public.t_season_team_rank WHERE team_id = 4265 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT team_id, team_name, shots_on_target FROM vm_agg_season_team WHERE season_id = 816527 ORDER BY shots_on_target DESC LIMIT 5

06-21 16:23:13 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:13 -> SELECT team_id, team_name, shots_on_target FROM vm_agg_season_team WHERE season_id = 816527 ORDER BY shots_on_target DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:13 -> SELECT team_id, team_name, shots_on_target FROM vm_agg_season_team WHERE season_id = 816527 ORDER BY shots_on_target DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT team_id, team_name, shots_on_target FROM vm_agg_season_team_opta WHERE season_id = 816527 ORDER BY shots_on_target DESC LIMIT 5

06-21 16:23:13 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:13 -> SELECT team_id, team_name, shots_on_target FROM vm_agg_season_team_opta WHERE season_id = 816527 ORDER BY shots_on_target DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:13 -> SELECT team_id, team_name, shots_on_target FROM vm_agg_season_team_opta WHERE season_id = 816527 ORDER BY shots_on_target DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, xa_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND xa_90 IS NOT NULL ORDER BY xa_90 DESC LIMIT 10

06-21 16:23:13 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:13 -> SELECT player_id, xa_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND xa_90 IS NOT NULL ORDER BY xa_90 DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:13 -> SELECT player_id, xa_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND xa_90 IS NOT NULL ORDER BY xa_90 DESC LIMIT 10

Successful query
Data Shape: (10, 2)
Running query: SELECT player_id, xa FROM vm_agg_season_player_opta WHERE season_id = 816527 AND xa IS NOT NULL ORDER BY xa DESC LIMIT 10

06-21 16:23:15 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:15 -> SELECT player_id, xa FROM vm_agg_season_player_opta WHERE season_id = 816527 AND xa IS NOT NULL ORDER BY xa DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:15 -> SELECT player_id, xa FROM vm_agg_season_player_opta WHERE season_id = 816527 AND xa IS NOT NULL ORDER BY xa DESC LIMIT 10

Successful query
Data Shape: (10, 2)
Running query: SELECT team_id, team_name, goals_scored FROM vm_agg_season_team WHERE season_id = 816527 ORDER BY goals_scored DESC LIMIT 5

06-21 16:23:15 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:15 -> SELECT team_id, team_name, goals_scored FROM vm_agg_season_team WHERE season_id = 816527 ORDER BY goals_scored DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:15 -> SELECT team_id, team_name, goals_scored FROM vm_agg_season_team WHERE season_id = 816527 ORDER BY goals_scored DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT team_id, team_name, goals_scored FROM vm_agg_season_team_opta WHERE season_id = 816527 ORDER BY goals_scored DESC LIMIT 5

06-21 16:23:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:16 -> SELECT team_id, team_name, goals_scored FROM vm_agg_season_team_opta WHERE season_id = 816527 ORDER BY goals_scored DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:16 -> SELECT team_id, team_name, goals_scored FROM vm_agg_season_team_opta WHERE season_id = 816527 ORDER BY goals_scored DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT * FROM t_match WHERE (home_team_id = 4265 OR away_team_id = 4265) AND (home_team_id = 4279 OR away_team_id = 4279) AND season_id = 816527

06-21 16:23:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:16 -> SELECT * FROM t_match WHERE (home_team_id = 4265 OR away_team_id = 4265) AND (home_team_id = 4279 OR away_team_id = 4279) AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:16 -> SELECT * FROM t_match WHERE (home_team_id = 4265 OR away_team_id = 4265) AND (home_team_id = 4279 OR away_team_id = 4279) AND season_id = 816527

Successful query
Data Shape: (2, 95)
Running query: SELECT player_id, passes_total, team_id, season_id FROM public.vt_match_stat_player WHERE match_id IN (SELECT match_id FROM t_match WHERE (home_team_id = 4265 OR away_team_id = 4265) AND (home_team_id = 4279 OR away_team_id = 4279) AND season_id = 816527) AND passes_total IS NOT NULL

06-21 16:23:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:16 -> SELECT player_id, passes_total, team_id, season_id FROM public.vt_match_stat_player WHERE match_id IN (SELECT match_id FROM t_match WHERE (home_team_id = 4265 OR away_team_id = 4265) AND (home_team_id = 4279 OR away_team_id = 4279) AND season_id = 816527) AND passes_total IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:16 -> SELECT player_id, passes_total, team_id, season_id FROM public.vt_match_stat_player WHERE match_id IN (SELECT match_id FROM t_match WHERE (home_team_id = 4265 OR away_team_id = 4265) AND (home_team_id = 4279 OR away_team_id = 4279) AND season_id = 816527) AND passes_total IS NOT NULL
ERROR:root:Database error: relation "public.vt_match_stat_player" does not exist
LINE 1: ... player_id, passes_total, team_id, season_id FROM public.vt_...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, team_id, season_id, goals_received, xg_faced, xg_saved_per_shot, xg_on_target, xg_faced_on_target, xg_faced_on_target_efficiency, xg_saved_per_xg_faced_on_target FROM vm_agg_season_player_opta WHERE season_id = 816527 AND player_position = 'GK' ORDER BY goals_received ASC LIMIT 5

06-21 16:23:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:16 -> SELECT player_id, player_name, team_id, season_id, goals_received, xg_faced, xg_saved_per_shot, xg_on_target, xg_faced_on_target, xg_faced_on_target_efficiency, xg_saved_per_xg_faced_on_target FROM vm_agg_season_player_opta WHERE season_id = 816527 AND player_position = 'GK' ORDER BY goals_received ASC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:16 -> SELECT player_id, player_name, team_id, season_id, goals_received, xg_faced, xg_saved_per_shot, xg_on_target, xg_faced_on_target, xg_faced_on_target_efficiency, xg_saved_per_xg_faced_on_target FROM vm_agg_season_player_opta WHERE season_id = 816527 AND player_position = 'GK' ORDER BY goals_received ASC LIMIT 5
ERROR:root:Database error: column "xg_faced" does not exist
LINE 1: ... player_name, team_id, season_id, goals_received, xg_faced, ...
                                                             ^

Failed query
Running query: SELECT player_id, passes_total, team_id, match_id FROM public.vt_match_player_stats WHERE match_id IN (SELECT match_id FROM t_match WHERE (home_team_id = 4265 OR away_team_id = 4265) AND (home_team_id = 4279 OR away_team_id = 4279) AND season_id = 816527) AND team_id IN (4265, 4279) AND passes_total IS NOT NULL

06-21 16:23:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:16 -> SELECT player_id, passes_total, team_id, match_id FROM public.vt_match_player_stats WHERE match_id IN (SELECT match_id FROM t_match WHERE (home_team_id = 4265 OR away_team_id = 4265) AND (home_team_id = 4279 OR away_team_id = 4279) AND season_id = 816527) AND team_id IN (4265, 4279) AND passes_total IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:16 -> SELECT player_id, passes_total, team_id, match_id FROM public.vt_match_player_stats WHERE match_id IN (SELECT match_id FROM t_match WHERE (home_team_id = 4265 OR away_team_id = 4265) AND (home_team_id = 4279 OR away_team_id = 4279) AND season_id = 816527) AND team_id IN (4265, 4279) AND passes_total IS NOT NULL
ERROR:root:Database error: relation "public.vt_match_player_stats" does not exist
LINE 1: ...T player_id, passes_total, team_id, match_id FROM public.vt_...
                                                             ^

Failed query
Running query: SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527 AND goals IS NOT NULL

06-21 16:23:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:16 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:16 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527 AND goals IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT goals FROM vm_agg_season_player_all WHERE player_id = 1163220 AND season_id = 816527 AND goals IS NOT NULL

06-21 16:23:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:16 -> SELECT goals FROM vm_agg_season_player_all WHERE player_id = 1163220 AND season_id = 816527 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:16 -> SELECT goals FROM vm_agg_season_player_all WHERE player_id = 1163220 AND season_id = 816527 AND goals IS NOT NULL
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT goals FROM vm_agg_season_player_all WHERE player_id =...
                          ^

Failed query
Running query: SELECT goals FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527 AND goals IS NOT NULL

06-21 16:23:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:16 -> SELECT goals FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:16 -> SELECT goals FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527 AND goals IS NOT NULL
ERROR:root:Database error: column "goals" does not exist
LINE 1: SELECT goals FROM vm_agg_season_player_similarity WHERE play...
               ^

Failed query
Running query: SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 5

06-21 16:23:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:16 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:16 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 5

06-21 16:23:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:17 -> SELECT player_id, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:17 -> SELECT player_id, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, xa, player_name FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY xa DESC LIMIT 10

06-21 16:23:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:17 -> SELECT player_id, xa, player_name FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY xa DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:17 -> SELECT player_id, xa, player_name FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY xa DESC LIMIT 10

Successful query
Data Shape: (0, 3)
Running query: SELECT player_id, xa, player_name FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY xa DESC LIMIT 10

06-21 16:23:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:17 -> SELECT player_id, xa, player_name FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY xa DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:17 -> SELECT player_id, xa, player_name FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY xa DESC LIMIT 10

Successful query
Data Shape: (0, 3)
Running query: SELECT player_name, goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:23:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:17 -> SELECT player_name, goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:17 -> SELECT player_name, goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
ERROR:root:Database error: column "goals" does not exist
LINE 1: SELECT player_name, goals FROM vm_agg_season_player_similari...
                            ^

Failed query
Running query: SELECT goals FROM vm_agg_season_player_opta WHERE player_name = 'Robert Lewandowski' AND season_id = 816527 AND goals IS NOT NULL

06-21 16:23:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:17 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_name = 'Robert Lewandowski' AND season_id = 816527 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:17 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_name = 'Robert Lewandowski' AND season_id = 816527 AND goals IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT age FROM vm_agg_year_player_info WHERE player_name = 'Artem Dovbyk' AND year = 2023

06-21 16:23:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:17 -> SELECT age FROM vm_agg_year_player_info WHERE player_name = 'Artem Dovbyk' AND year = 2023
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:17 -> SELECT age FROM vm_agg_year_player_info WHERE player_name = 'Artem Dovbyk' AND year = 2023

Successful query
Data Shape: (2, 1)
Running query: SELECT age FROM vm_agg_year_player_loan WHERE player_name = 'Artem Dovbyk' AND current_season_name = 'ESP I 2023' AND age IS NOT NULL

06-21 16:23:28 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:28 -> SELECT age FROM vm_agg_year_player_loan WHERE player_name = 'Artem Dovbyk' AND current_season_name = 'ESP I 2023' AND age IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:28 -> SELECT age FROM vm_agg_year_player_loan WHERE player_name = 'Artem Dovbyk' AND current_season_name = 'ESP I 2023' AND age IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT age FROM vm_agg_year_player_info WHERE player_name = 'Artem Dovbyk' AND year = 2023 AND age IS NOT NULL

06-21 16:23:28 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:28 -> SELECT age FROM vm_agg_year_player_info WHERE player_name = 'Artem Dovbyk' AND year = 2023 AND age IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:28 -> SELECT age FROM vm_agg_year_player_info WHERE player_name = 'Artem Dovbyk' AND year = 2023 AND age IS NOT NULL

Successful query
Data Shape: (2, 1)
Running query: SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_label = 'La Liga' ORDER BY goals DESC LIMIT 1

06-21 16:23:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:29 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_label = 'La Liga' ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:29 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_label = 'La Liga' ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT goals_scored FROM vm_agg_season_team WHERE team_id = 4266 AND season_id = 816527 AND ground_id = 2

06-21 16:23:31 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:31 -> SELECT goals_scored FROM vm_agg_season_team WHERE team_id = 4266 AND season_id = 816527 AND ground_id = 2
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:31 -> SELECT goals_scored FROM vm_agg_season_team WHERE team_id = 4266 AND season_id = 816527 AND ground_id = 2

Successful query
Data Shape: (1, 1)
Running query: SELECT SUM(assists) FROM vm_agg_season_player_opta WHERE league_label = 'La Liga' AND season_id = 816527

06-21 16:23:31 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:31 -> SELECT SUM(assists) FROM vm_agg_season_player_opta WHERE league_label = 'La Liga' AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:31 -> SELECT SUM(assists) FROM vm_agg_season_player_opta WHERE league_label = 'La Liga' AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT SUM(assists_90) FROM vm_agg_season_player_similarity WHERE team_id = 20076 AND season_id = 816527

06-21 16:23:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:32 -> SELECT SUM(assists_90) FROM vm_agg_season_player_similarity WHERE team_id = 20076 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:32 -> SELECT SUM(assists_90) FROM vm_agg_season_player_similarity WHERE team_id = 20076 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT SUM(assists_90) FROM vm_agg_season_player_similarity WHERE season_id = 816527

06-21 16:23:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:32 -> SELECT SUM(assists_90) FROM vm_agg_season_player_similarity WHERE season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:32 -> SELECT SUM(assists_90) FROM vm_agg_season_player_similarity WHERE season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT match_id, xg FROM public.vt_game_metric_player WHERE player_id = 1598188 AND season_id = 816527 AND xg IS NOT NULL ORDER BY xg DESC LIMIT 5

06-21 16:23:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:32 -> SELECT match_id, xg FROM public.vt_game_metric_player WHERE player_id = 1598188 AND season_id = 816527 AND xg IS NOT NULL ORDER BY xg DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:32 -> SELECT match_id, xg FROM public.vt_game_metric_player WHERE player_id = 1598188 AND season_id = 816527 AND xg IS NOT NULL ORDER BY xg DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT SUM(goals_scored) FROM vm_agg_season_team WHERE team_id = 4266 AND season_id = 816527 AND ground_id = 2

06-21 16:23:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:32 -> SELECT SUM(goals_scored) FROM vm_agg_season_team WHERE team_id = 4266 AND season_id = 816527 AND ground_id = 2
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:32 -> SELECT SUM(goals_scored) FROM vm_agg_season_team WHERE team_id = 4266 AND season_id = 816527 AND ground_id = 2

Successful query
Data Shape: (1, 1)
Running query: SELECT match_id, xg FROM public.vt_game_metric_player WHERE team_id = 20076 AND season_id = 816527 ORDER BY xg DESC LIMIT 5

06-21 16:23:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:32 -> SELECT match_id, xg FROM public.vt_game_metric_player WHERE team_id = 20076 AND season_id = 816527 ORDER BY xg DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:32 -> SELECT match_id, xg FROM public.vt_game_metric_player WHERE team_id = 20076 AND season_id = 816527 ORDER BY xg DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, passes_total, passes_accurate, team_id, match_id, season_id FROM public.vt_game_stat_player WHERE season_id = 816527 AND team_id = 4265 AND match_id IN (SELECT match_id FROM t_match WHERE season_id = 816527 AND (home_team_id = 4265 OR away_team_id = 4265)) ORDER BY passes_total DESC LIMIT 5

06-21 16:23:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:36 -> SELECT player_id, passes_total, passes_accurate, team_id, match_id, season_id FROM public.vt_game_stat_player WHERE season_id = 816527 AND team_id = 4265 AND match_id IN (SELECT match_id FROM t_match WHERE season_id = 816527 AND (home_team_id = 4265 OR away_team_id = 4265)) ORDER BY passes_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:36 -> SELECT player_id, passes_total, passes_accurate, team_id, match_id, season_id FROM public.vt_game_stat_player WHERE season_id = 816527 AND team_id = 4265 AND match_id IN (SELECT match_id FROM t_match WHERE season_id = 816527 AND (home_team_id = 4265 OR away_team_id = 4265)) ORDER BY passes_total DESC LIMIT 5

Successful query
Data Shape: (5, 6)
Running query: SELECT SUM(assists) FROM vm_agg_season_player_opta WHERE player_id = 1598188 AND season_id = 816527

06-21 16:23:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:36 -> SELECT SUM(assists) FROM vm_agg_season_player_opta WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:36 -> SELECT SUM(assists) FROM vm_agg_season_player_opta WHERE player_id = 1598188 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT assists FROM public.agg_season_player_pd WHERE player_id = 1598188 AND season_id = 816527 AND assists IS NOT NULL

06-21 16:23:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:36 -> SELECT assists FROM public.agg_season_player_pd WHERE player_id = 1598188 AND season_id = 816527 AND assists IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:36 -> SELECT assists FROM public.agg_season_player_pd WHERE player_id = 1598188 AND season_id = 816527 AND assists IS NOT NULL
ERROR:root:Database error: column "assists" does not exist
LINE 1: SELECT assists FROM public.agg_season_player_pd WHERE player...
               ^

Failed query
Running query: SELECT COUNT(assist_second) FROM public.agg_season_player_pd WHERE player_id = 1598188 AND season_id = 816527 AND assist_second IS NOT NULL

06-21 16:23:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:36 -> SELECT COUNT(assist_second) FROM public.agg_season_player_pd WHERE player_id = 1598188 AND season_id = 816527 AND assist_second IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:36 -> SELECT COUNT(assist_second) FROM public.agg_season_player_pd WHERE player_id = 1598188 AND season_id = 816527 AND assist_second IS NOT NULL
ERROR:root:Database error: column "assist_second" does not exist
LINE 1: SELECT COUNT(assist_second) FROM public.agg_season_player_pd...
                     ^

Failed query
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

06-21 16:23:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:36 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:36 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

06-21 16:23:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:36 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:36 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
ERROR:root:Database error: column "goals" does not exist
LINE 1: SELECT player_id, player_name, goals FROM vm_agg_season_play...
                                       ^

Failed query
Running query: SELECT player_id, player_name, salary FROM vm_agg_season_player_info WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY salary DESC LIMIT 5

06-21 16:23:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:36 -> SELECT player_id, player_name, salary FROM vm_agg_season_player_info WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY salary DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:36 -> SELECT player_id, player_name, salary FROM vm_agg_season_player_info WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY salary DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, player_name, salary FROM vm_agg_season_player_info WHERE team_id = 4265 AND season_id = 816527 ORDER BY salary DESC LIMIT 5

06-21 16:23:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:37 -> SELECT player_id, player_name, salary FROM vm_agg_season_player_info WHERE team_id = 4265 AND season_id = 816527 ORDER BY salary DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:37 -> SELECT player_id, player_name, salary FROM vm_agg_season_player_info WHERE team_id = 4265 AND season_id = 816527 ORDER BY salary DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT goals_scored FROM vm_agg_season_team WHERE team_name = 'Real Betis' AND season_id = 816527

06-21 16:23:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:37 -> SELECT goals_scored FROM vm_agg_season_team WHERE team_name = 'Real Betis' AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:37 -> SELECT goals_scored FROM vm_agg_season_team WHERE team_name = 'Real Betis' AND season_id = 816527

Successful query
Data Shape: (3, 1)
Running query: SELECT player_id, player_name, xg, season_id FROM vm_agg_season_player_opta WHERE season_id = 816527 AND age < 20 ORDER BY xg DESC LIMIT 5

06-21 16:23:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:37 -> SELECT player_id, player_name, xg, season_id FROM vm_agg_season_player_opta WHERE season_id = 816527 AND age < 20 ORDER BY xg DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:37 -> SELECT player_id, player_name, xg, season_id FROM vm_agg_season_player_opta WHERE season_id = 816527 AND age < 20 ORDER BY xg DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT goals_scored FROM vm_agg_season_team WHERE team_name = 'Real Madrid' AND season_id = 816527

06-21 16:23:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:37 -> SELECT goals_scored FROM vm_agg_season_team WHERE team_name = 'Real Madrid' AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:37 -> SELECT goals_scored FROM vm_agg_season_team WHERE team_name = 'Real Madrid' AND season_id = 816527

Successful query
Data Shape: (3, 1)
Running query: SELECT player_id, team_id, season_id, max_speed FROM public.vm_agg_season_player_similarity WHERE season_id = 't' AND age < 20 ORDER BY max_speed DESC LIMIT 5

06-21 16:23:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:37 -> SELECT player_id, team_id, season_id, max_speed FROM public.vm_agg_season_player_similarity WHERE season_id = 't' AND age < 20 ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:37 -> SELECT player_id, team_id, season_id, max_speed FROM public.vm_agg_season_player_similarity WHERE season_id = 't' AND age < 20 ORDER BY max_speed DESC LIMIT 5
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, team_id, season_id, max_speed FROM public....
                                              ^

Failed query
Running query: SELECT player_id, team_id, season_id, max_speed FROM public.vm_agg_season_player_similarity WHERE season_id = 't' AND age < 20 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 5

06-21 16:23:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:37 -> SELECT player_id, team_id, season_id, max_speed FROM public.vm_agg_season_player_similarity WHERE season_id = 't' AND age < 20 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:37 -> SELECT player_id, team_id, season_id, max_speed FROM public.vm_agg_season_player_similarity WHERE season_id = 't' AND age < 20 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 5
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, team_id, season_id, max_speed FROM public....
                                              ^

Failed query
Running query: SELECT assists_90 FROM vm_agg_season_player_opta WHERE player_name = 'Artem Dovbyk' AND season_id = 816527

06-21 16:23:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:39 -> SELECT assists_90 FROM vm_agg_season_player_opta WHERE player_name = 'Artem Dovbyk' AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:39 -> SELECT assists_90 FROM vm_agg_season_player_opta WHERE player_name = 'Artem Dovbyk' AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT assists_90 FROM vm_agg_season_player_opta WHERE player_id = 1598188 AND season_id = 816527

06-21 16:23:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:39 -> SELECT assists_90 FROM vm_agg_season_player_opta WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:39 -> SELECT assists_90 FROM vm_agg_season_player_opta WHERE player_id = 1598188 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT team_id, match_id, passes FROM public.vm_game_stat_team WHERE team_id = 4265 AND season_id = 816527 ORDER BY passes DESC LIMIT 5

06-21 16:23:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:39 -> SELECT team_id, match_id, passes FROM public.vm_game_stat_team WHERE team_id = 4265 AND season_id = 816527 ORDER BY passes DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:39 -> SELECT team_id, match_id, passes FROM public.vm_game_stat_team WHERE team_id = 4265 AND season_id = 816527 ORDER BY passes DESC LIMIT 5
ERROR:root:Database error: column "passes" does not exist
LINE 1: SELECT team_id, match_id, passes FROM public.vm_game_stat_te...
                                  ^

Failed query
Running query: SELECT match_id, passes FROM public.vt_game_metric_team WHERE team_id = 4265 AND season_id = 816527 ORDER BY passes DESC LIMIT 5

06-21 16:23:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:39 -> SELECT match_id, passes FROM public.vt_game_metric_team WHERE team_id = 4265 AND season_id = 816527 ORDER BY passes DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:39 -> SELECT match_id, passes FROM public.vt_game_metric_team WHERE team_id = 4265 AND season_id = 816527 ORDER BY passes DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816530 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

06-21 16:23:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:40 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816530 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:40 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816530 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, goals FROM public.agg_season_player_pd WHERE season_id = 816530 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

06-21 16:23:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:41 -> SELECT player_id, goals FROM public.agg_season_player_pd WHERE season_id = 816530 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:41 -> SELECT player_id, goals FROM public.agg_season_player_pd WHERE season_id = 816530 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
ERROR:root:Database error: column "goals" does not exist
LINE 1: SELECT player_id, goals FROM public.agg_season_player_pd WHE...
                          ^

Failed query
Running query: SELECT player_id, goals FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:23:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:41 -> SELECT player_id, goals FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:41 -> SELECT player_id, goals FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
ERROR:root:Database error: column "goals" does not exist
LINE 1: SELECT player_id, goals FROM public.agg_season_player_pd WHE...
                          ^

Failed query
Running query: SELECT player_name, salary FROM vm_agg_season_player_info WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY salary DESC LIMIT 5

06-21 16:23:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:41 -> SELECT player_name, salary FROM vm_agg_season_player_info WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY salary DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:41 -> SELECT player_name, salary FROM vm_agg_season_player_info WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY salary DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, xg, match_id, season_id FROM public.vt_game_metric_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY xg DESC LIMIT 5

06-21 16:23:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:41 -> SELECT player_id, xg, match_id, season_id FROM public.vt_game_metric_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY xg DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:41 -> SELECT player_id, xg, match_id, season_id FROM public.vt_game_metric_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY xg DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT match_id, passes FROM public.vt_game_metric_team WHERE team_id = 4265 AND season_id = 816527 AND passes IS NOT NULL ORDER BY passes DESC LIMIT 5

06-21 16:23:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:41 -> SELECT match_id, passes FROM public.vt_game_metric_team WHERE team_id = 4265 AND season_id = 816527 AND passes IS NOT NULL ORDER BY passes DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:41 -> SELECT match_id, passes FROM public.vt_game_metric_team WHERE team_id = 4265 AND season_id = 816527 AND passes IS NOT NULL ORDER BY passes DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 20

06-21 16:23:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:41 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 20
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:41 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 20

Successful query
Data Shape: (20, 2)
Running query: SELECT player_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 20

06-21 16:23:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:41 -> SELECT player_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 20
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:41 -> SELECT player_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 20
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, max_speed FROM vm_agg_season_player_simila...
                          ^

Failed query
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND provider_id = 1 ORDER BY max_speed DESC LIMIT 20

06-21 16:23:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:41 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND provider_id = 1 ORDER BY max_speed DESC LIMIT 20
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:41 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND provider_id = 1 ORDER BY max_speed DESC LIMIT 20

Successful query
Data Shape: (0, 2)
Running query: SELECT player_name, goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND position = 'FW' ORDER BY goals DESC LIMIT 1

06-21 16:23:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:41 -> SELECT player_name, goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND position = 'FW' ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:41 -> SELECT player_name, goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND position = 'FW' ORDER BY goals DESC LIMIT 1
ERROR:root:Database error: column "goals" does not exist
LINE 1: SELECT player_name, goals FROM vm_agg_season_player_similari...
                            ^

Failed query
Running query: SELECT assists FROM vm_agg_season_player_similarity WHERE player_name = 'Artem Dovbyk' AND season_id = 816527

06-21 16:23:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:42 -> SELECT assists FROM vm_agg_season_player_similarity WHERE player_name = 'Artem Dovbyk' AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:42 -> SELECT assists FROM vm_agg_season_player_similarity WHERE player_name = 'Artem Dovbyk' AND season_id = 816527
ERROR:root:Database error: column "assists" does not exist
LINE 1: SELECT assists FROM vm_agg_season_player_similarity WHERE pl...
               ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.assists_90".

Failed query
Running query: SELECT match_id, passes_accurate FROM public.vt_game_stat_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY passes_accurate DESC LIMIT 5

06-21 16:23:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:42 -> SELECT match_id, passes_accurate FROM public.vt_game_stat_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY passes_accurate DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:42 -> SELECT match_id, passes_accurate FROM public.vt_game_stat_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY passes_accurate DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:23:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:45 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:45 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:23:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:45 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:45 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
ERROR:root:Database error: column "goals" does not exist
LINE 1: SELECT player_id, player_name, goals FROM vm_agg_season_play...
                                       ^

Failed query
Running query: SELECT match_id, xg FROM public.vt_game_metric_team WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg DESC LIMIT 5

06-21 16:23:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:45 -> SELECT match_id, xg FROM public.vt_game_metric_team WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:45 -> SELECT match_id, xg FROM public.vt_game_metric_team WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT match_id, xg FROM public.vt_game_metric_team WHERE team_id = 4265 AND season_id = 816527 AND xg IS NOT NULL ORDER BY xg DESC LIMIT 5

06-21 16:23:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:46 -> SELECT match_id, xg FROM public.vt_game_metric_team WHERE team_id = 4265 AND season_id = 816527 AND xg IS NOT NULL ORDER BY xg DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:46 -> SELECT match_id, xg FROM public.vt_game_metric_team WHERE team_id = 4265 AND season_id = 816527 AND xg IS NOT NULL ORDER BY xg DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT match_id, xg FROM public.vt_game_metric_team WHERE team_id = 4265 AND season_id = 816527 AND xg IS NOT NULL ORDER BY xg DESC LIMIT 1

06-21 16:23:48 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:48 -> SELECT match_id, xg FROM public.vt_game_metric_team WHERE team_id = 4265 AND season_id = 816527 AND xg IS NOT NULL ORDER BY xg DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:48 -> SELECT match_id, xg FROM public.vt_game_metric_team WHERE team_id = 4265 AND season_id = 816527 AND xg IS NOT NULL ORDER BY xg DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_name, team_name, season_id, touches_90 FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY touches_90 DESC LIMIT 1

06-21 16:23:48 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:48 -> SELECT player_name, team_name, season_id, touches_90 FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY touches_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:48 -> SELECT player_name, team_name, season_id, touches_90 FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY touches_90 DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT player_name, team_name, season_id, dribbles_won_90 FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY dribbles_won_90 DESC LIMIT 1

06-21 16:23:48 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:48 -> SELECT player_name, team_name, season_id, dribbles_won_90 FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY dribbles_won_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:48 -> SELECT player_name, team_name, season_id, dribbles_won_90 FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY dribbles_won_90 DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT player_name FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

06-21 16:23:48 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:48 -> SELECT player_name FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:48 -> SELECT player_name FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 1)
Running query: SELECT player_name FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

06-21 16:23:48 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:48 -> SELECT player_name FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:48 -> SELECT player_name FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
ERROR:root:Database error: column "goals" does not exist
LINE 1: ...on_player_similarity WHERE season_id = 816527 AND goals IS N...
                                                             ^

Failed query
Running query: SELECT player_id, goals FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:23:48 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:48 -> SELECT player_id, goals FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:48 -> SELECT player_id, goals FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:23:48 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:48 -> SELECT player_id, goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:48 -> SELECT player_id, goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
ERROR:root:Database error: column "goals" does not exist
LINE 1: SELECT player_id, goals FROM vm_agg_season_player_similarity...
                          ^

Failed query
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_label = 'La Liga' ORDER BY goals DESC LIMIT 1

06-21 16:23:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:49 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_label = 'La Liga' ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:49 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_label = 'La Liga' ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY goals DESC LIMIT 1

06-21 16:23:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:49 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:49 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (0, 3)
Running query: SELECT player_name FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY goals DESC LIMIT 1

06-21 16:23:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:49 -> SELECT player_name FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:49 -> SELECT player_name FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (0, 1)
Running query: SELECT player_id, xa, player_name FROM vm_agg_season_player_opta WHERE season_id = 816527 AND xa IS NOT NULL ORDER BY xa DESC LIMIT 10

06-21 16:23:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:49 -> SELECT player_id, xa, player_name FROM vm_agg_season_player_opta WHERE season_id = 816527 AND xa IS NOT NULL ORDER BY xa DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:49 -> SELECT player_id, xa, player_name FROM vm_agg_season_player_opta WHERE season_id = 816527 AND xa IS NOT NULL ORDER BY xa DESC LIMIT 10

Successful query
Data Shape: (10, 3)
Running query: SELECT player_id, assists_90, player_name FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND assists_90 IS NOT NULL ORDER BY assists_90 DESC LIMIT 10

06-21 16:23:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:49 -> SELECT player_id, assists_90, player_name FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND assists_90 IS NOT NULL ORDER BY assists_90 DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:49 -> SELECT player_id, assists_90, player_name FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND assists_90 IS NOT NULL ORDER BY assists_90 DESC LIMIT 10

Successful query
Data Shape: (10, 3)
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

06-21 16:23:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:49 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:49 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, passes_total FROM public.vt_game_stat_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY passes_total DESC LIMIT 5

06-21 16:23:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:49 -> SELECT player_id, passes_total FROM public.vt_game_stat_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY passes_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:49 -> SELECT player_id, passes_total FROM public.vt_game_stat_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY passes_total DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, player_name, goals_90, xg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816530 AND age < 25 AND position = 'FW' ORDER BY (goals_90 - xg_90) DESC LIMIT 1

06-21 16:23:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:50 -> SELECT player_id, player_name, goals_90, xg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816530 AND age < 25 AND position = 'FW' ORDER BY (goals_90 - xg_90) DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:50 -> SELECT player_id, player_name, goals_90, xg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816530 AND age < 25 AND position = 'FW' ORDER BY (goals_90 - xg_90) DESC LIMIT 1
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: SELECT player_id, player_name, goals_90, xg_90 FROM vm_agg_s...
                                       ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT player_id, player_name, goals, xg, goals - xg AS goal_difference FROM vm_agg_season_player_opta WHERE season_id = 816530 AND age < 25 AND player_position = 'FW' ORDER BY goal_difference DESC LIMIT 1

06-21 16:23:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:50 -> SELECT player_id, player_name, goals, xg, goals - xg AS goal_difference FROM vm_agg_season_player_opta WHERE season_id = 816530 AND age < 25 AND player_position = 'FW' ORDER BY goal_difference DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:50 -> SELECT player_id, player_name, goals, xg, goals - xg AS goal_difference FROM vm_agg_season_player_opta WHERE season_id = 816530 AND age < 25 AND player_position = 'FW' ORDER BY goal_difference DESC LIMIT 1

Successful query
Data Shape: (1, 5)
Running query: SELECT player_name, max_speed FROM vm_agg_season_player_info WHERE season_id IN (816527, 816529, 816530, 816528, 816531) ORDER BY max_speed DESC LIMIT 1

06-21 16:23:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:50 -> SELECT player_name, max_speed FROM vm_agg_season_player_info WHERE season_id IN (816527, 816529, 816530, 816528, 816531) ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:50 -> SELECT player_name, max_speed FROM vm_agg_season_player_info WHERE season_id IN (816527, 816529, 816530, 816528, 816531) ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_name, max_speed FROM vm_agg_season_player_opta WHERE season_id IN (816527, 816529, 816530, 816528, 816531) ORDER BY max_speed DESC LIMIT 1

06-21 16:23:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:50 -> SELECT player_name, max_speed FROM vm_agg_season_player_opta WHERE season_id IN (816527, 816529, 816530, 816528, 816531) ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:50 -> SELECT player_name, max_speed FROM vm_agg_season_player_opta WHERE season_id IN (816527, 816529, 816530, 816528, 816531) ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, team_id, season_id, max_speed FROM public.vm_agg_season_player_similarity WHERE season_id IN (816527, 816529, 816530, 816528, 816531) ORDER BY max_speed DESC LIMIT 1

06-21 16:23:51 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:51 -> SELECT player_id, team_id, season_id, max_speed FROM public.vm_agg_season_player_similarity WHERE season_id IN (816527, 816529, 816530, 816528, 816531) ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:51 -> SELECT player_id, team_id, season_id, max_speed FROM public.vm_agg_season_player_similarity WHERE season_id IN (816527, 816529, 816530, 816528, 816531) ORDER BY max_speed DESC LIMIT 1
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, team_id, season_id, max_speed FROM public....
                                              ^

Failed query
Running query: SELECT player_id, team_id, team_games_played FROM vm_agg_season_player_all WHERE player_id = 1163220 AND team_id = 4265 AND season_id = 816527

06-21 16:23:51 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:51 -> SELECT player_id, team_id, team_games_played FROM vm_agg_season_player_all WHERE player_id = 1163220 AND team_id = 4265 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:51 -> SELECT player_id, team_id, team_games_played FROM vm_agg_season_player_all WHERE player_id = 1163220 AND team_id = 4265 AND season_id = 816527
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, team_id, team_games_played FROM vm_agg_sea...
                                                          ^

Failed query
Running query: SELECT games_played_65mins FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527

06-21 16:23:53 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:53 -> SELECT games_played_65mins FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:53 -> SELECT games_played_65mins FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527

Successful query
Data Shape: (4, 1)
Running query: SELECT player_id, season_id, sum(dl_index) as total_score FROM vm_agg_season_player_similarity WHERE season_id IN (816527, 816528, 816529, 816530, 816531) GROUP BY season_id, player_id ORDER BY total_score DESC LIMIT 1

06-21 16:23:53 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:53 -> SELECT player_id, season_id, sum(dl_index) as total_score FROM vm_agg_season_player_similarity WHERE season_id IN (816527, 816528, 816529, 816530, 816531) GROUP BY season_id, player_id ORDER BY total_score DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:53 -> SELECT player_id, season_id, sum(dl_index) as total_score FROM vm_agg_season_player_similarity WHERE season_id IN (816527, 816528, 816529, 816530, 816531) GROUP BY season_id, player_id ORDER BY total_score DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, team_id, season_id, player_name, MAX(goals_scored) as top_scorer FROM vm_agg_season_player_all WHERE league_type_id = 1 AND season_id IN (816527, 816528, 816529, 816530, 816531) GROUP BY season_id

06-21 16:23:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:54 -> SELECT player_id, team_id, season_id, player_name, MAX(goals_scored) as top_scorer FROM vm_agg_season_player_all WHERE league_type_id = 1 AND season_id IN (816527, 816528, 816529, 816530, 816531) GROUP BY season_id
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:54 -> SELECT player_id, team_id, season_id, player_name, MAX(goals_scored) as top_scorer FROM vm_agg_season_player_all WHERE league_type_id = 1 AND season_id IN (816527, 816528, 816529, 816530, 816531) GROUP BY season_id
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...player_name, MAX(goals_scored) as top_scorer FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id IN (816527, 816528, 816529, 816530, 816531) AND league_country_name = 'Spain' ORDER BY goals DESC LIMIT 1

06-21 16:23:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:54 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id IN (816527, 816528, 816529, 816530, 816531) AND league_country_name = 'Spain' ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:54 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id IN (816527, 816528, 816529, 816530, 816531) AND league_country_name = 'Spain' ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, COUNT(DISTINCT match_id) FROM public.t_goal WHERE player_id IN (SELECT player_id FROM t_player WHERE position = 'FW' AND age < 25 AND market_value < 50000000) AND season_id = 816527 GROUP BY player_id HAVING COUNT(DISTINCT match_id) >= 10

06-21 16:23:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:54 -> SELECT player_id, COUNT(DISTINCT match_id) FROM public.t_goal WHERE player_id IN (SELECT player_id FROM t_player WHERE position = 'FW' AND age < 25 AND market_value < 50000000) AND season_id = 816527 GROUP BY player_id HAVING COUNT(DISTINCT match_id) >= 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:54 -> SELECT player_id, COUNT(DISTINCT match_id) FROM public.t_goal WHERE player_id IN (SELECT player_id FROM t_player WHERE position = 'FW' AND age < 25 AND market_value < 50000000) AND season_id = 816527 GROUP BY player_id HAVING COUNT(DISTINCT match_id) >= 10
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...FW' AND age < 25 AND market_value < 50000000) AND season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, team_id, season_id, age, position, goals_90, xg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND age < 25 AND position = 'FW' AND market_value < 50 AND goals_90 > xg_90 AND goals > 10

06-21 16:23:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:54 -> SELECT player_id, player_name, team_id, season_id, age, position, goals_90, xg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND age < 25 AND position = 'FW' AND market_value < 50 AND goals_90 > xg_90 AND goals > 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:54 -> SELECT player_id, player_name, team_id, season_id, age, position, goals_90, xg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND age < 25 AND position = 'FW' AND market_value < 50 AND goals_90 > xg_90 AND goals > 10
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: ..., player_name, team_id, season_id, age, position, goals_90, ...
                                                             ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE position = 'GK' AND season_id = 816582 ORDER BY dl_index DESC LIMIT 5

06-21 16:23:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:54 -> SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE position = 'GK' AND season_id = 816582 ORDER BY dl_index DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:54 -> SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE position = 'GK' AND season_id = 816582 ORDER BY dl_index DESC LIMIT 5

Successful query
Data Shape: (0, 4)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE season_id = 816582 AND player_position = 'GK' ORDER BY dl_index DESC LIMIT 5

06-21 16:23:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:54 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE season_id = 816582 AND player_position = 'GK' ORDER BY dl_index DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:54 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE season_id = 816582 AND player_position = 'GK' ORDER BY dl_index DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816582 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY max_speed DESC LIMIT 5

06-21 16:23:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:54 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816582 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:54 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816582 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, player_name, team_id, dl_index FROM vm_agg_season_player_similarity WHERE season_id = 816582 AND position = 'GK' ORDER BY dl_index DESC LIMIT 5

06-21 16:23:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:54 -> SELECT player_id, player_name, team_id, dl_index FROM vm_agg_season_player_similarity WHERE season_id = 816582 AND position = 'GK' ORDER BY dl_index DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:54 -> SELECT player_id, player_name, team_id, dl_index FROM vm_agg_season_player_similarity WHERE season_id = 816582 AND position = 'GK' ORDER BY dl_index DESC LIMIT 5

Successful query
Data Shape: (0, 4)
Running query: SELECT player_id, player_name, team_name, games_played, minutes_played, dl_index FROM vm_agg_season_player_alert WHERE season_id = 816582 AND position = 'GK' ORDER BY dl_index DESC LIMIT 5

06-21 16:23:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:54 -> SELECT player_id, player_name, team_name, games_played, minutes_played, dl_index FROM vm_agg_season_player_alert WHERE season_id = 816582 AND position = 'GK' ORDER BY dl_index DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:54 -> SELECT player_id, player_name, team_name, games_played, minutes_played, dl_index FROM vm_agg_season_player_alert WHERE season_id = 816582 AND position = 'GK' ORDER BY dl_index DESC LIMIT 5

Successful query
Data Shape: (5, 6)
Running query: SELECT player_id, player_name, team_id, season_id, team_games_played, team_mins_played, games_lost FROM vm_agg_season_player_all WHERE season_id = 816582 AND player_country_code = 'POR' AND league_type_id = 1 ORDER BY games_lost ASC LIMIT 5

06-21 16:23:55 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:55 -> SELECT player_id, player_name, team_id, season_id, team_games_played, team_mins_played, games_lost FROM vm_agg_season_player_all WHERE season_id = 816582 AND player_country_code = 'POR' AND league_type_id = 1 ORDER BY games_lost ASC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:55 -> SELECT player_id, player_name, team_id, season_id, team_games_played, team_mins_played, games_lost FROM vm_agg_season_player_all WHERE season_id = 816582 AND player_country_code = 'POR' AND league_type_id = 1 ORDER BY games_lost ASC LIMIT 5
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...m_games_played, team_mins_played, games_lost FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, games_played, goals_received FROM vm_agg_season_player_info WHERE country_id = 15 AND position = 'GK' AND games_played >= 15 ORDER BY goals_received ASC LIMIT 5

06-21 16:23:55 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:55 -> SELECT player_id, player_name, games_played, goals_received FROM vm_agg_season_player_info WHERE country_id = 15 AND position = 'GK' AND games_played >= 15 ORDER BY goals_received ASC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:55 -> SELECT player_id, player_name, games_played, goals_received FROM vm_agg_season_player_info WHERE country_id = 15 AND position = 'GK' AND games_played >= 15 ORDER BY goals_received ASC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, team_id, season_id, player_name, mins_played, games_lost FROM vm_agg_season_player_all WHERE season_id = 15 AND player_country_code = 'PT' AND mins_played >= 15 ORDER BY games_lost ASC LIMIT 5

06-21 16:23:56 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:56 -> SELECT player_id, team_id, season_id, player_name, mins_played, games_lost FROM vm_agg_season_player_all WHERE season_id = 15 AND player_country_code = 'PT' AND mins_played >= 15 ORDER BY games_lost ASC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:56 -> SELECT player_id, team_id, season_id, player_name, mins_played, games_lost FROM vm_agg_season_player_all WHERE season_id = 15 AND player_country_code = 'PT' AND mins_played >= 15 ORDER BY games_lost ASC LIMIT 5
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...son_id, player_name, mins_played, games_lost FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, team_name, games, clean_sheets, saves_90, goals_conceded_90, save_pct, penalty_save_pct FROM vm_agg_season_player_similarity WHERE country_id = 15 AND position = 'GK' AND games >= 15 ORDER BY clean_sheets DESC, save_pct DESC LIMIT 5

06-21 16:23:56 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:56 -> SELECT player_id, player_name, team_name, games, clean_sheets, saves_90, goals_conceded_90, save_pct, penalty_save_pct FROM vm_agg_season_player_similarity WHERE country_id = 15 AND position = 'GK' AND games >= 15 ORDER BY clean_sheets DESC, save_pct DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:56 -> SELECT player_id, player_name, team_name, games, clean_sheets, saves_90, goals_conceded_90, save_pct, penalty_save_pct FROM vm_agg_season_player_similarity WHERE country_id = 15 AND position = 'GK' AND games >= 15 ORDER BY clean_sheets DESC, save_pct DESC LIMIT 5
ERROR:root:Database error: column "clean_sheets" does not exist
LINE 1: SELECT player_id, player_name, team_name, games, clean_sheet...
                                                         ^

Failed query
Running query: SELECT player_id, team_id, season_id FROM public.agg_season_player_pd WHERE season_id = 15 AND country_id = 15 AND games_played_65mins >= 15 ORDER BY max_speed DESC LIMIT 5

06-21 16:23:56 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:56 -> SELECT player_id, team_id, season_id FROM public.agg_season_player_pd WHERE season_id = 15 AND country_id = 15 AND games_played_65mins >= 15 ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:56 -> SELECT player_id, team_id, season_id FROM public.agg_season_player_pd WHERE season_id = 15 AND country_id = 15 AND games_played_65mins >= 15 ORDER BY max_speed DESC LIMIT 5
ERROR:root:Database error: column "country_id" does not exist
LINE 1: ...lic.agg_season_player_pd WHERE season_id = 15 AND country_id...
                                                             ^

Failed query
Running query: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id in (816527, 816529, 816530, 816528, 816531) ORDER BY max_speed DESC LIMIT 5

06-21 16:23:56 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:56 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id in (816527, 816529, 816530, 816528, 816531) ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:56 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id in (816527, 816529, 816530, 816528, 816531) ORDER BY max_speed DESC LIMIT 5
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_...
                                              ^

Failed query
Running query: SELECT player_id, player_name, max_speed FROM vm_agg_season_player_info WHERE season_id = 816527 AND country_id = 1 ORDER BY max_speed DESC LIMIT 5

06-21 16:23:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:57 -> SELECT player_id, player_name, max_speed FROM vm_agg_season_player_info WHERE season_id = 816527 AND country_id = 1 ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:57 -> SELECT player_id, player_name, max_speed FROM vm_agg_season_player_info WHERE season_id = 816527 AND country_id = 1 ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 5

06-21 16:23:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:57 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:57 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE country_id = 15 AND position = 'GK' ORDER BY dl_index DESC LIMIT 5

06-21 16:23:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:57 -> SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE country_id = 15 AND position = 'GK' ORDER BY dl_index DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:57 -> SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE country_id = 15 AND position = 'GK' ORDER BY dl_index DESC LIMIT 5
ERROR:root:Database error: column "country_id" does not exist
LINE 1: ..._index FROM vm_agg_season_player_similarity WHERE country_id...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 15 AND player_country_code = 'PRT' ORDER BY games_lost ASC LIMIT 5

06-21 16:23:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:59 -> SELECT player_id, player_name, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 15 AND player_country_code = 'PRT' ORDER BY games_lost ASC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:59 -> SELECT player_id, player_name, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 15 AND player_country_code = 'PRT' ORDER BY games_lost ASC LIMIT 5
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...T player_id, player_name, team_id, season_id FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, season_id, SUM(dl_index) AS total_score FROM vm_agg_season_player_similarity WHERE season_id = 816527 GROUP BY player_id, player_name, season_id ORDER BY total_score DESC LIMIT 1

06-21 16:23:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:59 -> SELECT player_id, player_name, season_id, SUM(dl_index) AS total_score FROM vm_agg_season_player_similarity WHERE season_id = 816527 GROUP BY player_id, player_name, season_id ORDER BY total_score DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:59 -> SELECT player_id, player_name, season_id, SUM(dl_index) AS total_score FROM vm_agg_season_player_similarity WHERE season_id = 816527 GROUP BY player_id, player_name, season_id ORDER BY total_score DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT player_id, team_id, season_id, player_name, SUM(goals_scored) AS total_goals FROM vm_agg_season_player_all WHERE season_id = 816527 GROUP BY player_id, team_id, season_id, player_name ORDER BY total_goals DESC LIMIT 1

06-21 16:23:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:59 -> SELECT player_id, team_id, season_id, player_name, SUM(goals_scored) AS total_goals FROM vm_agg_season_player_all WHERE season_id = 816527 GROUP BY player_id, team_id, season_id, player_name ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:59 -> SELECT player_id, team_id, season_id, player_name, SUM(goals_scored) AS total_goals FROM vm_agg_season_player_all WHERE season_id = 816527 GROUP BY player_id, team_id, season_id, player_name ORDER BY total_goals DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...layer_name, SUM(goals_scored) AS total_goals FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, team_id, season_id, score_pd_float FROM public.agg_season_player_pd WHERE player_id = 1359502 AND season_id = 816529

06-21 16:23:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:59 -> SELECT player_id, team_id, season_id, score_pd_float FROM public.agg_season_player_pd WHERE player_id = 1359502 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:59 -> SELECT player_id, team_id, season_id, score_pd_float FROM public.agg_season_player_pd WHERE player_id = 1359502 AND season_id = 816529

Successful query
Data Shape: (3, 4)
Running query: SELECT player_id, xg FROM vm_agg_season_player_opta WHERE player_id = 1359502 AND season_id = 816529

06-21 16:23:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:59 -> SELECT player_id, xg FROM vm_agg_season_player_opta WHERE player_id = 1359502 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:59 -> SELECT player_id, xg FROM vm_agg_season_player_opta WHERE player_id = 1359502 AND season_id = 816529

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, player_name, team_id, season_id, season_year, league_type_id, SUM(goals) AS total_goals FROM vm_agg_season_player_all WHERE season_id = 816527 GROUP BY player_id, player_name, team_id, season_id, season_year, league_type_id ORDER BY total_goals DESC LIMIT 1

06-21 16:23:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:23:59 -> SELECT player_id, player_name, team_id, season_id, season_year, league_type_id, SUM(goals) AS total_goals FROM vm_agg_season_player_all WHERE season_id = 816527 GROUP BY player_id, player_name, team_id, season_id, season_year, league_type_id ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:23:59 -> SELECT player_id, player_name, team_id, season_id, season_year, league_type_id, SUM(goals) AS total_goals FROM vm_agg_season_player_all WHERE season_id = 816527 GROUP BY player_id, player_name, team_id, season_id, season_year, league_type_id ORDER BY total_goals DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...r, league_type_id, SUM(goals) AS total_goals FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, goals, season_id FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:24:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:00 -> SELECT player_id, player_name, goals, season_id FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:00 -> SELECT player_id, player_name, goals, season_id FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT player_id, goals, season_id FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:24:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:00 -> SELECT player_id, goals, season_id FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:00 -> SELECT player_id, goals, season_id FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, xa_90 FROM vm_agg_season_player_similarity WHERE position = \'DL\' AND season_id = 816529 ORDER BY xa_90 DESC LIMIT 1

06-21 16:24:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:00 -> SELECT player_id, player_name, xa_90 FROM vm_agg_season_player_similarity WHERE position = \'DL\' AND season_id = 816529 ORDER BY xa_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:00 -> SELECT player_id, player_name, xa_90 FROM vm_agg_season_player_similarity WHERE position = \'DL\' AND season_id = 816529 ORDER BY xa_90 DESC LIMIT 1
ERROR:root:Database error: syntax error at or near "\"
LINE 1: ... vm_agg_season_player_similarity WHERE position = \'DL\' AND...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, xa FROM vm_agg_season_player_opta WHERE season_id = 816529 AND position = 'DL'

06-21 16:24:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:00 -> SELECT player_id, player_name, xa FROM vm_agg_season_player_opta WHERE season_id = 816529 AND position = 'DL'
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:00 -> SELECT player_id, player_name, xa FROM vm_agg_season_player_opta WHERE season_id = 816529 AND position = 'DL'

Successful query
Data Shape: (20, 3)
Running query: SELECT max_speed FROM public.agg_season_player_pd WHERE player_id = 1598188 AND season_id = 816527

06-21 16:24:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:00 -> SELECT max_speed FROM public.agg_season_player_pd WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:00 -> SELECT max_speed FROM public.agg_season_player_pd WHERE player_id = 1598188 AND season_id = 816527

Successful query
Data Shape: (4, 1)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE position = 'GK' AND season_id = 816590 ORDER BY dl_index DESC LIMIT 5

06-21 16:24:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:00 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE position = 'GK' AND season_id = 816590 ORDER BY dl_index DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:00 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE position = 'GK' AND season_id = 816590 ORDER BY dl_index DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE position = 'GK' AND season_id = 816590 ORDER BY dl_index DESC LIMIT 5

06-21 16:24:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:00 -> SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE position = 'GK' AND season_id = 816590 ORDER BY dl_index DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:00 -> SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE position = 'GK' AND season_id = 816590 ORDER BY dl_index DESC LIMIT 5

Successful query
Data Shape: (0, 4)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816590 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY max_speed DESC LIMIT 5

06-21 16:24:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:00 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816590 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:00 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816590 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (0, 2)
Running query: SELECT * FROM public.t_goal WHERE season_id = 816582 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY goal_id DESC LIMIT 5

06-21 16:24:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:00 -> SELECT * FROM public.t_goal WHERE season_id = 816582 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY goal_id DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:00 -> SELECT * FROM public.t_goal WHERE season_id = 816582 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY goal_id DESC LIMIT 5
ERROR:root:Database error: column "season_id" does not exist
LINE 1: SELECT * FROM public.t_goal WHERE season_id = 816582 AND pla...
                                          ^

Failed query
Running query: SELECT player_id, player_name, goals_received FROM vm_agg_season_player_info WHERE season_id = 816582 AND player_position = 'GK' AND country_id = 15 ORDER BY goals_received LIMIT 5

06-21 16:24:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:01 -> SELECT player_id, player_name, goals_received FROM vm_agg_season_player_info WHERE season_id = 816582 AND player_position = 'GK' AND country_id = 15 ORDER BY goals_received LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:01 -> SELECT player_id, player_name, goals_received FROM vm_agg_season_player_info WHERE season_id = 816582 AND player_position = 'GK' AND country_id = 15 ORDER BY goals_received LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE season_id = 816582 AND position = 'GK' ORDER BY dl_index DESC LIMIT 5

06-21 16:24:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:01 -> SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE season_id = 816582 AND position = 'GK' ORDER BY dl_index DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:01 -> SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE season_id = 816582 AND position = 'GK' ORDER BY dl_index DESC LIMIT 5

Successful query
Data Shape: (0, 4)
Running query: SELECT player_id, player_name, team_name, season_id, dl_index FROM vm_agg_season_player_similarity WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 5

06-21 16:24:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:01 -> SELECT player_id, player_name, team_name, season_id, dl_index FROM vm_agg_season_player_similarity WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:01 -> SELECT player_id, player_name, team_name, season_id, dl_index FROM vm_agg_season_player_similarity WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 5

Successful query
Data Shape: (5, 5)
Running query: SELECT player_id, player_name, goals, assists FROM vm_agg_season_player_info WHERE team_id = 4265 AND season_id = 816527 ORDER BY (goals + assists) DESC LIMIT 5

06-21 16:24:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:01 -> SELECT player_id, player_name, goals, assists FROM vm_agg_season_player_info WHERE team_id = 4265 AND season_id = 816527 ORDER BY (goals + assists) DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:01 -> SELECT player_id, player_name, goals, assists FROM vm_agg_season_player_info WHERE team_id = 4265 AND season_id = 816527 ORDER BY (goals + assists) DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, player_name, team_name FROM vm_agg_season_player_opta WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 5

06-21 16:24:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:01 -> SELECT player_id, player_name, team_name FROM vm_agg_season_player_opta WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:01 -> SELECT player_id, player_name, team_name FROM vm_agg_season_player_opta WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE season_id = 816582 AND position = \'GK\' ORDER BY dl_index DESC LIMIT 5

06-21 16:24:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:03 -> SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE season_id = 816582 AND position = \'GK\' ORDER BY dl_index DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:03 -> SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE season_id = 816582 AND position = \'GK\' ORDER BY dl_index DESC LIMIT 5
ERROR:root:Database error: syntax error at or near "\"
LINE 1: ...imilarity WHERE season_id = 816582 AND position = \'GK\' ORD...
                                                             ^

Failed query
Running query: SELECT player_id, team_id, season_id, player_name FROM vm_agg_season_player_all WHERE season_id = 816582 AND player_country_code = 'POR' ORDER BY games_lost ASC LIMIT 5

06-21 16:24:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:03 -> SELECT player_id, team_id, season_id, player_name FROM vm_agg_season_player_all WHERE season_id = 816582 AND player_country_code = 'POR' ORDER BY games_lost ASC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:03 -> SELECT player_id, team_id, season_id, player_name FROM vm_agg_season_player_all WHERE season_id = 816582 AND player_country_code = 'POR' ORDER BY games_lost ASC LIMIT 5
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...T player_id, team_id, season_id, player_name FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_alert WHERE season_id = 816582 AND position = 'GK' AND league_country_code = 'POR' ORDER BY dl_index DESC LIMIT 5

06-21 16:24:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:03 -> SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_alert WHERE season_id = 816582 AND position = 'GK' AND league_country_code = 'POR' ORDER BY dl_index DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:03 -> SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_alert WHERE season_id = 816582 AND position = 'GK' AND league_country_code = 'POR' ORDER BY dl_index DESC LIMIT 5

Successful query
Data Shape: (0, 4)
Running query: SELECT player_id, COUNT(DISTINCT match_id) FROM public.t_goal WHERE player_id IN (SELECT player_id FROM t_player WHERE country_id = 15) AND match_id IN (SELECT match_id FROM t_match WHERE season_id = 816582) GROUP BY player_id ORDER BY COUNT(DISTINCT match_id) DESC LIMIT 5

06-21 16:24:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:03 -> SELECT player_id, COUNT(DISTINCT match_id) FROM public.t_goal WHERE player_id IN (SELECT player_id FROM t_player WHERE country_id = 15) AND match_id IN (SELECT match_id FROM t_match WHERE season_id = 816582) GROUP BY player_id ORDER BY COUNT(DISTINCT match_id) DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:03 -> SELECT player_id, COUNT(DISTINCT match_id) FROM public.t_goal WHERE player_id IN (SELECT player_id FROM t_player WHERE country_id = 15) AND match_id IN (SELECT match_id FROM t_match WHERE season_id = 816582) GROUP BY player_id ORDER BY COUNT(DISTINCT match_id) DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE position = 'GK' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:24:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:04 -> SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE position = 'GK' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:04 -> SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE position = 'GK' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (0, 4)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY max_speed DESC LIMIT 1

06-21 16:24:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:04 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:04 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE season_id = 816527 AND position = 'GK' ORDER BY dl_index DESC LIMIT 1

06-21 16:24:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:04 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE season_id = 816527 AND position = 'GK' ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:04 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE season_id = 816527 AND position = 'GK' ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (SELECT p.player_id FROM t_player AS p WHERE p.position = 'GK' AND p.country_id = 15) ORDER BY max_speed DESC LIMIT 1

06-21 16:24:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:04 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (SELECT p.player_id FROM t_player AS p WHERE p.position = 'GK' AND p.country_id = 15) ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:04 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (SELECT p.player_id FROM t_player AS p WHERE p.position = 'GK' AND p.country_id = 15) ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, player_name, team_name, saves_90, clean_sheets_90, goals_conceded_90 FROM vm_agg_season_player_similarity WHERE country_id = 15 AND position = 'GK' ORDER BY clean_sheets_90 DESC, saves_90 DESC LIMIT 1

06-21 16:24:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:04 -> SELECT player_id, player_name, team_name, saves_90, clean_sheets_90, goals_conceded_90 FROM vm_agg_season_player_similarity WHERE country_id = 15 AND position = 'GK' ORDER BY clean_sheets_90 DESC, saves_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:04 -> SELECT player_id, player_name, team_name, saves_90, clean_sheets_90, goals_conceded_90 FROM vm_agg_season_player_similarity WHERE country_id = 15 AND position = 'GK' ORDER BY clean_sheets_90 DESC, saves_90 DESC LIMIT 1
ERROR:root:Database error: column "saves_90" does not exist
LINE 1: SELECT player_id, player_name, team_name, saves_90, clean_sh...
                                                  ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.shots_90".

Failed query
Running query: SELECT player_id, player_name, goals, assists FROM vm_agg_season_player_info WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals DESC, assists DESC LIMIT 5

06-21 16:24:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:04 -> SELECT player_id, player_name, goals, assists FROM vm_agg_season_player_info WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals DESC, assists DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:04 -> SELECT player_id, player_name, goals, assists FROM vm_agg_season_player_info WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals DESC, assists DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, player_name, team_name, season_id, dl_index FROM vm_agg_season_player_opta WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 5

06-21 16:24:04 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:04 -> SELECT player_id, player_name, team_name, season_id, dl_index FROM vm_agg_season_player_opta WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:04 -> SELECT player_id, player_name, team_name, season_id, dl_index FROM vm_agg_season_player_opta WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 5

Successful query
Data Shape: (5, 5)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 814198 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY max_speed DESC LIMIT 1

06-21 16:24:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:05 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 814198 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:05 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 814198 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (0, 2)
Running query: SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE position = 'GK' AND season_id = 814198 ORDER BY dl_index DESC LIMIT 1

06-21 16:24:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:05 -> SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE position = 'GK' AND season_id = 814198 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:05 -> SELECT player_id, player_name, team_name, dl_index FROM vm_agg_season_player_similarity WHERE position = 'GK' AND season_id = 814198 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (0, 4)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE season_id = 814198 AND position = 'GK' ORDER BY dl_index DESC LIMIT 1

06-21 16:24:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:05 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE season_id = 814198 AND position = 'GK' ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:05 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE season_id = 814198 AND position = 'GK' ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, team_id, season_id, player_name, SUM(goals) AS total_goals FROM vm_agg_season_player_all WHERE season_id = 816527 GROUP BY player_id, team_id, season_id, player_name ORDER BY total_goals DESC LIMIT 1

06-21 16:24:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:05 -> SELECT player_id, team_id, season_id, player_name, SUM(goals) AS total_goals FROM vm_agg_season_player_all WHERE season_id = 816527 GROUP BY player_id, team_id, season_id, player_name ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:05 -> SELECT player_id, team_id, season_id, player_name, SUM(goals) AS total_goals FROM vm_agg_season_player_all WHERE season_id = 816527 GROUP BY player_id, team_id, season_id, player_name ORDER BY total_goals DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...n_id, player_name, SUM(goals) AS total_goals FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, season_id, SUM(dl_index) AS total_score FROM public.vm_agg_season_player_similarity WHERE season_id = 816527 GROUP BY player_id, player_name, season_id ORDER BY total_score DESC LIMIT 1

06-21 16:24:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:05 -> SELECT player_id, player_name, season_id, SUM(dl_index) AS total_score FROM public.vm_agg_season_player_similarity WHERE season_id = 816527 GROUP BY player_id, player_name, season_id ORDER BY total_score DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:05 -> SELECT player_id, player_name, season_id, SUM(dl_index) AS total_score FROM public.vm_agg_season_player_similarity WHERE season_id = 816527 GROUP BY player_id, player_name, season_id ORDER BY total_score DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT passes_total FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527

06-21 16:24:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:05 -> SELECT passes_total FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:05 -> SELECT passes_total FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527
ERROR:root:Database error: column "passes_total" does not exist
LINE 1: SELECT passes_total FROM public.agg_season_player_pd WHERE p...
               ^

Failed query
Running query: SELECT passes_total FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527

06-21 16:24:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:05 -> SELECT passes_total FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:05 -> SELECT passes_total FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, player_name, max_speed, team_id FROM vm_agg_season_player_info WHERE country_id = 15 AND position = \'GK\' ORDER BY max_speed DESC LIMIT 1

06-21 16:24:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:05 -> SELECT player_id, player_name, max_speed, team_id FROM vm_agg_season_player_info WHERE country_id = 15 AND position = \'GK\' ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:05 -> SELECT player_id, player_name, max_speed, team_id FROM vm_agg_season_player_info WHERE country_id = 15 AND position = \'GK\' ORDER BY max_speed DESC LIMIT 1
ERROR:root:Database error: syntax error at or near "\"
LINE 1: ..._player_info WHERE country_id = 15 AND position = \'GK\' ORD...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, team_name, season_id, saves_90, clean_sheets_90, goals_conceded_90 FROM vm_agg_season_player_similarity WHERE country_id = 15 AND position = 'GK' ORDER BY clean_sheets_90 DESC, saves_90 DESC LIMIT 1

06-21 16:24:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:06 -> SELECT player_id, player_name, team_name, season_id, saves_90, clean_sheets_90, goals_conceded_90 FROM vm_agg_season_player_similarity WHERE country_id = 15 AND position = 'GK' ORDER BY clean_sheets_90 DESC, saves_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:06 -> SELECT player_id, player_name, team_name, season_id, saves_90, clean_sheets_90, goals_conceded_90 FROM vm_agg_season_player_similarity WHERE country_id = 15 AND position = 'GK' ORDER BY clean_sheets_90 DESC, saves_90 DESC LIMIT 1
ERROR:root:Database error: column "saves_90" does not exist
LINE 1: ...ECT player_id, player_name, team_name, season_id, saves_90, ...
                                                             ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.shots_90".

Failed query
Running query: SELECT player_id, player_name, team_name, goals_received, xg_saved_per_xg_faced_on_target, percent_saves, percent_saves_in_box, percent_saves_out_box FROM vm_agg_season_player_opta WHERE country_id = 15 AND player_position = \'GK\' ORDER BY percent_saves DESC LIMIT 1

06-21 16:24:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:08 -> SELECT player_id, player_name, team_name, goals_received, xg_saved_per_xg_faced_on_target, percent_saves, percent_saves_in_box, percent_saves_out_box FROM vm_agg_season_player_opta WHERE country_id = 15 AND player_position = \'GK\' ORDER BY percent_saves DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:08 -> SELECT player_id, player_name, team_name, goals_received, xg_saved_per_xg_faced_on_target, percent_saves, percent_saves_in_box, percent_saves_out_box FROM vm_agg_season_player_opta WHERE country_id = 15 AND player_position = \'GK\' ORDER BY percent_saves DESC LIMIT 1
ERROR:root:Database error: syntax error at or near "\"
LINE 1: ..._opta WHERE country_id = 15 AND player_position = \'GK\' ORD...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, team_name, season_id FROM vm_agg_season_player_similarity WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY scoring_contribution_90 DESC LIMIT 5

06-21 16:24:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:08 -> SELECT player_id, player_name, team_name, season_id FROM vm_agg_season_player_similarity WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY scoring_contribution_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:08 -> SELECT player_id, player_name, team_name, season_id FROM vm_agg_season_player_similarity WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY scoring_contribution_90 DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, player_name, team_name, season_id FROM vm_agg_season_player_opta WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY score_pd_float DESC LIMIT 5

06-21 16:24:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:08 -> SELECT player_id, player_name, team_name, season_id FROM vm_agg_season_player_opta WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY score_pd_float DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:08 -> SELECT player_id, player_name, team_name, season_id FROM vm_agg_season_player_opta WHERE team_name = 'Real Madrid' AND season_id = 816527 ORDER BY score_pd_float DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, player_name, goals_received FROM vm_agg_season_player_info WHERE country_id = 15 AND season_id = 816529 AND player_position = 'GK' ORDER BY goals_received ASC LIMIT 5

06-21 16:24:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:08 -> SELECT player_id, player_name, goals_received FROM vm_agg_season_player_info WHERE country_id = 15 AND season_id = 816529 AND player_position = 'GK' ORDER BY goals_received ASC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:08 -> SELECT player_id, player_name, goals_received FROM vm_agg_season_player_info WHERE country_id = 15 AND season_id = 816529 AND player_position = 'GK' ORDER BY goals_received ASC LIMIT 5

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, team_name, season_id, saves_90, clean_sheets_90, goals_conceded_90 FROM vm_agg_season_player_similarity WHERE country_id = 15 AND position = 'GK' ORDER BY clean_sheets_90 DESC LIMIT 5

06-21 16:24:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:08 -> SELECT player_id, player_name, team_name, season_id, saves_90, clean_sheets_90, goals_conceded_90 FROM vm_agg_season_player_similarity WHERE country_id = 15 AND position = 'GK' ORDER BY clean_sheets_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:08 -> SELECT player_id, player_name, team_name, season_id, saves_90, clean_sheets_90, goals_conceded_90 FROM vm_agg_season_player_similarity WHERE country_id = 15 AND position = 'GK' ORDER BY clean_sheets_90 DESC LIMIT 5
ERROR:root:Database error: column "saves_90" does not exist
LINE 1: ...ECT player_id, player_name, team_name, season_id, saves_90, ...
                                                             ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.shots_90".

Failed query
Running query: SELECT player_id, player_name, team_id, season_id, games_lost FROM vm_agg_season_player_all WHERE season_id = 15 AND player_country_code = 'PRT' ORDER BY games_lost ASC LIMIT 5

06-21 16:24:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:08 -> SELECT player_id, player_name, team_id, season_id, games_lost FROM vm_agg_season_player_all WHERE season_id = 15 AND player_country_code = 'PRT' ORDER BY games_lost ASC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:08 -> SELECT player_id, player_name, team_id, season_id, games_lost FROM vm_agg_season_player_all WHERE season_id = 15 AND player_country_code = 'PRT' ORDER BY games_lost ASC LIMIT 5
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ... player_name, team_id, season_id, games_lost FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, team_name, games_played, minutes_played, dl_index  FROM vm_agg_season_player_alert  WHERE season_id = (SELECT season_id FROM vm_agg_season_player_alert WHERE league_country_code = 'PT' LIMIT 1)  AND position = 'GK'  AND player_country_id = 15  ORDER BY dl_index DESC  LIMIT 5

06-21 16:24:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:08 -> SELECT player_id, player_name, team_name, games_played, minutes_played, dl_index  FROM vm_agg_season_player_alert  WHERE season_id = (SELECT season_id FROM vm_agg_season_player_alert WHERE league_country_code = 'PT' LIMIT 1)  AND position = 'GK'  AND player_country_id = 15  ORDER BY dl_index DESC  LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:08 -> SELECT player_id, player_name, team_name, games_played, minutes_played, dl_index  FROM vm_agg_season_player_alert  WHERE season_id = (SELECT season_id FROM vm_agg_season_player_alert WHERE league_country_code = 'PT' LIMIT 1)  AND position = 'GK'  AND player_country_id = 15  ORDER BY dl_index DESC  LIMIT 5

Successful query
Data Shape: (0, 6)
Running query: SELECT player_id, player_name, goals - xg AS goal_difference FROM vm_agg_season_player_opta WHERE season_id = 816530 AND player_position = 'FW' AND age < 25 ORDER BY goal_difference DESC LIMIT 5

06-21 16:24:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:17 -> SELECT player_id, player_name, goals - xg AS goal_difference FROM vm_agg_season_player_opta WHERE season_id = 816530 AND player_position = 'FW' AND age < 25 ORDER BY goal_difference DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:17 -> SELECT player_id, player_name, goals - xg AS goal_difference FROM vm_agg_season_player_opta WHERE season_id = 816530 AND player_position = 'FW' AND age < 25 ORDER BY goal_difference DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, player_name, team_id, season_id, goals_90, xg_90, goals_90 - xg_90 AS goals_xg_diff FROM vm_agg_season_player_similarity WHERE season_id = 816530 AND age < 25 AND position = 'FW' ORDER BY goals_xg_diff DESC LIMIT 5

06-21 16:24:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:17 -> SELECT player_id, player_name, team_id, season_id, goals_90, xg_90, goals_90 - xg_90 AS goals_xg_diff FROM vm_agg_season_player_similarity WHERE season_id = 816530 AND age < 25 AND position = 'FW' ORDER BY goals_xg_diff DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:17 -> SELECT player_id, player_name, team_id, season_id, goals_90, xg_90, goals_90 - xg_90 AS goals_xg_diff FROM vm_agg_season_player_similarity WHERE season_id = 816530 AND age < 25 AND position = 'FW' ORDER BY goals_xg_diff DESC LIMIT 5
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: ...ELECT player_id, player_name, team_id, season_id, goals_90, ...
                                                             ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id in (816527,816529,816530,816528,816531) ORDER BY max_speed DESC LIMIT 5

06-21 16:24:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:17 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id in (816527,816529,816530,816528,816531) ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:17 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id in (816527,816529,816530,816528,816531) ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id in (816527,816529,816530,816528,816531) ORDER BY max_speed DESC LIMIT 5

06-21 16:24:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:17 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id in (816527,816529,816530,816528,816531) ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:17 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id in (816527,816529,816530,816528,816531) ORDER BY max_speed DESC LIMIT 5
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_...
                                              ^

Failed query
Running query: SELECT player_id, team_id, season_id, age FROM vm_agg_season_player_all WHERE season_id in (816527,816529,816530,816528,816531) ORDER BY age DESC LIMIT 5

06-21 16:24:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:17 -> SELECT player_id, team_id, season_id, age FROM vm_agg_season_player_all WHERE season_id in (816527,816529,816530,816528,816531) ORDER BY age DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:17 -> SELECT player_id, team_id, season_id, age FROM vm_agg_season_player_all WHERE season_id in (816527,816529,816530,816528,816531) ORDER BY age DESC LIMIT 5
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, team_id, season_id, age FROM vm_agg_season...
                                                       ^

Failed query
Running query: SELECT player_id, max_speed FROM vm_agg_season_player_opta WHERE season_id in (816527,816529,816530,816528,816531) ORDER BY max_speed DESC LIMIT 5

06-21 16:24:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:17 -> SELECT player_id, max_speed FROM vm_agg_season_player_opta WHERE season_id in (816527,816529,816530,816528,816531) ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:17 -> SELECT player_id, max_speed FROM vm_agg_season_player_opta WHERE season_id in (816527,816529,816530,816528,816531) ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 5

06-21 16:24:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:17 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:17 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals IS NOT NULL ORDER BY goals DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE player_id IN (SELECT player_id FROM t_player WHERE team_id IN (SELECT team_id FROM t_team WHERE country_id = 'ESP' AND season_id = 816527)) AND season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 5

06-21 16:24:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:17 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE player_id IN (SELECT player_id FROM t_player WHERE team_id IN (SELECT team_id FROM t_team WHERE country_id = 'ESP' AND season_id = 816527)) AND season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:17 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE player_id IN (SELECT player_id FROM t_player WHERE team_id IN (SELECT team_id FROM t_team WHERE country_id = 'ESP' AND season_id = 816527)) AND season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 5
ERROR:root:Database error: invalid input syntax for integer: "ESP"
LINE 1: ...IN (SELECT team_id FROM t_team WHERE country_id = 'ESP' AND ...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, goals_per_shot, season_id FROM vm_agg_season_player_opta WHERE season_id = 816527 AND player_position = 'GK' ORDER BY goals_per_shot DESC LIMIT 1

06-21 16:24:18 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:18 -> SELECT player_id, player_name, goals_per_shot, season_id FROM vm_agg_season_player_opta WHERE season_id = 816527 AND player_position = 'GK' ORDER BY goals_per_shot DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:18 -> SELECT player_id, player_name, goals_per_shot, season_id FROM vm_agg_season_player_opta WHERE season_id = 816527 AND player_position = 'GK' ORDER BY goals_per_shot DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT player_id, player_name, team_name, position, saves_90, clean_sheets_90, goals_conceded_90, penalty_saves, penalty_misses, penalty_save_pct, season_id  FROM vm_agg_season_player_similarity  WHERE position = 'GK' AND season_id = 816527  ORDER BY clean_sheets_90 DESC, saves_90 DESC, penalty_save_pct DESC  LIMIT 1

06-21 16:24:18 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:18 -> SELECT player_id, player_name, team_name, position, saves_90, clean_sheets_90, goals_conceded_90, penalty_saves, penalty_misses, penalty_save_pct, season_id  FROM vm_agg_season_player_similarity  WHERE position = 'GK' AND season_id = 816527  ORDER BY clean_sheets_90 DESC, saves_90 DESC, penalty_save_pct DESC  LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:18 -> SELECT player_id, player_name, team_name, position, saves_90, clean_sheets_90, goals_conceded_90, penalty_saves, penalty_misses, penalty_save_pct, season_id  FROM vm_agg_season_player_similarity  WHERE position = 'GK' AND season_id = 816527  ORDER BY clean_sheets_90 DESC, saves_90 DESC, penalty_save_pct DESC  LIMIT 1
ERROR:root:Database error: column "saves_90" does not exist
LINE 1: ...LECT player_id, player_name, team_name, position, saves_90, ...
                                                             ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.shots_90".

Failed query
Running query: SELECT player_id, team_id, season_id, max_speed FROM public.vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:24:18 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:18 -> SELECT player_id, team_id, season_id, max_speed FROM public.vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:18 -> SELECT player_id, team_id, season_id, max_speed FROM public.vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, team_id, season_id, max_speed FROM public....
                                              ^

Failed query
Running query: SELECT player_name, max_speed FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:24:18 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:18 -> SELECT player_name, max_speed FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:18 -> SELECT player_name, max_speed FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_name, max_speed FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:24:18 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:18 -> SELECT player_name, max_speed FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:18 -> SELECT player_name, max_speed FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT assists FROM vm_agg_season_player_opta WHERE player_id = 1598188 AND season_id = 816527

06-21 16:24:20 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:20 -> SELECT assists FROM vm_agg_season_player_opta WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:20 -> SELECT assists FROM vm_agg_season_player_opta WHERE player_id = 1598188 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT * FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id = 1163220

06-21 16:24:20 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:20 -> SELECT * FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id = 1163220
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:20 -> SELECT * FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id = 1163220

Successful query
Data Shape: (4, 57)
Running query: SELECT match_id, season_id FROM public.vt_game_metric_player WHERE season_id = 816527 AND player_id = 1163220

06-21 16:24:20 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:20 -> SELECT match_id, season_id FROM public.vt_game_metric_player WHERE season_id = 816527 AND player_id = 1163220
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:20 -> SELECT match_id, season_id FROM public.vt_game_metric_player WHERE season_id = 816527 AND player_id = 1163220

Successful query
Data Shape: (20, 2)
Running query: SELECT match_id, match_date FROM public.vt_game_stat_player WHERE season_id = 816527 AND (home_team_id = 4265 OR away_team_id = 4265) AND player_id = 1163220

06-21 16:24:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:21 -> SELECT match_id, match_date FROM public.vt_game_stat_player WHERE season_id = 816527 AND (home_team_id = 4265 OR away_team_id = 4265) AND player_id = 1163220
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:21 -> SELECT match_id, match_date FROM public.vt_game_stat_player WHERE season_id = 816527 AND (home_team_id = 4265 OR away_team_id = 4265) AND player_id = 1163220
ERROR:root:Database error: column "home_team_id" does not exist
LINE 1: ...vt_game_stat_player WHERE season_id = 816527 AND (home_team_...
                                                             ^

Failed query
Running query: SELECT player_id, passes_total, dribbles_total FROM public.agg_season_player_pd WHERE season_id = 816527 AND team_id IN (4265, 4279) ORDER BY score_pd DESC LIMIT 1

06-21 16:24:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:21 -> SELECT player_id, passes_total, dribbles_total FROM public.agg_season_player_pd WHERE season_id = 816527 AND team_id IN (4265, 4279) ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:21 -> SELECT player_id, passes_total, dribbles_total FROM public.agg_season_player_pd WHERE season_id = 816527 AND team_id IN (4265, 4279) ORDER BY score_pd DESC LIMIT 1
ERROR:root:Database error: column "passes_total" does not exist
LINE 1: SELECT player_id, passes_total, dribbles_total FROM public.a...
                          ^

Failed query
Running query: SELECT player_id, goals_90, passes_90, dribbles_won_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals_90 DESC LIMIT 1

06-21 16:24:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:21 -> SELECT player_id, goals_90, passes_90, dribbles_won_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:21 -> SELECT player_id, goals_90, passes_90, dribbles_won_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals_90 DESC LIMIT 1
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: SELECT player_id, goals_90, passes_90, dribbles_won_90 FROM ...
                          ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT player_name, goals, passes_total, dribbles_total FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_label = 'La Liga' ORDER BY goals DESC LIMIT 1

06-21 16:24:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:21 -> SELECT player_name, goals, passes_total, dribbles_total FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_label = 'La Liga' ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:21 -> SELECT player_name, goals, passes_total, dribbles_total FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_label = 'La Liga' ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 4279 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:24:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:21 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 4279 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:21 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 4279 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE team_id = 4279 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:24:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:21 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE team_id = 4279 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:21 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE team_id = 4279 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT assists_90 FROM vm_agg_season_player_similarity WHERE player_id = 1598188 AND season_id = 816527

06-21 16:24:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:21 -> SELECT assists_90 FROM vm_agg_season_player_similarity WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:21 -> SELECT assists_90 FROM vm_agg_season_player_similarity WHERE player_id = 1598188 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT SUM(assist) FROM public.agg_season_player_pd WHERE player_id = 1598188 AND season_id = 816527

06-21 16:24:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:21 -> SELECT SUM(assist) FROM public.agg_season_player_pd WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:21 -> SELECT SUM(assist) FROM public.agg_season_player_pd WHERE player_id = 1598188 AND season_id = 816527
ERROR:root:Database error: column "assist" does not exist
LINE 1: SELECT SUM(assist) FROM public.agg_season_player_pd WHERE pl...
                   ^

Failed query
Running query: SELECT assists FROM vm_agg_season_player_info WHERE player_id = 1598188 AND season_id = 816527

06-21 16:24:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:21 -> SELECT assists FROM vm_agg_season_player_info WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:21 -> SELECT assists FROM vm_agg_season_player_info WHERE player_id = 1598188 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (1217052, 1248610, 1303293) ORDER BY max_speed DESC LIMIT 5

06-21 16:24:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:21 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (1217052, 1248610, 1303293) ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:21 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (1217052, 1248610, 1303293) ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, team_id, season_id, dribbles_won_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND position = 'FW' ORDER BY dribbles_won_90 DESC LIMIT 5

06-21 16:24:22 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:22 -> SELECT player_id, team_id, season_id, dribbles_won_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND position = 'FW' ORDER BY dribbles_won_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:22 -> SELECT player_id, team_id, season_id, dribbles_won_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND position = 'FW' ORDER BY dribbles_won_90 DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, player_name, dribbles_total FROM vm_agg_season_player_opta WHERE season_id = 816527 AND team_id IN (20074, 2, 4279) ORDER BY dribbles_total DESC LIMIT 5

06-21 16:24:22 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:22 -> SELECT player_id, player_name, dribbles_total FROM vm_agg_season_player_opta WHERE season_id = 816527 AND team_id IN (20074, 2, 4279) ORDER BY dribbles_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:22 -> SELECT player_id, player_name, dribbles_total FROM vm_agg_season_player_opta WHERE season_id = 816527 AND team_id IN (20074, 2, 4279) ORDER BY dribbles_total DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, gbe_score FROM vm_det_player_gbe WHERE player_id = 1776309 AND season_id = 816527

06-21 16:24:22 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:22 -> SELECT player_id, gbe_score FROM vm_det_player_gbe WHERE player_id = 1776309 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:22 -> SELECT player_id, gbe_score FROM vm_det_player_gbe WHERE player_id = 1776309 AND season_id = 816527
ERROR:root:Database error: relation "vm_det_player_gbe" does not exist
LINE 1: SELECT player_id, gbe_score FROM vm_det_player_gbe WHERE pla...
                                         ^

Failed query
Running query: SELECT dl_index FROM vm_agg_year_player_info WHERE player_name = 'Lamine Yamal' AND year = 2023

06-21 16:24:22 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:22 -> SELECT dl_index FROM vm_agg_year_player_info WHERE player_name = 'Lamine Yamal' AND year = 2023
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:22 -> SELECT dl_index FROM vm_agg_year_player_info WHERE player_name = 'Lamine Yamal' AND year = 2023

Successful query
Data Shape: (2, 1)
Running query: SELECT player_id, score_this_year, mins_played_this_year, mins_perc_this_year FROM vm_agg_year_player_loan WHERE player_id = 1776309 AND current_season_id = 816527

06-21 16:24:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:23 -> SELECT player_id, score_this_year, mins_played_this_year, mins_perc_this_year FROM vm_agg_year_player_loan WHERE player_id = 1776309 AND current_season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:23 -> SELECT player_id, score_this_year, mins_played_this_year, mins_perc_this_year FROM vm_agg_year_player_loan WHERE player_id = 1776309 AND current_season_id = 816527

Successful query
Data Shape: (1, 4)
Running query: SELECT match_id, xp FROM public.vt_game_stat_player WHERE player_id = 1257 AND season_id = 816527 ORDER BY xp DESC LIMIT 1

06-21 16:24:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:23 -> SELECT match_id, xp FROM public.vt_game_stat_player WHERE player_id = 1257 AND season_id = 816527 ORDER BY xp DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:23 -> SELECT match_id, xp FROM public.vt_game_stat_player WHERE player_id = 1257 AND season_id = 816527 ORDER BY xp DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT match_id, MAX(score_pd) as max_expected_goals FROM public.agg_game_player_pd WHERE player_id = 1257 AND season_id = 816527 GROUP BY match_id ORDER BY max_expected_goals DESC LIMIT 1

06-21 16:24:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:24 -> SELECT match_id, MAX(score_pd) as max_expected_goals FROM public.agg_game_player_pd WHERE player_id = 1257 AND season_id = 816527 GROUP BY match_id ORDER BY max_expected_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:24 -> SELECT match_id, MAX(score_pd) as max_expected_goals FROM public.agg_game_player_pd WHERE player_id = 1257 AND season_id = 816527 GROUP BY match_id ORDER BY max_expected_goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT match_id, xg FROM public.vt_game_metric_player WHERE player_id = 1257 AND season_id = 816527 ORDER BY xg DESC LIMIT 1

06-21 16:24:26 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:26 -> SELECT match_id, xg FROM public.vt_game_metric_player WHERE player_id = 1257 AND season_id = 816527 ORDER BY xg DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:26 -> SELECT match_id, xg FROM public.vt_game_metric_player WHERE player_id = 1257 AND season_id = 816527 ORDER BY xg DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY npg_90 DESC LIMIT 1

06-21 16:24:26 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:26 -> SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY npg_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:26 -> SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY npg_90 DESC LIMIT 1

Successful query
Data Shape: (1, 5)
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_country_name = 'Spain' ORDER BY goals DESC LIMIT 1

06-21 16:24:27 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:27 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_country_name = 'Spain' ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:27 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_country_name = 'Spain' ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, season_id, non_penalty_shots_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY non_penalty_shots_90 DESC LIMIT 1

06-21 16:24:27 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:27 -> SELECT player_id, player_name, season_id, non_penalty_shots_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY non_penalty_shots_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:27 -> SELECT player_id, player_name, season_id, non_penalty_shots_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY non_penalty_shots_90 DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT COUNT(*) FROM public.t_goal WHERE player_id = 1730571 AND team_id = 1946 AND season_id = 816529

06-21 16:24:27 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:27 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 1730571 AND team_id = 1946 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:27 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 1730571 AND team_id = 1946 AND season_id = 816529
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ... WHERE player_id = 1730571 AND team_id = 1946 AND season_id ...
                                                             ^

Failed query
Running query: SELECT * FROM public.agg_season_player_pd WHERE player_id = 1730571 AND team_id = 1946 AND season_id = 816529

06-21 16:24:27 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:27 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 1730571 AND team_id = 1946 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:27 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 1730571 AND team_id = 1946 AND season_id = 816529

Successful query
Data Shape: (0, 57)
Running query: SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 1730571 AND team_id = 81956 AND season_id = 816529

06-21 16:24:27 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:27 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 1730571 AND team_id = 81956 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:27 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 1730571 AND team_id = 81956 AND season_id = 816529

Successful query
Data Shape: (0, 1)
Running query: SELECT player_id, team_games_played FROM vm_agg_season_player_all WHERE player_id = 1163220 AND season_id = 816527

06-21 16:24:27 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:27 -> SELECT player_id, team_games_played FROM vm_agg_season_player_all WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:27 -> SELECT player_id, team_games_played FROM vm_agg_season_player_all WHERE player_id = 1163220 AND season_id = 816527
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, team_games_played FROM vm_agg_season_playe...
                                                 ^

Failed query
Running query: SELECT COUNT(DISTINCT match_id) FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527

06-21 16:24:27 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:27 -> SELECT COUNT(DISTINCT match_id) FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:27 -> SELECT COUNT(DISTINCT match_id) FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT match_id, xp FROM public.vt_game_stat_player WHERE player_id = 69936 AND season_id = 816527 ORDER BY xp DESC LIMIT 1

06-21 16:24:28 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:28 -> SELECT match_id, xp FROM public.vt_game_stat_player WHERE player_id = 69936 AND season_id = 816527 ORDER BY xp DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:28 -> SELECT match_id, xp FROM public.vt_game_stat_player WHERE player_id = 69936 AND season_id = 816527 ORDER BY xp DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT match_id, xg, season_id FROM public.vt_game_metric_player WHERE player_id = 69936 AND season_id = 816527 ORDER BY xg DESC LIMIT 1

06-21 16:24:28 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:28 -> SELECT match_id, xg, season_id FROM public.vt_game_metric_player WHERE player_id = 69936 AND season_id = 816527 ORDER BY xg DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:28 -> SELECT match_id, xg, season_id FROM public.vt_game_metric_player WHERE player_id = 69936 AND season_id = 816527 ORDER BY xg DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT match_id, score_pd, expected_goals FROM public.agg_game_player_pd WHERE player_id = 69936 AND season_id = 816527 ORDER BY expected_goals DESC LIMIT 1

06-21 16:24:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:29 -> SELECT match_id, score_pd, expected_goals FROM public.agg_game_player_pd WHERE player_id = 69936 AND season_id = 816527 ORDER BY expected_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:29 -> SELECT match_id, score_pd, expected_goals FROM public.agg_game_player_pd WHERE player_id = 69936 AND season_id = 816527 ORDER BY expected_goals DESC LIMIT 1
ERROR:root:Database error: column "expected_goals" does not exist
LINE 1: SELECT match_id, score_pd, expected_goals FROM public.agg_ga...
                                   ^

Failed query
Running query: SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:24:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:29 -> SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:29 -> SELECT player_id, max_speed FROM public.agg_game_player_pd WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, team_id, season_id, max_speed FROM public.vt_game_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:24:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:29 -> SELECT player_id, team_id, season_id, max_speed FROM public.vt_game_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:29 -> SELECT player_id, team_id, season_id, max_speed FROM public.vt_game_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, team_id, season_id, max_speed FROM public....
                                              ^

Failed query
Running query: SELECT match_id, season_id FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527

06-21 16:24:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:29 -> SELECT match_id, season_id FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:29 -> SELECT match_id, season_id FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527

Successful query
Data Shape: (20, 2)
Running query: SELECT player_id, assists FROM vm_agg_season_player_all WHERE player_id = 1598188 AND season_id = 816527

06-21 16:24:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:29 -> SELECT player_id, assists FROM vm_agg_season_player_all WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:29 -> SELECT player_id, assists FROM vm_agg_season_player_all WHERE player_id = 1598188 AND season_id = 816527
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, assists FROM vm_agg_season_player_all WHER...
                                       ^

Failed query
Running query: SELECT assists_90 FROM vm_agg_season_player_similarity WHERE player_name = 'Artem Dovbyk' AND team_name = 'Girona FC' AND season_id = 816527

06-21 16:24:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:29 -> SELECT assists_90 FROM vm_agg_season_player_similarity WHERE player_name = 'Artem Dovbyk' AND team_name = 'Girona FC' AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:29 -> SELECT assists_90 FROM vm_agg_season_player_similarity WHERE player_name = 'Artem Dovbyk' AND team_name = 'Girona FC' AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT assists FROM vm_agg_season_player_opta WHERE player_name = 'Artem Dovbyk' AND team_name = 'Girona FC' AND season_id = 816527

06-21 16:24:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:29 -> SELECT assists FROM vm_agg_season_player_opta WHERE player_name = 'Artem Dovbyk' AND team_name = 'Girona FC' AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:29 -> SELECT assists FROM vm_agg_season_player_opta WHERE player_name = 'Artem Dovbyk' AND team_name = 'Girona FC' AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:24:29 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:29 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:29 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE team_id = 4265 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:24:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:30 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE team_id = 4265 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:30 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE team_id = 4265 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT * FROM public.agg_season_player_pd WHERE player_id = 1730571 AND season_id IN (SELECT season_id FROM t_season WHERE EXTRACT(year FROM season_name) = 2023) AND score_pd > 0

06-21 16:24:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:32 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 1730571 AND season_id IN (SELECT season_id FROM t_season WHERE EXTRACT(year FROM season_name) = 2023) AND score_pd > 0
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:32 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 1730571 AND season_id IN (SELECT season_id FROM t_season WHERE EXTRACT(year FROM season_name) = 2023) AND score_pd > 0
ERROR:root:Database error: column "season_name" does not exist
LINE 1: ...T season_id FROM t_season WHERE EXTRACT(year FROM season_nam...
                                                             ^

Failed query
Running query: SELECT COUNT(*) FROM public.t_goal WHERE player_id = 1730571 AND season_id IN (SELECT season_id FROM t_season WHERE EXTRACT(year FROM start_date) = 2023)

06-21 16:24:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:32 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 1730571 AND season_id IN (SELECT season_id FROM t_season WHERE EXTRACT(year FROM start_date) = 2023)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:32 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 1730571 AND season_id IN (SELECT season_id FROM t_season WHERE EXTRACT(year FROM start_date) = 2023)
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ... FROM public.t_goal WHERE player_id = 1730571 AND season_id ...
                                                             ^

Failed query
Running query: SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 1730571 AND season_id IN (SELECT season_id FROM vm_agg_season_player_opta WHERE season_year = 2023) AND team_id = 81956

06-21 16:24:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:32 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 1730571 AND season_id IN (SELECT season_id FROM vm_agg_season_player_opta WHERE season_year = 2023) AND team_id = 81956
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:32 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 1730571 AND season_id IN (SELECT season_id FROM vm_agg_season_player_opta WHERE season_year = 2023) AND team_id = 81956

Successful query
Data Shape: (0, 1)
Running query: SELECT player_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:24:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:32 -> SELECT player_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:32 -> SELECT player_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, max_speed FROM vm_agg_season_player_simila...
                          ^

Failed query
Running query: SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816530 ORDER BY score_pd DESC LIMIT 1

06-21 16:24:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:32 -> SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816530 ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:32 -> SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816530 ORDER BY score_pd DESC LIMIT 1

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, player_name, team_id, season_id, non_penalty_shots_90 FROM vm_agg_season_player_similarity WHERE season_id = 816530 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 3) ORDER BY non_penalty_shots_90 DESC LIMIT 1

06-21 16:24:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:32 -> SELECT player_id, player_name, team_id, season_id, non_penalty_shots_90 FROM vm_agg_season_player_similarity WHERE season_id = 816530 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 3) ORDER BY non_penalty_shots_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:32 -> SELECT player_id, player_name, team_id, season_id, non_penalty_shots_90 FROM vm_agg_season_player_similarity WHERE season_id = 816530 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 3) ORDER BY non_penalty_shots_90 DESC LIMIT 1

Successful query
Data Shape: (1, 5)
Running query: SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816530 AND goals = (SELECT MAX(goals) FROM vm_agg_season_player_opta WHERE season_id = 816530)

06-21 16:24:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:32 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816530 AND goals = (SELECT MAX(goals) FROM vm_agg_season_player_opta WHERE season_id = 816530)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:32 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816530 AND goals = (SELECT MAX(goals) FROM vm_agg_season_player_opta WHERE season_id = 816530)

Successful query
Data Shape: (2, 2)
Running query: SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816527) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1

06-21 16:24:32 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:32 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816527) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:32 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816527) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...goal_id) AS goals_scored FROM public.t_goal WHERE season_id ...
                                                             ^

Failed query
Running query: SELECT COUNT(DISTINCT match_id) FROM public.t_goal WHERE player_id = 38708 AND match_id IN (SELECT match_id FROM public.t_match WHERE season_id = 816529)

06-21 16:24:33 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:33 -> SELECT COUNT(DISTINCT match_id) FROM public.t_goal WHERE player_id = 38708 AND match_id IN (SELECT match_id FROM public.t_match WHERE season_id = 816529)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:33 -> SELECT COUNT(DISTINCT match_id) FROM public.t_goal WHERE player_id = 38708 AND match_id IN (SELECT match_id FROM public.t_match WHERE season_id = 816529)

Successful query
Data Shape: (1, 1)
Running query: SELECT * FROM public.agg_season_player_pd WHERE player_id = 38708 AND season_id = 816529

06-21 16:24:33 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:33 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 38708 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:33 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 38708 AND season_id = 816529

Successful query
Data Shape: (3, 57)
Running query: SELECT player_id, team_id, season_id, goals, assists, yellow_cards, red_cards FROM vm_agg_season_player_info WHERE player_id = 38708 AND season_id = 816529

06-21 16:24:33 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:33 -> SELECT player_id, team_id, season_id, goals, assists, yellow_cards, red_cards FROM vm_agg_season_player_info WHERE player_id = 38708 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:33 -> SELECT player_id, team_id, season_id, goals, assists, yellow_cards, red_cards FROM vm_agg_season_player_info WHERE player_id = 38708 AND season_id = 816529

Successful query
Data Shape: (1, 7)
Running query: SELECT match_id, goals_scored, goals_against, possession FROM public.vm_game_stat_team WHERE team_id = 1 AND season_id = 816527 ORDER BY goals_scored DESC LIMIT 1

06-21 16:24:33 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:33 -> SELECT match_id, goals_scored, goals_against, possession FROM public.vm_game_stat_team WHERE team_id = 1 AND season_id = 816527 ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:33 -> SELECT match_id, goals_scored, goals_against, possession FROM public.vm_game_stat_team WHERE team_id = 1 AND season_id = 816527 ORDER BY goals_scored DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT match_id, xg FROM public.vt_game_metric_team WHERE team_id = 1 AND season_id = 816527 ORDER BY xg DESC LIMIT 1

06-21 16:24:33 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:33 -> SELECT match_id, xg FROM public.vt_game_metric_team WHERE team_id = 1 AND season_id = 816527 ORDER BY xg DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:33 -> SELECT match_id, xg FROM public.vt_game_metric_team WHERE team_id = 1 AND season_id = 816527 ORDER BY xg DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, COUNT(goal_id) as total_goals FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1

06-21 16:24:33 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:33 -> SELECT player_id, COUNT(goal_id) as total_goals FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:33 -> SELECT player_id, COUNT(goal_id) as total_goals FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...(goal_id) as total_goals FROM public.t_goal WHERE season_id ...
                                                             ^

Failed query
Running query: SELECT match_id, team_id, player_id, provider_id, season_id, score_pd FROM public.agg_game_player_pd WHERE player_id = 1163220 AND season_id = 816527 ORDER BY score_pd DESC LIMIT 1

06-21 16:24:34 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:34 -> SELECT match_id, team_id, player_id, provider_id, season_id, score_pd FROM public.agg_game_player_pd WHERE player_id = 1163220 AND season_id = 816527 ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:34 -> SELECT match_id, team_id, player_id, provider_id, season_id, score_pd FROM public.agg_game_player_pd WHERE player_id = 1163220 AND season_id = 816527 ORDER BY score_pd DESC LIMIT 1

Successful query
Data Shape: (1, 6)
Running query: SELECT match_id, MAX(carries) AS max_dribbles FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527 GROUP BY match_id ORDER BY max_dribbles DESC LIMIT 1

06-21 16:24:34 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:34 -> SELECT match_id, MAX(carries) AS max_dribbles FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527 GROUP BY match_id ORDER BY max_dribbles DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:34 -> SELECT match_id, MAX(carries) AS max_dribbles FROM public.vt_game_metric_player WHERE player_id = 1163220 AND season_id = 816527 GROUP BY match_id ORDER BY max_dribbles DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT match_id, dribbles_won FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY dribbles_won DESC LIMIT 1

06-21 16:24:34 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:34 -> SELECT match_id, dribbles_won FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY dribbles_won DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:34 -> SELECT match_id, dribbles_won FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY dribbles_won DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, max_speed FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:24:34 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:34 -> SELECT player_id, max_speed FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:34 -> SELECT player_id, max_speed FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, max_speed FROM vm_agg_season_player_simila...
                          ^

Failed query
Running query: SELECT player_id, player_name, max_speed FROM vm_agg_season_player_opta WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:24:34 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:34 -> SELECT player_id, player_name, max_speed FROM vm_agg_season_player_opta WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:34 -> SELECT player_id, player_name, max_speed FROM vm_agg_season_player_opta WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 5

06-21 16:24:34 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:34 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:34 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 20076 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 5

06-21 16:24:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:36 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 20076 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:36 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 20076 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 5

06-21 16:24:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:36 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:36 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT goals_90, assists_90 FROM vm_agg_season_player_similarity WHERE player_id = 38708 AND season_id = 816529

06-21 16:24:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:36 -> SELECT goals_90, assists_90 FROM vm_agg_season_player_similarity WHERE player_id = 38708 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:36 -> SELECT goals_90, assists_90 FROM vm_agg_season_player_similarity WHERE player_id = 38708 AND season_id = 816529
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: SELECT goals_90, assists_90 FROM vm_agg_season_player_simila...
               ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT goals, assists FROM vm_agg_season_player_opta WHERE player_id = 38708 AND season_id = 816529

06-21 16:24:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:37 -> SELECT goals, assists FROM vm_agg_season_player_opta WHERE player_id = 38708 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:37 -> SELECT goals, assists FROM vm_agg_season_player_opta WHERE player_id = 38708 AND season_id = 816529

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, SUM(goals) AS total_goals, SUM(assists) AS total_assists FROM public.agg_season_player_pd WHERE player_id = 38708 AND season_id = 816529

06-21 16:24:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:37 -> SELECT player_id, SUM(goals) AS total_goals, SUM(assists) AS total_assists FROM public.agg_season_player_pd WHERE player_id = 38708 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:37 -> SELECT player_id, SUM(goals) AS total_goals, SUM(assists) AS total_assists FROM public.agg_season_player_pd WHERE player_id = 38708 AND season_id = 816529
ERROR:root:Database error: column "goals" does not exist
LINE 1: SELECT player_id, SUM(goals) AS total_goals, SUM(assists) AS...
                              ^

Failed query
Running query: SELECT COUNT(*) FROM public.t_goal WHERE player_id = 38708 AND season_id = 816529

06-21 16:24:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:37 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 38708 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:37 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 38708 AND season_id = 816529
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...*) FROM public.t_goal WHERE player_id = 38708 AND season_id ...
                                                             ^

Failed query
Running query: SELECT goals FROM public.agg_season_player_pd WHERE player_id = 38708 AND season_id = 816529

06-21 16:24:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:37 -> SELECT goals FROM public.agg_season_player_pd WHERE player_id = 38708 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:37 -> SELECT goals FROM public.agg_season_player_pd WHERE player_id = 38708 AND season_id = 816529
ERROR:root:Database error: column "goals" does not exist
LINE 1: SELECT goals FROM public.agg_season_player_pd WHERE player_i...
               ^

Failed query
Running query: SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 38708 AND season_id = 816529

06-21 16:24:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:37 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 38708 AND season_id = 816529
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:37 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 38708 AND season_id = 816529

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND provider_id = 4265 ORDER BY score_pd DESC LIMIT 1

06-21 16:24:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:37 -> SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND provider_id = 4265 ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:37 -> SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND provider_id = 4265 ORDER BY score_pd DESC LIMIT 1

Successful query
Data Shape: (0, 1)
Running query: SELECT player_id, season_id, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals_90 DESC LIMIT 1

06-21 16:24:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:37 -> SELECT player_id, season_id, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:37 -> SELECT player_id, season_id, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals_90 DESC LIMIT 1
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: SELECT player_id, season_id, goals_90 FROM vm_agg_season_pla...
                                     ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816530 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 3) ORDER BY npg_90 DESC LIMIT 1

06-21 16:24:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:37 -> SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816530 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 3) ORDER BY npg_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:37 -> SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816530 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 3) ORDER BY npg_90 DESC LIMIT 1

Successful query
Data Shape: (1, 5)
Running query: SELECT COUNT(*) FROM public.vt_game_metric_player WHERE team_id = 20076 AND season_id = 816527 AND xg > 0

06-21 16:24:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:37 -> SELECT COUNT(*) FROM public.vt_game_metric_player WHERE team_id = 20076 AND season_id = 816527 AND xg > 0
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:37 -> SELECT COUNT(*) FROM public.vt_game_metric_player WHERE team_id = 20076 AND season_id = 816527 AND xg > 0

Successful query
Data Shape: (1, 1)
Running query: SELECT COUNT(*) FROM public.vt_game_metric_team WHERE team_id = 20076 AND result = 'W' AND season_id = 816527

06-21 16:24:38 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:38 -> SELECT COUNT(*) FROM public.vt_game_metric_team WHERE team_id = 20076 AND result = 'W' AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:38 -> SELECT COUNT(*) FROM public.vt_game_metric_team WHERE team_id = 20076 AND result = 'W' AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT COUNT(*) FROM public.vt_game_stat_player WHERE team_id = 20076 AND team_score > 0 AND season_id = 816527

06-21 16:24:38 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:38 -> SELECT COUNT(*) FROM public.vt_game_stat_player WHERE team_id = 20076 AND team_score > 0 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:38 -> SELECT COUNT(*) FROM public.vt_game_stat_player WHERE team_id = 20076 AND team_score > 0 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT gbe_score FROM vm_det_player_gbe WHERE player_id = 1598188 AND season_id = 816527

06-21 16:24:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:41 -> SELECT gbe_score FROM vm_det_player_gbe WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:41 -> SELECT gbe_score FROM vm_det_player_gbe WHERE player_id = 1598188 AND season_id = 816527
ERROR:root:Database error: relation "vm_det_player_gbe" does not exist
LINE 1: SELECT gbe_score FROM vm_det_player_gbe WHERE player_id = 15...
                              ^

Failed query
Running query: SELECT global_score FROM vm_det_player_placer WHERE player_id = 1598188 AND team_id = 20076

06-21 16:24:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:42 -> SELECT global_score FROM vm_det_player_placer WHERE player_id = 1598188 AND team_id = 20076
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:42 -> SELECT global_score FROM vm_det_player_placer WHERE player_id = 1598188 AND team_id = 20076
ERROR:root:Database error: relation "vm_det_player_placer" does not exist
LINE 1: SELECT global_score FROM vm_det_player_placer WHERE player_i...
                                 ^

Failed query
Running query: SELECT player_name, dl_index FROM vm_agg_year_player_loan WHERE player_name = 'Artem Dovbyk' AND current_season_id = 816527

06-21 16:24:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:42 -> SELECT player_name, dl_index FROM vm_agg_year_player_loan WHERE player_name = 'Artem Dovbyk' AND current_season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:42 -> SELECT player_name, dl_index FROM vm_agg_year_player_loan WHERE player_name = 'Artem Dovbyk' AND current_season_id = 816527
ERROR:root:Database error: column "dl_index" does not exist
LINE 1: SELECT player_name, dl_index FROM vm_agg_year_player_loan WH...
                            ^

Failed query
Running query: SELECT team_id, goals, goals_against, diff_goals FROM public.t_season_team_rank WHERE season_id = 816527 ORDER BY diff_goals DESC LIMIT 1

06-21 16:24:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:42 -> SELECT team_id, goals, goals_against, diff_goals FROM public.t_season_team_rank WHERE season_id = 816527 ORDER BY diff_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:42 -> SELECT team_id, goals, goals_against, diff_goals FROM public.t_season_team_rank WHERE season_id = 816527 ORDER BY diff_goals DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT team_id, wins, draws, loses FROM public.t_season_team_rank WHERE season_id = 816527 ORDER BY wins DESC, draws DESC LIMIT 1

06-21 16:24:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:42 -> SELECT team_id, wins, draws, loses FROM public.t_season_team_rank WHERE season_id = 816527 ORDER BY wins DESC, draws DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:42 -> SELECT team_id, wins, draws, loses FROM public.t_season_team_rank WHERE season_id = 816527 ORDER BY wins DESC, draws DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT player_id, (xg - goals) AS xg_goals_diff FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY xg_goals_diff DESC LIMIT 1

06-21 16:24:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:42 -> SELECT player_id, (xg - goals) AS xg_goals_diff FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY xg_goals_diff DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:42 -> SELECT player_id, (xg - goals) AS xg_goals_diff FROM public.vt_season_metric_player WHERE season_id = 816527 ORDER BY xg_goals_diff DESC LIMIT 1
ERROR:root:Database error: column "goals" does not exist
LINE 1: SELECT player_id, (xg - goals) AS xg_goals_diff FROM public....
                                ^

Failed query
Running query: SELECT player_id, (xg - non_penalty_goals) AS xg_goals_diff FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY xg_goals_diff DESC LIMIT 1

06-21 16:24:44 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:44 -> SELECT player_id, (xg - non_penalty_goals) AS xg_goals_diff FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY xg_goals_diff DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:44 -> SELECT player_id, (xg - non_penalty_goals) AS xg_goals_diff FROM public.vt_season_info_player WHERE season_id = 816527 ORDER BY xg_goals_diff DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, xg, xa, xg_chain, xg_build_up, individual_pressure, ball_progression FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg DESC LIMIT 3

06-21 16:24:44 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:44 -> SELECT player_id, xg, xa, xg_chain, xg_build_up, individual_pressure, ball_progression FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg DESC LIMIT 3
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:44 -> SELECT player_id, xg, xa, xg_chain, xg_build_up, individual_pressure, ball_progression FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg DESC LIMIT 3

Successful query
Data Shape: (3, 7)
Running query: SELECT player_id, top_speed FROM public.vt_season_stat_player WHERE team_id = 4265 AND season_id = 816527 AND top_speed IS NOT NULL ORDER BY top_speed DESC LIMIT 1

06-21 16:24:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:45 -> SELECT player_id, top_speed FROM public.vt_season_stat_player WHERE team_id = 4265 AND season_id = 816527 AND top_speed IS NOT NULL ORDER BY top_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:45 -> SELECT player_id, top_speed FROM public.vt_season_stat_player WHERE team_id = 4265 AND season_id = 816527 AND top_speed IS NOT NULL ORDER BY top_speed DESC LIMIT 1
ERROR:root:Database error: column "top_speed" does not exist
LINE 1: SELECT player_id, top_speed FROM public.vt_season_stat_playe...
                          ^

Failed query
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 4265 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

06-21 16:24:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:45 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 4265 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:45 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 4265 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, max_speed FROM public.vt_season_metric_player WHERE team_id = 4265 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

06-21 16:24:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:45 -> SELECT player_id, max_speed FROM public.vt_season_metric_player WHERE team_id = 4265 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:45 -> SELECT player_id, max_speed FROM public.vt_season_metric_player WHERE team_id = 4265 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, max_speed FROM public.vt_season_metric_pla...
                          ^

Failed query
Running query: SELECT player_id, xg FROM public.vt_season_metric_player WHERE player_id = 1163220 AND season_id = 816527

06-21 16:24:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:45 -> SELECT player_id, xg FROM public.vt_season_metric_player WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:45 -> SELECT player_id, xg FROM public.vt_season_metric_player WHERE player_id = 1163220 AND season_id = 816527

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, xg FROM public.vt_season_metric_player WHERE player_id = 20 AND season_id = 816527

06-21 16:24:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:45 -> SELECT player_id, xg FROM public.vt_season_metric_player WHERE player_id = 20 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:45 -> SELECT player_id, xg FROM public.vt_season_metric_player WHERE player_id = 20 AND season_id = 816527

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, xg FROM public.vt_season_metric_player WHERE player_id = 69936 AND season_id = 816527

06-21 16:24:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:45 -> SELECT player_id, xg FROM public.vt_season_metric_player WHERE player_id = 69936 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:45 -> SELECT player_id, xg FROM public.vt_season_metric_player WHERE player_id = 69936 AND season_id = 816527

Successful query
Data Shape: (1, 2)
Running query: SELECT match_id, player_id, shots_total FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY shots_total DESC LIMIT 5

06-21 16:24:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:45 -> SELECT match_id, player_id, shots_total FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY shots_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:45 -> SELECT match_id, player_id, shots_total FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 ORDER BY shots_total DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT match_id, player_id, shots_total FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 AND shots_total IS NOT NULL ORDER BY shots_total DESC LIMIT 5

06-21 16:24:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:45 -> SELECT match_id, player_id, shots_total FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 AND shots_total IS NOT NULL ORDER BY shots_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:45 -> SELECT match_id, player_id, shots_total FROM public.vt_game_stat_player WHERE player_id = 1163220 AND season_id = 816527 AND shots_total IS NOT NULL ORDER BY shots_total DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, xg, xa, xg_chain, xg_build_up FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg DESC LIMIT 5

06-21 16:24:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:45 -> SELECT player_id, xg, xa, xg_chain, xg_build_up FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:45 -> SELECT player_id, xg, xa, xg_chain, xg_build_up FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg DESC LIMIT 5

Successful query
Data Shape: (5, 5)
Running query: SELECT player_id, xg, xa, xg_chain, xg_build_up FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg_chain DESC LIMIT 5

06-21 16:24:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:46 -> SELECT player_id, xg, xa, xg_chain, xg_build_up FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg_chain DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:46 -> SELECT player_id, xg, xa, xg_chain, xg_build_up FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 ORDER BY xg_chain DESC LIMIT 5

Successful query
Data Shape: (5, 5)
Running query: SELECT player_id, non_penalty_goals FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY non_penalty_goals DESC LIMIT 1

06-21 16:24:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:46 -> SELECT player_id, non_penalty_goals FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY non_penalty_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:46 -> SELECT player_id, non_penalty_goals FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY non_penalty_goals DESC LIMIT 1
ERROR:root:Database error: column "non_penalty_goals" does not exist
LINE 1: SELECT player_id, non_penalty_goals FROM public.vt_season_op...
                          ^

Failed query
Running query: SELECT player_id, max_speed FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

06-21 16:24:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:46 -> SELECT player_id, max_speed FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:46 -> SELECT player_id, max_speed FROM public.vt_season_metric_player WHERE team_id = 4265 AND season_id = 816527 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, max_speed FROM public.vt_season_metric_pla...
                          ^

Failed query
Running query: SELECT player_id, tackles_total, team_id, season_id FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY tackles_total DESC LIMIT 5

06-21 16:24:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:46 -> SELECT player_id, tackles_total, team_id, season_id FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY tackles_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:46 -> SELECT player_id, tackles_total, team_id, season_id FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY tackles_total DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, tackles_total, team_id, season_id FROM public.vt_season_opta_player WHERE season_id = 816527 AND tackles_total IS NOT NULL ORDER BY tackles_total DESC LIMIT 5

06-21 16:24:47 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:47 -> SELECT player_id, tackles_total, team_id, season_id FROM public.vt_season_opta_player WHERE season_id = 816527 AND tackles_total IS NOT NULL ORDER BY tackles_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:47 -> SELECT player_id, tackles_total, team_id, season_id FROM public.vt_season_opta_player WHERE season_id = 816527 AND tackles_total IS NOT NULL ORDER BY tackles_total DESC LIMIT 5
ERROR:root:Database error: column "tackles_total" does not exist
LINE 1: SELECT player_id, tackles_total, team_id, season_id FROM pub...
                          ^

Failed query
Running query: SELECT player_id, speed FROM public.vt_player_stats WHERE team_id = 4265 AND speed IS NOT NULL ORDER BY speed DESC LIMIT 1

06-21 16:24:47 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:47 -> SELECT player_id, speed FROM public.vt_player_stats WHERE team_id = 4265 AND speed IS NOT NULL ORDER BY speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:47 -> SELECT player_id, speed FROM public.vt_player_stats WHERE team_id = 4265 AND speed IS NOT NULL ORDER BY speed DESC LIMIT 1
ERROR:root:Database error: relation "public.vt_player_stats" does not exist
LINE 1: SELECT player_id, speed FROM public.vt_player_stats WHERE te...
                                     ^

Failed query
Running query: SELECT player_id, speed FROM public.vt_match_player_stats WHERE team_id = 4265 AND speed IS NOT NULL ORDER BY speed DESC LIMIT 1

06-21 16:24:47 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:47 -> SELECT player_id, speed FROM public.vt_match_player_stats WHERE team_id = 4265 AND speed IS NOT NULL ORDER BY speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:47 -> SELECT player_id, speed FROM public.vt_match_player_stats WHERE team_id = 4265 AND speed IS NOT NULL ORDER BY speed DESC LIMIT 1
ERROR:root:Database error: relation "public.vt_match_player_stats" does not exist
LINE 1: SELECT player_id, speed FROM public.vt_match_player_stats WH...
                                     ^

Failed query
Running query: SELECT match_id, team_id, passes FROM public.vm_game_stat_team WHERE season_id = 816527 ORDER BY passes DESC LIMIT 5

06-21 16:24:47 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:47 -> SELECT match_id, team_id, passes FROM public.vm_game_stat_team WHERE season_id = 816527 ORDER BY passes DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:47 -> SELECT match_id, team_id, passes FROM public.vm_game_stat_team WHERE season_id = 816527 ORDER BY passes DESC LIMIT 5
ERROR:root:Database error: column "passes" does not exist
LINE 1: SELECT match_id, team_id, passes FROM public.vm_game_stat_te...
                                  ^

Failed query
Running query: SELECT match_id, team_id, passes FROM public.vm_game_stat_team WHERE season_id = 816527 AND passes IS NOT NULL ORDER BY passes DESC LIMIT 5

06-21 16:24:47 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:47 -> SELECT match_id, team_id, passes FROM public.vm_game_stat_team WHERE season_id = 816527 AND passes IS NOT NULL ORDER BY passes DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:47 -> SELECT match_id, team_id, passes FROM public.vm_game_stat_team WHERE season_id = 816527 AND passes IS NOT NULL ORDER BY passes DESC LIMIT 5
ERROR:root:Database error: column "passes" does not exist
LINE 1: SELECT match_id, team_id, passes FROM public.vm_game_stat_te...
                                  ^

Failed query
Running query: SELECT player_id, dribbles_final_third FROM public.vt_season_stat_player WHERE season_id = 816527 AND dribbles_final_third IS NOT NULL ORDER BY dribbles_final_third DESC LIMIT 5

06-21 16:24:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:49 -> SELECT player_id, dribbles_final_third FROM public.vt_season_stat_player WHERE season_id = 816527 AND dribbles_final_third IS NOT NULL ORDER BY dribbles_final_third DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:49 -> SELECT player_id, dribbles_final_third FROM public.vt_season_stat_player WHERE season_id = 816527 AND dribbles_final_third IS NOT NULL ORDER BY dribbles_final_third DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, dribbles_final_third FROM public.vt_season_opta_player WHERE season_id = 816527 AND dribbles_final_third IS NOT NULL ORDER BY dribbles_final_third DESC LIMIT 5

06-21 16:24:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:50 -> SELECT player_id, dribbles_final_third FROM public.vt_season_opta_player WHERE season_id = 816527 AND dribbles_final_third IS NOT NULL ORDER BY dribbles_final_third DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:50 -> SELECT player_id, dribbles_final_third FROM public.vt_season_opta_player WHERE season_id = 816527 AND dribbles_final_third IS NOT NULL ORDER BY dribbles_final_third DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, name, position FROM public.t_player WHERE team_id = 4279 ORDER BY market_value DESC LIMIT 1

06-21 16:24:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:50 -> SELECT player_id, name, position FROM public.t_player WHERE team_id = 4279 ORDER BY market_value DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:50 -> SELECT player_id, name, position FROM public.t_player WHERE team_id = 4279 ORDER BY market_value DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT name_eng FROM public.v_player_profile WHERE player_profile_id = (SELECT player_id FROM public.t_player WHERE team_id = 4279 ORDER BY market_value DESC LIMIT 1) AND name_eng IS NOT NULL

06-21 16:24:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:50 -> SELECT name_eng FROM public.v_player_profile WHERE player_profile_id = (SELECT player_id FROM public.t_player WHERE team_id = 4279 ORDER BY market_value DESC LIMIT 1) AND name_eng IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:50 -> SELECT name_eng FROM public.v_player_profile WHERE player_profile_id = (SELECT player_id FROM public.t_player WHERE team_id = 4279 ORDER BY market_value DESC LIMIT 1) AND name_eng IS NOT NULL

Successful query
Data Shape: (0, 1)
Running query: SELECT passes_total_final_third FROM public.vt_season_stat_player WHERE player_id = 1163220 AND season_id = 816527 AND passes_total_final_third IS NOT NULL

06-21 16:24:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:50 -> SELECT passes_total_final_third FROM public.vt_season_stat_player WHERE player_id = 1163220 AND season_id = 816527 AND passes_total_final_third IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:50 -> SELECT passes_total_final_third FROM public.vt_season_stat_player WHERE player_id = 1163220 AND season_id = 816527 AND passes_total_final_third IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT team_id, transfer_balance FROM public.agg_season_team_info WHERE team_id = 4266 AND season_id = 816527

06-21 16:24:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:50 -> SELECT team_id, transfer_balance FROM public.agg_season_team_info WHERE team_id = 4266 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:50 -> SELECT team_id, transfer_balance FROM public.agg_season_team_info WHERE team_id = 4266 AND season_id = 816527

Successful query
Data Shape: (1, 2)
Running query: SELECT team_id, xg, xa FROM public.vt_season_metric_team WHERE team_id = 4266 AND season_id = 816527

06-21 16:24:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:50 -> SELECT team_id, xg, xa FROM public.vt_season_metric_team WHERE team_id = 4266 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:50 -> SELECT team_id, xg, xa FROM public.vt_season_metric_team WHERE team_id = 4266 AND season_id = 816527

Successful query
Data Shape: (3, 3)
Running query: SELECT team_id, current_elo FROM pro.agg_history_season_team_sos WHERE team_id = 4266 AND season_id = 816527

06-21 16:24:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:50 -> SELECT team_id, current_elo FROM pro.agg_history_season_team_sos WHERE team_id = 4266 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:50 -> SELECT team_id, current_elo FROM pro.agg_history_season_team_sos WHERE team_id = 4266 AND season_id = 816527

Successful query
Data Shape: (0, 2)
Running query: SELECT first_name, last_name, position, dob, height, weight, nationality_confirmed FROM public.t_player WHERE player_id = 1163220

06-21 16:24:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:50 -> SELECT first_name, last_name, position, dob, height, weight, nationality_confirmed FROM public.t_player WHERE player_id = 1163220
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:50 -> SELECT first_name, last_name, position, dob, height, weight, nationality_confirmed FROM public.t_player WHERE player_id = 1163220

Successful query
Data Shape: (1, 7)
Running query: SELECT name_eng, name_esp, des_eng, des_esp FROM public.v_player_profile WHERE player_profile_id = 1163220

06-21 16:24:51 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:51 -> SELECT name_eng, name_esp, des_eng, des_esp FROM public.v_player_profile WHERE player_profile_id = 1163220
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:51 -> SELECT name_eng, name_esp, des_eng, des_esp FROM public.v_player_profile WHERE player_profile_id = 1163220

Successful query
Data Shape: (0, 4)
Running query: SELECT match_id, home_team_id, away_team_id, passes_total FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY passes_total DESC LIMIT 5

06-21 16:24:51 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:51 -> SELECT match_id, home_team_id, away_team_id, passes_total FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY passes_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:51 -> SELECT match_id, home_team_id, away_team_id, passes_total FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY passes_total DESC LIMIT 5
ERROR:root:Database error: column "match_id" does not exist
LINE 1: SELECT match_id, home_team_id, away_team_id, passes_total FR...
               ^

Failed query
Running query: SELECT match_id, home_team_id, away_team_id, passes_accurate FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY passes_accurate DESC LIMIT 5

06-21 16:24:51 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:51 -> SELECT match_id, home_team_id, away_team_id, passes_accurate FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY passes_accurate DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:51 -> SELECT match_id, home_team_id, away_team_id, passes_accurate FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY passes_accurate DESC LIMIT 5
ERROR:root:Database error: column "match_id" does not exist
LINE 1: SELECT match_id, home_team_id, away_team_id, passes_accurate...
               ^

Failed query
Running query: SELECT player_id, tackles_successful_with_possession, player_id, team_id, season_id FROM public.vt_season_stat_player WHERE season_id = 816529 AND tackles_successful_with_possession IS NOT NULL ORDER BY tackles_successful_with_possession DESC LIMIT 1

06-21 16:24:51 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:51 -> SELECT player_id, tackles_successful_with_possession, player_id, team_id, season_id FROM public.vt_season_stat_player WHERE season_id = 816529 AND tackles_successful_with_possession IS NOT NULL ORDER BY tackles_successful_with_possession DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:51 -> SELECT player_id, tackles_successful_with_possession, player_id, team_id, season_id FROM public.vt_season_stat_player WHERE season_id = 816529 AND tackles_successful_with_possession IS NOT NULL ORDER BY tackles_successful_with_possession DESC LIMIT 1

Successful query
Data Shape: (1, 5)
Running query: SELECT COUNT(*) FROM public.t_goal WHERE player_id = 80992

06-21 16:24:51 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:51 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 80992
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:51 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 80992

Successful query
Data Shape: (1, 1)
Running query: SELECT * FROM public.agg_season_player_pd WHERE player_id = 80992

06-21 16:24:51 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:51 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 80992
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:51 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 80992

Successful query
Data Shape: (9, 57)
Running query: SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 80992

06-21 16:24:52 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:52 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 80992
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:52 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 80992

Successful query
Data Shape: (20, 1)
Running query: SELECT SUM(goals) FROM public.vt_game_stat_player WHERE player_id = 80992 AND season_id = 817326

06-21 16:24:52 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:52 -> SELECT SUM(goals) FROM public.vt_game_stat_player WHERE player_id = 80992 AND season_id = 817326
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:52 -> SELECT SUM(goals) FROM public.vt_game_stat_player WHERE player_id = 80992 AND season_id = 817326

Successful query
Data Shape: (1, 1)
Running query: SELECT SUM(goals_xg_0 + goals_xg_01 + goals_xg_025 + goals_xg_04) AS total_goals_scored FROM public.vt_game_metric_player WHERE player_id = 80992 AND season_id IN (817326, 817267)

06-21 16:24:52 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:52 -> SELECT SUM(goals_xg_0 + goals_xg_01 + goals_xg_025 + goals_xg_04) AS total_goals_scored FROM public.vt_game_metric_player WHERE player_id = 80992 AND season_id IN (817326, 817267)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:52 -> SELECT SUM(goals_xg_0 + goals_xg_01 + goals_xg_025 + goals_xg_04) AS total_goals_scored FROM public.vt_game_metric_player WHERE player_id = 80992 AND season_id IN (817326, 817267)

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals_90 DESC LIMIT 1

06-21 16:24:53 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:53 -> SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:53 -> SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals_90 DESC LIMIT 1
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: SELECT player_id, player_name, goals_90 FROM vm_agg_season_p...
                                       ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT player_id, COUNT(*) as goals FROM public.t_goal WHERE team_id = 4265 AND season_id = 816527 GROUP BY player_id ORDER BY goals DESC LIMIT 1

06-21 16:24:53 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:53 -> SELECT player_id, COUNT(*) as goals FROM public.t_goal WHERE team_id = 4265 AND season_id = 816527 GROUP BY player_id ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:53 -> SELECT player_id, COUNT(*) as goals FROM public.t_goal WHERE team_id = 4265 AND season_id = 816527 GROUP BY player_id ORDER BY goals DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...goals FROM public.t_goal WHERE team_id = 4265 AND season_id ...
                                                             ^

Failed query
Running query: SELECT player_id FROM public.agg_season_player_pd WHERE team_id = 4265 AND season_id = 816527 ORDER BY score_pd DESC LIMIT 1

06-21 16:24:55 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:55 -> SELECT player_id FROM public.agg_season_player_pd WHERE team_id = 4265 AND season_id = 816527 ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:55 -> SELECT player_id FROM public.agg_season_player_pd WHERE team_id = 4265 AND season_id = 816527 ORDER BY score_pd DESC LIMIT 1

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:24:55 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:55 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:55 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, goals FROM vm_agg_season_player_opta WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:24:55 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:55 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:55 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE team_id = 4265 AND season_id = 816527 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, score_pd FROM public.agg_season_player_pd WHERE season_id = 816530 ORDER BY score_pd DESC LIMIT 1

06-21 16:24:55 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:55 -> SELECT player_id, score_pd FROM public.agg_season_player_pd WHERE season_id = 816530 ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:55 -> SELECT player_id, score_pd FROM public.agg_season_player_pd WHERE season_id = 816530 ORDER BY score_pd DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816530 ORDER BY goals DESC LIMIT 1

06-21 16:24:55 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:55 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816530 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:55 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816530 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_name, SUM(dl_index) AS total_goals FROM vm_agg_season_player_similarity WHERE season_id = 816530 GROUP BY player_name ORDER BY total_goals DESC LIMIT 1

06-21 16:24:55 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:55 -> SELECT player_name, SUM(dl_index) AS total_goals FROM vm_agg_season_player_similarity WHERE season_id = 816530 GROUP BY player_name ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:55 -> SELECT player_name, SUM(dl_index) AS total_goals FROM vm_agg_season_player_similarity WHERE season_id = 816530 GROUP BY player_name ORDER BY total_goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, COUNT(goal_id) as goals FROM public.t_goal WHERE season_id = 816530 GROUP BY player_id ORDER BY goals DESC LIMIT 1

06-21 16:24:56 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:56 -> SELECT player_id, COUNT(goal_id) as goals FROM public.t_goal WHERE season_id = 816530 GROUP BY player_id ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:56 -> SELECT player_id, COUNT(goal_id) as goals FROM public.t_goal WHERE season_id = 816530 GROUP BY player_id ORDER BY goals DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ... COUNT(goal_id) as goals FROM public.t_goal WHERE season_id ...
                                                             ^

Failed query
Running query: SELECT player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816530 ORDER BY goals DESC LIMIT 1

06-21 16:24:56 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:56 -> SELECT player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816530 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:56 -> SELECT player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816530 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT assists FROM vm_agg_season_player_info WHERE season_year = 2023 AND player_name = 'he'

06-21 16:24:56 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:56 -> SELECT assists FROM vm_agg_season_player_info WHERE season_year = 2023 AND player_name = 'he'
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:56 -> SELECT assists FROM vm_agg_season_player_info WHERE season_year = 2023 AND player_name = 'he'

Successful query
Data Shape: (0, 1)
Running query: SELECT assists_90 FROM vm_agg_season_player_similarity WHERE season_id IN (SELECT season_id FROM t_season WHERE year = 2023) AND player_id = (SELECT player_id FROM vm_agg_season_player_similarity ORDER BY dl_index DESC LIMIT 1)

06-21 16:24:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:57 -> SELECT assists_90 FROM vm_agg_season_player_similarity WHERE season_id IN (SELECT season_id FROM t_season WHERE year = 2023) AND player_id = (SELECT player_id FROM vm_agg_season_player_similarity ORDER BY dl_index DESC LIMIT 1)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:57 -> SELECT assists_90 FROM vm_agg_season_player_similarity WHERE season_id IN (SELECT season_id FROM t_season WHERE year = 2023) AND player_id = (SELECT player_id FROM vm_agg_season_player_similarity ORDER BY dl_index DESC LIMIT 1)

Successful query
Data Shape: (0, 1)
Running query: SELECT assists FROM vm_agg_season_player_opta WHERE season_id IN (SELECT season_id FROM vm_agg_season_player_opta WHERE season_year = 2023) AND player_name = 'he'

06-21 16:24:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:24:57 -> SELECT assists FROM vm_agg_season_player_opta WHERE season_id IN (SELECT season_id FROM vm_agg_season_player_opta WHERE season_year = 2023) AND player_name = 'he'
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:24:57 -> SELECT assists FROM vm_agg_season_player_opta WHERE season_id IN (SELECT season_id FROM vm_agg_season_player_opta WHERE season_year = 2023) AND player_name = 'he'

Successful query
Data Shape: (0, 1)
Running query: SELECT player_id, COUNT(*) AS assists FROM vm_agg_season_player_all WHERE season_year = 2023 AND season_id IN (SELECT season_id FROM vm_agg_season_player_all WHERE season_year = 2023) AND player_id = [player_id] AND assists > 0 GROUP BY player_id

06-21 16:25:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:37 -> SELECT player_id, COUNT(*) AS assists FROM vm_agg_season_player_all WHERE season_year = 2023 AND season_id IN (SELECT season_id FROM vm_agg_season_player_all WHERE season_year = 2023) AND player_id = [player_id] AND assists > 0 GROUP BY player_id
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:37 -> SELECT player_id, COUNT(*) AS assists FROM vm_agg_season_player_all WHERE season_year = 2023 AND season_id IN (SELECT season_id FROM vm_agg_season_player_all WHERE season_year = 2023) AND player_id = [player_id] AND assists > 0 GROUP BY player_id
ERROR:root:Database error: syntax error at or near "["
LINE 1: ...yer_all WHERE season_year = 2023) AND player_id = [player_id...
                                                             ^

Failed query
Running query: SELECT * FROM public.agg_season_player_pd WHERE season_id IN (SELECT season_id FROM public.agg_season_player_pd WHERE season_id IN (SELECT season_id FROM public.agg_season_player_pd WHERE season_id = 2023) AND player_id = (SELECT player_id FROM public.agg_season_player_pd WHERE season_id IN (SELECT season_id FROM public.agg_season_player_pd WHERE season_id = 2023) ORDER BY dl_index DESC LIMIT 1))

06-21 16:25:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:37 -> SELECT * FROM public.agg_season_player_pd WHERE season_id IN (SELECT season_id FROM public.agg_season_player_pd WHERE season_id IN (SELECT season_id FROM public.agg_season_player_pd WHERE season_id = 2023) AND player_id = (SELECT player_id FROM public.agg_season_player_pd WHERE season_id IN (SELECT season_id FROM public.agg_season_player_pd WHERE season_id = 2023) ORDER BY dl_index DESC LIMIT 1))
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:37 -> SELECT * FROM public.agg_season_player_pd WHERE season_id IN (SELECT season_id FROM public.agg_season_player_pd WHERE season_id IN (SELECT season_id FROM public.agg_season_player_pd WHERE season_id = 2023) AND player_id = (SELECT player_id FROM public.agg_season_player_pd WHERE season_id IN (SELECT season_id FROM public.agg_season_player_pd WHERE season_id = 2023) ORDER BY dl_index DESC LIMIT 1))
ERROR:root:Database error: column "dl_index" does not exist
LINE 1: ...season_player_pd WHERE season_id = 2023) ORDER BY dl_index D...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY npg_90 DESC LIMIT 1

06-21 16:25:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:37 -> SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY npg_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:37 -> SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND season_id = 816527 ORDER BY npg_90 DESC LIMIT 1

Successful query
Data Shape: (1, 5)
Running query: SELECT player_id, player_name, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND npg_90 = (SELECT MAX(npg_90) FROM vm_agg_season_player_similarity WHERE season_id = 816527)

06-21 16:25:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:37 -> SELECT player_id, player_name, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND npg_90 = (SELECT MAX(npg_90) FROM vm_agg_season_player_similarity WHERE season_id = 816527)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:37 -> SELECT player_id, player_name, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND npg_90 = (SELECT MAX(npg_90) FROM vm_agg_season_player_similarity WHERE season_id = 816527)

Successful query
Data Shape: (1, 4)
Running query: SELECT player_id, COUNT(goal_id) as goals_scored FROM public.t_goal WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816527) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1

06-21 16:25:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:37 -> SELECT player_id, COUNT(goal_id) as goals_scored FROM public.t_goal WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816527) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:37 -> SELECT player_id, COUNT(goal_id) as goals_scored FROM public.t_goal WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816527) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...goal_id) as goals_scored FROM public.t_goal WHERE season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE season_id = 816530 AND player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816530) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1

06-21 16:25:37 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:37 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE season_id = 816530 AND player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816530) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:37 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE season_id = 816530 AND player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816530) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...goal_id) AS goals_scored FROM public.t_goal WHERE season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816530 AND league_name = 'Bundesliga' ORDER BY goals DESC LIMIT 1

06-21 16:25:38 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:38 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816530 AND league_name = 'Bundesliga' ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:38 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816530 AND league_name = 'Bundesliga' ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (0, 3)
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816530 AND goals = (SELECT MAX(goals) FROM vm_agg_season_player_opta WHERE season_id = 816530)

06-21 16:25:38 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:38 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816530 AND goals = (SELECT MAX(goals) FROM vm_agg_season_player_opta WHERE season_id = 816530)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:38 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816530 AND goals = (SELECT MAX(goals) FROM vm_agg_season_player_opta WHERE season_id = 816530)

Successful query
Data Shape: (2, 3)
Running query: SELECT player_id, SUM(score_pd) AS total_goals FROM public.agg_season_player_pd WHERE season_id = 816529 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1

06-21 16:25:38 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:38 -> SELECT player_id, SUM(score_pd) AS total_goals FROM public.agg_season_player_pd WHERE season_id = 816529 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:38 -> SELECT player_id, SUM(score_pd) AS total_goals FROM public.agg_season_player_pd WHERE season_id = 816529 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816529 AND league_name = 'ENG I 2023' ORDER BY goals DESC LIMIT 1

06-21 16:25:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:40 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816529 AND league_name = 'ENG I 2023' ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:40 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816529 AND league_name = 'ENG I 2023' ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816529 AND npg_90 = (SELECT MAX(npg_90) FROM vm_agg_season_player_similarity WHERE season_id = 816529)

06-21 16:25:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:40 -> SELECT player_id, player_name, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816529 AND npg_90 = (SELECT MAX(npg_90) FROM vm_agg_season_player_similarity WHERE season_id = 816529)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:40 -> SELECT player_id, player_name, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816529 AND npg_90 = (SELECT MAX(npg_90) FROM vm_agg_season_player_similarity WHERE season_id = 816529)

Successful query
Data Shape: (1, 4)
Running query: SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816529) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1

06-21 16:25:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:40 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816529) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:40 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816529) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...goal_id) AS goals_scored FROM public.t_goal WHERE season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816529 AND goals = (SELECT MAX(goals) FROM vm_agg_season_player_opta WHERE season_id = 816529)

06-21 16:25:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:40 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816529 AND goals = (SELECT MAX(goals) FROM vm_agg_season_player_opta WHERE season_id = 816529)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:40 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816529 AND goals = (SELECT MAX(goals) FROM vm_agg_season_player_opta WHERE season_id = 816529)

Successful query
Data Shape: (2, 2)
Running query: SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND npg_90 = (SELECT MAX(npg_90) FROM vm_agg_season_player_similarity WHERE season_id = 816527)

06-21 16:25:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:40 -> SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND npg_90 = (SELECT MAX(npg_90) FROM vm_agg_season_player_similarity WHERE season_id = 816527)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:40 -> SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND npg_90 = (SELECT MAX(npg_90) FROM vm_agg_season_player_similarity WHERE season_id = 816527)

Successful query
Data Shape: (1, 5)
Running query: SELECT player_id, player_name, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY mins_played DESC LIMIT 1

06-21 16:25:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:41 -> SELECT player_id, player_name, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY mins_played DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:41 -> SELECT player_id, player_name, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY mins_played DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...T player_id, player_name, team_id, season_id FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT team_id FROM public.vm_fac_games_player WHERE player_id = 80992 AND season_id = 817326

06-21 16:25:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:41 -> SELECT team_id FROM public.vm_fac_games_player WHERE player_id = 80992 AND season_id = 817326
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:41 -> SELECT team_id FROM public.vm_fac_games_player WHERE player_id = 80992 AND season_id = 817326
ERROR:root:Database error: relation "public.vm_fac_games_player" does not exist
LINE 1: SELECT team_id FROM public.vm_fac_games_player WHERE player_...
                            ^

Failed query
Running query: SELECT team_id FROM vm_det_player_gbe WHERE player_id = 80992 AND season_id = 817326

06-21 16:25:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:41 -> SELECT team_id FROM vm_det_player_gbe WHERE player_id = 80992 AND season_id = 817326
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:41 -> SELECT team_id FROM vm_det_player_gbe WHERE player_id = 80992 AND season_id = 817326
ERROR:root:Database error: relation "vm_det_player_gbe" does not exist
LINE 1: SELECT team_id FROM vm_det_player_gbe WHERE player_id = 8099...
                            ^

Failed query
Running query: SELECT team_id FROM vm_det_player_placer WHERE player_id = 80992 AND season_id = 817326

06-21 16:25:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:41 -> SELECT team_id FROM vm_det_player_placer WHERE player_id = 80992 AND season_id = 817326
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:41 -> SELECT team_id FROM vm_det_player_placer WHERE player_id = 80992 AND season_id = 817326
ERROR:root:Database error: relation "vm_det_player_placer" does not exist
LINE 1: SELECT team_id FROM vm_det_player_placer WHERE player_id = 8...
                            ^

Failed query
Running query: SELECT team_id FROM public.vt_game_metric_player WHERE player_id = 80992 AND season_id = 817326

06-21 16:25:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:41 -> SELECT team_id FROM public.vt_game_metric_player WHERE player_id = 80992 AND season_id = 817326
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:41 -> SELECT team_id FROM public.vt_game_metric_player WHERE player_id = 80992 AND season_id = 817326

Successful query
Data Shape: (12, 1)
Running query: SELECT team_id FROM public.vt_game_stat_player WHERE player_id = 80992 AND season_id = 817326

06-21 16:25:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:41 -> SELECT team_id FROM public.vt_game_stat_player WHERE player_id = 80992 AND season_id = 817326
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:41 -> SELECT team_id FROM public.vt_game_stat_player WHERE player_id = 80992 AND season_id = 817326

Successful query
Data Shape: (12, 1)
Running query: SELECT assists_90 FROM vm_agg_season_player_similarity WHERE player_id = 45067 AND season_id = 816530

06-21 16:25:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:41 -> SELECT assists_90 FROM vm_agg_season_player_similarity WHERE player_id = 45067 AND season_id = 816530
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:41 -> SELECT assists_90 FROM vm_agg_season_player_similarity WHERE player_id = 45067 AND season_id = 816530

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, assists FROM vm_agg_season_player_all WHERE player_id = 45067 AND season_id = 816530

06-21 16:25:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:41 -> SELECT player_id, assists FROM vm_agg_season_player_all WHERE player_id = 45067 AND season_id = 816530
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:41 -> SELECT player_id, assists FROM vm_agg_season_player_all WHERE player_id = 45067 AND season_id = 816530
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, assists FROM vm_agg_season_player_all WHER...
                                       ^

Failed query
Running query: SELECT assists FROM public.agg_season_player_pd WHERE player_id = 45067 AND season_id = 816530

06-21 16:25:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:41 -> SELECT assists FROM public.agg_season_player_pd WHERE player_id = 45067 AND season_id = 816530
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:41 -> SELECT assists FROM public.agg_season_player_pd WHERE player_id = 45067 AND season_id = 816530
ERROR:root:Database error: column "assists" does not exist
LINE 1: SELECT assists FROM public.agg_season_player_pd WHERE player...
               ^

Failed query
Running query: SELECT assists FROM vm_agg_season_player_info WHERE player_id = 45067 AND season_id = 816530

06-21 16:25:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:42 -> SELECT assists FROM vm_agg_season_player_info WHERE player_id = 45067 AND season_id = 816530
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:42 -> SELECT assists FROM vm_agg_season_player_info WHERE player_id = 45067 AND season_id = 816530

Successful query
Data Shape: (1, 1)
Running query: SELECT assists FROM vm_agg_season_player_opta WHERE player_id = 45067 AND season_id = 816530

06-21 16:25:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:42 -> SELECT assists FROM vm_agg_season_player_opta WHERE player_id = 45067 AND season_id = 816530
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:42 -> SELECT assists FROM vm_agg_season_player_opta WHERE player_id = 45067 AND season_id = 816530

Successful query
Data Shape: (1, 1)
Running query: SELECT * FROM vm_det_player_placer WHERE player_id = 1296920

06-21 16:25:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:42 -> SELECT * FROM vm_det_player_placer WHERE player_id = 1296920
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:42 -> SELECT * FROM vm_det_player_placer WHERE player_id = 1296920
ERROR:root:Database error: relation "vm_det_player_placer" does not exist
LINE 1: SELECT * FROM vm_det_player_placer WHERE player_id = 1296920
                      ^

Failed query
Running query: SELECT height FROM vm_agg_year_player_loan WHERE player_name = "Jude Bellingham" AND season_id = 816527

06-21 16:25:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:42 -> SELECT height FROM vm_agg_year_player_loan WHERE player_name = "Jude Bellingham" AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:42 -> SELECT height FROM vm_agg_year_player_loan WHERE player_name = "Jude Bellingham" AND season_id = 816527
ERROR:root:Database error: column "Jude Bellingham" does not exist
LINE 1: ... FROM vm_agg_year_player_loan WHERE player_name = "Jude Bell...
                                                             ^

Failed query
Running query: SELECT player_id FROM vm_det_player_gbe WHERE player_id = 1296920 AND season_id = 816527

06-21 16:25:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:42 -> SELECT player_id FROM vm_det_player_gbe WHERE player_id = 1296920 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:42 -> SELECT player_id FROM vm_det_player_gbe WHERE player_id = 1296920 AND season_id = 816527
ERROR:root:Database error: relation "vm_det_player_gbe" does not exist
LINE 1: SELECT player_id FROM vm_det_player_gbe WHERE player_id = 12...
                              ^

Failed query
Running query: SELECT max_speed FROM public.agg_season_player_pd WHERE player_id = 1296920 AND season_id = 816527

06-21 16:25:42 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:42 -> SELECT max_speed FROM public.agg_season_player_pd WHERE player_id = 1296920 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:42 -> SELECT max_speed FROM public.agg_season_player_pd WHERE player_id = 1296920 AND season_id = 816527

Successful query
Data Shape: (4, 1)
Running query: SELECT player_id, passes_distance FROM public.vt_game_stat_player WHERE player_id = 1296920 AND season_id = 816527

06-21 16:25:44 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:44 -> SELECT player_id, passes_distance FROM public.vt_game_stat_player WHERE player_id = 1296920 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:44 -> SELECT player_id, passes_distance FROM public.vt_game_stat_player WHERE player_id = 1296920 AND season_id = 816527

Successful query
Data Shape: (20, 2)
Running query: SELECT player_id, SUM(goals) AS total_goals FROM vm_agg_season_player_all WHERE team_id = 4265 AND season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1

06-21 16:25:44 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:44 -> SELECT player_id, SUM(goals) AS total_goals FROM vm_agg_season_player_all WHERE team_id = 4265 AND season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:44 -> SELECT player_id, SUM(goals) AS total_goals FROM vm_agg_season_player_all WHERE team_id = 4265 AND season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, SUM(goals) AS total_goals FROM vm_agg_seas...
                                                         ^

Failed query
Running query: SELECT player_id, COUNT(*) as goals FROM public.t_goal WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816527) GROUP BY player_id ORDER BY goals DESC LIMIT 1

06-21 16:25:44 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:44 -> SELECT player_id, COUNT(*) as goals FROM public.t_goal WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816527) GROUP BY player_id ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:44 -> SELECT player_id, COUNT(*) as goals FROM public.t_goal WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM public.t_goal WHERE season_id = 816527) GROUP BY player_id ORDER BY goals DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...er_id, COUNT(*) as goals FROM public.t_goal WHERE season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, team_id, season_id, player_name FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY mins_played DESC LIMIT 1

06-21 16:25:44 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:44 -> SELECT player_id, team_id, season_id, player_name FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY mins_played DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:44 -> SELECT player_id, team_id, season_id, player_name FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY mins_played DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...T player_id, team_id, season_id, player_name FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, SUM(goals_scored) as total_goals FROM vm_agg_season_player_all WHERE season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1

06-21 16:25:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:45 -> SELECT player_id, SUM(goals_scored) as total_goals FROM vm_agg_season_player_all WHERE season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:45 -> SELECT player_id, SUM(goals_scored) as total_goals FROM vm_agg_season_player_all WHERE season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ... player_id, SUM(goals_scored) as total_goals FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id IN (2022, 2023) ORDER BY goals DESC LIMIT 1

06-21 16:25:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:45 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id IN (2022, 2023) ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:45 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id IN (2022, 2023) ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (0, 3)
Running query: SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id IN (2022, 2023) ORDER BY dl_index DESC LIMIT 1

06-21 16:25:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:45 -> SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id IN (2022, 2023) ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:45 -> SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id IN (2022, 2023) ORDER BY dl_index DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, team_id, season_id FROM vm_agg_season_play...
                                                  ^

Failed query
Running query: SELECT player_id, score_pd FROM public.agg_season_player_pd WHERE season_id IN (2022, 2023) ORDER BY score_pd DESC LIMIT 1

06-21 16:25:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:45 -> SELECT player_id, score_pd FROM public.agg_season_player_pd WHERE season_id IN (2022, 2023) ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:45 -> SELECT player_id, score_pd FROM public.agg_season_player_pd WHERE season_id IN (2022, 2023) ORDER BY score_pd DESC LIMIT 1

Successful query
Data Shape: (0, 2)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE season_id IN (2022, 2023) ORDER BY dl_index DESC LIMIT 1

06-21 16:25:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:45 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE season_id IN (2022, 2023) ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:45 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE season_id IN (2022, 2023) ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (0, 3)
Running query: SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id IN (2022, 2023) ORDER BY goals DESC LIMIT 1

06-21 16:25:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:45 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id IN (2022, 2023) ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:45 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id IN (2022, 2023) ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (0, 2)
Running query: SELECT COUNT(*) FROM public.t_goal WHERE player_id = 80992 AND season_id = 817326

06-21 16:25:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:45 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 80992 AND season_id = 817326
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:45 -> SELECT COUNT(*) FROM public.t_goal WHERE player_id = 80992 AND season_id = 817326
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...*) FROM public.t_goal WHERE player_id = 80992 AND season_id ...
                                                             ^

Failed query
Running query: SELECT goals_90 FROM vm_agg_season_player_similarity WHERE player_id = 80992 AND season_id = 817326

06-21 16:25:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:45 -> SELECT goals_90 FROM vm_agg_season_player_similarity WHERE player_id = 80992 AND season_id = 817326
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:45 -> SELECT goals_90 FROM vm_agg_season_player_similarity WHERE player_id = 80992 AND season_id = 817326
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: SELECT goals_90 FROM vm_agg_season_player_similarity WHERE p...
               ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT goals FROM vm_agg_season_player_info WHERE player_id = 80992 AND season_id = 817326

06-21 16:25:45 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:45 -> SELECT goals FROM vm_agg_season_player_info WHERE player_id = 80992 AND season_id = 817326
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:45 -> SELECT goals FROM vm_agg_season_player_info WHERE player_id = 80992 AND season_id = 817326

Successful query
Data Shape: (1, 1)
Running query: SELECT * FROM public.agg_season_player_pd WHERE player_id = 80992 AND season_id = 817326

06-21 16:25:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:46 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 80992 AND season_id = 817326
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:46 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 80992 AND season_id = 817326

Successful query
Data Shape: (0, 57)
Running query: SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 80992 AND season_id = 817326

06-21 16:25:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:46 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 80992 AND season_id = 817326
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:46 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 80992 AND season_id = 817326

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, COUNT(*) as goals FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals DESC

06-21 16:25:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:46 -> SELECT player_id, COUNT(*) as goals FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals DESC
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:46 -> SELECT player_id, COUNT(*) as goals FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals DESC
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...er_id, COUNT(*) as goals FROM public.t_goal WHERE season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, SUM(goals_scored) AS total_goals FROM vm_agg_season_player_all WHERE season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1

06-21 16:25:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:46 -> SELECT player_id, SUM(goals_scored) AS total_goals FROM vm_agg_season_player_all WHERE season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:46 -> SELECT player_id, SUM(goals_scored) AS total_goals FROM vm_agg_season_player_all WHERE season_id = 816527 GROUP BY player_id ORDER BY total_goals DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ... player_id, SUM(goals_scored) AS total_goals FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_name, SUM(dl_index) as total_goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 GROUP BY player_name ORDER BY total_goals DESC LIMIT 1

06-21 16:25:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:46 -> SELECT player_name, SUM(dl_index) as total_goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 GROUP BY player_name ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:46 -> SELECT player_name, SUM(dl_index) as total_goals FROM vm_agg_season_player_similarity WHERE season_id = 816527 GROUP BY player_name ORDER BY total_goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT team_id FROM vm_det_player_placer WHERE player_id = 45067

06-21 16:25:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:46 -> SELECT team_id FROM vm_det_player_placer WHERE player_id = 45067
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:46 -> SELECT team_id FROM vm_det_player_placer WHERE player_id = 45067
ERROR:root:Database error: relation "vm_det_player_placer" does not exist
LINE 1: SELECT team_id FROM vm_det_player_placer WHERE player_id = 4...
                            ^

Failed query
Running query: SELECT team_id FROM vm_det_player_gbe WHERE player_id = 45067 AND season_id = 816530

06-21 16:25:46 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:46 -> SELECT team_id FROM vm_det_player_gbe WHERE player_id = 45067 AND season_id = 816530
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:46 -> SELECT team_id FROM vm_det_player_gbe WHERE player_id = 45067 AND season_id = 816530
ERROR:root:Database error: relation "vm_det_player_gbe" does not exist
LINE 1: SELECT team_id FROM vm_det_player_gbe WHERE player_id = 4506...
                            ^

Failed query
Running query: SELECT team_id FROM public.vm_fac_games_player WHERE player_id = 45067 AND season_id = 816530

06-21 16:25:48 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:48 -> SELECT team_id FROM public.vm_fac_games_player WHERE player_id = 45067 AND season_id = 816530
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:48 -> SELECT team_id FROM public.vm_fac_games_player WHERE player_id = 45067 AND season_id = 816530
ERROR:root:Database error: relation "public.vm_fac_games_player" does not exist
LINE 1: SELECT team_id FROM public.vm_fac_games_player WHERE player_...
                            ^

Failed query
Running query: SELECT team_id FROM vm_agg_season_player_all WHERE player_id = 45067 AND season_id = 816530

06-21 16:25:48 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:48 -> SELECT team_id FROM vm_agg_season_player_all WHERE player_id = 45067 AND season_id = 816530
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:48 -> SELECT team_id FROM vm_agg_season_player_all WHERE player_id = 45067 AND season_id = 816530
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT team_id FROM vm_agg_season_player_all WHERE player_id...
                            ^

Failed query
Running query: SELECT current_team_name FROM vm_agg_season_player_info WHERE player_id = 45067 AND season_id = 816530

06-21 16:25:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:49 -> SELECT current_team_name FROM vm_agg_season_player_info WHERE player_id = 45067 AND season_id = 816530
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:49 -> SELECT current_team_name FROM vm_agg_season_player_info WHERE player_id = 45067 AND season_id = 816530

Successful query
Data Shape: (1, 1)
Running query: SELECT * FROM public.agg_season_player_pd WHERE player_id = 1296920 AND team_id = 4265 AND season_id = 816527

06-21 16:25:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:49 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 1296920 AND team_id = 4265 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:49 -> SELECT * FROM public.agg_season_player_pd WHERE player_id = 1296920 AND team_id = 4265 AND season_id = 816527

Successful query
Data Shape: (4, 57)
Running query: SELECT tm_contract_option FROM vm_agg_season_player_info WHERE player_id = 1296920 AND current_team_id = 4265 AND season_id = 816527

06-21 16:25:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:49 -> SELECT tm_contract_option FROM vm_agg_season_player_info WHERE player_id = 1296920 AND current_team_id = 4265 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:49 -> SELECT tm_contract_option FROM vm_agg_season_player_info WHERE player_id = 1296920 AND current_team_id = 4265 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT contract_score, contract_strength FROM vm_det_player_placer WHERE player_id = 1296920 AND team_id = 4265 AND season_id = 816527

06-21 16:25:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:49 -> SELECT contract_score, contract_strength FROM vm_det_player_placer WHERE player_id = 1296920 AND team_id = 4265 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:49 -> SELECT contract_score, contract_strength FROM vm_det_player_placer WHERE player_id = 1296920 AND team_id = 4265 AND season_id = 816527
ERROR:root:Database error: relation "vm_det_player_placer" does not exist
LINE 1: SELECT contract_score, contract_strength FROM vm_det_player_...
                                                      ^

Failed query
Running query: SELECT * FROM vm_agg_year_player_info WHERE player_name = 'Jude Bellingham' AND team_id = 4265 AND year = 2023

06-21 16:25:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:49 -> SELECT * FROM vm_agg_year_player_info WHERE player_name = 'Jude Bellingham' AND team_id = 4265 AND year = 2023
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:49 -> SELECT * FROM vm_agg_year_player_info WHERE player_name = 'Jude Bellingham' AND team_id = 4265 AND year = 2023
ERROR:root:Database error: column "team_id" does not exist
LINE 1: ...er_info WHERE player_name = 'Jude Bellingham' AND team_id = ...
                                                             ^

Failed query
Running query: SELECT tm_end_contract_date FROM vm_agg_year_player_loan WHERE player_name = 'Jude Bellingham' AND player_team_id = 4265 AND tm_end_contract_date IS NOT NULL AND current_season_id = 816527

06-21 16:25:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:49 -> SELECT tm_end_contract_date FROM vm_agg_year_player_loan WHERE player_name = 'Jude Bellingham' AND player_team_id = 4265 AND tm_end_contract_date IS NOT NULL AND current_season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:49 -> SELECT tm_end_contract_date FROM vm_agg_year_player_loan WHERE player_name = 'Jude Bellingham' AND player_team_id = 4265 AND tm_end_contract_date IS NOT NULL AND current_season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, team_id, season_id, season_year FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY team_games_played DESC, team_mins_played DESC, mins_played DESC LIMIT 1

06-21 16:25:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:49 -> SELECT player_id, team_id, season_id, season_year FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY team_games_played DESC, team_mins_played DESC, mins_played DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:49 -> SELECT player_id, team_id, season_id, season_year FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY team_games_played DESC, team_mins_played DESC, mins_played DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...T player_id, team_id, season_id, season_year FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT goals FROM public.vt_game_stat_player WHERE player_id = 80992 AND season_id = 817326

06-21 16:25:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:49 -> SELECT goals FROM public.vt_game_stat_player WHERE player_id = 80992 AND season_id = 817326
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:49 -> SELECT goals FROM public.vt_game_stat_player WHERE player_id = 80992 AND season_id = 817326

Successful query
Data Shape: (12, 1)
Running query: SELECT SUM(goals_xg_0 + goals_xg_01 + goals_xg_025 + goals_xg_04) AS total_goals_scored FROM public.vt_game_metric_player WHERE player_id = 80992 AND season_id = 817326

06-21 16:25:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:49 -> SELECT SUM(goals_xg_0 + goals_xg_01 + goals_xg_025 + goals_xg_04) AS total_goals_scored FROM public.vt_game_metric_player WHERE player_id = 80992 AND season_id = 817326
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:49 -> SELECT SUM(goals_xg_0 + goals_xg_01 + goals_xg_025 + goals_xg_04) AS total_goals_scored FROM public.vt_game_metric_player WHERE player_id = 80992 AND season_id = 817326

Successful query
Data Shape: (1, 1)
Running query: SELECT * FROM vm_agg_year_player_loan WHERE player_id = 80992 AND current_season_id = 817326

06-21 16:25:49 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:49 -> SELECT * FROM vm_agg_year_player_loan WHERE player_id = 80992 AND current_season_id = 817326
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:49 -> SELECT * FROM vm_agg_year_player_loan WHERE player_id = 80992 AND current_season_id = 817326

Successful query
Data Shape: (1, 43)
Running query: SELECT goals_xg_0, goals_xg_01, goals_xg_025, goals_xg_04 FROM public.vt_game_metric_player WHERE player_id = 80992 AND season_id = 817326

06-21 16:25:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:50 -> SELECT goals_xg_0, goals_xg_01, goals_xg_025, goals_xg_04 FROM public.vt_game_metric_player WHERE player_id = 80992 AND season_id = 817326
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:50 -> SELECT goals_xg_0, goals_xg_01, goals_xg_025, goals_xg_04 FROM public.vt_game_metric_player WHERE player_id = 80992 AND season_id = 817326

Successful query
Data Shape: (12, 4)
Running query: SELECT * FROM vm_det_player_placer WHERE player_id = 80992

06-21 16:25:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:50 -> SELECT * FROM vm_det_player_placer WHERE player_id = 80992
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:50 -> SELECT * FROM vm_det_player_placer WHERE player_id = 80992
ERROR:root:Database error: relation "vm_det_player_placer" does not exist
LINE 1: SELECT * FROM vm_det_player_placer WHERE player_id = 80992
                      ^

Failed query
Running query: SELECT positions_played FROM public.vm_fac_games_player WHERE player_id = 80992 AND team_id = 69410 AND season_id = 817326

06-21 16:25:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:50 -> SELECT positions_played FROM public.vm_fac_games_player WHERE player_id = 80992 AND team_id = 69410 AND season_id = 817326
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:50 -> SELECT positions_played FROM public.vm_fac_games_player WHERE player_id = 80992 AND team_id = 69410 AND season_id = 817326
ERROR:root:Database error: relation "public.vm_fac_games_player" does not exist
LINE 1: SELECT positions_played FROM public.vm_fac_games_player WHER...
                                     ^

Failed query
Running query: SELECT height FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527

06-21 16:25:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:50 -> SELECT height FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:50 -> SELECT height FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT height FROM vm_agg_year_player_loan WHERE player_id = 1163220 AND season_id = 816527

06-21 16:25:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:50 -> SELECT height FROM vm_agg_year_player_loan WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:50 -> SELECT height FROM vm_agg_year_player_loan WHERE player_id = 1163220 AND season_id = 816527
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...gg_year_player_loan WHERE player_id = 1163220 AND season_id ...
                                                             ^

Failed query
Running query: SELECT max_speed FROM public.agg_game_player_pd WHERE player_id = 1163220 AND season_id = 816527

06-21 16:25:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:50 -> SELECT max_speed FROM public.agg_game_player_pd WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:50 -> SELECT max_speed FROM public.agg_game_player_pd WHERE player_id = 1163220 AND season_id = 816527

Successful query
Data Shape: (20, 1)
Running query: SELECT player_id, player_name, height FROM vm_agg_year_player_info WHERE player_name = \'Vinicius Junior\' AND year = 2023

06-21 16:25:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:50 -> SELECT player_id, player_name, height FROM vm_agg_year_player_info WHERE player_name = \'Vinicius Junior\' AND year = 2023
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:50 -> SELECT player_id, player_name, height FROM vm_agg_year_player_info WHERE player_name = \'Vinicius Junior\' AND year = 2023
ERROR:root:Database error: syntax error at or near "\"
LINE 1: ... FROM vm_agg_year_player_info WHERE player_name = \'Vinicius...
                                                             ^

Failed query
Running query: SELECT max_speed FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527

06-21 16:25:50 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:50 -> SELECT max_speed FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:50 -> SELECT max_speed FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527

Successful query
Data Shape: (4, 1)
Running query: SELECT player_id, team_id, season_id, season_year FROM vm_agg_season_player_all WHERE season_id = 816530 ORDER BY games_lost DESC LIMIT 1

06-21 16:25:52 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:52 -> SELECT player_id, team_id, season_id, season_year FROM vm_agg_season_player_all WHERE season_id = 816530 ORDER BY games_lost DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:52 -> SELECT player_id, team_id, season_id, season_year FROM vm_agg_season_player_all WHERE season_id = 816530 ORDER BY games_lost DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...T player_id, team_id, season_id, season_year FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE season_id = 816530 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1

06-21 16:25:53 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:53 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE season_id = 816530 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:53 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE season_id = 816530 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...goal_id) AS goals_scored FROM public.t_goal WHERE season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, COUNT(*) as goals FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals DESC LIMIT 1

06-21 16:25:53 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:53 -> SELECT player_id, COUNT(*) as goals FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:53 -> SELECT player_id, COUNT(*) as goals FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...er_id, COUNT(*) as goals FROM public.t_goal WHERE season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, team_id, season_id, season_year, league_type_id, player_name, team_games_played, team_mins_played, mins_played FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY mins_played DESC LIMIT 1

06-21 16:25:53 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:53 -> SELECT player_id, team_id, season_id, season_year, league_type_id, player_name, team_games_played, team_mins_played, mins_played FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY mins_played DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:53 -> SELECT player_id, team_id, season_id, season_year, league_type_id, player_name, team_games_played, team_mins_played, mins_played FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY mins_played DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ..._games_played, team_mins_played, mins_played FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY npg_90 DESC LIMIT 1

06-21 16:25:53 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:53 -> SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY npg_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:53 -> SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY npg_90 DESC LIMIT 1

Successful query
Data Shape: (1, 5)
Running query: SELECT player_id, player_name, team_id, season_id FROM vm_agg_season_player_all WHERE team_id = 4265 AND season_id = 816527 ORDER BY games_lost ASC LIMIT 1

06-21 16:25:53 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:53 -> SELECT player_id, player_name, team_id, season_id FROM vm_agg_season_player_all WHERE team_id = 4265 AND season_id = 816527 ORDER BY games_lost ASC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:53 -> SELECT player_id, player_name, team_id, season_id FROM vm_agg_season_player_all WHERE team_id = 4265 AND season_id = 816527 ORDER BY games_lost ASC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...T player_id, player_name, team_id, season_id FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 ORDER BY team_games_played DESC, team_mins_played DESC LIMIT 1

06-21 16:25:53 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:53 -> SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 ORDER BY team_games_played DESC, team_mins_played DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:53 -> SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 ORDER BY team_games_played DESC, team_mins_played DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, team_id, season_id FROM vm_agg_season_play...
                                                  ^

Failed query
Running query: SELECT player_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY npg_90 DESC LIMIT 1

06-21 16:25:53 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:53 -> SELECT player_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY npg_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:53 -> SELECT player_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY npg_90 DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE team_id = 20076 AND season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:25:53 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:53 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE team_id = 20076 AND season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:53 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE team_id = 20076 AND season_id = 816527 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE team_id = 20076 AND season_id = 816527 ORDER BY npg_90 DESC LIMIT 1

06-21 16:25:53 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:53 -> SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE team_id = 20076 AND season_id = 816527 ORDER BY npg_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:53 -> SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE team_id = 20076 AND season_id = 816527 ORDER BY npg_90 DESC LIMIT 1

Successful query
Data Shape: (1, 5)
Running query: SELECT player_name, goals FROM vm_agg_season_player_opta WHERE team_id = 20076 AND season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:25:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:54 -> SELECT player_name, goals FROM vm_agg_season_player_opta WHERE team_id = 20076 AND season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:54 -> SELECT player_name, goals FROM vm_agg_season_player_opta WHERE team_id = 20076 AND season_id = 816527 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, team_id, season_id, season_year, league_type_id, player_name, age, player_country_code, team_games_played, team_mins_played, mins_played FROM vm_agg_season_player_all WHERE team_id = 20076 AND season_id = 816527 ORDER BY mins_played DESC LIMIT 1

06-21 16:25:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:54 -> SELECT player_id, team_id, season_id, season_year, league_type_id, player_name, age, player_country_code, team_games_played, team_mins_played, mins_played FROM vm_agg_season_player_all WHERE team_id = 20076 AND season_id = 816527 ORDER BY mins_played DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:54 -> SELECT player_id, team_id, season_id, season_year, league_type_id, player_name, age, player_country_code, team_games_played, team_mins_played, mins_played FROM vm_agg_season_player_all WHERE team_id = 20076 AND season_id = 816527 ORDER BY mins_played DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ..._games_played, team_mins_played, mins_played FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id FROM public.agg_season_player_pd WHERE team_id = 20076 AND season_id = 816527 ORDER BY score_pd DESC LIMIT 1

06-21 16:25:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:54 -> SELECT player_id FROM public.agg_season_player_pd WHERE team_id = 20076 AND season_id = 816527 ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:54 -> SELECT player_id FROM public.agg_season_player_pd WHERE team_id = 20076 AND season_id = 816527 ORDER BY score_pd DESC LIMIT 1

Successful query
Data Shape: (1, 1)
Running query: SELECT sum(goals_xg_0 + goals_xg_01 + goals_xg_025 + goals_xg_04) AS total_goals_scored FROM public.vt_game_metric_player WHERE player_id = 80992 AND season_id = 817326

06-21 16:25:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:54 -> SELECT sum(goals_xg_0 + goals_xg_01 + goals_xg_025 + goals_xg_04) AS total_goals_scored FROM public.vt_game_metric_player WHERE player_id = 80992 AND season_id = 817326
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:54 -> SELECT sum(goals_xg_0 + goals_xg_01 + goals_xg_025 + goals_xg_04) AS total_goals_scored FROM public.vt_game_metric_player WHERE player_id = 80992 AND season_id = 817326

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, COUNT(*) AS goals_scored FROM public.t_goal WHERE season_id IN (815896, 816529) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1

06-21 16:25:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:54 -> SELECT player_id, COUNT(*) AS goals_scored FROM public.t_goal WHERE season_id IN (815896, 816529) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:54 -> SELECT player_id, COUNT(*) AS goals_scored FROM public.t_goal WHERE season_id IN (815896, 816529) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...COUNT(*) AS goals_scored FROM public.t_goal WHERE season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816529 ORDER BY npg_90 DESC LIMIT 1

06-21 16:25:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:54 -> SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816529 ORDER BY npg_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:54 -> SELECT player_id, player_name, team_id, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816529 ORDER BY npg_90 DESC LIMIT 1

Successful query
Data Shape: (1, 5)
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id IN (815896, 816529) AND league_name = 'ENG I' ORDER BY goals DESC LIMIT 1

06-21 16:25:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:54 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id IN (815896, 816529) AND league_name = 'ENG I' ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:54 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id IN (815896, 816529) AND league_name = 'ENG I' ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (0, 3)
Running query: SELECT player_id, SUM(score_pd) AS total_goals FROM public.agg_season_player_pd WHERE season_id IN (815896, 816529) GROUP BY player_id ORDER BY total_goals DESC LIMIT 1

06-21 16:25:54 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:54 -> SELECT player_id, SUM(score_pd) AS total_goals FROM public.agg_season_player_pd WHERE season_id IN (815896, 816529) GROUP BY player_id ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:54 -> SELECT player_id, SUM(score_pd) AS total_goals FROM public.agg_season_player_pd WHERE season_id IN (815896, 816529) GROUP BY player_id ORDER BY total_goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816529 ORDER BY goals DESC LIMIT 1

06-21 16:25:55 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:55 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816529 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:55 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816529 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, team_id, season_id, mins_played, score_pd FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY score_pd DESC LIMIT 1

06-21 16:25:55 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:55 -> SELECT player_id, team_id, season_id, mins_played, score_pd FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:55 -> SELECT player_id, team_id, season_id, mins_played, score_pd FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY score_pd DESC LIMIT 1

Successful query
Data Shape: (1, 5)
Running query: SELECT player_id, player_name, team_id, season_id, season_year, league_type_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY team_games_played DESC LIMIT 1

06-21 16:25:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:57 -> SELECT player_id, player_name, team_id, season_id, season_year, league_type_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY team_games_played DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:57 -> SELECT player_id, player_name, team_id, season_id, season_year, league_type_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY team_games_played DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...m_id, season_id, season_year, league_type_id FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id FROM public.agg_season_player_pd WHERE team_id = 7960 AND season_id = 816580 ORDER BY score_pd DESC LIMIT 1

06-21 16:25:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:57 -> SELECT player_id FROM public.agg_season_player_pd WHERE team_id = 7960 AND season_id = 816580 ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:57 -> SELECT player_id FROM public.agg_season_player_pd WHERE team_id = 7960 AND season_id = 816580 ORDER BY score_pd DESC LIMIT 1

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE team_id = 7960 AND season_id = 816580 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1

06-21 16:25:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:57 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE team_id = 7960 AND season_id = 816580 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:57 -> SELECT player_id, COUNT(goal_id) AS goals_scored FROM public.t_goal WHERE team_id = 7960 AND season_id = 816580 GROUP BY player_id ORDER BY goals_scored DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...cored FROM public.t_goal WHERE team_id = 7960 AND season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE team_id = 7960 AND season_id = 816580 ORDER BY goals DESC LIMIT 1

06-21 16:25:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:57 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE team_id = 7960 AND season_id = 816580 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:57 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE team_id = 7960 AND season_id = 816580 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, season_id, goals_90 FROM vm_agg_season_player_similarity WHERE team_id = 7960 AND season_id = 816580 ORDER BY goals_90 DESC LIMIT 1

06-21 16:25:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:57 -> SELECT player_id, player_name, season_id, goals_90 FROM vm_agg_season_player_similarity WHERE team_id = 7960 AND season_id = 816580 ORDER BY goals_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:57 -> SELECT player_id, player_name, season_id, goals_90 FROM vm_agg_season_player_similarity WHERE team_id = 7960 AND season_id = 816580 ORDER BY goals_90 DESC LIMIT 1
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: SELECT player_id, player_name, season_id, goals_90 FROM vm_a...
                                                  ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE team_id = 7960 AND season_id = 816580 ORDER BY goals DESC LIMIT 1

06-21 16:25:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:57 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE team_id = 7960 AND season_id = 816580 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:57 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE team_id = 7960 AND season_id = 816580 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, COUNT(*) AS goals_scored FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC

06-21 16:25:58 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:58 -> SELECT player_id, COUNT(*) AS goals_scored FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:58 -> SELECT player_id, COUNT(*) AS goals_scored FROM public.t_goal WHERE season_id = 816527 GROUP BY player_id ORDER BY goals_scored DESC
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...COUNT(*) AS goals_scored FROM public.t_goal WHERE season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, team_id, season_id, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals_90 DESC LIMIT 1

06-21 16:25:58 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:58 -> SELECT player_id, team_id, season_id, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:58 -> SELECT player_id, team_id, season_id, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY goals_90 DESC LIMIT 1
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: SELECT player_id, team_id, season_id, goals_90 FROM vm_agg_s...
                                              ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT player_id, team_id, season_id, season_year, league_type_id, player_name, SUM(goals_scored) AS total_goals FROM vm_agg_season_player_all WHERE season_id = 816527 GROUP BY player_id, team_id, season_id, season_year, league_type_id, player_name ORDER BY total_goals DESC LIMIT 1

06-21 16:25:58 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:58 -> SELECT player_id, team_id, season_id, season_year, league_type_id, player_name, SUM(goals_scored) AS total_goals FROM vm_agg_season_player_all WHERE season_id = 816527 GROUP BY player_id, team_id, season_id, season_year, league_type_id, player_name ORDER BY total_goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:58 -> SELECT player_id, team_id, season_id, season_year, league_type_id, player_name, SUM(goals_scored) AS total_goals FROM vm_agg_season_player_all WHERE season_id = 816527 GROUP BY player_id, team_id, season_id, season_year, league_type_id, player_name ORDER BY total_goals DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...layer_name, SUM(goals_scored) AS total_goals FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:25:58 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:58 -> SELECT player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:58 -> SELECT player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id FROM public.agg_season_player_pd WHERE team_id = 7960 AND season_id = 816580 ORDER BY dl_index DESC LIMIT 1

06-21 16:25:58 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:58 -> SELECT player_id FROM public.agg_season_player_pd WHERE team_id = 7960 AND season_id = 816580 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:58 -> SELECT player_id FROM public.agg_season_player_pd WHERE team_id = 7960 AND season_id = 816580 ORDER BY dl_index DESC LIMIT 1
ERROR:root:Database error: column "dl_index" does not exist
LINE 1: ...RE team_id = 7960 AND season_id = 816580 ORDER BY dl_index D...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 7960 AND season_id = 816580 AND position IN ('DC', 'DR', 'DL') ORDER BY dl_index DESC LIMIT 1

06-21 16:25:58 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:58 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 7960 AND season_id = 816580 AND position IN ('DC', 'DR', 'DL') ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:58 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 7960 AND season_id = 816580 AND position IN ('DC', 'DR', 'DL') ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, team_id, season_id, games_lost FROM vm_agg_season_player_all WHERE team_id = 7960 AND season_id = 816580 AND age > 20 ORDER BY games_lost ASC LIMIT 1

06-21 16:25:58 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:58 -> SELECT player_id, player_name, team_id, season_id, games_lost FROM vm_agg_season_player_all WHERE team_id = 7960 AND season_id = 816580 AND age > 20 ORDER BY games_lost ASC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:58 -> SELECT player_id, player_name, team_id, season_id, games_lost FROM vm_agg_season_player_all WHERE team_id = 7960 AND season_id = 816580 AND age > 20 ORDER BY games_lost ASC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ... player_name, team_id, season_id, games_lost FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE team_id = 7960 AND player_position IN ('DC', 'DR', 'DL') AND season_id = 816580 ORDER BY dl_index DESC LIMIT 1

06-21 16:25:58 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:58 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE team_id = 7960 AND player_position IN ('DC', 'DR', 'DL') AND season_id = 816580 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:58 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE team_id = 7960 AND player_position IN ('DC', 'DR', 'DL') AND season_id = 816580 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE team_id = 7960 AND season_id = 816580 AND player_position IN ('DC', 'DF') ORDER BY dl_index DESC LIMIT 1

06-21 16:25:58 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:58 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE team_id = 7960 AND season_id = 816580 AND player_position IN ('DC', 'DF') ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:58 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE team_id = 7960 AND season_id = 816580 AND player_position IN ('DC', 'DF') ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816529 ORDER BY goals DESC LIMIT 1

06-21 16:25:58 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:58 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816529 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:58 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816529 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, score_pd FROM public.agg_season_player_pd WHERE season_id = 816529 ORDER BY score_pd DESC LIMIT 1

06-21 16:25:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:59 -> SELECT player_id, score_pd FROM public.agg_season_player_pd WHERE season_id = 816529 ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:59 -> SELECT player_id, score_pd FROM public.agg_season_player_pd WHERE season_id = 816529 ORDER BY score_pd DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_year = 2023 ORDER BY dl_index DESC LIMIT 1

06-21 16:25:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:59 -> SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_year = 2023 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:59 -> SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_year = 2023 ORDER BY dl_index DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, team_id, season_id FROM vm_agg_season_play...
                                                  ^

Failed query
Running query: SELECT player_id, season_id, dl_index FROM vm_agg_season_player_similarity WHERE season_id = 816529 ORDER BY dl_index DESC LIMIT 1

06-21 16:25:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:59 -> SELECT player_id, season_id, dl_index FROM vm_agg_season_player_similarity WHERE season_id = 816529 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:59 -> SELECT player_id, season_id, dl_index FROM vm_agg_season_player_similarity WHERE season_id = 816529 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id IN (816529) ORDER BY goals DESC LIMIT 1

06-21 16:25:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:25:59 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id IN (816529) ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:25:59 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id IN (816529) ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, team_id, season_id, season_year FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY games_lost ASC LIMIT 1

06-21 16:26:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:01 -> SELECT player_id, team_id, season_id, season_year FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY games_lost ASC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:01 -> SELECT player_id, team_id, season_id, season_year FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY games_lost ASC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...T player_id, team_id, season_id, season_year FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, team_id, season_id, dl_index FROM vm_agg_season_player_similarity WHERE team_name = 'Malaga' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:01 -> SELECT player_id, player_name, team_id, season_id, dl_index FROM vm_agg_season_player_similarity WHERE team_name = 'Malaga' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:01 -> SELECT player_id, player_name, team_id, season_id, dl_index FROM vm_agg_season_player_similarity WHERE team_name = 'Malaga' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (0, 5)
Running query: SELECT player_id FROM public.agg_season_player_pd WHERE team_id = (SELECT team_id FROM t_team WHERE name = 'Malaga' AND season_id = 816527) AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:01 -> SELECT player_id FROM public.agg_season_player_pd WHERE team_id = (SELECT team_id FROM t_team WHERE name = 'Malaga' AND season_id = 816527) AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:01 -> SELECT player_id FROM public.agg_season_player_pd WHERE team_id = (SELECT team_id FROM t_team WHERE name = 'Malaga' AND season_id = 816527) AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
ERROR:root:Database error: column "dl_index" does not exist
LINE 1: ...ason_id = 816527) AND season_id = 816527 ORDER BY dl_index D...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, player_position, team_name FROM vm_agg_season_player_info WHERE team_name = 'Malaga' AND season_id = 816527

06-21 16:26:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:01 -> SELECT player_id, player_name, player_position, team_name FROM vm_agg_season_player_info WHERE team_name = 'Malaga' AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:01 -> SELECT player_id, player_name, player_position, team_name FROM vm_agg_season_player_info WHERE team_name = 'Malaga' AND season_id = 816527

Successful query
Data Shape: (0, 4)
Running query: SELECT player_id, player_name, age FROM vm_agg_season_player_all WHERE team_id = (SELECT team_id FROM t_team WHERE team_name = 'Malaga' AND season_id = 816527) AND season_id = 816527

06-21 16:26:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:01 -> SELECT player_id, player_name, age FROM vm_agg_season_player_all WHERE team_id = (SELECT team_id FROM t_team WHERE team_name = 'Malaga' AND season_id = 816527) AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:01 -> SELECT player_id, player_name, age FROM vm_agg_season_player_all WHERE team_id = (SELECT team_id FROM t_team WHERE team_name = 'Malaga' AND season_id = 816527) AND season_id = 816527
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, player_name, age FROM vm_agg_season_player...
                                                ^

Failed query
Running query: SELECT player_id, player_name, team_name, season_id FROM vm_agg_season_player_opta WHERE team_name = 'Malaga' AND season_id = 816527

06-21 16:26:02 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:02 -> SELECT player_id, player_name, team_name, season_id FROM vm_agg_season_player_opta WHERE team_name = 'Malaga' AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:02 -> SELECT player_id, player_name, team_name, season_id FROM vm_agg_season_player_opta WHERE team_name = 'Malaga' AND season_id = 816527

Successful query
Data Shape: (0, 4)
Running query: SELECT player_id, goals FROM vm_agg_season_player_info WHERE player_name = 'Binsia Yunir' AND season_id = 816527

06-21 16:26:02 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:02 -> SELECT player_id, goals FROM vm_agg_season_player_info WHERE player_name = 'Binsia Yunir' AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:02 -> SELECT player_id, goals FROM vm_agg_season_player_info WHERE player_name = 'Binsia Yunir' AND season_id = 816527

Successful query
Data Shape: (0, 2)
Running query: SELECT player_id, SUM(goals) FROM vm_agg_season_player_all WHERE player_name = 'Binsia Yunir' AND season_id = 816527 GROUP BY player_id

06-21 16:26:02 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:02 -> SELECT player_id, SUM(goals) FROM vm_agg_season_player_all WHERE player_name = 'Binsia Yunir' AND season_id = 816527 GROUP BY player_id
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:02 -> SELECT player_id, SUM(goals) FROM vm_agg_season_player_all WHERE player_name = 'Binsia Yunir' AND season_id = 816527 GROUP BY player_id
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, SUM(goals) FROM vm_agg_season_player_all W...
                                          ^

Failed query
Running query: SELECT goals_90 FROM vm_agg_season_player_similarity WHERE player_name = 'Binsia Yunir' AND season_id = 816527

06-21 16:26:02 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:02 -> SELECT goals_90 FROM vm_agg_season_player_similarity WHERE player_name = 'Binsia Yunir' AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:02 -> SELECT goals_90 FROM vm_agg_season_player_similarity WHERE player_name = 'Binsia Yunir' AND season_id = 816527
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: SELECT goals_90 FROM vm_agg_season_player_similarity WHERE p...
               ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT goals FROM vm_agg_season_player_opta WHERE player_name = 'Binsia Yunir' AND season_id = 816527

06-21 16:26:02 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:02 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_name = 'Binsia Yunir' AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:02 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_name = 'Binsia Yunir' AND season_id = 816527

Successful query
Data Shape: (0, 1)
Running query: SELECT match_id, match_date, home_team_id, away_team_id, home_score, away_score, result FROM public.vt_game_metric_team WHERE season_id = 816527 AND (home_team_id = 4265 OR away_team_id = 4265)

06-21 16:26:02 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:02 -> SELECT match_id, match_date, home_team_id, away_team_id, home_score, away_score, result FROM public.vt_game_metric_team WHERE season_id = 816527 AND (home_team_id = 4265 OR away_team_id = 4265)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:02 -> SELECT match_id, match_date, home_team_id, away_team_id, home_score, away_score, result FROM public.vt_game_metric_team WHERE season_id = 816527 AND (home_team_id = 4265 OR away_team_id = 4265)
ERROR:root:Database error: column "home_team_id" does not exist
LINE 1: SELECT match_id, match_date, home_team_id, away_team_id, hom...
                                     ^

Failed query
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 1 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:02 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:02 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 1 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:02 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 1 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, score_pd FROM public.agg_season_player_pd WHERE team_id = 1 AND season_id = 816527 ORDER BY score_pd DESC LIMIT 1

06-21 16:26:02 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:02 -> SELECT player_id, score_pd FROM public.agg_season_player_pd WHERE team_id = 1 AND season_id = 816527 ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:02 -> SELECT player_id, score_pd FROM public.agg_season_player_pd WHERE team_id = 1 AND season_id = 816527 ORDER BY score_pd DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_all WHERE team_id = 1 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:03 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_all WHERE team_id = 1 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:03 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_all WHERE team_id = 1 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, player_name, dl_index FROM vm_agg_season_p...
                                                     ^

Failed query
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE team_id = 1 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:03 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE team_id = 1 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:03 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE team_id = 1 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE team_id = 1 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:03 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE team_id = 1 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:03 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE team_id = 1 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, COUNT(DISTINCT match_id) FROM public.t_goal WHERE player_id = 1339445 AND match_id IN (SELECT match_id FROM public.t_match WHERE season_id = 816527) GROUP BY player_id

06-21 16:26:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:03 -> SELECT player_id, COUNT(DISTINCT match_id) FROM public.t_goal WHERE player_id = 1339445 AND match_id IN (SELECT match_id FROM public.t_match WHERE season_id = 816527) GROUP BY player_id
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:03 -> SELECT player_id, COUNT(DISTINCT match_id) FROM public.t_goal WHERE player_id = 1339445 AND match_id IN (SELECT match_id FROM public.t_match WHERE season_id = 816527) GROUP BY player_id

Successful query
Data Shape: (0, 2)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE team_id = 4279 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:03 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE team_id = 4279 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:03 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE team_id = 4279 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, SUM(goals_scored) AS total_goals_scored FROM vm_agg_season_player_all WHERE player_id = 1163220 AND season_id = 816527 GROUP BY player_id

06-21 16:26:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:03 -> SELECT player_id, SUM(goals_scored) AS total_goals_scored FROM vm_agg_season_player_all WHERE player_id = 1163220 AND season_id = 816527 GROUP BY player_id
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:03 -> SELECT player_id, SUM(goals_scored) AS total_goals_scored FROM vm_agg_season_player_all WHERE player_id = 1163220 AND season_id = 816527 GROUP BY player_id
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ..._id, SUM(goals_scored) AS total_goals_scored FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT goals_90 FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527

06-21 16:26:03 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:03 -> SELECT goals_90 FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:03 -> SELECT goals_90 FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: SELECT goals_90 FROM vm_agg_season_player_similarity WHERE p...
               ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT player_id, score_pd_float FROM public.agg_season_player_pd WHERE team_id = 1 AND season_id = 816527 ORDER BY score_pd_float DESC LIMIT 1

06-21 16:26:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:05 -> SELECT player_id, score_pd_float FROM public.agg_season_player_pd WHERE team_id = 1 AND season_id = 816527 ORDER BY score_pd_float DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:05 -> SELECT player_id, score_pd_float FROM public.agg_season_player_pd WHERE team_id = 1 AND season_id = 816527 ORDER BY score_pd_float DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, player_name, team_id, season_id, team_games_played, team_mins_played, mins_played, games_lost FROM vm_agg_season_player_all WHERE team_id = 1 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:05 -> SELECT player_id, player_name, team_id, season_id, team_games_played, team_mins_played, mins_played, games_lost FROM vm_agg_season_player_all WHERE team_id = 1 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:05 -> SELECT player_id, player_name, team_id, season_id, team_games_played, team_mins_played, mins_played, games_lost FROM vm_agg_season_player_all WHERE team_id = 1 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...d, team_mins_played, mins_played, games_lost FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY games_lost ASC LIMIT 1

06-21 16:26:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:06 -> SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY games_lost ASC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:06 -> SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY games_lost ASC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, team_id, season_id FROM vm_agg_season_play...
                                                  ^

Failed query
Running query: SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_id = 1 ORDER BY goals DESC LIMIT 1

06-21 16:26:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:06 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_id = 1 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:06 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_id = 1 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT match_id FROM public.vm_fac_games_player WHERE player_id = 1598188 AND team_id = 20076 AND season_id = 816527 ORDER BY mins_played DESC LIMIT 1

06-21 16:26:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:06 -> SELECT match_id FROM public.vm_fac_games_player WHERE player_id = 1598188 AND team_id = 20076 AND season_id = 816527 ORDER BY mins_played DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:06 -> SELECT match_id FROM public.vm_fac_games_player WHERE player_id = 1598188 AND team_id = 20076 AND season_id = 816527 ORDER BY mins_played DESC LIMIT 1
ERROR:root:Database error: relation "public.vm_fac_games_player" does not exist
LINE 1: SELECT match_id FROM public.vm_fac_games_player WHERE player...
                             ^

Failed query
Running query: SELECT match_id, team_id, player_id, season_id, score_pd FROM public.agg_game_player_pd WHERE player_id = 1598188 AND season_id = 816527 ORDER BY score_pd DESC LIMIT 1

06-21 16:26:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:06 -> SELECT match_id, team_id, player_id, season_id, score_pd FROM public.agg_game_player_pd WHERE player_id = 1598188 AND season_id = 816527 ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:06 -> SELECT match_id, team_id, player_id, season_id, score_pd FROM public.agg_game_player_pd WHERE player_id = 1598188 AND season_id = 816527 ORDER BY score_pd DESC LIMIT 1

Successful query
Data Shape: (1, 5)
Running query: SELECT match_id, COUNT(goal_id) as goals_scored FROM public.t_goal WHERE player_id = 1598188 AND season_id = 816527 GROUP BY match_id ORDER BY goals_scored DESC LIMIT 1

06-21 16:26:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:06 -> SELECT match_id, COUNT(goal_id) as goals_scored FROM public.t_goal WHERE player_id = 1598188 AND season_id = 816527 GROUP BY match_id ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:06 -> SELECT match_id, COUNT(goal_id) as goals_scored FROM public.t_goal WHERE player_id = 1598188 AND season_id = 816527 GROUP BY match_id ORDER BY goals_scored DESC LIMIT 1
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ... FROM public.t_goal WHERE player_id = 1598188 AND season_id ...
                                                             ^

Failed query
Running query: SELECT match_id, goals_xg_0, goals_xg_01, goals_xg_025, goals_xg_04 FROM public.vt_game_metric_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY goals_xg_0 DESC LIMIT 1

06-21 16:26:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:06 -> SELECT match_id, goals_xg_0, goals_xg_01, goals_xg_025, goals_xg_04 FROM public.vt_game_metric_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY goals_xg_0 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:06 -> SELECT match_id, goals_xg_0, goals_xg_01, goals_xg_025, goals_xg_04 FROM public.vt_game_metric_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY goals_xg_0 DESC LIMIT 1

Successful query
Data Shape: (1, 5)
Running query: SELECT match_id, goals FROM public.vt_game_stat_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY goals DESC LIMIT 1

06-21 16:26:06 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:06 -> SELECT match_id, goals FROM public.vt_game_stat_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:06 -> SELECT match_id, goals FROM public.vt_game_stat_player WHERE player_id = 1598188 AND season_id = 816527 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_all WHERE team_id = 4279 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:07 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:07 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_all WHERE team_id = 4279 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:07 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_all WHERE team_id = 4279 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, player_name, dl_index FROM vm_agg_season_p...
                                                     ^

Failed query
Running query: SELECT player_id, team_id, index_score FROM vm_det_player_placer WHERE team_id = 65 AND season_id = 816527 ORDER BY index_score DESC

06-21 16:26:07 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:07 -> SELECT player_id, team_id, index_score FROM vm_det_player_placer WHERE team_id = 65 AND season_id = 816527 ORDER BY index_score DESC
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:07 -> SELECT player_id, team_id, index_score FROM vm_det_player_placer WHERE team_id = 65 AND season_id = 816527 ORDER BY index_score DESC
ERROR:root:Database error: relation "vm_det_player_placer" does not exist
LINE 1: SELECT player_id, team_id, index_score FROM vm_det_player_pl...
                                                    ^

Failed query
Running query: SELECT player_id, team_id, season_id, dl_index FROM public.vt_game_stat_player WHERE team_id = 863 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:07 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:07 -> SELECT player_id, team_id, season_id, dl_index FROM public.vt_game_stat_player WHERE team_id = 863 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:07 -> SELECT player_id, team_id, season_id, dl_index FROM public.vt_game_stat_player WHERE team_id = 863 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
ERROR:root:Database error: column "dl_index" does not exist
LINE 1: SELECT player_id, team_id, season_id, dl_index FROM public.v...
                                              ^

Failed query
Running query: SELECT player_id FROM public.vt_game_metric_player WHERE team_id = (SELECT team_id FROM t_team WHERE name = 'FC Barcelona') AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:07 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:07 -> SELECT player_id FROM public.vt_game_metric_player WHERE team_id = (SELECT team_id FROM t_team WHERE name = 'FC Barcelona') AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:07 -> SELECT player_id FROM public.vt_game_metric_player WHERE team_id = (SELECT team_id FROM t_team WHERE name = 'FC Barcelona') AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
ERROR:root:Database error: column "dl_index" does not exist
LINE 1: ...= 'FC Barcelona') AND season_id = 816527 ORDER BY dl_index D...
                                                             ^

Failed query
Running query: SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 ORDER BY games_lost LIMIT 1

06-21 16:26:07 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:07 -> SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 ORDER BY games_lost LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:07 -> SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 ORDER BY games_lost LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, team_id, season_id FROM vm_agg_season_play...
                                                  ^

Failed query
Running query: SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY goals_scored DESC LIMIT 1

06-21 16:26:07 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:07 -> SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY goals_scored DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:07 -> SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY goals_scored DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, team_id, season_id FROM vm_agg_season_play...
                                                  ^

Failed query
Running query: SELECT player_id, team_id, season_id, season_year, league_type_id, player_name, age, player_country_code, team_games_played, team_mins_played, mins_played FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY mins_played DESC LIMIT 1

06-21 16:26:07 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:07 -> SELECT player_id, team_id, season_id, season_year, league_type_id, player_name, age, player_country_code, team_games_played, team_mins_played, mins_played FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY mins_played DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:07 -> SELECT player_id, team_id, season_id, season_year, league_type_id, player_name, age, player_country_code, team_games_played, team_mins_played, mins_played FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY mins_played DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ..._games_played, team_mins_played, mins_played FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT assists FROM vm_agg_season_player_all WHERE player_id = 1163220 AND season_id = 816527

06-21 16:26:07 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:07 -> SELECT assists FROM vm_agg_season_player_all WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:07 -> SELECT assists FROM vm_agg_season_player_all WHERE player_id = 1163220 AND season_id = 816527
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT assists FROM vm_agg_season_player_all WHERE player_id...
                            ^

Failed query
Running query: SELECT assists FROM vm_agg_season_player_info WHERE player_id = 1163220 AND season_id = 816527

06-21 16:26:07 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:07 -> SELECT assists FROM vm_agg_season_player_info WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:07 -> SELECT assists FROM vm_agg_season_player_info WHERE player_id = 1163220 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT assists_90 FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527

06-21 16:26:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:08 -> SELECT assists_90 FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:08 -> SELECT assists_90 FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT match_id, season_id, match_date, home_team_id, away_team_id, home_score, away_score FROM public.vt_game_metric_team WHERE season_id = 816527 AND (home_team_id = 4265 OR away_team_id = 4265)

06-21 16:26:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:08 -> SELECT match_id, season_id, match_date, home_team_id, away_team_id, home_score, away_score FROM public.vt_game_metric_team WHERE season_id = 816527 AND (home_team_id = 4265 OR away_team_id = 4265)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:08 -> SELECT match_id, season_id, match_date, home_team_id, away_team_id, home_score, away_score FROM public.vt_game_metric_team WHERE season_id = 816527 AND (home_team_id = 4265 OR away_team_id = 4265)
ERROR:root:Database error: column "home_team_id" does not exist
LINE 1: SELECT match_id, season_id, match_date, home_team_id, away_t...
                                                ^

Failed query
Running query: SELECT assists FROM vm_agg_season_player_all WHERE player_id = 1598188 AND season_id = 816527

06-21 16:26:10 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:10 -> SELECT assists FROM vm_agg_season_player_all WHERE player_id = 1598188 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:10 -> SELECT assists FROM vm_agg_season_player_all WHERE player_id = 1598188 AND season_id = 816527
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT assists FROM vm_agg_season_player_all WHERE player_id...
                            ^

Failed query
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 3

06-21 16:26:10 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:10 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 3
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:10 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 3

Successful query
Data Shape: (3, 3)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 3

06-21 16:26:10 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:10 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 3
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:10 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 3

Successful query
Data Shape: (3, 3)
Running query: SELECT player_id, score_pd_float FROM public.agg_season_player_pd WHERE team_id = 20076 AND season_id = 816527 ORDER BY score_pd_float DESC LIMIT 3

06-21 16:26:10 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:10 -> SELECT player_id, score_pd_float FROM public.agg_season_player_pd WHERE team_id = 20076 AND season_id = 816527 ORDER BY score_pd_float DESC LIMIT 3
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:10 -> SELECT player_id, score_pd_float FROM public.agg_season_player_pd WHERE team_id = 20076 AND season_id = 816527 ORDER BY score_pd_float DESC LIMIT 3

Successful query
Data Shape: (3, 2)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 3

06-21 16:26:10 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:10 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 3
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:10 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_opta WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 3

Successful query
Data Shape: (3, 3)
Running query: SELECT player_id, COUNT(DISTINCT match_id) FROM public.t_goal WHERE team_id = 20076 AND season_id = 816527 GROUP BY player_id ORDER BY COUNT(DISTINCT match_id) DESC LIMIT 3

06-21 16:26:10 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:10 -> SELECT player_id, COUNT(DISTINCT match_id) FROM public.t_goal WHERE team_id = 20076 AND season_id = 816527 GROUP BY player_id ORDER BY COUNT(DISTINCT match_id) DESC LIMIT 3
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:10 -> SELECT player_id, COUNT(DISTINCT match_id) FROM public.t_goal WHERE team_id = 20076 AND season_id = 816527 GROUP BY player_id ORDER BY COUNT(DISTINCT match_id) DESC LIMIT 3
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ..._id) FROM public.t_goal WHERE team_id = 20076 AND season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816528 AND league_name = 'Serie A' ORDER BY goals DESC LIMIT 1

06-21 16:26:10 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:10 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816528 AND league_name = 'Serie A' ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:10 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816528 AND league_name = 'Serie A' ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (0, 3)
Running query: SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816528 ORDER BY goals DESC LIMIT 1

06-21 16:26:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:11 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816528 ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:11 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816528 ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816528 ORDER BY score_pd DESC LIMIT 1

06-21 16:26:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:11 -> SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816528 ORDER BY score_pd DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:11 -> SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816528 ORDER BY score_pd DESC LIMIT 1

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, player_name, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816528 ORDER BY npg_90 DESC LIMIT 1

06-21 16:26:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:11 -> SELECT player_id, player_name, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816528 ORDER BY npg_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:11 -> SELECT player_id, player_name, season_id, npg_90 FROM vm_agg_season_player_similarity WHERE season_id = 816528 ORDER BY npg_90 DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT player_id, player_name, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816528 AND league_type_id = 4 ORDER BY team_games_played DESC, team_mins_played DESC LIMIT 1

06-21 16:26:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:11 -> SELECT player_id, player_name, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816528 AND league_type_id = 4 ORDER BY team_games_played DESC, team_mins_played DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:11 -> SELECT player_id, player_name, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816528 AND league_type_id = 4 ORDER BY team_games_played DESC, team_mins_played DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...T player_id, player_name, team_id, season_id FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816529 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

06-21 16:26:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:11 -> SELECT player_id, player_name, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816529 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:11 -> SELECT player_id, player_name, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816529 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, player_name, max_speed FROM vm_agg_season_...
                                       ^

Failed query
Running query: SELECT player_id, player_name, max_speed FROM vm_agg_season_player_info WHERE season_id = 816529 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

06-21 16:26:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:11 -> SELECT player_id, player_name, max_speed FROM vm_agg_season_player_info WHERE season_id = 816529 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:11 -> SELECT player_id, player_name, max_speed FROM vm_agg_season_player_info WHERE season_id = 816529 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 1

06-21 16:26:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:11 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:11 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_all WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 1

06-21 16:26:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:11 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_all WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:11 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_all WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...ECT player_id, team_id, season_id, max_speed FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, max_speed FROM vm_agg_season_player_opta WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 1

06-21 16:26:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:11 -> SELECT player_id, max_speed FROM vm_agg_season_player_opta WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:11 -> SELECT player_id, max_speed FROM vm_agg_season_player_opta WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:12 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:12 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:12 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:12 -> SELECT player_id, player_name, dl_index FROM vm_agg_season_player_info WHERE team_id = 20076 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 20076 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:26:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:12 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 20076 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:12 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 20076 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_name, dl_index FROM vm_agg_season_player_opta WHERE team_name = 'FC Barcelona' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:12 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:12 -> SELECT player_name, dl_index FROM vm_agg_season_player_opta WHERE team_name = 'FC Barcelona' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:12 -> SELECT player_name, dl_index FROM vm_agg_season_player_opta WHERE team_name = 'FC Barcelona' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, COUNT(DISTINCT match_id) FROM public.t_goal WHERE team_id = 20076 AND match_id IN (SELECT match_id FROM t_match WHERE season_id = 816527) GROUP BY player_id ORDER BY COUNT(DISTINCT match_id) DESC LIMIT 1

06-21 16:26:14 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:14 -> SELECT player_id, COUNT(DISTINCT match_id) FROM public.t_goal WHERE team_id = 20076 AND match_id IN (SELECT match_id FROM t_match WHERE season_id = 816527) GROUP BY player_id ORDER BY COUNT(DISTINCT match_id) DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:14 -> SELECT player_id, COUNT(DISTINCT match_id) FROM public.t_goal WHERE team_id = 20076 AND match_id IN (SELECT match_id FROM t_match WHERE season_id = 816527) GROUP BY player_id ORDER BY COUNT(DISTINCT match_id) DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 4282 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:26:14 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:14 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 4282 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:14 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE team_id = 4282 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (0, 2)
Running query: SELECT player_id, player_name, team_id, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 4282 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:14 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:14 -> SELECT player_id, player_name, team_id, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 4282 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:14 -> SELECT player_id, player_name, team_id, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 4282 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (0, 4)
Running query: SELECT player_id, player_name, team_name, season_id, dl_index FROM vm_agg_season_player_opta WHERE team_name = 'Malaga' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:14 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:14 -> SELECT player_id, player_name, team_name, season_id, dl_index FROM vm_agg_season_player_opta WHERE team_name = 'Malaga' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:14 -> SELECT player_id, player_name, team_name, season_id, dl_index FROM vm_agg_season_player_opta WHERE team_name = 'Malaga' AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (0, 5)
Running query: SELECT player_id, player_name, player_position, dl_index FROM vm_agg_season_player_info WHERE team_id = 4282 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:15 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:15 -> SELECT player_id, player_name, player_position, dl_index FROM vm_agg_season_player_info WHERE team_id = 4282 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:15 -> SELECT player_id, player_name, player_position, dl_index FROM vm_agg_season_player_info WHERE team_id = 4282 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (0, 4)
Running query: SELECT player_id, player_name, age, team_games_played, team_mins_played, mins_played, games_lost FROM vm_agg_season_player_all WHERE team_id = 4282 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:15 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:15 -> SELECT player_id, player_name, age, team_games_played, team_mins_played, mins_played, games_lost FROM vm_agg_season_player_all WHERE team_id = 4282 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:15 -> SELECT player_id, player_name, age, team_games_played, team_mins_played, mins_played, games_lost FROM vm_agg_season_player_all WHERE team_id = 4282 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...d, team_mins_played, mins_played, games_lost FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, goals, season_id FROM vm_agg_season_player_opta WHERE season_id = 817313 ORDER BY goals DESC LIMIT 5

06-21 16:26:15 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:15 -> SELECT player_id, goals, season_id FROM vm_agg_season_player_opta WHERE season_id = 817313 ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:15 -> SELECT player_id, goals, season_id FROM vm_agg_season_player_opta WHERE season_id = 817313 ORDER BY goals DESC LIMIT 5

Successful query
Data Shape: (0, 3)
Running query: SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 817313 ORDER BY team_games_played DESC, team_mins_played DESC, mins_played DESC LIMIT 5

06-21 16:26:15 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:15 -> SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 817313 ORDER BY team_games_played DESC, team_mins_played DESC, mins_played DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:15 -> SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 817313 ORDER BY team_games_played DESC, team_mins_played DESC, mins_played DESC LIMIT 5
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, team_id, season_id FROM vm_agg_season_play...
                                                  ^

Failed query
Running query: SELECT player_id, player_name, goals, season_id FROM vm_agg_season_player_info WHERE season_id = 817313 ORDER BY goals DESC LIMIT 5

06-21 16:26:15 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:15 -> SELECT player_id, player_name, goals, season_id FROM vm_agg_season_player_info WHERE season_id = 817313 ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:15 -> SELECT player_id, player_name, goals, season_id FROM vm_agg_season_player_info WHERE season_id = 817313 ORDER BY goals DESC LIMIT 5

Successful query
Data Shape: (0, 4)
Running query: SELECT player_id, SUM(score_pd) AS total_score FROM public.agg_season_player_pd WHERE season_id = 817313 GROUP BY player_id ORDER BY total_score DESC LIMIT 5

06-21 16:26:15 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:15 -> SELECT player_id, SUM(score_pd) AS total_score FROM public.agg_season_player_pd WHERE season_id = 817313 GROUP BY player_id ORDER BY total_score DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:15 -> SELECT player_id, SUM(score_pd) AS total_score FROM public.agg_season_player_pd WHERE season_id = 817313 GROUP BY player_id ORDER BY total_score DESC LIMIT 5

Successful query
Data Shape: (0, 2)
Running query: SELECT player_id, dl_index, season_id FROM vm_agg_season_player_similarity WHERE season_id = 817313 ORDER BY dl_index DESC LIMIT 5

06-21 16:26:15 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:15 -> SELECT player_id, dl_index, season_id FROM vm_agg_season_player_similarity WHERE season_id = 817313 ORDER BY dl_index DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:15 -> SELECT player_id, dl_index, season_id FROM vm_agg_season_player_similarity WHERE season_id = 817313 ORDER BY dl_index DESC LIMIT 5

Successful query
Data Shape: (0, 3)
Running query: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_all WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:26:15 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:15 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_all WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:15 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_all WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...ECT player_id, team_id, season_id, max_speed FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, max_speed FROM vm_agg_season_player_info WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:26:15 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:15 -> SELECT player_id, max_speed FROM vm_agg_season_player_info WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:15 -> SELECT player_id, max_speed FROM vm_agg_season_player_info WHERE team_id = 4265 AND season_id = 816527 ORDER BY max_speed DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT * FROM vm_agg_season_coach_similarity WHERE season_id = 816529 LIMIT 15

06-21 16:26:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:16 -> SELECT * FROM vm_agg_season_coach_similarity WHERE season_id = 816529 LIMIT 15
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:16 -> SELECT * FROM vm_agg_season_coach_similarity WHERE season_id = 816529 LIMIT 15

Successful query
Data Shape: (15, 67)
Running query: SELECT team_id, season_id, team_name, goals_scored, goals_against, possession, shots_total, shots_on_target, passes, xg, assists, key_passes, tackles_total, interceptions, aerials_won, crosses FROM vm_agg_season_team_opta WHERE season_id = 816529 LIMIT 15

06-21 16:26:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:16 -> SELECT team_id, season_id, team_name, goals_scored, goals_against, possession, shots_total, shots_on_target, passes, xg, assists, key_passes, tackles_total, interceptions, aerials_won, crosses FROM vm_agg_season_team_opta WHERE season_id = 816529 LIMIT 15
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:16 -> SELECT team_id, season_id, team_name, goals_scored, goals_against, possession, shots_total, shots_on_target, passes, xg, assists, key_passes, tackles_total, interceptions, aerials_won, crosses FROM vm_agg_season_team_opta WHERE season_id = 816529 LIMIT 15

Successful query
Data Shape: (15, 16)
Running query: SELECT team_id, season_id, team_name, goals_scored, goals_against, possession, shots_total, shots_on_target, xg, npg, xg_chain, recoveries, xg_open_play, crosses_per_xg, touches_in_opponent_box, fouls, passes_per_shot FROM vm_agg_season_team WHERE season_id = 816529 ORDER BY goals_scored DESC LIMIT 15

06-21 16:26:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:16 -> SELECT team_id, season_id, team_name, goals_scored, goals_against, possession, shots_total, shots_on_target, xg, npg, xg_chain, recoveries, xg_open_play, crosses_per_xg, touches_in_opponent_box, fouls, passes_per_shot FROM vm_agg_season_team WHERE season_id = 816529 ORDER BY goals_scored DESC LIMIT 15
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:16 -> SELECT team_id, season_id, team_name, goals_scored, goals_against, possession, shots_total, shots_on_target, xg, npg, xg_chain, recoveries, xg_open_play, crosses_per_xg, touches_in_opponent_box, fouls, passes_per_shot FROM vm_agg_season_team WHERE season_id = 816529 ORDER BY goals_scored DESC LIMIT 15
ERROR:root:Database error: column "crosses_per_xg" does not exist
LINE 1: ...get, xg, npg, xg_chain, recoveries, xg_open_play, crosses_pe...
                                                             ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_team.crossing_per_xg".

Failed query
Running query: SELECT player_id, team_id, mins_played, distance, distance_90, hsr_num, hsr_num_90, sprint_num, sprint_num_90, sprint_distance, sprint_distance_90, max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 AND player_id = 1287016

06-21 16:26:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:16 -> SELECT player_id, team_id, mins_played, distance, distance_90, hsr_num, hsr_num_90, sprint_num, sprint_num_90, sprint_distance, sprint_distance_90, max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 AND player_id = 1287016
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:16 -> SELECT player_id, team_id, mins_played, distance, distance_90, hsr_num, hsr_num_90, sprint_num, sprint_num_90, sprint_distance, sprint_distance_90, max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 AND player_id = 1287016

Successful query
Data Shape: (3, 12)
Running query: SELECT coach_id, team_id, season_id, points, points_per_game, goals_scored, goals_scored_per_game, goals_against, goals_against_per_game, npg, npg_per_game, npg_against, npg_against_per_game, xg_per_game, xa_per_game FROM vm_agg_season_coach WHERE season_id = 816529 ORDER BY points_per_game DESC LIMIT 15

06-21 16:26:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:16 -> SELECT coach_id, team_id, season_id, points, points_per_game, goals_scored, goals_scored_per_game, goals_against, goals_against_per_game, npg, npg_per_game, npg_against, npg_against_per_game, xg_per_game, xa_per_game FROM vm_agg_season_coach WHERE season_id = 816529 ORDER BY points_per_game DESC LIMIT 15
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:16 -> SELECT coach_id, team_id, season_id, points, points_per_game, goals_scored, goals_scored_per_game, goals_against, goals_against_per_game, npg, npg_per_game, npg_against, npg_against_per_game, xg_per_game, xa_per_game FROM vm_agg_season_coach WHERE season_id = 816529 ORDER BY points_per_game DESC LIMIT 15

Successful query
Data Shape: (15, 15)
Running query: SELECT player_id, team_id, season_id, player_name, position, touches_in_opp_box_90, season_info_player_id FROM vm_agg_season_player_similarity WHERE position = 'DC' AND secondary_position = 'DL' AND season_id = 816531 ORDER BY touches_in_opp_box_90 DESC LIMIT 5

06-21 16:26:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:17 -> SELECT player_id, team_id, season_id, player_name, position, touches_in_opp_box_90, season_info_player_id FROM vm_agg_season_player_similarity WHERE position = 'DC' AND secondary_position = 'DL' AND season_id = 816531 ORDER BY touches_in_opp_box_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:17 -> SELECT player_id, team_id, season_id, player_name, position, touches_in_opp_box_90, season_info_player_id FROM vm_agg_season_player_similarity WHERE position = 'DC' AND secondary_position = 'DL' AND season_id = 816531 ORDER BY touches_in_opp_box_90 DESC LIMIT 5

Successful query
Data Shape: (3, 7)
Running query: SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816531 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'DC' AND player_id IN (SELECT player_id FROM t_player WHERE team_id IN (SELECT team_id FROM t_team WHERE country_id = 5))) ORDER BY avg_max_speed DESC LIMIT 5

06-21 16:26:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:17 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816531 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'DC' AND player_id IN (SELECT player_id FROM t_player WHERE team_id IN (SELECT team_id FROM t_team WHERE country_id = 5))) ORDER BY avg_max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:17 -> SELECT player_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816531 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'DC' AND player_id IN (SELECT player_id FROM t_player WHERE team_id IN (SELECT team_id FROM t_team WHERE country_id = 5))) ORDER BY avg_max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, player_name, team_id, season_id, progressive_passes_total, progressive_passes_total_90 FROM vm_agg_season_player_opta WHERE season_id = 816531 AND position = 'DC' AND player_position = 'DC' AND player_secondary_position = 'DC' AND player_side_id = 1 AND dl_foot = 'left' ORDER BY progressive_passes_total_90 DESC LIMIT 5

06-21 16:26:19 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:19 -> SELECT player_id, player_name, team_id, season_id, progressive_passes_total, progressive_passes_total_90 FROM vm_agg_season_player_opta WHERE season_id = 816531 AND position = 'DC' AND player_position = 'DC' AND player_secondary_position = 'DC' AND player_side_id = 1 AND dl_foot = 'left' ORDER BY progressive_passes_total_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:19 -> SELECT player_id, player_name, team_id, season_id, progressive_passes_total, progressive_passes_total_90 FROM vm_agg_season_player_opta WHERE season_id = 816531 AND position = 'DC' AND player_position = 'DC' AND player_secondary_position = 'DC' AND player_side_id = 1 AND dl_foot = 'left' ORDER BY progressive_passes_total_90 DESC LIMIT 5

Successful query
Data Shape: (0, 6)
Running query: SELECT player_id, team_id, season_id, player_name, age, height, position, games, minutes_played, dl_index, ball_progression_90 FROM vm_agg_season_player_similarity WHERE position = 'DC' AND secondary_position = 'DL' AND age <= 25 AND dl_index < 50 AND season_id = 816527 ORDER BY ball_progression_90 DESC LIMIT 15

06-21 16:26:19 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:19 -> SELECT player_id, team_id, season_id, player_name, age, height, position, games, minutes_played, dl_index, ball_progression_90 FROM vm_agg_season_player_similarity WHERE position = 'DC' AND secondary_position = 'DL' AND age <= 25 AND dl_index < 50 AND season_id = 816527 ORDER BY ball_progression_90 DESC LIMIT 15
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:19 -> SELECT player_id, team_id, season_id, player_name, age, height, position, games, minutes_played, dl_index, ball_progression_90 FROM vm_agg_season_player_similarity WHERE position = 'DC' AND secondary_position = 'DL' AND age <= 25 AND dl_index < 50 AND season_id = 816527 ORDER BY ball_progression_90 DESC LIMIT 15

Successful query
Data Shape: (1, 11)
Running query: SELECT player_id, player_name, team_id, market_value, dl_index, max_speed, explosive_distance, hsr_distance, sprints_distance, accelerations, age FROM vm_agg_season_player_info WHERE position = 'DC' AND player_position_side = 'L' AND age <= 25 AND market_value < 50000000 AND league_name = 'La Liga' AND season_id = 816527 ORDER BY explosive_distance DESC LIMIT 15

06-21 16:26:19 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:19 -> SELECT player_id, player_name, team_id, market_value, dl_index, max_speed, explosive_distance, hsr_distance, sprints_distance, accelerations, age FROM vm_agg_season_player_info WHERE position = 'DC' AND player_position_side = 'L' AND age <= 25 AND market_value < 50000000 AND league_name = 'La Liga' AND season_id = 816527 ORDER BY explosive_distance DESC LIMIT 15
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:19 -> SELECT player_id, player_name, team_id, market_value, dl_index, max_speed, explosive_distance, hsr_distance, sprints_distance, accelerations, age FROM vm_agg_season_player_info WHERE position = 'DC' AND player_position_side = 'L' AND age <= 25 AND market_value < 50000000 AND league_name = 'La Liga' AND season_id = 816527 ORDER BY explosive_distance DESC LIMIT 15

Successful query
Data Shape: (0, 11)
Running query: SELECT player_id, player_name, team_id, season_id, progressive_passes_total FROM vm_agg_season_player_opta WHERE player_position = 'DC' AND player_secondary_position = 'DL' AND age <= 25 AND market_value < 50000000 AND league_country_name = 'Spain' AND season_id = 816527 ORDER BY progressive_passes_total DESC LIMIT 15

06-21 16:26:19 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:19 -> SELECT player_id, player_name, team_id, season_id, progressive_passes_total FROM vm_agg_season_player_opta WHERE player_position = 'DC' AND player_secondary_position = 'DL' AND age <= 25 AND market_value < 50000000 AND league_country_name = 'Spain' AND season_id = 816527 ORDER BY progressive_passes_total DESC LIMIT 15
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:19 -> SELECT player_id, player_name, team_id, season_id, progressive_passes_total FROM vm_agg_season_player_opta WHERE player_position = 'DC' AND player_secondary_position = 'DL' AND age <= 25 AND market_value < 50000000 AND league_country_name = 'Spain' AND season_id = 816527 ORDER BY progressive_passes_total DESC LIMIT 15

Successful query
Data Shape: (7, 5)
Running query: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_all WHERE season_id in (816529, 816528, 816527, 817313, 816531) ORDER BY max_speed DESC LIMIT 5

06-21 16:26:19 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:19 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_all WHERE season_id in (816529, 816528, 816527, 817313, 816531) ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:19 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_all WHERE season_id in (816529, 816528, 816527, 817313, 816531) ORDER BY max_speed DESC LIMIT 5
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...ECT player_id, team_id, season_id, max_speed FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, team_id, season_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 5

06-21 16:26:20 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:20 -> SELECT player_id, team_id, season_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:20 -> SELECT player_id, team_id, season_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, max_speed, player_name, team_id, season_id FROM vm_agg_season_player_info WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM vm_agg_season_player_info WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 5)

06-21 16:26:20 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:20 -> SELECT player_id, max_speed, player_name, team_id, season_id FROM vm_agg_season_player_info WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM vm_agg_season_player_info WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 5)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:20 -> SELECT player_id, max_speed, player_name, team_id, season_id FROM vm_agg_season_player_info WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM vm_agg_season_player_info WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 5)

Successful query
Data Shape: (5, 5)
Running query: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 5

06-21 16:26:20 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:20 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:20 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 5
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_...
                                              ^

Failed query
Running query: SELECT player_id, max_speed FROM vm_agg_season_player_opta WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 5

06-21 16:26:20 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:20 -> SELECT player_id, max_speed FROM vm_agg_season_player_opta WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:20 -> SELECT player_id, max_speed FROM vm_agg_season_player_opta WHERE season_id = 816529 ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, passes_total FROM vm_agg_season_player_info WHERE player_id = 1509277 AND season_id = 816527

06-21 16:26:20 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:20 -> SELECT player_id, passes_total FROM vm_agg_season_player_info WHERE player_id = 1509277 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:20 -> SELECT player_id, passes_total FROM vm_agg_season_player_info WHERE player_id = 1509277 AND season_id = 816527
ERROR:root:Database error: column "passes_total" does not exist
LINE 1: SELECT player_id, passes_total FROM vm_agg_season_player_inf...
                          ^

Failed query
Running query: SELECT passes_accurate_90 FROM vm_agg_season_player_similarity WHERE player_id = 1509277 AND season_id = 816527

06-21 16:26:20 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:20 -> SELECT passes_accurate_90 FROM vm_agg_season_player_similarity WHERE player_id = 1509277 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:20 -> SELECT passes_accurate_90 FROM vm_agg_season_player_similarity WHERE player_id = 1509277 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, SUM(passes_completed) AS total_passes_completed FROM vm_agg_season_player_all WHERE player_id = 1509277 AND season_year = 2023 AND season_id = 816527

06-21 16:26:20 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:20 -> SELECT player_id, SUM(passes_completed) AS total_passes_completed FROM vm_agg_season_player_all WHERE player_id = 1509277 AND season_year = 2023 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:20 -> SELECT player_id, SUM(passes_completed) AS total_passes_completed FROM vm_agg_season_player_all WHERE player_id = 1509277 AND season_year = 2023 AND season_id = 816527
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...(passes_completed) AS total_passes_completed FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT passes_total FROM vm_agg_season_player_opta WHERE player_id = 1509277 AND season_id = 816527

06-21 16:26:20 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:20 -> SELECT passes_total FROM vm_agg_season_player_opta WHERE player_id = 1509277 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:20 -> SELECT passes_total FROM vm_agg_season_player_opta WHERE player_id = 1509277 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT passes_total FROM public.agg_season_player_pd WHERE player_id = 1509277 AND season_id = 816527

06-21 16:26:20 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:20 -> SELECT passes_total FROM public.agg_season_player_pd WHERE player_id = 1509277 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:20 -> SELECT passes_total FROM public.agg_season_player_pd WHERE player_id = 1509277 AND season_id = 816527
ERROR:root:Database error: column "passes_total" does not exist
LINE 1: SELECT passes_total FROM public.agg_season_player_pd WHERE p...
               ^

Failed query
Running query: SELECT player_id, player_name, crosses_successful FROM vm_agg_season_player_info WHERE season_id = 816529 AND league_name = 'ENG I 2023' ORDER BY crosses_successful DESC LIMIT 1

06-21 16:26:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:21 -> SELECT player_id, player_name, crosses_successful FROM vm_agg_season_player_info WHERE season_id = 816529 AND league_name = 'ENG I 2023' ORDER BY crosses_successful DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:21 -> SELECT player_id, player_name, crosses_successful FROM vm_agg_season_player_info WHERE season_id = 816529 AND league_name = 'ENG I 2023' ORDER BY crosses_successful DESC LIMIT 1
ERROR:root:Database error: column "crosses_successful" does not exist
LINE 1: SELECT player_id, player_name, crosses_successful FROM vm_ag...
                                       ^

Failed query
Running query: SELECT player_id, SUM(successful_crosses) AS total_successful_crosses FROM vm_agg_season_player_all WHERE season_id = 816529 AND league_type_id = 1 GROUP BY player_id ORDER BY total_successful_crosses DESC LIMIT 1

06-21 16:26:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:21 -> SELECT player_id, SUM(successful_crosses) AS total_successful_crosses FROM vm_agg_season_player_all WHERE season_id = 816529 AND league_type_id = 1 GROUP BY player_id ORDER BY total_successful_crosses DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:21 -> SELECT player_id, SUM(successful_crosses) AS total_successful_crosses FROM vm_agg_season_player_all WHERE season_id = 816529 AND league_type_id = 1 GROUP BY player_id ORDER BY total_successful_crosses DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...cessful_crosses) AS total_successful_crosses FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, sum(successful_crosses) as total_successful_crosses FROM public.agg_season_player_pd WHERE season_id = 816529 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 2) GROUP BY player_id ORDER BY total_successful_crosses DESC LIMIT 1

06-21 16:26:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:21 -> SELECT player_id, sum(successful_crosses) as total_successful_crosses FROM public.agg_season_player_pd WHERE season_id = 816529 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 2) GROUP BY player_id ORDER BY total_successful_crosses DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:21 -> SELECT player_id, sum(successful_crosses) as total_successful_crosses FROM public.agg_season_player_pd WHERE season_id = 816529 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 2) GROUP BY player_id ORDER BY total_successful_crosses DESC LIMIT 1
ERROR:root:Database error: column "successful_crosses" does not exist
LINE 1: SELECT player_id, sum(successful_crosses) as total_successfu...
                              ^

Failed query
Running query: SELECT player_id, player_name, team_id, season_id, completed_crosses_90, open_play_key_passes_90 FROM vm_agg_season_player_similarity WHERE season_id = 816529 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 2) ORDER BY (completed_crosses_90 + open_play_key_passes_90) DESC LIMIT 1

06-21 16:26:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:21 -> SELECT player_id, player_name, team_id, season_id, completed_crosses_90, open_play_key_passes_90 FROM vm_agg_season_player_similarity WHERE season_id = 816529 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 2) ORDER BY (completed_crosses_90 + open_play_key_passes_90) DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:21 -> SELECT player_id, player_name, team_id, season_id, completed_crosses_90, open_play_key_passes_90 FROM vm_agg_season_player_similarity WHERE season_id = 816529 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 2) ORDER BY (completed_crosses_90 + open_play_key_passes_90) DESC LIMIT 1

Successful query
Data Shape: (1, 6)
Running query: SELECT player_id, player_name, crosses_successful, key_passes FROM vm_agg_season_player_opta WHERE season_id = 816529 AND league_country_name = 'England' AND crosses_successful + key_passes = (SELECT MAX(crosses_successful + key_passes) FROM vm_agg_season_player_opta WHERE season_id = 816529 AND league_country_name = 'England')

06-21 16:26:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:21 -> SELECT player_id, player_name, crosses_successful, key_passes FROM vm_agg_season_player_opta WHERE season_id = 816529 AND league_country_name = 'England' AND crosses_successful + key_passes = (SELECT MAX(crosses_successful + key_passes) FROM vm_agg_season_player_opta WHERE season_id = 816529 AND league_country_name = 'England')
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:21 -> SELECT player_id, player_name, crosses_successful, key_passes FROM vm_agg_season_player_opta WHERE season_id = 816529 AND league_country_name = 'England' AND crosses_successful + key_passes = (SELECT MAX(crosses_successful + key_passes) FROM vm_agg_season_player_opta WHERE season_id = 816529 AND league_country_name = 'England')
ERROR:root:Database error: column "crosses_successful" does not exist
LINE 1: SELECT player_id, player_name, crosses_successful, key_passe...
                                       ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_opta.crosses_successful_op".

Failed query
Running query: SELECT player_id, team_id, season_id, score_pd_float FROM public.agg_season_player_pd WHERE season_id = 816709 ORDER BY score_pd_float DESC LIMIT 5

06-21 16:26:21 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:21 -> SELECT player_id, team_id, season_id, score_pd_float FROM public.agg_season_player_pd WHERE season_id = 816709 ORDER BY score_pd_float DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:21 -> SELECT player_id, team_id, season_id, score_pd_float FROM public.agg_season_player_pd WHERE season_id = 816709 ORDER BY score_pd_float DESC LIMIT 5

Successful query
Data Shape: (0, 4)
Running query: SELECT player_id, player_name, season_id, diff_dl_index FROM vm_agg_season_player_info WHERE season_id = 816527 OR season_id = 816709 ORDER BY diff_dl_index DESC LIMIT 5

06-21 16:26:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:23 -> SELECT player_id, player_name, season_id, diff_dl_index FROM vm_agg_season_player_info WHERE season_id = 816527 OR season_id = 816709 ORDER BY diff_dl_index DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:23 -> SELECT player_id, player_name, season_id, diff_dl_index FROM vm_agg_season_player_info WHERE season_id = 816527 OR season_id = 816709 ORDER BY diff_dl_index DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, player_name, team_id, season_id, dl_index FROM vm_agg_season_player_similarity WHERE season_id = 816709 ORDER BY dl_index DESC LIMIT 5

06-21 16:26:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:23 -> SELECT player_id, player_name, team_id, season_id, dl_index FROM vm_agg_season_player_similarity WHERE season_id = 816709 ORDER BY dl_index DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:23 -> SELECT player_id, player_name, team_id, season_id, dl_index FROM vm_agg_season_player_similarity WHERE season_id = 816709 ORDER BY dl_index DESC LIMIT 5

Successful query
Data Shape: (0, 5)
Running query: SELECT player_id, player_name, season_id, dl_index, dl_index_float FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY dl_index DESC LIMIT 5

06-21 16:26:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:24 -> SELECT player_id, player_name, season_id, dl_index, dl_index_float FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY dl_index DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:24 -> SELECT player_id, player_name, season_id, dl_index, dl_index_float FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY dl_index DESC LIMIT 5

Successful query
Data Shape: (5, 5)
Running query: SELECT player_id, team_id, season_id, season_year, team_games_played, team_mins_played, mins_played, games_lost FROM vm_agg_season_player_all WHERE season_id = 816709 OR season_id = 816527 ORDER BY mins_played DESC LIMIT 5

06-21 16:26:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:24 -> SELECT player_id, team_id, season_id, season_year, team_games_played, team_mins_played, mins_played, games_lost FROM vm_agg_season_player_all WHERE season_id = 816709 OR season_id = 816527 ORDER BY mins_played DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:24 -> SELECT player_id, team_id, season_id, season_year, team_games_played, team_mins_played, mins_played, games_lost FROM vm_agg_season_player_all WHERE season_id = 816709 OR season_id = 816527 ORDER BY mins_played DESC LIMIT 5
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...d, team_mins_played, mins_played, games_lost FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, xg FROM vm_agg_season_player_info WHERE age < 25 AND games_played > 20 AND dl_foot = 'L' AND height > 180 AND season_id IN (SELECT season_id FROM vm_agg_season_player_info WHERE season_year = 2023) AND country_id = 1 ORDER BY xg DESC LIMIT 5

06-21 16:26:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:24 -> SELECT player_id, player_name, xg FROM vm_agg_season_player_info WHERE age < 25 AND games_played > 20 AND dl_foot = 'L' AND height > 180 AND season_id IN (SELECT season_id FROM vm_agg_season_player_info WHERE season_year = 2023) AND country_id = 1 ORDER BY xg DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:24 -> SELECT player_id, player_name, xg FROM vm_agg_season_player_info WHERE age < 25 AND games_played > 20 AND dl_foot = 'L' AND height > 180 AND season_id IN (SELECT season_id FROM vm_agg_season_player_info WHERE season_year = 2023) AND country_id = 1 ORDER BY xg DESC LIMIT 5

Successful query
Data Shape: (0, 3)
Running query: SELECT player_id, player_name, xg_90 FROM vm_agg_season_player_similarity WHERE season_id IN (SELECT season_id FROM t_season WHERE EXTRACT(year FROM season_start_date) = 2023) AND age < 25 AND games > 20 AND height > 180 AND secondary_field_position_id = 13 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY xg_90 DESC LIMIT 5

06-21 16:26:25 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:25 -> SELECT player_id, player_name, xg_90 FROM vm_agg_season_player_similarity WHERE season_id IN (SELECT season_id FROM t_season WHERE EXTRACT(year FROM season_start_date) = 2023) AND age < 25 AND games > 20 AND height > 180 AND secondary_field_position_id = 13 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY xg_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:25 -> SELECT player_id, player_name, xg_90 FROM vm_agg_season_player_similarity WHERE season_id IN (SELECT season_id FROM t_season WHERE EXTRACT(year FROM season_start_date) = 2023) AND age < 25 AND games > 20 AND height > 180 AND secondary_field_position_id = 13 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY xg_90 DESC LIMIT 5
ERROR:root:Database error: column "season_start_date" does not exist
LINE 1: ...T season_id FROM t_season WHERE EXTRACT(year FROM season_sta...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, xg FROM vm_agg_season_player_opta WHERE age < 25 AND games_played > 20 AND height > 180 AND dl_foot = 'left' AND season_id IN (SELECT season_id FROM vm_agg_season_player_opta WHERE season_year = 2023) ORDER BY xg DESC LIMIT 5

06-21 16:26:25 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:25 -> SELECT player_id, player_name, xg FROM vm_agg_season_player_opta WHERE age < 25 AND games_played > 20 AND height > 180 AND dl_foot = 'left' AND season_id IN (SELECT season_id FROM vm_agg_season_player_opta WHERE season_year = 2023) ORDER BY xg DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:25 -> SELECT player_id, player_name, xg FROM vm_agg_season_player_opta WHERE age < 25 AND games_played > 20 AND height > 180 AND dl_foot = 'left' AND season_id IN (SELECT season_id FROM vm_agg_season_player_opta WHERE season_year = 2023) ORDER BY xg DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, player_name, max_speed, season_id FROM vm_agg_season_player_info WHERE season_id = 816531 AND position = 'DC' AND dl_foot = 'Left' ORDER BY max_speed DESC LIMIT 5

06-21 16:26:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:30 -> SELECT player_id, player_name, max_speed, season_id FROM vm_agg_season_player_info WHERE season_id = 816531 AND position = 'DC' AND dl_foot = 'Left' ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:30 -> SELECT player_id, player_name, max_speed, season_id FROM vm_agg_season_player_info WHERE season_id = 816531 AND position = 'DC' AND dl_foot = 'Left' ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (0, 4)
Running query: SELECT player_id, player_name, team_id, season_id, progressive_runs_90 FROM vm_agg_season_player_opta WHERE season_id = 816531 AND position = 'DC' AND player_foot = 'Left' ORDER BY progressive_runs_90 DESC LIMIT 5

06-21 16:26:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:30 -> SELECT player_id, player_name, team_id, season_id, progressive_runs_90 FROM vm_agg_season_player_opta WHERE season_id = 816531 AND position = 'DC' AND player_foot = 'Left' ORDER BY progressive_runs_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:30 -> SELECT player_id, player_name, team_id, season_id, progressive_runs_90 FROM vm_agg_season_player_opta WHERE season_id = 816531 AND position = 'DC' AND player_foot = 'Left' ORDER BY progressive_runs_90 DESC LIMIT 5
ERROR:root:Database error: column "player_foot" does not exist
LINE 1: ... WHERE season_id = 816531 AND position = 'DC' AND player_foo...
                                                             ^

Failed query
Running query: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_all WHERE season_id IN (816664, 816711, 817309, 816649, 816600) ORDER BY max_speed DESC LIMIT 5

06-21 16:26:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:30 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_all WHERE season_id IN (816664, 816711, 817309, 816649, 816600) ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:30 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_all WHERE season_id IN (816664, 816711, 817309, 816649, 816600) ORDER BY max_speed DESC LIMIT 5
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...ECT player_id, team_id, season_id, max_speed FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816711 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 5

06-21 16:26:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:30 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816711 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:30 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816711 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 5
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_...
                                              ^

Failed query
Running query: SELECT player_id, team_id, season_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816711 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 5

06-21 16:26:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:30 -> SELECT player_id, team_id, season_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816711 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:30 -> SELECT player_id, team_id, season_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816711 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (0, 4)
Running query: SELECT player_id, max_speed, season_id FROM vm_agg_season_player_opta WHERE season_id = 816711 ORDER BY max_speed DESC LIMIT 5

06-21 16:26:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:30 -> SELECT player_id, max_speed, season_id FROM vm_agg_season_player_opta WHERE season_id = 816711 ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:30 -> SELECT player_id, max_speed, season_id FROM vm_agg_season_player_opta WHERE season_id = 816711 ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 ORDER BY dl_index DESC, mins_played ASC LIMIT 1

06-21 16:26:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:30 -> SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 ORDER BY dl_index DESC, mins_played ASC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:30 -> SELECT player_id, team_id, season_id FROM vm_agg_season_player_all WHERE season_id = 816527 ORDER BY dl_index DESC, mins_played ASC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, team_id, season_id FROM vm_agg_season_play...
                                                  ^

Failed query
Running query: SELECT player_id, team_id, score_pd_float FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY score_pd_float DESC, score_pd LIMIT 1

06-21 16:26:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:30 -> SELECT player_id, team_id, score_pd_float FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY score_pd_float DESC, score_pd LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:30 -> SELECT player_id, team_id, score_pd_float FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY score_pd_float DESC, score_pd LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, player_name, market_value, dl_index FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY market_value ASC, dl_index DESC LIMIT 1

06-21 16:26:30 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:30 -> SELECT player_id, player_name, market_value, dl_index FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY market_value ASC, dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:30 -> SELECT player_id, player_name, market_value, dl_index FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY market_value ASC, dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT player_id, team_id, season_id, dl_index FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY dl_index DESC, passes_accurate_90 DESC LIMIT 1

06-21 16:26:31 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:31 -> SELECT player_id, team_id, season_id, dl_index FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY dl_index DESC, passes_accurate_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:31 -> SELECT player_id, team_id, season_id, dl_index FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY dl_index DESC, passes_accurate_90 DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT player_id, player_name, market_value, dl_index FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY market_value ASC, dl_index DESC LIMIT 1

06-21 16:26:31 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:31 -> SELECT player_id, player_name, market_value, dl_index FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY market_value ASC, dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:31 -> SELECT player_id, player_name, market_value, dl_index FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY market_value ASC, dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT player_id, season_id, SUM(dl_index) AS total_score FROM vm_agg_season_player_similarity WHERE season_id IN (816527, 816019, 815453, 814198, 813658) GROUP BY player_id, season_id ORDER BY total_score DESC LIMIT 1

06-21 16:26:31 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:31 -> SELECT player_id, season_id, SUM(dl_index) AS total_score FROM vm_agg_season_player_similarity WHERE season_id IN (816527, 816019, 815453, 814198, 813658) GROUP BY player_id, season_id ORDER BY total_score DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:31 -> SELECT player_id, season_id, SUM(dl_index) AS total_score FROM vm_agg_season_player_similarity WHERE season_id IN (816527, 816019, 815453, 814198, 813658) GROUP BY player_id, season_id ORDER BY total_score DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, season_id, season_year FROM vm_agg_season_player_all WHERE season_id = 816527 ORDER BY team_games_played DESC LIMIT 1

06-21 16:26:31 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:31 -> SELECT player_id, season_id, season_year FROM vm_agg_season_player_all WHERE season_id = 816527 ORDER BY team_games_played DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:31 -> SELECT player_id, season_id, season_year FROM vm_agg_season_player_all WHERE season_id = 816527 ORDER BY team_games_played DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, season_id, season_year FROM vm_agg_season_...
                                                      ^

Failed query
Running query: SELECT player_id, player_name, goals, season_id FROM vm_agg_season_player_info WHERE season_id in (816527, 816019, 815453, 814198, 813658) AND league_country_name = 'Spain' AND player_position IN ('FW', 'AML', 'AMR', 'FWL', 'FWR') ORDER BY goals DESC

06-21 16:26:33 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:33 -> SELECT player_id, player_name, goals, season_id FROM vm_agg_season_player_info WHERE season_id in (816527, 816019, 815453, 814198, 813658) AND league_country_name = 'Spain' AND player_position IN ('FW', 'AML', 'AMR', 'FWL', 'FWR') ORDER BY goals DESC
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:33 -> SELECT player_id, player_name, goals, season_id FROM vm_agg_season_player_info WHERE season_id in (816527, 816019, 815453, 814198, 813658) AND league_country_name = 'Spain' AND player_position IN ('FW', 'AML', 'AMR', 'FWL', 'FWR') ORDER BY goals DESC

Successful query
Data Shape: (20, 4)
Running query: SELECT player_id, goals, season_id FROM vm_agg_season_player_opta WHERE season_id IN (816527, 816019, 815453, 814198, 813658) AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

06-21 16:26:33 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:33 -> SELECT player_id, goals, season_id FROM vm_agg_season_player_opta WHERE season_id IN (816527, 816019, 815453, 814198, 813658) AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:33 -> SELECT player_id, goals, season_id FROM vm_agg_season_player_opta WHERE season_id IN (816527, 816019, 815453, 814198, 813658) AND goals IS NOT NULL ORDER BY goals DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND score_pd = 1 ORDER BY score_pd_float DESC LIMIT 5

06-21 16:26:33 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:33 -> SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND score_pd = 1 ORDER BY score_pd_float DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:33 -> SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND score_pd = 1 ORDER BY score_pd_float DESC LIMIT 5

Successful query
Data Shape: (0, 1)
Running query: SELECT player_id, COUNT(goal_id) as left_footed_goals FROM public.t_goal WHERE body_part_id = 1 AND season_id = 816527 GROUP BY player_id ORDER BY left_footed_goals DESC LIMIT 5

06-21 16:26:34 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:34 -> SELECT player_id, COUNT(goal_id) as left_footed_goals FROM public.t_goal WHERE body_part_id = 1 AND season_id = 816527 GROUP BY player_id ORDER BY left_footed_goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:34 -> SELECT player_id, COUNT(goal_id) as left_footed_goals FROM public.t_goal WHERE body_part_id = 1 AND season_id = 816527 GROUP BY player_id ORDER BY left_footed_goals DESC LIMIT 5
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...als FROM public.t_goal WHERE body_part_id = 1 AND season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND player_position = 'FWL' ORDER BY goals DESC LIMIT 5

06-21 16:26:34 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:34 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND player_position = 'FWL' ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:34 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_info WHERE season_id = 816527 AND player_position = 'FWL' ORDER BY goals DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND position = 'FWL' ORDER BY goals_90 DESC LIMIT 5

06-21 16:26:34 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:34 -> SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND position = 'FWL' ORDER BY goals_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:34 -> SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND position = 'FWL' ORDER BY goals_90 DESC LIMIT 5
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: SELECT player_id, player_name, goals_90 FROM vm_agg_season_p...
                                       ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND player_position = 'FWL' ORDER BY goals DESC LIMIT 5

06-21 16:26:34 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:34 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND player_position = 'FWL' ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:34 -> SELECT player_id, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND player_position = 'FWL' ORDER BY goals DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, max_speed, team_id FROM public.agg_season_player_pd WHERE age <= 25 AND position = 'DC' AND max_speed < 50 AND season_id = 816529 ORDER BY max_speed DESC LIMIT 1

06-21 16:26:34 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:34 -> SELECT player_id, max_speed, team_id FROM public.agg_season_player_pd WHERE age <= 25 AND position = 'DC' AND max_speed < 50 AND season_id = 816529 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:34 -> SELECT player_id, max_speed, team_id FROM public.agg_season_player_pd WHERE age <= 25 AND position = 'DC' AND max_speed < 50 AND season_id = 816529 ORDER BY max_speed DESC LIMIT 1
ERROR:root:Database error: column "age" does not exist
LINE 1: ...d, team_id FROM public.agg_season_player_pd WHERE age <= 25 ...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, player_position, market_value, max_speed, dl_index, dl_foot, height FROM vm_agg_season_player_info WHERE age <= 25 AND player_position = 'DC' AND dl_foot = 'left' AND market_value < 50000000 AND league_name IN ('ENG I', 'FRA I', 'ITA I', 'ESP I', 'W ITA I') ORDER BY explosive_distance DESC LIMIT 1

06-21 16:26:34 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:34 -> SELECT player_id, player_name, player_position, market_value, max_speed, dl_index, dl_foot, height FROM vm_agg_season_player_info WHERE age <= 25 AND player_position = 'DC' AND dl_foot = 'left' AND market_value < 50000000 AND league_name IN ('ENG I', 'FRA I', 'ITA I', 'ESP I', 'W ITA I') ORDER BY explosive_distance DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:34 -> SELECT player_id, player_name, player_position, market_value, max_speed, dl_index, dl_foot, height FROM vm_agg_season_player_info WHERE age <= 25 AND player_position = 'DC' AND dl_foot = 'left' AND market_value < 50000000 AND league_name IN ('ENG I', 'FRA I', 'ITA I', 'ESP I', 'W ITA I') ORDER BY explosive_distance DESC LIMIT 1

Successful query
Data Shape: (0, 8)
Running query: SELECT player_id, player_name, team_name, age, market_value, progressive_runs FROM vm_agg_season_player_opta WHERE age <= 25 AND player_position = 'DC' AND dl_foot = 'left' AND market_value < 50000000 AND league_country_name IN ('Spain', 'England', 'Germany', 'Italy', 'France') AND season_id = 816529 ORDER BY progressive_runs DESC LIMIT 1

06-21 16:26:35 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:35 -> SELECT player_id, player_name, team_name, age, market_value, progressive_runs FROM vm_agg_season_player_opta WHERE age <= 25 AND player_position = 'DC' AND dl_foot = 'left' AND market_value < 50000000 AND league_country_name IN ('Spain', 'England', 'Germany', 'Italy', 'France') AND season_id = 816529 ORDER BY progressive_runs DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:35 -> SELECT player_id, player_name, team_name, age, market_value, progressive_runs FROM vm_agg_season_player_opta WHERE age <= 25 AND player_position = 'DC' AND dl_foot = 'left' AND market_value < 50000000 AND league_country_name IN ('Spain', 'England', 'Germany', 'Italy', 'France') AND season_id = 816529 ORDER BY progressive_runs DESC LIMIT 1

Successful query
Data Shape: (1, 6)
Running query: SELECT player_id, team_id, season_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'DC' AND age <= 25) ORDER BY avg_max_speed DESC LIMIT 10

06-21 16:26:35 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:35 -> SELECT player_id, team_id, season_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'DC' AND age <= 25) ORDER BY avg_max_speed DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:35 -> SELECT player_id, team_id, season_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'DC' AND age <= 25) ORDER BY avg_max_speed DESC LIMIT 10

Successful query
Data Shape: (10, 4)
Running query: SELECT player_id, team_id, season_id, progressive_carries_90 FROM vm_agg_season_player_similarity WHERE age <= 25 AND position = 'DC' AND season_id IN (816529, 816527, 816528, 817311, 816531) AND field_position_id = 3 AND secondary_field_position_id = 3 ORDER BY progressive_carries_90 DESC LIMIT 10

06-21 16:26:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:36 -> SELECT player_id, team_id, season_id, progressive_carries_90 FROM vm_agg_season_player_similarity WHERE age <= 25 AND position = 'DC' AND season_id IN (816529, 816527, 816528, 817311, 816531) AND field_position_id = 3 AND secondary_field_position_id = 3 ORDER BY progressive_carries_90 DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:36 -> SELECT player_id, team_id, season_id, progressive_carries_90 FROM vm_agg_season_player_similarity WHERE age <= 25 AND position = 'DC' AND season_id IN (816529, 816527, 816528, 817311, 816531) AND field_position_id = 3 AND secondary_field_position_id = 3 ORDER BY progressive_carries_90 DESC LIMIT 10
ERROR:root:Database error: column "progressive_carries_90" does not exist
LINE 1: SELECT player_id, team_id, season_id, progressive_carries_90...
                                              ^

Failed query
Running query: SELECT player_id, player_name, team_name, season_id, percent_progressive_passes_total FROM vm_agg_season_player_opta WHERE season_id = 816529 AND player_position = 'DC' AND player_secondary_position = 'DL' AND age <= 25 ORDER BY percent_progressive_passes_total DESC LIMIT 10

06-21 16:26:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:36 -> SELECT player_id, player_name, team_name, season_id, percent_progressive_passes_total FROM vm_agg_season_player_opta WHERE season_id = 816529 AND player_position = 'DC' AND player_secondary_position = 'DL' AND age <= 25 ORDER BY percent_progressive_passes_total DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:36 -> SELECT player_id, player_name, team_name, season_id, percent_progressive_passes_total FROM vm_agg_season_player_opta WHERE season_id = 816529 AND player_position = 'DC' AND player_secondary_position = 'DL' AND age <= 25 ORDER BY percent_progressive_passes_total DESC LIMIT 10

Successful query
Data Shape: (8, 5)
Running query: SELECT player_id, player_name, dribbles_per_90 FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY dribbles_per_90 DESC LIMIT 5

06-21 16:26:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:36 -> SELECT player_id, player_name, dribbles_per_90 FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY dribbles_per_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:36 -> SELECT player_id, player_name, dribbles_per_90 FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY dribbles_per_90 DESC LIMIT 5
ERROR:root:Database error: column "dribbles_per_90" does not exist
LINE 1: SELECT player_id, player_name, dribbles_per_90 FROM vm_agg_s...
                                       ^

Failed query
Running query: SELECT player_id, avg_max_acceleration FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY avg_max_acceleration DESC LIMIT 5

06-21 16:26:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:36 -> SELECT player_id, avg_max_acceleration FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY avg_max_acceleration DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:36 -> SELECT player_id, avg_max_acceleration FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY avg_max_acceleration DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, team_id, season_id, dribbles_won_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY dribbles_won_90 DESC LIMIT 5

06-21 16:26:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:36 -> SELECT player_id, team_id, season_id, dribbles_won_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY dribbles_won_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:36 -> SELECT player_id, team_id, season_id, dribbles_won_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY dribbles_won_90 DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, team_id, season_id, season_year, player_name, age, player_country_code, team_games_played, team_mins_played, mins_played, games_lost FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY (dribbles_total / (mins_played / 90)) DESC LIMIT 5

06-21 16:26:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:36 -> SELECT player_id, team_id, season_id, season_year, player_name, age, player_country_code, team_games_played, team_mins_played, mins_played, games_lost FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY (dribbles_total / (mins_played / 90)) DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:36 -> SELECT player_id, team_id, season_id, season_year, player_name, age, player_country_code, team_games_played, team_mins_played, mins_played, games_lost FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY (dribbles_total / (mins_played / 90)) DESC LIMIT 5
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...d, team_mins_played, mins_played, games_lost FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, dribbles_90 FROM vm_agg_season_player_opta WHERE season_id = 816527 AND player_id NOT IN (SELECT player_id FROM vm_agg_season_player_opta WHERE season_id = 816527 AND player_position = 'GK') ORDER BY dribbles_90 DESC LIMIT 5

06-21 16:26:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:36 -> SELECT player_id, player_name, dribbles_90 FROM vm_agg_season_player_opta WHERE season_id = 816527 AND player_id NOT IN (SELECT player_id FROM vm_agg_season_player_opta WHERE season_id = 816527 AND player_position = 'GK') ORDER BY dribbles_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:36 -> SELECT player_id, player_name, dribbles_90 FROM vm_agg_season_player_opta WHERE season_id = 816527 AND player_id NOT IN (SELECT player_id FROM vm_agg_season_player_opta WHERE season_id = 816527 AND player_position = 'GK') ORDER BY dribbles_90 DESC LIMIT 5
ERROR:root:Database error: column "dribbles_90" does not exist
LINE 1: SELECT player_id, player_name, dribbles_90 FROM vm_agg_seaso...
                                       ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_opta.dribbles_won".

Failed query
Running query: SELECT player_id, dl_index, team_id, season_id FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:36 -> SELECT player_id, dl_index, team_id, season_id FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:36 -> SELECT player_id, dl_index, team_id, season_id FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 4)
Running query: SELECT player_id, score_pd_float FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY score_pd_float DESC LIMIT 1

06-21 16:26:36 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:36 -> SELECT player_id, score_pd_float FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY score_pd_float DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:36 -> SELECT player_id, score_pd_float FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY score_pd_float DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, player_name, market_value, dl_index, dl_index_float FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY dl_index_float DESC LIMIT 1

06-21 16:26:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:39 -> SELECT player_id, player_name, market_value, dl_index, dl_index_float FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY dl_index_float DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:39 -> SELECT player_id, player_name, market_value, dl_index, dl_index_float FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY dl_index_float DESC LIMIT 1

Successful query
Data Shape: (1, 5)
Running query: SELECT player_name, market_value, dl_index FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:39 -> SELECT player_name, market_value, dl_index FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:39 -> SELECT player_name, market_value, dl_index FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, team_id, season_id, (team_games_played + team_mins_played + mins_played + games_lost) / dl_index AS stats_market_value_ratio  FROM vm_agg_season_player_all  WHERE season_id = 816527  ORDER BY stats_market_value_ratio DESC LIMIT 1

06-21 16:26:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:39 -> SELECT player_id, team_id, season_id, (team_games_played + team_mins_played + mins_played + games_lost) / dl_index AS stats_market_value_ratio  FROM vm_agg_season_player_all  WHERE season_id = 816527  ORDER BY stats_market_value_ratio DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:39 -> SELECT player_id, team_id, season_id, (team_games_played + team_mins_played + mins_played + games_lost) / dl_index AS stats_market_value_ratio  FROM vm_agg_season_player_all  WHERE season_id = 816527  ORDER BY stats_market_value_ratio DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...ost) / dl_index AS stats_market_value_ratio  FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, age FROM vm_agg_season_player_all WHERE team_id = 4265 AND season_id = 816527 AND age < 25 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:39 -> SELECT player_id, player_name, age FROM vm_agg_season_player_all WHERE team_id = 4265 AND season_id = 816527 AND age < 25 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:39 -> SELECT player_id, player_name, age FROM vm_agg_season_player_all WHERE team_id = 4265 AND season_id = 816527 AND age < 25 ORDER BY dl_index DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT player_id, player_name, age FROM vm_agg_season_player...
                                                ^

Failed query
Running query: SELECT player_id, player_name, age, position FROM vm_agg_year_player_info WHERE team_id = 4265 AND age < 25 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:39 -> SELECT player_id, player_name, age, position FROM vm_agg_year_player_info WHERE team_id = 4265 AND age < 25 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:39 -> SELECT player_id, player_name, age, position FROM vm_agg_year_player_info WHERE team_id = 4265 AND age < 25 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
ERROR:root:Database error: column "team_id" does not exist
LINE 1: ... age, position FROM vm_agg_year_player_info WHERE team_id = ...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, age, position FROM vm_agg_year_player_loan WHERE player_team_id = 4265 AND age < 25 AND current_season_id = 816527

06-21 16:26:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:39 -> SELECT player_id, player_name, age, position FROM vm_agg_year_player_loan WHERE player_team_id = 4265 AND age < 25 AND current_season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:39 -> SELECT player_id, player_name, age, position FROM vm_agg_year_player_loan WHERE player_team_id = 4265 AND age < 25 AND current_season_id = 816527

Successful query
Data Shape: (8, 4)
Running query: SELECT player_id, team_id, match_id, mins_played_team, mins_played, positions_played FROM public.vm_fac_games_player WHERE team_id = 4265 AND player_id IN (SELECT player_id FROM t_player WHERE age < 25) AND season_id = 816527

06-21 16:26:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:39 -> SELECT player_id, team_id, match_id, mins_played_team, mins_played, positions_played FROM public.vm_fac_games_player WHERE team_id = 4265 AND player_id IN (SELECT player_id FROM t_player WHERE age < 25) AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:39 -> SELECT player_id, team_id, match_id, mins_played_team, mins_played, positions_played FROM public.vm_fac_games_player WHERE team_id = 4265 AND player_id IN (SELECT player_id FROM t_player WHERE age < 25) AND season_id = 816527
ERROR:root:Database error: relation "public.vm_fac_games_player" does not exist
LINE 1: ...s_played_team, mins_played, positions_played FROM public.vm_...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, age, team_id, season_id, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND age < 25 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

06-21 16:26:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:39 -> SELECT player_id, player_name, age, team_id, season_id, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND age < 25 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:39 -> SELECT player_id, player_name, age, team_id, season_id, dl_index FROM vm_agg_season_player_similarity WHERE team_id = 4265 AND age < 25 AND season_id = 816527 ORDER BY dl_index DESC LIMIT 1

Successful query
Data Shape: (1, 6)
Running query: SELECT games FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527

06-21 16:26:39 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:39 -> SELECT games FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:39 -> SELECT games FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT COUNT(*) FROM vm_agg_season_player_all WHERE player_id = 1163220 AND team_id = 4265 AND season_id = 816527

06-21 16:26:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:40 -> SELECT COUNT(*) FROM vm_agg_season_player_all WHERE player_id = 1163220 AND team_id = 4265 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:40 -> SELECT COUNT(*) FROM vm_agg_season_player_all WHERE player_id = 1163220 AND team_id = 4265 AND season_id = 816527
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT COUNT(*) FROM vm_agg_season_player_all WHERE player_i...
                             ^

Failed query
Running query: SELECT games_played_65mins FROM public.agg_season_player_pd WHERE player_id = 1163220 AND team_id = 4265 AND season_id = 816527

06-21 16:26:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:40 -> SELECT games_played_65mins FROM public.agg_season_player_pd WHERE player_id = 1163220 AND team_id = 4265 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:40 -> SELECT games_played_65mins FROM public.agg_season_player_pd WHERE player_id = 1163220 AND team_id = 4265 AND season_id = 816527

Successful query
Data Shape: (4, 1)
Running query: SELECT COUNT(*) FROM public.vt_game_stat_player WHERE player_id = 1163220 AND team_id = 4265 AND season_id = 816527

06-21 16:26:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:40 -> SELECT COUNT(*) FROM public.vt_game_stat_player WHERE player_id = 1163220 AND team_id = 4265 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:40 -> SELECT COUNT(*) FROM public.vt_game_stat_player WHERE player_id = 1163220 AND team_id = 4265 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT COUNT(*) FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527

06-21 16:26:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:40 -> SELECT COUNT(*) FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:40 -> SELECT COUNT(*) FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, player_name, avg_max_speed FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY avg_max_speed DESC LIMIT 5

06-21 16:26:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:40 -> SELECT player_id, player_name, avg_max_speed FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY avg_max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:40 -> SELECT player_id, player_name, avg_max_speed FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' ORDER BY avg_max_speed DESC LIMIT 5

Successful query
Data Shape: (0, 3)
Running query: SELECT player_id, team_id, season_id, avg_max_acceleration FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY avg_max_acceleration DESC LIMIT 5

06-21 16:26:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:40 -> SELECT player_id, team_id, season_id, avg_max_acceleration FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY avg_max_acceleration DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:40 -> SELECT player_id, team_id, season_id, avg_max_acceleration FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY avg_max_acceleration DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, team_id, season_id, player_name, (team_mins_played::decimal / 90) AS dribblers_per_90 FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY dribblers_per_90 DESC LIMIT 5

06-21 16:26:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:40 -> SELECT player_id, team_id, season_id, player_name, (team_mins_played::decimal / 90) AS dribblers_per_90 FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY dribblers_per_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:40 -> SELECT player_id, team_id, season_id, player_name, (team_mins_played::decimal / 90) AS dribblers_per_90 FROM vm_agg_season_player_all WHERE season_id = 816527 AND league_type_id = 1 ORDER BY dribblers_per_90 DESC LIMIT 5
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...ns_played::decimal / 90) AS dribblers_per_90 FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, team_id, season_id, dribbles_won_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY dribbles_won_90 DESC

06-21 16:26:40 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:40 -> SELECT player_id, player_name, team_id, season_id, dribbles_won_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY dribbles_won_90 DESC
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:40 -> SELECT player_id, player_name, team_id, season_id, dribbles_won_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 1) ORDER BY dribbles_won_90 DESC

Successful query
Data Shape: (20, 5)
Running query: SELECT player_id, player_name, dribbles_total_90 FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_country_name = 'Spain' ORDER BY dribbles_total_90 DESC

06-21 16:26:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:41 -> SELECT player_id, player_name, dribbles_total_90 FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_country_name = 'Spain' ORDER BY dribbles_total_90 DESC
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:41 -> SELECT player_id, player_name, dribbles_total_90 FROM vm_agg_season_player_opta WHERE season_id = 816527 AND league_country_name = 'Spain' ORDER BY dribbles_total_90 DESC

Successful query
Data Shape: (20, 3)
Running query: SELECT player_id, player_name, assists, crosses_total FROM vm_agg_season_player_info WHERE season_id = 816529 AND player_position = 'FWR' AND league_name = 'Premier League' ORDER BY crosses_total DESC LIMIT 1

06-21 16:26:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:41 -> SELECT player_id, player_name, assists, crosses_total FROM vm_agg_season_player_info WHERE season_id = 816529 AND player_position = 'FWR' AND league_name = 'Premier League' ORDER BY crosses_total DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:41 -> SELECT player_id, player_name, assists, crosses_total FROM vm_agg_season_player_info WHERE season_id = 816529 AND player_position = 'FWR' AND league_name = 'Premier League' ORDER BY crosses_total DESC LIMIT 1
ERROR:root:Database error: column "crosses_total" does not exist
LINE 1: SELECT player_id, player_name, assists, crosses_total FROM v...
                                                ^

Failed query
Running query: SELECT player_id, player_name, team_id, season_id, completed_crosses_90 FROM vm_agg_season_player_similarity WHERE season_id = 816529 AND position = 'FWR' AND country_id = 2 ORDER BY completed_crosses_90 DESC LIMIT 1

06-21 16:26:41 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:41 -> SELECT player_id, player_name, team_id, season_id, completed_crosses_90 FROM vm_agg_season_player_similarity WHERE season_id = 816529 AND position = 'FWR' AND country_id = 2 ORDER BY completed_crosses_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:41 -> SELECT player_id, player_name, team_id, season_id, completed_crosses_90 FROM vm_agg_season_player_similarity WHERE season_id = 816529 AND position = 'FWR' AND country_id = 2 ORDER BY completed_crosses_90 DESC LIMIT 1
ERROR:root:Database error: column "country_id" does not exist
LINE 1: ...WHERE season_id = 816529 AND position = 'FWR' AND country_id...
                                                             ^

Failed query
Running query: SELECT player_id, season_id, sum(successful_crosses) AS total_successful_crosses FROM public.agg_season_player_pd WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'FWR') GROUP BY player_id, season_id ORDER BY total_successful_crosses DESC LIMIT 1

06-21 16:26:43 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:43 -> SELECT player_id, season_id, sum(successful_crosses) AS total_successful_crosses FROM public.agg_season_player_pd WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'FWR') GROUP BY player_id, season_id ORDER BY total_successful_crosses DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:43 -> SELECT player_id, season_id, sum(successful_crosses) AS total_successful_crosses FROM public.agg_season_player_pd WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'FWR') GROUP BY player_id, season_id ORDER BY total_successful_crosses DESC LIMIT 1
ERROR:root:Database error: column "successful_crosses" does not exist
LINE 1: SELECT player_id, season_id, sum(successful_crosses) AS tota...
                                         ^

Failed query
Running query: SELECT player_id, player_name, crosses_successful FROM vm_agg_season_player_opta WHERE season_id = 816529 AND player_position = 'RW' AND league_country_name = 'England' ORDER BY crosses_successful DESC LIMIT 1

06-21 16:26:43 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:43 -> SELECT player_id, player_name, crosses_successful FROM vm_agg_season_player_opta WHERE season_id = 816529 AND player_position = 'RW' AND league_country_name = 'England' ORDER BY crosses_successful DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:43 -> SELECT player_id, player_name, crosses_successful FROM vm_agg_season_player_opta WHERE season_id = 816529 AND player_position = 'RW' AND league_country_name = 'England' ORDER BY crosses_successful DESC LIMIT 1
ERROR:root:Database error: column "crosses_successful" does not exist
LINE 1: SELECT player_id, player_name, crosses_successful FROM vm_ag...
                                       ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_opta.crosses_successful_op".

Failed query
Running query: SELECT player_id, player_name, team_id, season_id, progressive_carries_90 FROM vm_agg_season_player_similarity WHERE position = 'DC' AND secondary_position = 'DL' AND age <= 25 AND dl_index < 50 ORDER BY progressive_carries_90 DESC LIMIT 10

06-21 16:26:43 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:43 -> SELECT player_id, player_name, team_id, season_id, progressive_carries_90 FROM vm_agg_season_player_similarity WHERE position = 'DC' AND secondary_position = 'DL' AND age <= 25 AND dl_index < 50 ORDER BY progressive_carries_90 DESC LIMIT 10
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:43 -> SELECT player_id, player_name, team_id, season_id, progressive_carries_90 FROM vm_agg_season_player_similarity WHERE position = 'DC' AND secondary_position = 'DL' AND age <= 25 AND dl_index < 50 ORDER BY progressive_carries_90 DESC LIMIT 10
ERROR:root:Database error: column "progressive_carries_90" does not exist
LINE 1: ...ELECT player_id, player_name, team_id, season_id, progressiv...
                                                             ^

Failed query
Running query: SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id IN (SELECT season_id FROM public.agg_season_player_pd WHERE provider_id = 5) AND player_id IN (SELECT player_id FROM t_player WHERE position = 'DC' AND age <= 25) AND max_speed < 50 AND player_id IN (SELECT player_id FROM t_player WHERE country_id = 5) ORDER BY max_speed DESC LIMIT 5

06-21 16:26:43 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:43 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id IN (SELECT season_id FROM public.agg_season_player_pd WHERE provider_id = 5) AND player_id IN (SELECT player_id FROM t_player WHERE position = 'DC' AND age <= 25) AND max_speed < 50 AND player_id IN (SELECT player_id FROM t_player WHERE country_id = 5) ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:43 -> SELECT player_id, max_speed FROM public.agg_season_player_pd WHERE season_id IN (SELECT season_id FROM public.agg_season_player_pd WHERE provider_id = 5) AND player_id IN (SELECT player_id FROM t_player WHERE position = 'DC' AND age <= 25) AND max_speed < 50 AND player_id IN (SELECT player_id FROM t_player WHERE country_id = 5) ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (0, 2)
Running query: SELECT player_id, team_id, season_id, progressive_carries_90 FROM vm_agg_season_player_similarity WHERE age <= 25 AND position = 'DC' AND season_id IN (SELECT season_id FROM t_season WHERE year = 2023 AND division_id = 1) ORDER BY progressive_carries_90 DESC LIMIT 1

06-21 16:26:44 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:44 -> SELECT player_id, team_id, season_id, progressive_carries_90 FROM vm_agg_season_player_similarity WHERE age <= 25 AND position = 'DC' AND season_id IN (SELECT season_id FROM t_season WHERE year = 2023 AND division_id = 1) ORDER BY progressive_carries_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:44 -> SELECT player_id, team_id, season_id, progressive_carries_90 FROM vm_agg_season_player_similarity WHERE age <= 25 AND position = 'DC' AND season_id IN (SELECT season_id FROM t_season WHERE year = 2023 AND division_id = 1) ORDER BY progressive_carries_90 DESC LIMIT 1
ERROR:root:Database error: column "progressive_carries_90" does not exist
LINE 1: SELECT player_id, team_id, season_id, progressive_carries_90...
                                              ^

Failed query
Running query: SELECT player_id, team_id, season_id, progressive_carries_per_90 FROM vm_agg_season_player_all WHERE age <= 25 AND season_year = 2023 AND league_type_id = 1 AND player_id IN (SELECT player_id FROM vm_agg_season_player_all WHERE position = 'DC' AND player_id IN (SELECT player_id FROM vm_agg_season_player_all WHERE foot = 'left')) ORDER BY progressive_carries_per_90 DESC LIMIT 1

06-21 16:26:44 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:44 -> SELECT player_id, team_id, season_id, progressive_carries_per_90 FROM vm_agg_season_player_all WHERE age <= 25 AND season_year = 2023 AND league_type_id = 1 AND player_id IN (SELECT player_id FROM vm_agg_season_player_all WHERE position = 'DC' AND player_id IN (SELECT player_id FROM vm_agg_season_player_all WHERE foot = 'left')) ORDER BY progressive_carries_per_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:44 -> SELECT player_id, team_id, season_id, progressive_carries_per_90 FROM vm_agg_season_player_all WHERE age <= 25 AND season_year = 2023 AND league_type_id = 1 AND player_id IN (SELECT player_id FROM vm_agg_season_player_all WHERE position = 'DC' AND player_id IN (SELECT player_id FROM vm_agg_season_player_all WHERE foot = 'left')) ORDER BY progressive_carries_per_90 DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...am_id, season_id, progressive_carries_per_90 FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, team_id, season_id, progressive_runs_90 FROM vm_agg_season_player_opta WHERE player_position = 'DC' AND dl_foot = 'left' AND age <= 25 AND season_id IN (SELECT season_id FROM vm_agg_season_player_opta WHERE season_year = 2023) ORDER BY progressive_runs_90 DESC LIMIT 1

06-21 16:26:44 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:44 -> SELECT player_id, player_name, team_id, season_id, progressive_runs_90 FROM vm_agg_season_player_opta WHERE player_position = 'DC' AND dl_foot = 'left' AND age <= 25 AND season_id IN (SELECT season_id FROM vm_agg_season_player_opta WHERE season_year = 2023) ORDER BY progressive_runs_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:44 -> SELECT player_id, player_name, team_id, season_id, progressive_runs_90 FROM vm_agg_season_player_opta WHERE player_position = 'DC' AND dl_foot = 'left' AND age <= 25 AND season_id IN (SELECT season_id FROM vm_agg_season_player_opta WHERE season_year = 2023) ORDER BY progressive_runs_90 DESC LIMIT 1

Successful query
Data Shape: (1, 5)
Running query: SELECT player_id, team_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 OR season_id = 816528 OR season_id = 816529 OR season_id = 816531 OR season_id = 817309 ORDER BY max_speed DESC LIMIT 5

06-21 16:26:56 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:56 -> SELECT player_id, team_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 OR season_id = 816528 OR season_id = 816529 OR season_id = 816531 OR season_id = 817309 ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:56 -> SELECT player_id, team_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 OR season_id = 816528 OR season_id = 816529 OR season_id = 816531 OR season_id = 817309 ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, player_name, max_speed, team_id, season_id FROM vm_agg_season_player_info WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM vm_agg_season_player_info WHERE season_id = 816529 AND league_name = 'ENG I' ORDER BY max_speed DESC LIMIT 5)

06-21 16:26:56 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:56 -> SELECT player_id, player_name, max_speed, team_id, season_id FROM vm_agg_season_player_info WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM vm_agg_season_player_info WHERE season_id = 816529 AND league_name = 'ENG I' ORDER BY max_speed DESC LIMIT 5)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:56 -> SELECT player_id, player_name, max_speed, team_id, season_id FROM vm_agg_season_player_info WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM vm_agg_season_player_info WHERE season_id = 816529 AND league_name = 'ENG I' ORDER BY max_speed DESC LIMIT 5)

Successful query
Data Shape: (0, 5)
Running query: SELECT player_id, team_id, season_id, mins_played FROM vm_agg_season_player_all WHERE season_id = 816529 AND player_id NOT IN (SELECT player_id FROM vm_agg_season_player_all WHERE mins_played IS NULL) AND player_id IN (SELECT player_id FROM vm_agg_season_player_all WHERE season_id = 816529 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 2)) ORDER BY mins_played DESC LIMIT 5

06-21 16:26:56 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:56 -> SELECT player_id, team_id, season_id, mins_played FROM vm_agg_season_player_all WHERE season_id = 816529 AND player_id NOT IN (SELECT player_id FROM vm_agg_season_player_all WHERE mins_played IS NULL) AND player_id IN (SELECT player_id FROM vm_agg_season_player_all WHERE season_id = 816529 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 2)) ORDER BY mins_played DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:56 -> SELECT player_id, team_id, season_id, mins_played FROM vm_agg_season_player_all WHERE season_id = 816529 AND player_id NOT IN (SELECT player_id FROM vm_agg_season_player_all WHERE mins_played IS NULL) AND player_id IN (SELECT player_id FROM vm_agg_season_player_all WHERE season_id = 816529 AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 2)) ORDER BY mins_played DESC LIMIT 5
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...T player_id, team_id, season_id, mins_played FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT COUNT(*) FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527 AND xg_90 > 0

06-21 16:26:56 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:56 -> SELECT COUNT(*) FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527 AND xg_90 > 0
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:56 -> SELECT COUNT(*) FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527 AND xg_90 > 0

Successful query
Data Shape: (1, 1)
Running query: SELECT COUNT(*) FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527 AND score_pd >= 1

06-21 16:26:56 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:56 -> SELECT COUNT(*) FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527 AND score_pd >= 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:56 -> SELECT COUNT(*) FROM public.agg_season_player_pd WHERE player_id = 1163220 AND season_id = 816527 AND score_pd >= 1

Successful query
Data Shape: (1, 1)
Running query: SELECT COUNT(*) FROM vm_agg_season_player_all WHERE player_id = 1163220 AND season_id = 816527 AND player_name = 'Vinicius Junior' AND games_lost < team_games_played AND mins_played > 0

06-21 16:26:56 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:56 -> SELECT COUNT(*) FROM vm_agg_season_player_all WHERE player_id = 1163220 AND season_id = 816527 AND player_name = 'Vinicius Junior' AND games_lost < team_games_played AND mins_played > 0
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:56 -> SELECT COUNT(*) FROM vm_agg_season_player_all WHERE player_id = 1163220 AND season_id = 816527 AND player_name = 'Vinicius Junior' AND games_lost < team_games_played AND mins_played > 0
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT COUNT(*) FROM vm_agg_season_player_all WHERE player_i...
                             ^

Failed query
Running query: SELECT COUNT(DISTINCT match_id) FROM public.t_goal WHERE player_id = 1163220 AND match_id IN (SELECT match_id FROM public.t_match WHERE season_id = 816527)

06-21 16:26:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:57 -> SELECT COUNT(DISTINCT match_id) FROM public.t_goal WHERE player_id = 1163220 AND match_id IN (SELECT match_id FROM public.t_match WHERE season_id = 816527)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:57 -> SELECT COUNT(DISTINCT match_id) FROM public.t_goal WHERE player_id = 1163220 AND match_id IN (SELECT match_id FROM public.t_match WHERE season_id = 816527)

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, player_name, dribbles, height, age FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' AND dribbles IS NOT NULL AND age < 25 AND height > 170 AND games_played > 20 ORDER BY dribbles DESC LIMIT 5

06-21 16:26:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:57 -> SELECT player_id, player_name, dribbles, height, age FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' AND dribbles IS NOT NULL AND age < 25 AND height > 170 AND games_played > 20 ORDER BY dribbles DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:57 -> SELECT player_id, player_name, dribbles, height, age FROM vm_agg_season_player_info WHERE season_id = 816527 AND league_name = 'La Liga' AND dribbles IS NOT NULL AND age < 25 AND height > 170 AND games_played > 20 ORDER BY dribbles DESC LIMIT 5
ERROR:root:Database error: column "dribbles" does not exist
LINE 1: SELECT player_id, player_name, dribbles, height, age FROM vm...
                                       ^

Failed query
Running query: SELECT player_id, team_id, season_id, dribbles FROM public.agg_season_player_pd WHERE season_id = 816527 AND age < 25 AND height > 170 AND games_played_65mins > 20 ORDER BY dribbles DESC LIMIT 5

06-21 16:26:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:57 -> SELECT player_id, team_id, season_id, dribbles FROM public.agg_season_player_pd WHERE season_id = 816527 AND age < 25 AND height > 170 AND games_played_65mins > 20 ORDER BY dribbles DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:57 -> SELECT player_id, team_id, season_id, dribbles FROM public.agg_season_player_pd WHERE season_id = 816527 AND age < 25 AND height > 170 AND games_played_65mins > 20 ORDER BY dribbles DESC LIMIT 5
ERROR:root:Database error: column "dribbles" does not exist
LINE 1: SELECT player_id, team_id, season_id, dribbles FROM public.a...
                                              ^

Failed query
Running query: SELECT player_id, player_name, dribbles_won_90, age, height FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND dribbles_won_90 IS NOT NULL AND age < 25 AND height > 170 AND games > 20 ORDER BY dribbles_won_90 DESC LIMIT 5

06-21 16:26:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:57 -> SELECT player_id, player_name, dribbles_won_90, age, height FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND dribbles_won_90 IS NOT NULL AND age < 25 AND height > 170 AND games > 20 ORDER BY dribbles_won_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:57 -> SELECT player_id, player_name, dribbles_won_90, age, height FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND dribbles_won_90 IS NOT NULL AND age < 25 AND height > 170 AND games > 20 ORDER BY dribbles_won_90 DESC LIMIT 5

Successful query
Data Shape: (5, 5)
Running query: SELECT player_id, player_name, dribbles_total FROM vm_agg_season_player_opta WHERE season_id = 816527 AND age < 25 AND height > 170 AND games_played > 20 ORDER BY dribbles_total DESC LIMIT 5

06-21 16:26:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:57 -> SELECT player_id, player_name, dribbles_total FROM vm_agg_season_player_opta WHERE season_id = 816527 AND age < 25 AND height > 170 AND games_played > 20 ORDER BY dribbles_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:57 -> SELECT player_id, player_name, dribbles_total FROM vm_agg_season_player_opta WHERE season_id = 816527 AND age < 25 AND height > 170 AND games_played > 20 ORDER BY dribbles_total DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_all WHERE season_id IN (816527, 816528, 816529, 816531) ORDER BY max_speed DESC LIMIT 5

06-21 16:26:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:57 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_all WHERE season_id IN (816527, 816528, 816529, 816531) ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:57 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_all WHERE season_id IN (816527, 816528, 816529, 816531) ORDER BY max_speed DESC LIMIT 5
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...ECT player_id, team_id, season_id, max_speed FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, max_speed, team_id, season_id FROM vm_agg_season_player_info WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM vm_agg_season_player_info WHERE season_id = 816529 AND team_id IN (SELECT team_id FROM vm_agg_season_player_info WHERE season_id = 816529 AND league_name = 'ENG I' ORDER BY max_speed DESC LIMIT 5))" ]

06-21 16:26:57 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:57 -> SELECT player_id, player_name, max_speed, team_id, season_id FROM vm_agg_season_player_info WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM vm_agg_season_player_info WHERE season_id = 816529 AND team_id IN (SELECT team_id FROM vm_agg_season_player_info WHERE season_id = 816529 AND league_name = 'ENG I' ORDER BY max_speed DESC LIMIT 5))" ]
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:57 -> SELECT player_id, player_name, max_speed, team_id, season_id FROM vm_agg_season_player_info WHERE season_id = 816529 AND player_id IN (SELECT player_id FROM vm_agg_season_player_info WHERE season_id = 816529 AND team_id IN (SELECT team_id FROM vm_agg_season_player_info WHERE season_id = 816529 AND league_name = 'ENG I' ORDER BY max_speed DESC LIMIT 5))" ]
ERROR:root:Database error: unterminated quoted identifier at or near "" ]"
LINE 1: ...D league_name = 'ENG I' ORDER BY max_speed DESC LIMIT 5))" ]
                                                                    ^

Failed query
Running query: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816529 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 5

06-21 16:26:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:59 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816529 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:59 -> SELECT player_id, team_id, season_id, max_speed FROM vm_agg_season_player_similarity WHERE season_id = 816529 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 5
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, team_id, season_id, max_speed FROM vm_agg_...
                                              ^

Failed query
Running query: SELECT player_id, team_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 AND player_id NOT IN (60, 61, 62, 63, 64, 65, 66, 100) ORDER BY max_speed DESC LIMIT 5

06-21 16:26:59 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:26:59 -> SELECT player_id, team_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 AND player_id NOT IN (60, 61, 62, 63, 64, 65, 66, 100) ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:26:59 -> SELECT player_id, team_id, max_speed FROM public.agg_season_player_pd WHERE season_id = 816529 AND player_id NOT IN (60, 61, 62, 63, 64, 65, 66, 100) ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, max_speed FROM vm_agg_season_player_opta WHERE season_id = 816528 AND country_id = 4 ORDER BY max_speed DESC LIMIT 5

06-21 16:27:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:00 -> SELECT player_id, max_speed FROM vm_agg_season_player_opta WHERE season_id = 816528 AND country_id = 4 ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:00 -> SELECT player_id, max_speed FROM vm_agg_season_player_opta WHERE season_id = 816528 AND country_id = 4 ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND age < 25 AND team_id = 4265 ORDER BY goals_90 DESC LIMIT 5

06-21 16:27:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:00 -> SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND age < 25 AND team_id = 4265 ORDER BY goals_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:00 -> SELECT player_id, player_name, goals_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 AND age < 25 AND team_id = 4265 ORDER BY goals_90 DESC LIMIT 5
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: SELECT player_id, player_name, goals_90 FROM vm_agg_season_p...
                                       ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT player_id, team_id, season_id, player_name, age, mins_played FROM vm_agg_season_player_all WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND age < 25 ORDER BY mins_played DESC LIMIT 5)

06-21 16:27:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:00 -> SELECT player_id, team_id, season_id, player_name, age, mins_played FROM vm_agg_season_player_all WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND age < 25 ORDER BY mins_played DESC LIMIT 5)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:00 -> SELECT player_id, team_id, season_id, player_name, age, mins_played FROM vm_agg_season_player_all WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM vm_agg_season_player_all WHERE season_id = 816527 AND age < 25 ORDER BY mins_played DESC LIMIT 5)
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...id, season_id, player_name, age, mins_played FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals > 0 AND age < 25 ORDER BY goals DESC LIMIT 5

06-21 16:27:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:00 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals > 0 AND age < 25 ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:00 -> SELECT player_id, player_name, goals FROM vm_agg_season_player_opta WHERE season_id = 816527 AND goals > 0 AND age < 25 ORDER BY goals DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, SUM(score_pd) AS total_goals FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND age < 25) GROUP BY player_id ORDER BY total_goals DESC LIMIT 5

06-21 16:27:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:00 -> SELECT player_id, SUM(score_pd) AS total_goals FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND age < 25) GROUP BY player_id ORDER BY total_goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:00 -> SELECT player_id, SUM(score_pd) AS total_goals FROM public.agg_season_player_pd WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM public.agg_season_player_pd WHERE season_id = 816527 AND age < 25) GROUP BY player_id ORDER BY total_goals DESC LIMIT 5
ERROR:root:Database error: column "age" does not exist
LINE 1: ...agg_season_player_pd WHERE season_id = 816527 AND age < 25) ...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, team_id, season_id, avg_max_speed FROM vm_agg_season_player_info WHERE season_id = 816531 AND position = 'DC' AND player_foot = 'Left' ORDER BY avg_max_speed DESC LIMIT 5

06-21 16:27:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:00 -> SELECT player_id, player_name, team_id, season_id, avg_max_speed FROM vm_agg_season_player_info WHERE season_id = 816531 AND position = 'DC' AND player_foot = 'Left' ORDER BY avg_max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:00 -> SELECT player_id, player_name, team_id, season_id, avg_max_speed FROM vm_agg_season_player_info WHERE season_id = 816531 AND position = 'DC' AND player_foot = 'Left' ORDER BY avg_max_speed DESC LIMIT 5
ERROR:root:Database error: column "player_foot" does not exist
LINE 1: ... WHERE season_id = 816531 AND position = 'DC' AND player_foo...
                                                             ^

Failed query
Running query: SELECT player_id, team_id, season_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816531 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'DC' AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 5)) ORDER BY avg_max_speed DESC LIMIT 5

06-21 16:27:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:00 -> SELECT player_id, team_id, season_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816531 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'DC' AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 5)) ORDER BY avg_max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:00 -> SELECT player_id, team_id, season_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816531 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'DC' AND team_id IN (SELECT team_id FROM t_team WHERE country_id = 5)) ORDER BY avg_max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 4)
Running query: SELECT player_id, player_name, team_id, season_id, progressive_passes_total_90 FROM vm_agg_season_player_opta WHERE season_id = 816531 AND position = 'DC' AND player_position = 'DC' AND player_side_id = 1 ORDER BY progressive_passes_total_90 DESC LIMIT 5

06-21 16:27:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:00 -> SELECT player_id, player_name, team_id, season_id, progressive_passes_total_90 FROM vm_agg_season_player_opta WHERE season_id = 816531 AND position = 'DC' AND player_position = 'DC' AND player_side_id = 1 ORDER BY progressive_passes_total_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:00 -> SELECT player_id, player_name, team_id, season_id, progressive_passes_total_90 FROM vm_agg_season_player_opta WHERE season_id = 816531 AND position = 'DC' AND player_position = 'DC' AND player_side_id = 1 ORDER BY progressive_passes_total_90 DESC LIMIT 5

Successful query
Data Shape: (5, 5)
Running query: SELECT player_id, team_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY avg_max_speed DESC LIMIT 5

06-21 16:27:00 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:00 -> SELECT player_id, team_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY avg_max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:00 -> SELECT player_id, team_id, avg_max_speed FROM public.agg_season_player_pd WHERE season_id = 816527 ORDER BY avg_max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, player_name, dribbles_won_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY dribbles_won_90 DESC LIMIT 5

06-21 16:27:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:01 -> SELECT player_id, player_name, dribbles_won_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY dribbles_won_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:01 -> SELECT player_id, player_name, dribbles_won_90 FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY dribbles_won_90 DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, team_id, season_id, (dribbles_total / (mins_played / 90)) AS dribbles_per_90 FROM vm_agg_season_player_all WHERE season_id = 816527 ORDER BY dribbles_per_90 DESC LIMIT 5

06-21 16:27:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:01 -> SELECT player_id, team_id, season_id, (dribbles_total / (mins_played / 90)) AS dribbles_per_90 FROM vm_agg_season_player_all WHERE season_id = 816527 ORDER BY dribbles_per_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:01 -> SELECT player_id, team_id, season_id, (dribbles_total / (mins_played / 90)) AS dribbles_per_90 FROM vm_agg_season_player_all WHERE season_id = 816527 ORDER BY dribbles_per_90 DESC LIMIT 5
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...tal / (mins_played / 90)) AS dribbles_per_90 FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, avg_max_speed FROM vm_agg_season_player_info WHERE season_id = 816527 AND player_id IN (1169575, 1217644, 1169797, 1216616, 1254156) ORDER BY avg_max_speed DESC LIMIT 5

06-21 16:27:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:01 -> SELECT player_id, player_name, avg_max_speed FROM vm_agg_season_player_info WHERE season_id = 816527 AND player_id IN (1169575, 1217644, 1169797, 1216616, 1254156) ORDER BY avg_max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:01 -> SELECT player_id, player_name, avg_max_speed FROM vm_agg_season_player_info WHERE season_id = 816527 AND player_id IN (1169575, 1217644, 1169797, 1216616, 1254156) ORDER BY avg_max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, player_name, dribbles_total_90 FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY dribbles_total_90 DESC LIMIT 5

06-21 16:27:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:01 -> SELECT player_id, player_name, dribbles_total_90 FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY dribbles_total_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:01 -> SELECT player_id, player_name, dribbles_total_90 FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY dribbles_total_90 DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, team_id, distance_90 FROM public.agg_season_player_pd WHERE age <= 25 AND max_speed < 50 AND position = 'DC' AND season_id = 816529 ORDER BY distance_90 DESC LIMIT 15

06-21 16:27:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:01 -> SELECT player_id, team_id, distance_90 FROM public.agg_season_player_pd WHERE age <= 25 AND max_speed < 50 AND position = 'DC' AND season_id = 816529 ORDER BY distance_90 DESC LIMIT 15
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:01 -> SELECT player_id, team_id, distance_90 FROM public.agg_season_player_pd WHERE age <= 25 AND max_speed < 50 AND position = 'DC' AND season_id = 816529 ORDER BY distance_90 DESC LIMIT 15
ERROR:root:Database error: column "age" does not exist
LINE 1: ...istance_90 FROM public.agg_season_player_pd WHERE age <= 25 ...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, team_id, team_name, season_id, percent_carries, market_value FROM vm_agg_season_player_opta WHERE player_position = 'DC' AND player_secondary_position = 'DL' AND age <= 25 AND percent_carries > 0 AND market_value < 50000000 AND league_country_name IN ('Spain', 'England', 'Germany', 'Italy', 'France') ORDER BY percent_carries DESC LIMIT 15

06-21 16:27:01 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:01 -> SELECT player_id, player_name, team_id, team_name, season_id, percent_carries, market_value FROM vm_agg_season_player_opta WHERE player_position = 'DC' AND player_secondary_position = 'DL' AND age <= 25 AND percent_carries > 0 AND market_value < 50000000 AND league_country_name IN ('Spain', 'England', 'Germany', 'Italy', 'France') ORDER BY percent_carries DESC LIMIT 15
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:01 -> SELECT player_id, player_name, team_id, team_name, season_id, percent_carries, market_value FROM vm_agg_season_player_opta WHERE player_position = 'DC' AND player_secondary_position = 'DL' AND age <= 25 AND percent_carries > 0 AND market_value < 50000000 AND league_country_name IN ('Spain', 'England', 'Germany', 'Italy', 'France') ORDER BY percent_carries DESC LIMIT 15

Successful query
Data Shape: (15, 7)
Running query: SELECT age_score, contract_score, availability_score, index_score, global_score FROM vm_det_player_placer WHERE player_id = 48364 AND team_id = 4266 AND season_id = 816527

06-21 16:27:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:05 -> SELECT age_score, contract_score, availability_score, index_score, global_score FROM vm_det_player_placer WHERE player_id = 48364 AND team_id = 4266 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:05 -> SELECT age_score, contract_score, availability_score, index_score, global_score FROM vm_det_player_placer WHERE player_id = 48364 AND team_id = 4266 AND season_id = 816527
ERROR:root:Database error: relation "vm_det_player_placer" does not exist
LINE 1: ...vailability_score, index_score, global_score FROM vm_det_pla...
                                                             ^

Failed query
Running query: SELECT player_id, mins_played, distance, hsr_num, sprint_num, max_speed, acceleration_num FROM public.agg_game_player_pd WHERE player_id = 48364 AND season_id = 816527

06-21 16:27:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:05 -> SELECT player_id, mins_played, distance, hsr_num, sprint_num, max_speed, acceleration_num FROM public.agg_game_player_pd WHERE player_id = 48364 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:05 -> SELECT player_id, mins_played, distance, hsr_num, sprint_num, max_speed, acceleration_num FROM public.agg_game_player_pd WHERE player_id = 48364 AND season_id = 816527

Successful query
Data Shape: (20, 7)
Running query: SELECT player_id, max_speed, avg_max_speed, sprint_distance, sprint_distance_90, acceleration_num, acceleration_num_90, extreme_acceleration_num, extreme_acceleration_num_90 FROM public.agg_season_player_pd WHERE player_id = 48364 AND season_id = 816527

06-21 16:27:05 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:05 -> SELECT player_id, max_speed, avg_max_speed, sprint_distance, sprint_distance_90, acceleration_num, acceleration_num_90, extreme_acceleration_num, extreme_acceleration_num_90 FROM public.agg_season_player_pd WHERE player_id = 48364 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:05 -> SELECT player_id, max_speed, avg_max_speed, sprint_distance, sprint_distance_90, acceleration_num, acceleration_num_90, extreme_acceleration_num, extreme_acceleration_num_90 FROM public.agg_season_player_pd WHERE player_id = 48364 AND season_id = 816527

Successful query
Data Shape: (4, 9)
Running query: SELECT player_id, passes_accurate, interceptions, tackles_total, aerials_won, dribbles_won, goals, assists FROM public.vt_game_stat_player WHERE player_id = 48364 AND season_id = 816527

06-21 16:27:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:08 -> SELECT player_id, passes_accurate, interceptions, tackles_total, aerials_won, dribbles_won, goals, assists FROM public.vt_game_stat_player WHERE player_id = 48364 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:08 -> SELECT player_id, passes_accurate, interceptions, tackles_total, aerials_won, dribbles_won, goals, assists FROM public.vt_game_stat_player WHERE player_id = 48364 AND season_id = 816527

Successful query
Data Shape: (20, 8)
Running query: SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 122649 AND season_id = 817340 AND goals IS NOT NULL

06-21 16:27:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:08 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 122649 AND season_id = 817340 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:08 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 122649 AND season_id = 817340 AND goals IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT goals FROM vm_agg_season_player_all WHERE player_id = 122649 AND season_id = 817340 AND goals IS NOT NULL

06-21 16:27:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:08 -> SELECT goals FROM vm_agg_season_player_all WHERE player_id = 122649 AND season_id = 817340 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:08 -> SELECT goals FROM vm_agg_season_player_all WHERE player_id = 122649 AND season_id = 817340 AND goals IS NOT NULL
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT goals FROM vm_agg_season_player_all WHERE player_id =...
                          ^

Failed query
Running query: SELECT goals_90 FROM vm_agg_season_player_similarity WHERE player_id = 122649 AND season_id = 817340 AND goals_90 IS NOT NULL

06-21 16:27:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:08 -> SELECT goals_90 FROM vm_agg_season_player_similarity WHERE player_id = 122649 AND season_id = 817340 AND goals_90 IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:08 -> SELECT goals_90 FROM vm_agg_season_player_similarity WHERE player_id = 122649 AND season_id = 817340 AND goals_90 IS NOT NULL
ERROR:root:Database error: column "goals_90" does not exist
LINE 1: SELECT goals_90 FROM vm_agg_season_player_similarity WHERE p...
               ^
HINT:  Perhaps you meant to reference the column "vm_agg_season_player_similarity.fouls_90".

Failed query
Running query: SELECT player_id, goals_total, team_id, season_id FROM public.vt_season_stat_player WHERE season_id = 816527 AND player_id NOT IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY goals_total DESC LIMIT 1

06-21 16:27:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:08 -> SELECT player_id, goals_total, team_id, season_id FROM public.vt_season_stat_player WHERE season_id = 816527 AND player_id NOT IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY goals_total DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:08 -> SELECT player_id, goals_total, team_id, season_id FROM public.vt_season_stat_player WHERE season_id = 816527 AND player_id NOT IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY goals_total DESC LIMIT 1
ERROR:root:Database error: column "goals_total" does not exist
LINE 1: SELECT player_id, goals_total, team_id, season_id FROM publi...
                          ^
HINT:  Perhaps you meant to reference the column "vt_season_stat_player.duels_total".

Failed query
Running query: SELECT team_id, shots_on_target, season_id FROM public.vt_season_metric_team WHERE season_id = 816527 AND shots_on_target IS NOT NULL ORDER BY shots_on_target DESC LIMIT 5

06-21 16:27:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:08 -> SELECT team_id, shots_on_target, season_id FROM public.vt_season_metric_team WHERE season_id = 816527 AND shots_on_target IS NOT NULL ORDER BY shots_on_target DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:08 -> SELECT team_id, shots_on_target, season_id FROM public.vt_season_metric_team WHERE season_id = 816527 AND shots_on_target IS NOT NULL ORDER BY shots_on_target DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT team_id, shots_on_target, season_id FROM public.t_season_team_rank WHERE season_id = 816527 AND shots_on_target IS NOT NULL ORDER BY shots_on_target DESC LIMIT 5

06-21 16:27:08 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:08 -> SELECT team_id, shots_on_target, season_id FROM public.t_season_team_rank WHERE season_id = 816527 AND shots_on_target IS NOT NULL ORDER BY shots_on_target DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:08 -> SELECT team_id, shots_on_target, season_id FROM public.t_season_team_rank WHERE season_id = 816527 AND shots_on_target IS NOT NULL ORDER BY shots_on_target DESC LIMIT 5
ERROR:root:Database error: column "shots_on_target" does not exist
LINE 1: SELECT team_id, shots_on_target, season_id FROM public.t_sea...
                        ^

Failed query
Running query: SELECT team_id, possession FROM public.t_match WHERE season_id = 816527 AND league_id = 'ESP I' ORDER BY possession DESC LIMIT 5

06-21 16:27:09 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:09 -> SELECT team_id, possession FROM public.t_match WHERE season_id = 816527 AND league_id = 'ESP I' ORDER BY possession DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:09 -> SELECT team_id, possession FROM public.t_match WHERE season_id = 816527 AND league_id = 'ESP I' ORDER BY possession DESC LIMIT 5
ERROR:root:Database error: column "team_id" does not exist
LINE 1: SELECT team_id, possession FROM public.t_match WHERE season_...
               ^
HINT:  Perhaps you meant to reference the column "t_match.tm_id".

Failed query
Running query: SELECT team_id, avg_possession FROM public.t_team_stats WHERE season_id = 816527 AND league_id = 'ESP I' ORDER BY avg_possession DESC LIMIT 5

06-21 16:27:09 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:09 -> SELECT team_id, avg_possession FROM public.t_team_stats WHERE season_id = 816527 AND league_id = 'ESP I' ORDER BY avg_possession DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:09 -> SELECT team_id, avg_possession FROM public.t_team_stats WHERE season_id = 816527 AND league_id = 'ESP I' ORDER BY avg_possession DESC LIMIT 5
ERROR:root:Database error: relation "public.t_team_stats" does not exist
LINE 1: SELECT team_id, avg_possession FROM public.t_team_stats WHER...
                                            ^

Failed query
Running query: SELECT team_id, possession FROM public.vt_season_metric_team WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM public.t_season_team_rank WHERE total_teams = 20 AND season_id = 816527) AND possession IS NOT NULL ORDER BY possession DESC LIMIT 5

06-21 16:27:09 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:09 -> SELECT team_id, possession FROM public.vt_season_metric_team WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM public.t_season_team_rank WHERE total_teams = 20 AND season_id = 816527) AND possession IS NOT NULL ORDER BY possession DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:09 -> SELECT team_id, possession FROM public.vt_season_metric_team WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM public.t_season_team_rank WHERE total_teams = 20 AND season_id = 816527) AND possession IS NOT NULL ORDER BY possession DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT team_id, possession FROM public.vt_season_metric_team WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM public.t_season_team_rank WHERE season_id = 816527 ORDER BY games_played DESC LIMIT 5) ORDER BY possession DESC

06-21 16:27:09 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:09 -> SELECT team_id, possession FROM public.vt_season_metric_team WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM public.t_season_team_rank WHERE season_id = 816527 ORDER BY games_played DESC LIMIT 5) ORDER BY possession DESC
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:09 -> SELECT team_id, possession FROM public.vt_season_metric_team WHERE season_id = 816527 AND team_id IN (SELECT team_id FROM public.t_season_team_rank WHERE season_id = 816527 ORDER BY games_played DESC LIMIT 5) ORDER BY possession DESC

Successful query
Data Shape: (15, 2)
Running query: SELECT player_id, dribbles_final_third_90 FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY dribbles_final_third_90 DESC LIMIT 5

06-21 16:27:09 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:09 -> SELECT player_id, dribbles_final_third_90 FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY dribbles_final_third_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:09 -> SELECT player_id, dribbles_final_third_90 FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY dribbles_final_third_90 DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, dribbles_final_third_90 FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY dribbles_final_third_90 DESC LIMIT 5

06-21 16:27:10 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:10 -> SELECT player_id, dribbles_final_third_90 FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY dribbles_final_third_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:10 -> SELECT player_id, dribbles_final_third_90 FROM public.vt_season_stat_player WHERE season_id = 816527 ORDER BY dribbles_final_third_90 DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, goals FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5

06-21 16:27:10 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:10 -> SELECT player_id, goals FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:10 -> SELECT player_id, goals FROM public.vt_season_opta_player WHERE season_id = 816527 ORDER BY goals DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, games_played FROM public.vt_season_info_player WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY games_played DESC LIMIT 1

06-21 16:27:10 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:10 -> SELECT player_id, games_played FROM public.vt_season_info_player WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY games_played DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:10 -> SELECT player_id, games_played FROM public.vt_season_info_player WHERE season_id = 816527 AND player_id IN (SELECT player_id FROM t_player WHERE position = 'GK') ORDER BY games_played DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT player_id, market_value, name FROM public.t_player_value WHERE team = 'Real Madrid' AND date = '2023-01-01' ORDER BY market_value DESC LIMIT 5

06-21 16:27:10 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:10 -> SELECT player_id, market_value, name FROM public.t_player_value WHERE team = 'Real Madrid' AND date = '2023-01-01' ORDER BY market_value DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:10 -> SELECT player_id, market_value, name FROM public.t_player_value WHERE team = 'Real Madrid' AND date = '2023-01-01' ORDER BY market_value DESC LIMIT 5
ERROR:root:Database error: column "name" does not exist
LINE 1: SELECT player_id, market_value, name FROM public.t_player_va...
                                        ^
HINT:  Perhaps you meant to reference the column "t_player_value.date" or the column "t_player_value.age".

Failed query
Running query: SELECT player_id, name, position FROM public.t_player WHERE team_id = 4265 AND position IN ('FW', 'AMC', 'MC') ORDER BY market_value DESC LIMIT 5

06-21 16:27:10 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:10 -> SELECT player_id, name, position FROM public.t_player WHERE team_id = 4265 AND position IN ('FW', 'AMC', 'MC') ORDER BY market_value DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:10 -> SELECT player_id, name, position FROM public.t_player WHERE team_id = 4265 AND position IN ('FW', 'AMC', 'MC') ORDER BY market_value DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 122649 AND season_id = 816527 AND goals IS NOT NULL

06-21 16:27:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:11 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 122649 AND season_id = 816527 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:11 -> SELECT goals FROM vm_agg_season_player_opta WHERE player_id = 122649 AND season_id = 816527 AND goals IS NOT NULL

Successful query
Data Shape: (0, 1)
Running query: SELECT goals FROM vm_agg_season_player_all WHERE player_id = 122649 AND season_id = 816527 AND goals IS NOT NULL

06-21 16:27:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:11 -> SELECT goals FROM vm_agg_season_player_all WHERE player_id = 122649 AND season_id = 816527 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:11 -> SELECT goals FROM vm_agg_season_player_all WHERE player_id = 122649 AND season_id = 816527 AND goals IS NOT NULL
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: SELECT goals FROM vm_agg_season_player_all WHERE player_id =...
                          ^

Failed query
Running query: SELECT goals FROM vm_agg_season_player_similarity WHERE player_id = 122649 AND season_id = 816527 AND goals IS NOT NULL

06-21 16:27:11 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:11 -> SELECT goals FROM vm_agg_season_player_similarity WHERE player_id = 122649 AND season_id = 816527 AND goals IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:11 -> SELECT goals FROM vm_agg_season_player_similarity WHERE player_id = 122649 AND season_id = 816527 AND goals IS NOT NULL
ERROR:root:Database error: column "goals" does not exist
LINE 1: SELECT goals FROM vm_agg_season_player_similarity WHERE play...
               ^

Failed query
Running query: SELECT dribbles_total FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527 AND dribbles_total IS NOT NULL

06-21 16:27:13 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:13 -> SELECT dribbles_total FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527 AND dribbles_total IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:13 -> SELECT dribbles_total FROM vm_agg_season_player_opta WHERE player_id = 1163220 AND season_id = 816527 AND dribbles_total IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT dribbles_total FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527 AND dribbles_total IS NOT NULL

06-21 16:27:13 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:13 -> SELECT dribbles_total FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527 AND dribbles_total IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:13 -> SELECT dribbles_total FROM vm_agg_season_player_similarity WHERE player_id = 1163220 AND season_id = 816527 AND dribbles_total IS NOT NULL
ERROR:root:Database error: column "dribbles_total" does not exist
LINE 1: SELECT dribbles_total FROM vm_agg_season_player_similarity W...
               ^

Failed query
Running query: SELECT tackles_total FROM public.vt_season_stat_player WHERE player_id = 349 AND season_id = 816527 AND tackles_total IS NOT NULL

06-21 16:27:13 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:13 -> SELECT tackles_total FROM public.vt_season_stat_player WHERE player_id = 349 AND season_id = 816527 AND tackles_total IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:13 -> SELECT tackles_total FROM public.vt_season_stat_player WHERE player_id = 349 AND season_id = 816527 AND tackles_total IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT tackles_total FROM public.vt_season_stat_player WHERE player_id = 349 AND season_id = 816690 AND tackles_total IS NOT NULL

06-21 16:27:13 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:13 -> SELECT tackles_total FROM public.vt_season_stat_player WHERE player_id = 349 AND season_id = 816690 AND tackles_total IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:13 -> SELECT tackles_total FROM public.vt_season_stat_player WHERE player_id = 349 AND season_id = 816690 AND tackles_total IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, team_id, season_id, goals FROM public.vt_season_info_player WHERE player_id = 1296920 AND season_id = 816527

06-21 16:27:13 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:13 -> SELECT player_id, team_id, season_id, goals FROM public.vt_season_info_player WHERE player_id = 1296920 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:13 -> SELECT player_id, team_id, season_id, goals FROM public.vt_season_info_player WHERE player_id = 1296920 AND season_id = 816527

Successful query
Data Shape: (1, 4)
Running query: SELECT player_id, team_id, season_id, goals FROM public.vt_season_info_player WHERE player_id = 69936 AND season_id = 816527

06-21 16:27:13 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:13 -> SELECT player_id, team_id, season_id, goals FROM public.vt_season_info_player WHERE player_id = 69936 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:13 -> SELECT player_id, team_id, season_id, goals FROM public.vt_season_info_player WHERE player_id = 69936 AND season_id = 816527

Successful query
Data Shape: (1, 4)
Running query: SELECT player_id, passes_accurate FROM public.vt_game_stat_player WHERE team_id = 4265 AND season_id = 816527 AND passes_accurate IS NOT NULL ORDER BY passes_accurate DESC LIMIT 5

06-21 16:27:14 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:14 -> SELECT player_id, passes_accurate FROM public.vt_game_stat_player WHERE team_id = 4265 AND season_id = 816527 AND passes_accurate IS NOT NULL ORDER BY passes_accurate DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:14 -> SELECT player_id, passes_accurate FROM public.vt_game_stat_player WHERE team_id = 4265 AND season_id = 816527 AND passes_accurate IS NOT NULL ORDER BY passes_accurate DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT COUNT(*) AS goals_scored FROM public.t_goal WHERE match_id IN (SELECT match_id FROM public.t_match WHERE (home_team_id = 4265 AND away_team_id = 4279) OR (home_team_id = 4279 AND away_team_id = 4265))

06-21 16:27:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:16 -> SELECT COUNT(*) AS goals_scored FROM public.t_goal WHERE match_id IN (SELECT match_id FROM public.t_match WHERE (home_team_id = 4265 AND away_team_id = 4279) OR (home_team_id = 4279 AND away_team_id = 4265))
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:16 -> SELECT COUNT(*) AS goals_scored FROM public.t_goal WHERE match_id IN (SELECT match_id FROM public.t_match WHERE (home_team_id = 4265 AND away_team_id = 4279) OR (home_team_id = 4279 AND away_team_id = 4265))

Successful query
Data Shape: (1, 1)
Running query: SELECT COUNT(goal_id) FROM public.t_goal WHERE match_id IN (SELECT match_id FROM public.t_match WHERE (home_team_id = 4265 OR away_team_id = 4265) AND (home_team_id = 4279 OR away_team_id = 4279) AND season_id = 816527)

06-21 16:27:16 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:16 -> SELECT COUNT(goal_id) FROM public.t_goal WHERE match_id IN (SELECT match_id FROM public.t_match WHERE (home_team_id = 4265 OR away_team_id = 4265) AND (home_team_id = 4279 OR away_team_id = 4279) AND season_id = 816527)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:16 -> SELECT COUNT(goal_id) FROM public.t_goal WHERE match_id IN (SELECT match_id FROM public.t_match WHERE (home_team_id = 4265 OR away_team_id = 4265) AND (home_team_id = 4279 OR away_team_id = 4279) AND season_id = 816527)

Successful query
Data Shape: (1, 1)
Running query: SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 and team_id = 4265 and season_id = 816527 and outcome IS NOT NULL

06-21 16:27:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:17 -> SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 and team_id = 4265 and season_id = 816527 and outcome IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:17 -> SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 and team_id = 4265 and season_id = 816527 and outcome IS NOT NULL
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...ckle WHERE player_id = 349 and team_id = 4265 and season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, crosses_accurate_per_game FROM public.vt_season_opta_player WHERE team_id = 4265 AND regular_season_id = 816527 ORDER BY crosses_accurate_per_game DESC LIMIT 5

06-21 16:27:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:17 -> SELECT player_id, player_name, crosses_accurate_per_game FROM public.vt_season_opta_player WHERE team_id = 4265 AND regular_season_id = 816527 ORDER BY crosses_accurate_per_game DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:17 -> SELECT player_id, player_name, crosses_accurate_per_game FROM public.vt_season_opta_player WHERE team_id = 4265 AND regular_season_id = 816527 ORDER BY crosses_accurate_per_game DESC LIMIT 5
ERROR:root:Database error: column "player_name" does not exist
LINE 1: SELECT player_id, player_name, crosses_accurate_per_game FRO...
                          ^

Failed query
Running query: SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816372

06-21 16:27:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:17 -> SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816372
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:17 -> SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816372
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...d) FROM public.t_tackle WHERE player_id = 349 AND season_id ...
                                                             ^

Failed query
Running query: SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816372 AND outcome IS NOT NULL

06-21 16:27:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:17 -> SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816372 AND outcome IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:17 -> SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816372 AND outcome IS NOT NULL
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...d) FROM public.t_tackle WHERE player_id = 349 AND season_id ...
                                                             ^

Failed query
Running query: SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816372 AND outcome = true

06-21 16:27:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:17 -> SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816372 AND outcome = true
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:17 -> SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816372 AND outcome = true
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...d) FROM public.t_tackle WHERE player_id = 349 AND season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, max_speed FROM public.agg_period_player_pd WHERE season_id = 816527 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1

06-21 16:27:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:17 -> SELECT player_id, max_speed FROM public.agg_period_player_pd WHERE season_id = 816527 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:17 -> SELECT player_id, max_speed FROM public.agg_period_player_pd WHERE season_id = 816527 AND max_speed IS NOT NULL ORDER BY max_speed DESC LIMIT 1
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, max_speed FROM public.agg_period_player_pd...
                          ^

Failed query
Running query: SELECT team_id FROM public.t_player WHERE player_id = 477947 AND team_id <> 0 AND team_id IS NOT NULL

06-21 16:27:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:17 -> SELECT team_id FROM public.t_player WHERE player_id = 477947 AND team_id <> 0 AND team_id IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:17 -> SELECT team_id FROM public.t_player WHERE player_id = 477947 AND team_id <> 0 AND team_id IS NOT NULL

Successful query
Data Shape: (0, 1)
Running query: SELECT team_id FROM public.t_player WHERE player_id = 53079 AND team_id = 2019 AND team_id IS NOT NULL

06-21 16:27:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:17 -> SELECT team_id FROM public.t_player WHERE player_id = 53079 AND team_id = 2019 AND team_id IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:17 -> SELECT team_id FROM public.t_player WHERE player_id = 53079 AND team_id = 2019 AND team_id IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT team_id FROM public.t_player WHERE player_id = 1211988 AND team_id = 1928 AND team_id IS NOT NULL

06-21 16:27:17 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:17 -> SELECT team_id FROM public.t_player WHERE player_id = 1211988 AND team_id = 1928 AND team_id IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:17 -> SELECT team_id FROM public.t_player WHERE player_id = 1211988 AND team_id = 1928 AND team_id IS NOT NULL

Successful query
Data Shape: (1, 1)
Running query: SELECT player_id, SUM(dribbles_attempted) AS total_dribbles_attempts FROM public.vt_game_stat_player WHERE team_id = 4279 AND season_id = 816527 GROUP BY player_id ORDER BY total_dribbles_attempts DESC LIMIT 1

06-21 16:27:18 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:18 -> SELECT player_id, SUM(dribbles_attempted) AS total_dribbles_attempts FROM public.vt_game_stat_player WHERE team_id = 4279 AND season_id = 816527 GROUP BY player_id ORDER BY total_dribbles_attempts DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:18 -> SELECT player_id, SUM(dribbles_attempted) AS total_dribbles_attempts FROM public.vt_game_stat_player WHERE team_id = 4279 AND season_id = 816527 GROUP BY player_id ORDER BY total_dribbles_attempts DESC LIMIT 1

Successful query
Data Shape: (1, 2)
Running query: SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816527

06-21 16:27:20 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:20 -> SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:20 -> SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816527
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...d) FROM public.t_tackle WHERE player_id = 349 AND season_id ...
                                                             ^

Failed query
Running query: SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816527 AND outcome IS NOT NULL

06-21 16:27:22 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:22 -> SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816527 AND outcome IS NOT NULL
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:22 -> SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816527 AND outcome IS NOT NULL
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...d) FROM public.t_tackle WHERE player_id = 349 AND season_id ...
                                                             ^

Failed query
Running query: SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816527 AND outcome = true

06-21 16:27:22 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:22 -> SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816527 AND outcome = true
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:22 -> SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816527 AND outcome = true
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...d) FROM public.t_tackle WHERE player_id = 349 AND season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, team_id, season_id, goals FROM public.vt_season_info_player WHERE (player_id = 1296920 AND season_id = 816527) OR (player_id = 69936 AND season_id = 816527)

06-21 16:27:22 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:22 -> SELECT player_id, team_id, season_id, goals FROM public.vt_season_info_player WHERE (player_id = 1296920 AND season_id = 816527) OR (player_id = 69936 AND season_id = 816527)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:22 -> SELECT player_id, team_id, season_id, goals FROM public.vt_season_info_player WHERE (player_id = 1296920 AND season_id = 816527) OR (player_id = 69936 AND season_id = 816527)

Successful query
Data Shape: (2, 4)
Running query: SELECT player_id, max_speed FROM public.agg_period_player_pd WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1

06-21 16:27:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:23 -> SELECT player_id, max_speed FROM public.agg_period_player_pd WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:23 -> SELECT player_id, max_speed FROM public.agg_period_player_pd WHERE season_id = 816527 ORDER BY max_speed DESC LIMIT 1
ERROR:root:Database error: column "max_speed" does not exist
LINE 1: SELECT player_id, max_speed FROM public.agg_period_player_pd...
                          ^

Failed query
Running query: SELECT COUNT(*) FROM public.t_goal WHERE match_id IN (SELECT match_id FROM public.t_match WHERE (home_team_id = 4265 AND away_team_id = 4279) OR (home_team_id = 4279 AND away_team_id = 4265))

06-21 16:27:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:23 -> SELECT COUNT(*) FROM public.t_goal WHERE match_id IN (SELECT match_id FROM public.t_match WHERE (home_team_id = 4265 AND away_team_id = 4279) OR (home_team_id = 4279 AND away_team_id = 4265))
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:23 -> SELECT COUNT(*) FROM public.t_goal WHERE match_id IN (SELECT match_id FROM public.t_match WHERE (home_team_id = 4265 AND away_team_id = 4279) OR (home_team_id = 4279 AND away_team_id = 4265))

Successful query
Data Shape: (1, 1)
Running query: SELECT COUNT(*) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816372

06-21 16:27:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:23 -> SELECT COUNT(*) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816372
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:23 -> SELECT COUNT(*) FROM public.t_tackle WHERE player_id = 349 AND season_id = 816372
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...*) FROM public.t_tackle WHERE player_id = 349 AND season_id ...
                                                             ^

Failed query
Running query: SELECT COUNT(*) FROM public.t_goal WHERE match_id IN (SELECT match_id FROM public.vm_game_stat_team WHERE (team_id = 4265 OR team_id = 4279) AND season_id = 816527)

06-21 16:27:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:23 -> SELECT COUNT(*) FROM public.t_goal WHERE match_id IN (SELECT match_id FROM public.vm_game_stat_team WHERE (team_id = 4265 OR team_id = 4279) AND season_id = 816527)
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:23 -> SELECT COUNT(*) FROM public.t_goal WHERE match_id IN (SELECT match_id FROM public.vm_game_stat_team WHERE (team_id = 4265 OR team_id = 4279) AND season_id = 816527)

Successful query
Data Shape: (1, 1)
Running query: SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND team_id = 4265 AND season_id = 816527

06-21 16:27:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:23 -> SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND team_id = 4265 AND season_id = 816527
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:23 -> SELECT COUNT(tackle_id) FROM public.t_tackle WHERE player_id = 349 AND team_id = 4265 AND season_id = 816527
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ...ckle WHERE player_id = 349 AND team_id = 4265 AND season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, max_speed FROM vm_agg_season_player_info WHERE season_id in (816527, 816529, 816530, 816528, 816531) ORDER BY max_speed DESC LIMIT 5

06-21 16:27:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:23 -> SELECT player_id, max_speed FROM vm_agg_season_player_info WHERE season_id in (816527, 816529, 816530, 816528, 816531) ORDER BY max_speed DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:23 -> SELECT player_id, max_speed FROM vm_agg_season_player_info WHERE season_id in (816527, 816529, 816530, 816528, 816531) ORDER BY max_speed DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, team_id, season_id, player_name, age, team_mins_played FROM vm_agg_season_player_all WHERE season_id IN (816527, 816529, 816530, 816528, 816531) ORDER BY team_mins_played DESC LIMIT 5

06-21 16:27:23 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:23 -> SELECT player_id, team_id, season_id, player_name, age, team_mins_played FROM vm_agg_season_player_all WHERE season_id IN (816527, 816529, 816530, 816528, 816531) ORDER BY team_mins_played DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:23 -> SELECT player_id, team_id, season_id, player_name, age, team_mins_played FROM vm_agg_season_player_all WHERE season_id IN (816527, 816529, 816530, 816528, 816531) ORDER BY team_mins_played DESC LIMIT 5
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...eason_id, player_name, age, team_mins_played FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, passes_accurate_90, season_id FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY passes_accurate_90 DESC LIMIT 1

06-21 16:27:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:24 -> SELECT player_id, passes_accurate_90, season_id FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY passes_accurate_90 DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:24 -> SELECT player_id, passes_accurate_90, season_id FROM vm_agg_season_player_similarity WHERE season_id = 816527 ORDER BY passes_accurate_90 DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, passes_total, season_id FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY passes_total DESC LIMIT 1

06-21 16:27:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:24 -> SELECT player_id, passes_total, season_id FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY passes_total DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:24 -> SELECT player_id, passes_total, season_id FROM vm_agg_season_player_opta WHERE season_id = 816527 ORDER BY passes_total DESC LIMIT 1

Successful query
Data Shape: (1, 3)
Running query: SELECT player_id, team_id, season_id, passes_total FROM vm_agg_season_player_all WHERE season_id = 816527 ORDER BY passes_total DESC LIMIT 1

06-21 16:27:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:24 -> SELECT player_id, team_id, season_id, passes_total FROM vm_agg_season_player_all WHERE season_id = 816527 ORDER BY passes_total DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:24 -> SELECT player_id, team_id, season_id, passes_total FROM vm_agg_season_player_all WHERE season_id = 816527 ORDER BY passes_total DESC LIMIT 1
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ... player_id, team_id, season_id, passes_total FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, player_name, passes_total FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY passes_total DESC LIMIT 1

06-21 16:27:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:24 -> SELECT player_id, player_name, passes_total FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY passes_total DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:24 -> SELECT player_id, player_name, passes_total FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY passes_total DESC LIMIT 1
ERROR:root:Database error: column "passes_total" does not exist
LINE 1: SELECT player_id, player_name, passes_total FROM vm_agg_seas...
                                       ^

Failed query
Running query: SELECT player_id, player_name, passes_total, season_id FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY passes_total DESC LIMIT 1

06-21 16:27:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:24 -> SELECT player_id, player_name, passes_total, season_id FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY passes_total DESC LIMIT 1
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:24 -> SELECT player_id, player_name, passes_total, season_id FROM vm_agg_season_player_info WHERE season_id = 816527 ORDER BY passes_total DESC LIMIT 1
ERROR:root:Database error: column "passes_total" does not exist
LINE 1: SELECT player_id, player_name, passes_total, season_id FROM ...
                                       ^

Failed query
Running query: SELECT player_id, COUNT(goal_id) as goals_scored FROM public.t_goal WHERE player_id IN (SELECT player_id FROM public.t_goal WHERE season_id in (816527, 816019, 815453, 814198, 813658) AND outcome = True) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 5

06-21 16:27:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:24 -> SELECT player_id, COUNT(goal_id) as goals_scored FROM public.t_goal WHERE player_id IN (SELECT player_id FROM public.t_goal WHERE season_id in (816527, 816019, 815453, 814198, 813658) AND outcome = True) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:24 -> SELECT player_id, COUNT(goal_id) as goals_scored FROM public.t_goal WHERE player_id IN (SELECT player_id FROM public.t_goal WHERE season_id in (816527, 816019, 815453, 814198, 813658) AND outcome = True) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 5
ERROR:root:Database error: column "season_id" does not exist
LINE 1: ..._id IN (SELECT player_id FROM public.t_goal WHERE season_id ...
                                                             ^

Failed query
Running query: SELECT player_id, goals, season_id FROM vm_agg_season_player_opta WHERE season_id in (816527, 816019, 815453, 814198, 813658) AND goals IS NOT NULL ORDER BY goals DESC LIMIT 5

06-21 16:27:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:24 -> SELECT player_id, goals, season_id FROM vm_agg_season_player_opta WHERE season_id in (816527, 816019, 815453, 814198, 813658) AND goals IS NOT NULL ORDER BY goals DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:24 -> SELECT player_id, goals, season_id FROM vm_agg_season_player_opta WHERE season_id in (816527, 816019, 815453, 814198, 813658) AND goals IS NOT NULL ORDER BY goals DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, player_name, team_id, season_id, SUM(dl_index) AS total_goals_scored FROM vm_agg_season_player_similarity WHERE season_id in (816527, 816019, 815453, 814198, 813658) AND position = 'FW' GROUP BY player_id, player_name, team_id, season_id ORDER BY total_goals_scored DESC LIMIT 5

06-21 16:27:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:24 -> SELECT player_id, player_name, team_id, season_id, SUM(dl_index) AS total_goals_scored FROM vm_agg_season_player_similarity WHERE season_id in (816527, 816019, 815453, 814198, 813658) AND position = 'FW' GROUP BY player_id, player_name, team_id, season_id ORDER BY total_goals_scored DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:24 -> SELECT player_id, player_name, team_id, season_id, SUM(dl_index) AS total_goals_scored FROM vm_agg_season_player_similarity WHERE season_id in (816527, 816019, 815453, 814198, 813658) AND position = 'FW' GROUP BY player_id, player_name, team_id, season_id ORDER BY total_goals_scored DESC LIMIT 5

Successful query
Data Shape: (5, 5)
Running query: SELECT player_id, SUM(score_pd) AS goals_scored FROM public.agg_season_player_pd WHERE season_id in (816527, 816019, 815453, 814198, 813658) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 5

06-21 16:27:24 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:24 -> SELECT player_id, SUM(score_pd) AS goals_scored FROM public.agg_season_player_pd WHERE season_id in (816527, 816019, 815453, 814198, 813658) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:24 -> SELECT player_id, SUM(score_pd) AS goals_scored FROM public.agg_season_player_pd WHERE season_id in (816527, 816019, 815453, 814198, 813658) GROUP BY player_id ORDER BY goals_scored DESC LIMIT 5

Successful query
Data Shape: (5, 2)
Running query: SELECT player_id, passes_accurate_90, season_id FROM vm_agg_season_player_similarity WHERE season_id IN (816527, 816019, 815453) ORDER BY passes_accurate_90 DESC LIMIT 5

06-21 16:27:25 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:25 -> SELECT player_id, passes_accurate_90, season_id FROM vm_agg_season_player_similarity WHERE season_id IN (816527, 816019, 815453) ORDER BY passes_accurate_90 DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:25 -> SELECT player_id, passes_accurate_90, season_id FROM vm_agg_season_player_similarity WHERE season_id IN (816527, 816019, 815453) ORDER BY passes_accurate_90 DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Running query: SELECT player_id, team_id, season_id, player_name, passes_total FROM vm_agg_season_player_all WHERE season_id IN (816527, 816019, 815453) AND league_type_id = 1 ORDER BY passes_total DESC LIMIT 5

06-21 16:27:27 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:27 -> SELECT player_id, team_id, season_id, player_name, passes_total FROM vm_agg_season_player_all WHERE season_id IN (816527, 816019, 815453) AND league_type_id = 1 ORDER BY passes_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:27 -> SELECT player_id, team_id, season_id, player_name, passes_total FROM vm_agg_season_player_all WHERE season_id IN (816527, 816019, 815453) AND league_type_id = 1 ORDER BY passes_total DESC LIMIT 5
ERROR:root:Database error: relation "vm_agg_season_player_all" does not exist
LINE 1: ...eam_id, season_id, player_name, passes_total FROM vm_agg_sea...
                                                             ^

Failed query
Running query: SELECT player_id, passes_total, season_id FROM vm_agg_season_player_opta WHERE season_id IN (816527, 816019, 815453) ORDER BY passes_total DESC LIMIT 5

06-21 16:27:27 - logger_SQL_Query_test2 - INFO - Fetching data from the database at: 06-21 16:27:27 -> SELECT player_id, passes_total, season_id FROM vm_agg_season_player_opta WHERE season_id IN (816527, 816019, 815453) ORDER BY passes_total DESC LIMIT 5
INFO:logger_SQL_Query_test2:Fetching data from the database at: 06-21 16:27:27 -> SELECT player_id, passes_total, season_id FROM vm_agg_season_player_opta WHERE season_id IN (816527, 816019, 815453) ORDER BY passes_total DESC LIMIT 5

Successful query
Data Shape: (5, 3)
Database connection pool closed at: 06-21 16:27:29

                                              SQL Query  Valid  \
0     SELECT player_id FROM public.agg_season_player...  False
1     SELECT player_name, SUM(dl_index) AS total_goa...   True
2     SELECT player_name, goals FROM vm_agg_season_p...   True
3     SELECT player_name, goals FROM vm_agg_season_p...   True
4     SELECT player_id, team_id, score_pd FROM publi...   True
...                                                 ...    ...
1157  SELECT player_id, player_name, team_id, season...   True
1158  SELECT player_id, SUM(score_pd) AS goals_score...   True
1159  SELECT player_id, passes_accurate_90, season_i...   True
1160  SELECT player_id, team_id, season_id, player_n...  False
1161  SELECT player_id, passes_total, season_id FROM...   True

                                            Description
0     column "age" does not exist\nLINE 1: ...agg_se...
1                                                (1, 2)
2                                                (0, 2)
3                                                (1, 2)
4                                                (1, 3)
...                                                 ...
1157                                             (5, 5)
1158                                             (5, 2)
1159                                             (5, 3)
1160  relation "vm_agg_season_player_all" does not e...
1161                                             (5, 3)

[1162 rows x 3 columns]